alphagov/frontend

- app/assets/stylesheets/views/_travel-advice.scss
- app/views/travel_advice/index.html.erb
This updates the travel advice index page to modify a few pieces of
static content, and also show the description of the associated content
item in a lead paragraph. Previously the notification div had a custom
margin to align it with the bottom of the search box div. This removes
the padding, since it was proving difficult to maintain.
Related ticket: https://govuk.zendesk.com/agent/tickets/3934135
> Update travel advice page to show more content

- app/views/homepage/index.html.erb
- [Current homepage says 408 agencies or other public bodies](https://www.gov.uk/#departments-and-policy-label)
- [Current actual organisations are 409](https://www.gov.uk/government/organisations#agencies_and_other_public_bodies)
This PR corrects that...
... and updating this is also my personal hobby.
> Change number of agencies / public bodies to 409

- Gemfile
- Gemfile.lock
Adds the Listen gem to the developer dependencies.
The Listen gem was required when this app was upgraded to use the Rails 6
defaults - [see the diff showing this change](https://github.com/alphagov/frontend/commit/d83ce6ff613b6861269a95612b0c8baf4f52256b#diff-a2f09e1db7a47eb67c5849478a97f3d7R51) - but the gem wasn't added to the Gemfile. 
None.
> Add Listen gem to developer dependencies

- app/views/homepage/index.html.erb
This change removes the Renew vehicle tax link and adds in Travel advice for COVID-19.
Trello:
https://trello.com/c/gWEwtJXq/21-coronavirus-link-updates-for-footer-and-popular-links
Screenshot:
> Update popular links to include COVID-19

- app/assets/stylesheets/application.scss
- app/views/travel_advice/index.html.erb
Add a warning about travel to the foreign travel advice list of countries.
See https://github.com/alphagov/government-frontend/pull/1692 for the sibling pull request.
Design has been signed off by @stephenjoe1
Example URL: https://www.gov.uk/foreign-travel-advice
Before on desktop:
After on desktop:
---
<table>
<tr>
<th>
Before on mobile
</th>
<th>
After on mobile
</th>
</tr>
<tr>
<td valign="top">
</td><tr></table>
> Update foreign travel advice template

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/rDnIEsE3/34-prevent-users-signing-up-to-all-travel-alerts
Moves the ability to subscribe to all travel alerts from the top of `/foreign-travel-advice` to slightly more obscure opportunity at the bottom. (screenshots below)
Notifications are experiencing a spike in demand. We believe some users are selecting all alerts (which has a high burden) because it is front and center when more relevant choice are more appropriate. This PR makes country selection the first thing the user sees.
**from this**
**to this - Mobile**
**to this - Desktop**
> Move all travel subscriptions from top of page to bottom

- app/views/homepage/index.html.erb
Removal of search form on homepage.
Before on desktop:
After on desktop:
<table>
<tr>
<th>Before on mobile</th>
<th>After on mobile</th>
</tr>
<tr><td>
</td><td>
</td>
</tr>
> Remove search from homepage

- app/views/licence/continues_on.html.erb
- app/views/transaction/show.html.erb
Fixes the styling of text beneath start buttons on start pages, specifically on these pages:
- https://www.gov.uk/cancel-theory-test
- https://www.gov.uk/tv-licence
Before:
After:
> Fix text beneath start buttons

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/print.scss
- app/views/travel_advice/index.html.erb
Update frontend to import the sass for only the components it is using, instead of all components, as [documented here](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md#import-sass-for-individual-components).
Before:
Total **900 KB**
After:
Total **562 KB**
Also update [foreign travel advice](/foreign-travel-advice/) to use the warning text component. This was previously not possible because the component did not allow for a heading but has been updated to allow this.
This is being done as part of this PR because this page used styles from the component but not the component itself - so I noticed it had broken when I made the Sass change (because the warning text component is not used anywhere, it was not part of the 'suggested sass' output. It …
> Use individual component sass

- app/assets/stylesheets/application.scss
These were missed in 6ff4cb9cb496edcd7bb55d5b435130e540873939:
Bad:
Good:
> Pull in summary-list component styles

- app/presenters/simple_smart_answer_presenter.rb
- app/views/simple_smart_answers/_completed_question.html.erb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/flow.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- test/unit/presenters/simple_smart_answer_presenter_test.rb
| Context | English | Welsh |
| - | - | - |
| Button to enter the flow | Start now | Dechrau nawr |
| Button to go to the next question | Next step | Cam nesaf |
| Validation message for a missing answer | Please answer this question | Atebwch y cwestiwn hwn |
| Link to go back to the beginning from the answers page | Start again | Dechrau eto |
| Link to change a specific answer | Change | Newid |
| Screenreader-visible hidden text after the link to change a specific answer | this answer | yr ateb hwn |
| Screenreader-visible hidden heading on answers page | Your answers | Eich atebion |
| Screenreader-visible hidden heading on question pages | Current question | Cwestiwn presennol |
---
[Trello card](https://trello.com/c/JFBMRXY9/1936-2-provide-welsh-translation-for-buttons-in-simple-sma …
> Add more Welsh translations for simple smart answers

- app/presenters/calendar_content_item.rb
- app/services/calendar_publisher.rb
- lib/tasks/publishing_api.rake
- spec/unit/presenters/calendar_content_item_spec.rb
- spec/unit/services/calendar_publisher_spec.rb
We have these routes in router-api, which look a bit weird:
```
[#<Route _id: 5277d004fa5ee55bbe000018, created_at: nil, updated_at: nil, incoming_path: "/bank-holidays.json", route_type: "exact", handler: "backend", disabled: false, backend_id: "calendars", redirect_to: nil, redirect_type: nil, segments_mode: nil>,
#<Route _id: 5277d004fa5ee55bbe000019, created_at: nil, updated_at: nil, incoming_path: "/gwyliau-banc", route_type: "prefix", handler: "backend", disabled: false, backend_id: "calendars", redirect_to: nil, redirect_type: nil, segments_mode: nil>,
#<Route _id: 5277d004fa5ee55bbe00001a, created_at: nil, updated_at: nil, incoming_path: "/gwyliau-banc.json", route_type: "exact", handler: "backend", disabled: false, backend_id: "calendars", redirect_to: nil, redirect_type: nil, …
```
> Add some more calendars routes

- app/views/layouts/application.html.erb
- app/views/shared/_base_page.html.erb
- test/integration/licence_test.rb
- test/integration/place_test.rb
- test/integration/simple_smart_answers_test.rb
Previously we were showing the phase label below the title in an
inconsistent manner with other government services. This moves this to
be at the top of the page as the first item in the wrapper. I am a bit
baffled how this ever worked before, perhaps it got lost in the midst of
a re-design.
Before:
After:
This does end up looking a little janky if a page is part of a step by step, where the two margins join to create a 2px margin:
I'm reluctant to edit the component for this scenario though as it may break presentation if a different context. We currently don't have any beta content in Mainstream publisher that would trigger this scenario.
> Move phase banner to conventional location

- README.md
- app/assets/javascripts/transactions.js
- config/environments/test.rb
- spec/javascripts/unit/transactions.spec.js
The gov.uk/ask service cannot use the existing cross-domain tracking
abilities set-up in publisher as we do not have google analytics running
on the destination Smart Survey, instead we need to pass this via a
query string variable.
To achieve this we look for any links to our particular Smart Survey
when the page loads for users who have allowed Google Analytics and then
add a query string of the client Id from Analytics.
This change ports over the work from alphagov/government-frontend#1744
which was done to enable this to run on an Answer page format, moving it
here allows this to be done on a transaction format instead.
I've put in the famous last words in a comment of "this should only be
short term" hopefully this doesn't come back to haunt me.
> Add special tracking behaviour for the /ask transaction (with some JS debt cleaned up)

- app/assets/stylesheets/application-ie6.scss
- app/assets/stylesheets/application-ie7.scss
- app/assets/stylesheets/application-ie8.scss
- app/assets/stylesheets/views/_homepage.scss
- app/views/homepage/index.html.erb
The black background column on the right of the front page's header is currently absolutely positioned so that it always touches the bottom of the blue section. This works, but could mean that content could bleed out of the top of the element if too much is added (this can seen to begin on Chrome at a width of 942px).
This PR changes the layout to switch to using the govuk-frontend grid for this column. The effect of the black background always reaching the bottom is achieved using an absolutely positioned pseudo element.
Before:
After:
Note that this change involves a reduction in the width of this column. This is because the previous version ignored the grid column width and was technically too wide. To compensate for this change I've added non-breaking dashes into the link text to stop …
> Update 'Popular on GOV.UK' column styles

- Dockerfile
- app/controllers/calendar_controller.rb
- app/presenters/faq_presenter.rb
- config/application.rb
- config/environments/production.rb
- spec/unit/presenters/faq_presenter_spec.rb
Trello: https://trello.com/c/oNEtjIVp/99-serve-static-assets-from-www-hostname
This is marked as a draft until [Puppet](https://github.com/alphagov/govuk-puppet/pull/10360) is merged and deployed.
This removes the configuration in this app that specifies that this app should use the `assets.publishing.service.gov.uk` hostname for serving assets with the expectation that these assets will instead be served off the `www` hostname. This is to implement [RFC 115](https://github.com/alphagov/govuk-rfcs/blob/master/rfc-115-enabling-http2-on-govuk.md). Because of this the path to assets will be changed to be prefixed with `/assets` so all GOV.UK assets are hosted in the same path.
The asset host can still be configured in this app by a `ASSET_HOST` environment variable, this will be used in …
> Switch asset hostname

- app/views/simple_smart_answers/_outcome.html.erb
This was changed in 5fb281fc560b9a1d77a27ff555c834dcd1c7df09 and it prevents tables from rendering correctly on the pages:
See https://www.gov.uk/student-finance-forms/y/english-student-part-time/apply-for-student-loans-and-grants/2018-to-2019/no/no/yes for an example.
I think it's fine to mark this string as HTML safe because it comes from a trusted source and can only be modified by a content designer.
See https://govuk.zendesk.com/agent/tickets/4093099 for more information.
https://govuk-fronte-html-safe--1nvqxh.herokuapp.com/student-finance-forms/y/english-student-part-time/apply-for-student-loans-and-grants/2018-to-2019/no/no/yes
[Zendesk Ticket](https://govuk.zendesk.com/agent/tickets/4093099)
> Make outcome body safe for simple smart answers

- app/assets/stylesheets/views/_homepage.scss
- app/views/layouts/application.html.erb
Adds a width restricting element to stop the feedback component from hitting the edge of the page on tablet and mobile, bringing it into line with the layout everywhere else.
Long has this annoyed me.
This is how it looks on desktop (before and after) i.e. correct:
But as soon as the page width starts to get narrow, the feedback component collides with the edge of the page:
This continues on mobile:
On all other pages, the feedback component appears normally, like this:
This is the fix introduced by this PR:
The fix also applies on mobile:
This fix doesn't address the width of the component when it is opened, as this is internal to the component (note the width of the blue bar at the top of the component compared with the content above). I'll raise a [separate PR on the …
> Fix feedback layout on homepage

- config/routes.rb
- test/routing/simple_smart_answers_routing_test.rb
When a simple smart answer document is replaced with a transaction page, users may still visit paths for the smart answer.
This is currently serving a 500 error and logging an error to Sentry.
Adding a format constraint so we only try to serve simple smart answers that are actually documents of that format.  A 404 error will be served where the smart answer has been removed.
Trello card: https://trello.com/c/TOhYQdpt/918-fix-no-method-error-in-simple-smart-answers
> Add format constraint for simple smart answer routing

- Rakefile
- lib/tasks/lint.rake
Devs are not aware of lint errors until ci runs it, which could be captured locally as part of the default rake task as opposed to running it separately as an explicit task.
https://trello.com/c/5Gob6WUL
> Add lint task to default rake task

- app/views/simple_smart_answers/_outcome.html.erb
Mainstream Publisher labels the description as "optional" for outcomes.  In simple smart answer outcomes without a description, we are currently generating a 500 error rather than showing no content.
Example: https://gov.uk/vehicles-can-drive/y/motor-tricycle-categories-a-and-a1/yes (which is outcome 41 in https://publisher.integration.publishing.service.gov.uk/editions/5efcb3f53ac8e236a7c3b72e)
Trello card: https://trello.com/c/TOhYQdpt
> Allow simple smart answer description to be optional

- app/assets/javascripts/transactions.js
- spec/javascripts/unit/transactions.spec.js
We now use a GOV.UK hostname for our surveys so this is updated
accordingly, we also use the URL without a trailing slash.
At the time of writing there isn't much tracking of user journeys for
smartsurvey usage, however the team decided they wanted to keep this
functionality in place for the time being while surveys were still being
run so that a dashboard could be re-opened.
> Update smartsurvey host name and path

- .github/workflows/ci.yml
This is a copy of the action config in [collections](https://github.com/alphagov/collections/blob/master/.github/workflows/tests.yml) albeit with a name that complies with the [developer docs](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#gov-uk-conventions-for-github-actions)
This helps us move towards [a reduced Jenkins world](https://docs.publishing.service.gov.uk/manual/test-and-build-a-project-with-github-actions.html#header).
> Add Github action for CI

- app/views/homepage/index.html.erb
Update the number of agencies and public bodies on the homepage from 410 to 411.
So the number is correct and matches the number on the [full list of organisations](https://www.gov.uk/government/organisations#agencies_and_other_public_bodies).
Before:
After:
> Update number for agencies and public bodies

- app/views/completed_transaction/show.html.erb
- test/integration/completed_transaction_test.rb
https://trello.com/c/wiuN997Y/266-update-transaction-thank-you-pages-to-be-unique
This switches from a hard coded string of "Thank you" to putting the
content item's title into the heading (H1) on completed transaction pages.
The relevant tests have been updated to accommodate this using more
realistic strings.
Currently there will be no visual changes as a result of this code update since the content items have been put into mainstream publisher with a title of "Thank you" but there is work in progress to fix that on the content design side. 
The main aim is to make HTML titles unique across the site, which the content updates will do, but we want the H1 to match and be more meaningful.
Some sample urls:
www.gov.uk/done/send-prisoner-money
www.gov.uk/done/apply-carers-allowance …
> Fix completed transaction heading

- app/views/simple_smart_answers/_current_question.html.erb
To cover cases where description contains lists and other govspeak elements.
This is a follow up on https://github.com/alphagov/frontend/pull/2228 – back then we relied on static styles part of the wrapper layout to style the description properly. Now that we use the `core_layout` template in frontend we need these to be rendered by govspeak before being passed to the radio component.
This PR is raised as an alternative approach to https://github.com/alphagov/govuk_publishing_components/pull/1618.
<table>
</td></tr>
</table>
> Render description as govspeak

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_simple-smart-answer.scss
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/simple_smart_answers/show.html.erb
- test/integration/simple_smart_answers_test.rb
The headings in the simple smart answers have been updated so that the heading on each page is the question being asked, rather than the title of the simple smart answer itself.
This is a partial replacement pull request for #2433 due to a decrease in scope - this only fixes the headings and not the `<title>` element.
Trello card: https://trello.com/c/HpZBzZAu
This is to try and meet [WCAG 2.4.2 - Page titles](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html), which asks that pages don't have the same titles on each page.
In this case "title" is understood to mean the main heading on the page rather than the `<title>` element.
If there are pages in a flow that have the same heading on each page, then it isn't immediately obvious that the browser has gone to a new page. Reading …
> Fix simple smart answers headings

- app/controllers/simple_smart_answers_controller.rb
- app/views/layouts/application.html.erb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
- test/integration/simple_smart_answers_test.rb
This pull request flips the logic used to choose how to display a page's `<title>` - `:title` is used if present, otherwise the publication title helper is used, and finally a fallback of "GOV.UK". 
This change allows the `<title>` of a page to be set from with the template, even if the page is a publication - which means we can fix the `<title>` for the simple smart answers.
The problem - simple smart answers were displaying the same text in each step's `<title>`, which means that the pages don't meet the [success criteria 2.4.2 of the WCAG](https://www.w3.org/WAI/WCAG21/Understanding/page-titled.html).
The page title has an conditional statment where if the page is a publication the `<title>` is set by a helper. This means that using `content_for :title` doesn't work for publications …
> Changes page `<title>` logic to fix simple smart answers

- app/views/local_transaction/results.html.erb
- app/views/local_transaction/search.html.erb
- app/views/place/show.html.erb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
HTML was not being rendered correctly in `govspeak` blocks.
It was found that the `sanitize` method was being used. This method strips all HTML tags and attributes that aren’t whitelisted and so the content being passed into the `govspeak` blocks was plain text.
We need to ensure the HTML presented is safe, so applying the `html_safe` method to the content.  Unfortunately, some fields are not mandatory so we need guard clauses to stop `nil` exceptions on all optional fields.
[Trello card](https://trello.com/c/s6Cs6X9t/971-fix-html-rendering-in-simple-smart-answers)
> Fix HTML render issues

- app/views/travel_advice/index.html.erb
Updated Foreign & Commonwealth Office to Foreign, Commonwealth and Development Office in the coronavirus travel advice message.
> Update FCO to FCDO in coronavirus message

- app/views/homepage/index.html.erb
There's now 23 ministerial departments after FCO and DFID merged to create FCDO.
> Update number of ministerial departments

- app/views/homepage/index.html.erb
Trello: https://trello.com/c/ggrga8HJ
Replace the "Personal tax account" link with a link to sign in to
Universal Credit in "Popular on GOV.UK" black box
Sign in to UC page is:
- most visited page on GOV.UK
- most browsed-for page on GOV.UK (32m accessing it via mainstream
browse Jan-Jul)
- most searched for page on GOV.UK (internal search) (4.5x the bottom 3
popular links combined - Jan-Jul)
- 71% of searches that lead to Sign into UC are made from homepage
> Update popular link on GOV.UK home page

- app/views/application/_location_form.html.erb
- app/views/local_transaction/results.html.erb
These are the changes necessary for Ruby 2.7.1 
I've left the version as 2.6.6 since there is a script to update all the apps' Ruby versions at once.
One deprecation warning coming from zeitwerk `zeitwerk/loader.rb:581: warning: constant ::Data is deprecated`, but it also appears on 2.6.6 so seems to be a separate issue
> Upgrade to Ruby 2.7.1

- app/views/application/_location_form.html.erb
Add the `postal-code` autocomplete attribute to the postcode form partial. [Example form usage](https://www.gov.uk/find-local-council).
Without the autocomplete attribute, this fails WCAG 1.3.5 because users with cognitive or motor impairments will find it more difficult to fill in forms.
No visual changes.
**Card:** https://trello.com/c/aQzSeo2n/408-postcode-form-missing-autocomplete-attribute
> Add postal code autocomplete attribute

- Gemfile
- Gemfile.lock
- config/initializers/assets.rb
- spec/javascripts/support/jasmine_helper.rb
- spec/javascripts/support/jasmine_selenium_runner.yml
This changes the configuration mechanism for Jasmine to use headless
Chrome rather than PhantomJS. We need to govuk_test as a development
dependency as the files need to be available when loading files for
the Jasmine rake task.
This also removes the conditional that only added all.js and
test_dependencies.js in the test environment. This caused problems when
running a Jasmine webserver (presumably that compiles assets in a dev
environment). Removing this is of low consequence as these files are
merely made available they're not forced on the app.
> Run Jasmine tests with Selenium driven Chrome

- app/views/homepage/index.html.erb
That's it....
This week I'm finally going to make an alert for this.
If you click on 412 on the homepage it immediately shows 413
It makes us look like we can't count if it's not up to date
> Update Agencies and other public bodies to 413

- app/views/transaction/_additional_information_tabbed.html.erb
Resolves:
https://sentry.io/organizations/govuk/issues/2004100825/?project=202225&query=is%3Aunresolved
Related to:
https://github.com/alphagov/govuk_publishing_components/pull/1632/
> Fix govspeak unsanitized content error

- app/views/homepage/index.html.erb
Trello: https://trello.com/c/IrWcChpd
# What?
Update the popular links section on the GOV.UK homepage, replacing the coronavirus landing page link with a link to the national restrictions guidance.
Replace with:
Coronavirus (COVID-19): National restrictions in England
Link to:
https://www.gov.uk/guidance/new-national-restrictions-from-5-november
> Change popular link to England COVID restrictions

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/AEbD9SBq
Remove 'travel advice' link from last sentence of the second paragraph in the callout.
This link is a circular reference as the page is linking to itself and should be removed.
> Remove link to travel advice search from callout

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/iS4WvL1j
Updates the link to Wales restrictions on https://www.gov.uk/foreign-travel-advice
We changed the link for wales information to:
https://gov.wales/coronavirus-firebreak-frequently-asked-questions
We should change it back to https://gov.wales/local-lockdown
> Update the Wales link on travel advice call out

- app/assets/stylesheets/views/_travel-advice.scss
Adds a bottom margin to the letters on the [foreign travel advice page](http://gov.uk/foreign-travel-advice).
A user has raised in [this zendesk ticket](https://govuk.zendesk.com/agent/tickets/4309667) that it's difficult to click on a link at the top of a list of alphabetical locations/topics. This is because the line spacing in `h3` letter at the top of the page is overflowing onto the following link, causing the browser to interpret it in a weird way. This PR creates a distinct, programatic space between the letter and the first link in the list.
There is a slight visual change but it is so small and inconsequential that I'm making the call to not include visual changes in this PR.
> Add bottom margin to travel advice world location letters

- app/views/help/cookie_settings.html.erb
- app/views/local_transaction/results.html.erb
- app/views/local_transaction/search.html.erb
- app/views/place/show.html.erb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
Updates any Govspeak component that was using the `content` parameter to use a `do` block.
So things are fixed. See https://github.com/alphagov/govuk_publishing_components/pull/1632 for the cause of this change.
None.
> Update Govspeak component usage

- config/locales/cy.yml
- config/locales/en.yml
- lib/data/bank-holidays.json
Standard generated bank hliday dates plus special case for royal occasion.
https://trello.com/c/tzHLWwhE/2227-add-2022-bank-holidays-and-clock-change-dates
> Add 2022 dates

- app/views/homepage/index.html.erb
Following renaming of the transition taxon, and site wide changes to use the more SEO friendly term 'Brexit transition', we should make the homepage consistent. 
- ### Update popular on GOV.UK section
---
- ### Update brexit promo image text
[Review app](https://govuk-fronte-make-homep-eitlmp.herokuapp.com/)
[Trello](https://trello.com/c/ynxEAip9/616-update-the-transition-wording-on-the-govuk-homepage-and-govuk-footer)
> Replace EU transition with Brexit transition on the homepage

- app/views/homepage/index.html.erb
[Trello](https://trello.com/c/wuw9gGA1/969-update-govuk-homepage-popular-link-to-link-to-postcode-checker)
- Remove link to `/new-national-restrictions-from-5-november` due to end of national coronavirus restrictions
- Add link to the coronavirus local restrictions postcode checker
> Update popular links

- app/views/travel_advice/index.html.erb
- due to the change from national to local coronavirus restrictions on 02/12/2020
[Trello](https://trello.com/c/xFCKku6i/948-update-the-travel-advice-callout-box-on-travel-pages)
> Update travel advice callout box content

- app/assets/javascripts/views/travel-advice.js
- spec/javascripts/unit/foreign-travel-advice.spec.js
Change the aria-live region on the foreign travel advice page - the region is now only wraps the number of countries and territories, not the entire list of countries and territories.
Previously the entire list of countries was being read out as you typed into the search input. This is too verbose and led to the page being nearly unusable when using JAWS.
For example, if you were searching for "Australia" all the countries with "A" in their name would be read out (all 198 of them), then all the countries with "Au" (9), then the two with "Aus" in them.
This has been changed to only read out the number of countries or territories that found for a search result. This means that searching for "Australia" will cause "198 countries or territories" to be read out, then "9 countries or …
> Change aria-live region to be less verbose

- app/views/transaction/_additional_information_tabbed.html.erb
Change from `sanitize` to `raw` to prevent the table elements from being stripped out.
The table on the page for [Request UK processing of an international patent application](https://www.gov.uk/request-uk-processing-of-international-patent-application) had an unformatted table - the contents of the table appeared as a string of text.
Before:
After:
> Update sanitize to raw to stop tables being removed

- app/views/travel_advice/index.html.erb
This is changed to reflect updated guidance from FCDO on December 19th.
> Foreign travel advice call out update

- app/controllers/local_transaction_controller.rb
- app/models/local_transaction_services.rb
- app/presenters/local_authority_presenter.rb
- app/views/local_transaction/unavailable_service.html.erb
- config/unavailable_services.yml
- test/fixtures/unavailable_services.yml
- test/functional/local_transaction_controller_test.rb
- test/integration/local_transactions_test.rb
- test/support/location_helpers.rb
- test/unit/models/local_transaction_services_test.rb
The Test and Trace self isolation payment is a service delivered by local councils.  However, it isn't available in Scotland and Northern Ireland. 
User's currently searching with a postcode for those nations are incorrectly told to search their local council site for more information. 
We'd like to explicitly tell users that the service isn't available in the country to which the postcode they have entered relates, and give them a link to the national COVID page.
[Trello](https://trello.com/c/QSY1CoAB/643-test-and-trace-nation-validation)
> Add Test and Trace Payment Service nation validation

- app/views/local_transaction/results.html.erb
- app/views/local_transaction/unavailable_service.html.erb
- test/integration/local_transactions_test.rb
There are both a `back link` and `breadcrumbs` on the `results` and `unavailable_service` pages used by `local_transaction`s.  This is not a recommended pattern and one of these elements should therefore be removed.
It is felt that we should remove the `back link` on these pages as `breadcrumbs` offer a better user experience. 
Remove the `back link`s and update the tests.
So that these pages are consistent with other GOV.UK pages and are in-line with the [design system guidance on the use of the back link component](https://design-system.service.gov.uk/components/back-link/)
[Trello](https://trello.com/c/qvKAugus/709-re-position-back-link-location-on-tt-payment-unavailable-page)
> Remove back links on the local_transaction pages

- .gitignore
- README.md
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_subscribe.scss
- app/assets/stylesheets/styleguide/_conditionals.scss
- app/assets/stylesheets/views/_homepage.scss
- app/assets/stylesheets/views/_jobsearch.scss
- app/assets/stylesheets/views/_local-transaction.scss
- app/assets/stylesheets/views/_simple-smart-answer.scss
- app/assets/stylesheets/views/_travel-advice.scss
- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/one_council.html.erb
- app/views/homepage/index.html.erb
- app/views/place/show.html.erb
- app/views/transaction/_additional_information_single.html.erb
- package.json
As part of on-going work, update to `frontend` to use components when appropriate.
To improve a11y ensuring consistency of component architecture
[Trello ticket](https://trello.com/c/wk438rpt)
Live Link: https://www.gov.uk/register-to-vote
Before (Left) After (Right)
---
https://www.gov.uk/report-child-abuse-to-local-council
---
https://www.gov.uk/find-local-council/warwick
---
https://www.gov.uk
Note `margin-top` visual change on mobile, this is inline with the [Design system spacing](https://design-system.service.gov.uk/styles/spacing/)
- if preferred desktop can visually update instead. 
- [GDS Stylelint](https://github.com/alphagov/stylelint-config-gds) installed, config added and run on app.
- update to redirected link within `README`
> Update to use components

- app/views/travel_advice/index.html.erb
The last line should not be `<strong>`, so this has been amended.
> No longer render text as <strong> importance

- app/assets/javascripts/modules/cookieless-tracker.js
- app/assets/javascripts/modules/track-variant.js
- app/controllers/application_controller.rb
- app/controllers/concerns/cookieless_testable.rb
- app/views/layouts/application.html.erb
- spec/javascripts/unit/modules/track-variant-spec.js
- test/integration/bank_holidays_test.rb
This PR adds a new Cookieless A/A test, which sends hit-only data to analytics up until cookies have been accepted by the user. This is necessary to understand whether we can rely on the approach offered by our CDN to reliably assign users to a variant of an A/B test and maintain that variant, such that we'd expect to see an even distribution of users across all active variants of a test (or according to any prescribed percentages of variants).
**This PR should not be merged until we're ready to turn on the A/A test.**
> Add cookieless test

- app/views/travel_advice/index.html.erb
Update component references following this change to correct component file names: https://github.com/alphagov/govuk_publishing_components/pull/1848
> Use correct component references

- test/functional/local_transaction_controller_test.rb
- test/integration/local_transactions_test.rb
- test/support/location_helpers.rb
We would like to be able to retrieve the link status from the Local Links Manager API response.
[Trello](https://trello.com/c/CcwdnK7A/745-add-link-status-in-api-response)
> Update GDS API Adapter Local Links Manager stubs

- app/controllers/local_transaction_controller.rb
- app/models/local_transaction_services.rb
- app/views/local_transaction/unavailable_service.html.erb
- config/brakeman.ignore
- config/unavailable_services.yml
- test/fixtures/unavailable_services.yml
- test/integration/local_transactions_test.rb
- test/unit/models/local_transaction_services_test.rb
Expand on the existing `unavailable_service` view by moving and abstracting the page content in to the `unavailable_services` YAML configuration file.
We would like to support the ability to customise the text on the 'Service unavailable for <country>' page.
[Trello](https://trello.com/c/vcsLBkOw/748-allow-custom-content-for-service-unavailable-for-country-page)
> Allow custom content for 'Service unavailable for <country>' page

- app/controllers/local_transaction_controller.rb
- app/models/local_transaction_services.rb
- config/brakeman.ignore
- config/unavailable_services.yml
- test/fixtures/unavailable_services.yml
- test/integration/local_transactions_test.rb
- test/unit/models/local_transaction_services_test.rb
Add configuration and suitable content for services that are unavailable for a particular local authority 
We want to offer better user support and advice when a particular service in unavailable within their local authority
[Trello](https://trello.com/c/ljHCvkAj/752-configure-unavailable-local-authorities)
> Add support for services that are unavailable for a local authority

- app/controllers/local_transaction_controller.rb
- app/models/local_transaction_services.rb
- config/brakeman.ignore
- config/unavailable_services.yml
- test/fixtures/unavailable_services.yml
- test/integration/local_transactions_test.rb
- test/unit/models/local_transaction_services_test.rb
This reverts commit 291aeac6a4119f601c4e27ce57f8a5ac66ba48c7, reversing changes made to 8764cdacbb9b5a00c07ebaf0b1c957c237d005e3.
This functionality is no longer require, revert to keep the codebase simple.
> Revert "Merge pull request #2610 from alphagov/unavailable-local-authorities"

- app/controllers/local_transaction_controller.rb
- app/models/local_transaction_services.rb
- config/brakeman.ignore
- config/unavailable_services.yml
- test/fixtures/unavailable_services.yml
- test/unit/models/local_transaction_services_test.rb
Add the ability to specify content on a per country basis and display that to the user when they have supplied a postcode that is within a country where the service is unavailable
We want to give a more tailored and specific response to the user depending on the country that their local authority is in so that we can support them better
[Trello](https://trello.com/c/BG1boLpY/756-add-ability-to-specify-content-per-country-for-unavailable-page)
> Add the ability to specify country specific content for unavailable page

- app/controllers/homepage_controller.rb
For consistency with other pages and most importantly to improve the performance of this page we swap the `homepage` template with `core-layout` which translates in dropping [`govuk_toolkit` scripts](https://github.com/alphagov/static/blob/master/app/assets/javascripts/application.js#L2) and [some SCSS mixins](https://github.com/alphagov/static/blob/master/app/assets/stylesheets/static.scss#L7-L14). Mentioned resources are not required nor used on this page.
No visual or functional changes, as seen in [the preview app](https://govuk-fronte-use-core-l-tpugmu.herokuapp.com/).
[Trello card](https://trello.com/c/Dpe7MWQp)
> Use core-layout on homepage

- config/locales/en.yml
One of the tasks was written before the transition period ended, so update the task description now it's ended.
> Update tense on Brexit work

- app/views/homepage/index.html.erb
Replace 'Travel advice: coronavirus (COVIV-19)' 'Sign in to your personal tax account'.
Personal tax account page data:
- consistently popular page - average 150,000 unique page views a week for past three years
- peak use is around February to late May
- 70% of users arriving via search this year come from the home page - suggesting they expect to find the page easily from the home page
- unique page views have increased by 33% since the start of 2021 - now 45,000 a day
When the link was removed last year:
- 10% fewer people looked at the page - suggesting that removing the link led to a drop in use
- searches for the page on GOV.UK’s home page more than tripled
Replacing travel advice page because:
- travel page usage peaked last month but has now dropped back to a similar level as the …
> Update popular links section

- app/assets/stylesheets/views/_homepage.scss
Two visual fixed on the homepage:
- font-size and line-heght on intro text
- link spacing on promo section
<table>
Chrome
Chrome
</td></tr>
Firefox
Firefox
</td></tr>
</td></tr>
</td></tr>
</table>
> Homepage fixes

- README.md
Add the GOVUK Roadmap page to the list of hard-coded routes on the repository's `README` file.
The page was recently created [here](https://github.com/alphagov/frontend/pull/2608).
> Document roadmap page on README.md

- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/one_council.html.erb
- app/views/help/cookie_settings.html.erb
Switch from using `trackClick` script to `gemTrackClick` script. They are virtually the same, the latter being [copied over from `static` to `govuk_publishing_components`](https://github.com/alphagov/govuk_publishing_components/pull/1751).
Part of [a bigger piece of work](https://github.com/alphagov/static/pull/2405) to reduce the size of assets served to users and keep our codebase to a minimum.
> Switch from trackClick to gemTrackClick script

- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- Jenkinsfile
- Rakefile
- lib/tasks/pact.rake
- test/service_consumers/pact_helper.rb
Depends on https://github.com/alphagov/gds-api-adapters/pull/1035 and #2643  (otherwise there'd be no pact tests to test against, and the build would fail).
Note that this PR takes a _lot_ of inspiration from https://github.com/alphagov/collections/pull/2281.
Trello: https://trello.com/c/Pvoq4sQY/2370-5-enable-continuous-deployment-for-frontend
> Run pact tests with gds-api-adapters as part of deployment pipeline

- .github/pull_request_template.md
- README.md
- Rakefile
- config/routes.rb
- doc/README_FOR_APP
Now that Frontend has implemented Pact testing ([1], [2], [3], [4]), has a healthcheck ([5]), and has adequate code coverage, it has achieved the [minimum safety standards](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-128-continuous-deployment.md#safety-checks) required of Continuous Deployment, which we can now enable.
See commits for details.
Trello: https://trello.com/c/Pvoq4sQY/2370-5-enable-continuous-deployment-for-frontend
[1]: https://github.com/alphagov/gds-api-adapters/pull/1035
[2]: https://github.com/alphagov/frontend/pull/2643
[3]: https://github.com/alphagov/frontend/pull/2644
[4]: https://github.com/alphagov/gds-api-adapters/pull/1036
[5]: https://github.com/alphagov/smokey/pull/795
> Enable Continuous Deployment for Frontend

- Jenkinsfile
We already run `pact:verify` in the default rake task:
https://github.com/alphagov/frontend/blob/693146acc420b58e83aaa8a99f864b18d8f8f9a3/Rakefile#L16
We don't need to explicitly run it _again_.
But we do need to _keep_ the `pact:verify:branch` task, as it is
called by gds-api-adapters:
https://github.com/alphagov/gds-api-adapters/blob/67ad7bece4b3a988e989ef90c4dde22871b5794b/Jenkinsfile#L76-L85
We _could_ delete it if we made more use of `PACT_URI`, but this
makes for a more complex and brittle experience, so on balance is
not worth it:
https://github.com/alphagov/frontend/pull/2647
> Stop running `pact:verify:branch` as part of standard build

- app/presenters/machine_readable/yaml_faq_page_schema_presenter.rb
- app/views/transaction/show.html.erb
- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
This PR adds a custom FAQPage schema for https://www.gov.uk/register-to-vote using the same method as [we did for the general election](https://gds.blog.gov.uk/2019/12/19/making-gov-uk-more-than-a-website/).
I've done it in 3 stages:
- resurrect the previous code (git revert `<committish>`)
- fix tiny broken things
- update the content of the schema to match [the updated intents](https://docs.google.com/document/d/12feerYNxmQjbPugtY6op38M6ocOBDQHGTu_yoinb2gM/edit?ts=60393f0a#heading=h.oahmgkb5jlyb)
> Add custom structured data for Register to Vote

- app/views/travel_advice/index.html.erb
This removes `from 8 March` from the copy in the callout boxes.
[Trello](https://trello.com/c/SGZS4z43/224-travel-advice-call-out-box-update-8-march)
> Update travel advice callout boxes

- app/assets/stylesheets/views/_local-transaction.scss
- app/views/local_transaction/results.html.erb
- test/integration/local_transactions_test.rb
Trello: https://trello.com/c/CdUKR3M4/204-accessibility-local-look-up-fix-the-non-descriptive-button
This sets the font size in text to be a normal one rather than the
rather giant one that previously exited. It also includes more
supplementary information.
This changes the start button to be the less bold "start" button style
to be the more conventional success operation style. The text has been
changed to include the name of the local authority. This resolves in
accessibility issue that has been flagged in the Digital Accessibility
Centre's WCAG 2.1 audit of GOV.UK:
> Screen reader comments:
> “The button to move to the service of the relevant council announced to me as ‘Go to their
> website’. It may be unclear to some screen reader users browsing out of context which
> council the …
> Modernise Local Transaction results view

- lib/config/local_transaction_config.yml
We want to add a duplicate configuration record for the lateral flow mass testing finder service with an LGSL code of `1827`. Once the LGSL code has been changed from `100001` to `1827` in `local-links-manager` - the config for service `100001` will be removed. 
When the lateral flow mass testing finder service was created, it was created with a dummy code of `100001`.  We now have a real code - `1827` - so would like to use this code instead of the dummy one.
[Trello](https://trello.com/c/MRGj9keG/210-llup-lateral-mass-test-apply-the-proper-assigned-service-code-1827-agreed-with-local-government-authority)
> Add duplicate service with correct LGSL code

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
This doesn't match the [live content](https://www.gov.uk/register-to-vote#register-using-a-paper-form).
This has been specifically crafted so that the schema only contains things that meet specific user needs - hence the duplication.
> Update FAQ schema to match the content

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
This PR relates to special work we're doing to promote voting prior to the local elections on 6 May.
We are not able to use a Top Actions tagged section, as we've been advised that this now has to be visible in order to be eligible for use in a result. (We're not able to do this)
We're renaming to "Related content" as this is more suited to the actual use, and may be picked up for a different treatment in search result pages.
> Rename Top Actions section

- app/controllers/local_transaction_controller.rb
- app/models/location_error.rb
- app/views/local_transaction/results.html.erb
- config/locales/en.yml
- test/functional/local_transaction_controller_test.rb
- test/integration/local_transactions_test.rb
- test/unit/models/location_error_test.rb
Trello: https://trello.com/c/BgI9a1t3/205-local-lookup-says-no-create-better-were-not-sure-if-this-council-offers-this-service-copy
This PR changes the renderings of errors when a local authority doesn't have a service, while also cleaning up some things to make this simple change possible.
Before:
After:
---
The other things this PR does is:
- It removes the usage of LocationError to handle cases where a local authority is missing a service. This made making changes harder and already seemed a rather uneasy fit as the conditionals were somewhat bent around it
- Removes an ActiveSuport::Notifier event for logging …
> Convoluted approach to changing local transaction error message copy

- app/assets/stylesheets/print.scss
Enable compatibility mode in print stylesheet (as we do in [`application.scss`](https://github.com/alphagov/frontend/blob/master/app/assets/stylesheets/application.scss#L1-L2)).
Not setting the compatibility flag with `govuk-template` results in referencing the new `GDS Transport` font which is not available in `static` at the moment as we still rely on `govuk-template` and the old `nta` font.
<table>
</td></tr>
</table>
> Enable compatibility mode in print stylesheet

- app/controllers/concerns/account_concern.rb
- app/controllers/sessions_controller.rb
- config/routes.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
- test/support/session_helpers.rb
[A part of this trello ticket](https://trello.com/c/RaI017p6/675-add-new-public-facing-oauth-endpoints-to-frontend)
What
===
A part of the work to broaden the transition checker login prototype to
the whole of GOV.UK. As outlined in [RFC#134][1] we are moving sign in
and sign out paths from being nested in finder-frontend (which would be
strange for a GOV.UK-wide login!) onto their own paths.
[1]: https://github.com/alphagov/govuk-rfcs/pull/134
> Add GOV.UK sessions

- lib/config/local_transaction_config.yml
Remove the configuration the Service with an LGSL code of 100001.
That service no longer exists.  It is now 1827.
[Trello](https://trello.com/c/MRGj9keG/210-local-lookup-lateral-mass-test-apply-the-proper-assigned-service-code-1827-agreed-with-local-government-authority)
> Remove config for service 100001

- app/views/homepage/index.html.erb
Trello: https://trello.com/c/A0QktLQc
This link was set to a short-url when the restrictions were being updated, but
should now link directly to the guidance rather than the short-url.
> Update popular COVID link

- app/views/application/_location_form.html.erb
Trello: https://trello.com/c/sNkGgV4D/300-accessibility-local-lookup-how-might-we-notify-users-that-a-new-tab-will-open-when-they-select-a-link
Removing this resolves an accessibility problem: that users are not
informed that a new tab will open.
The use of target=_blank is inconsistent for GOV.UK as a whole and
should only be applied mid-transaction [1]. This is not a mid
transaction scenario.
This also sets the URL to https since that is now the canonical URI for
the resource.
[1]: https://twitter.com/GDSTeam/status/983992989650423809
> Remove target="_blank" from postcode link

- app/views/travel_advice/index.html.erb
'England' currently links to the old https://www.gov.uk/guidance/national-lockdown-stay-at-home URL which has been redirected to the new guidance.
This PR updates it to points directly at: https://www.gov.uk/guidance/covid-19-coronavirus-restrictions-what-you-can-and-cannot-do
> Update link for England travel advice

- app/views/help/index.html.erb
https://trello.com/c/3EXpc25Z/2162-add-new-report-a-vulnerability-page-to-the-govuk-help-index
I've updated the help index page with a link to https://www.gov.uk/help/report-vulnerability
> Added a link to the report a vulnerability page

- app/controllers/sessions_controller.rb
- test/integration/sessions_test.rb
[Trello](https://trello.com/c/43FM4pwv/673-switch-to-the-new-sign-in-out-endpoints)
What
====
Requests to `/sign-in` should be sent here from buttons or links a user
has clicked somewhere on GOV.UK. With those requets should be an
HTTP_REFERER header that tells us where they were when they clicked.
Here we grab that header and use it to populate the redirect_path param
we send to the API.
Why
===
Whenever the user logs in, they are mostly likely trying to get
something done. The login flow appears as in interruption - they were
trying to find out about something, and GOV.UK took them away to log in
when the took an action.
So when they are authenticated we want to return the user to where they
started so they can continue with their journey.
Other options would be to send them to a fixed …
> Add fetch_http_referer header

- app/controllers/sessions_controller.rb
- test/integration/sessions_test.rb
This fixes a bug where:
- When clicking on the sign-in link in the GOV.UK header (which is
rendered in static and so cannot pass redirect_path values dynamically
from the page.
- Then the user is sent to log in
- Then the user is redirected to the path without any parameters.
This stops users seeing their transition checker results during the
login journey as the transition checker relies heavily on params to show
the results page
> Keep params from Referer Header session redirects

- lib/data/when-do-the-clocks-change.json
It's been pointed out that these are incorrect at the moment as they're referring to a Saturday rather than a Sunday.
See https://en.wikipedia.org/wiki/British_Summer_Time for a table showing the dates each year.
> Fix 2022 clock change dates

- app/views/homepage/index.html.erb
Performance platform has been shut down, so this link now redirects to
https://data.gov.uk/dataset/731b25a8-0462-4a7d-aa3f-5a5d44ae26d2/historical-performance-platform,
which is not a particularly useful place to send users from the
homepage.
For now, probably best just to remove this.
|-----|-----|
| ![Screenshot_2021-04-01 Welcome to GOV UK(1)](https://user-images.githubusercontent.com/1696784/113329639-b9754a00-9315-11eb-8728-0c11899995fe.png) | ![Screenshot_2021-04-01 Welcome to GOV UK](https://user-images.githubusercontent.com/1696784/113329670-c003c180-9315-11eb-905d-26c4fd56ae0e.png) |
> Remove link to performance platform from the homepage

- app/views/help/cookie_settings.html.erb
Adds `govuk-body` and `govuk-notification-banner__link` to the classes used in the content for the success alert banner call on the [cookie page](https://www.gov.uk/help/cookies).
As part of our work to ensure that our cookie page is in line with the design system cookie guidance, this work ensures that the content we're serving on our success banner on the cookie page is using the same styling as the design system notification banner success variant. The `govuk-body` change is a minor tweak as we should be using typography changes in as many places as possible.
This PR can't be merged until the [associated components gem PR](https://github.com/alphagov/govuk_publishing_components/pull/1929) is merged, released and updated in frontend.
> Add design system classes to content for the cookie banner success alert

- app/views/local_transaction/results.html.erb
Add a Google Analytics event to track when a user is shown a result for a [local transaction](https://github.com/alphagov/frontend/blob/7849f308d3c97178465b46932f424e83c79d063f/app/views/local_transaction/results.html.erb)
eventCategory postcodeSearch:local_transaction
eventAction postcodeResultShown
eventLabel [local authority area shown]
We currently track when users receive an error on these pages but not an event that they are shown a result, this data should help us understand further how users engage with local transactions.
https://trello.com/c/croKq9tY/263-add-extra-event-tracking-to-local-transactions
https://www.gov.uk/find-covid-19-lateral-flow-test-site
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/devel …
> Add extra event tracking to local transactions

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_transaction.scss
- app/presenters/transaction_presenter.rb
- app/views/transaction/_country_notice.html.erb
- app/views/transaction/show.html.erb
- test/unit/presenters/transaction_presenter_test.rb
We get the blue banner up (and down) on the business support smart answer for two weeks for the purpose of the test.
We are doing a before and after test and the banner is the key bit!
https://trello.com/c/Py8XjzRQ/275-implement-blue-banner-for-before-and-after-test
> Adds country notice to the business support smart answer

- Gemfile
- Gemfile.lock
- config/environments/production.rb
We are going to add a new election lookup service to Frontend. Using a [shared](https://github.com/alphagov/govuk-aws/blob/c993f31604b7023dc0292e8bdf79eb8e2cced8b7/terraform/projects/app-frontend/main.tf#L193-L205) memcached server will help performance. 
> Use memcached as the default cache store.

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/electoral_controller.rb
- app/presenters/electoral_presenter.rb
- app/views/electoral/_contact_details.html.erb
- app/views/electoral/_form.html.erb
- app/views/electoral/_upcoming_elections.html.erb
- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
- app/views/local_transaction/search.html.erb
- config/locales/en.yml
- config/routes.rb
- test/fixtures/electoral-result.json
- test/functional/electoral_controller_test.rb
- test/integration/electoral_look_up_test.rb
- test/unit/presenters/electoral_presenter_test.rb
Build election lookup service based on [Simon's prototype](https://github.com/alphagov/collections/pull/2293)
- Replace staging api with production api
- Error handing (for postcode input errors as well as api error responses) as per [this doc](https://docs.google.com/document/d/113cwWlIpFfmUwyCE0_akzGEGJFcPxh4IQs3o2Prjf1A/edit?ts=60701d72).
- Caching
- Check that the GA stuff is correct
- Add graphite timings around the external API call
- Move results page content into locale file
> Election lookup service

- app.json
The review apps for this app are on a stack type that is coming to its
[end of life](https://help.heroku.com/0S5P41DC/heroku-16-end-of-life-faq).
This should update the review app to a more recent version.
> Upgrade Frontend's Heroku stack type

- Gemfile
- Gemfile.lock
[Heroku determines ruby versions](https://devcenter.heroku.com/articles/ruby-versions) by looking at the Gemfile. Normally it's OK for review apps because they're short-lived and get created with a recent version each time.
Long running apps like [the current master version of Frontend](https://dashboard.heroku.com/apps/govuk-frontend-app/activity/builds/db88f35a-fac3-481c-a2ca-54414f9a9071) stick at the version of ruby they were created with unless it's updated in the Gemfile.
The master review app is currently failing to build because its ruby version is no longer available in Heroku.
> Update ruby version used in Heroku apps

- app/presenters/electoral_presenter.rb
- app/views/electoral/_contact_details.html.erb
This should make it easier to keep the address presentation consistent, and removes some use of `html_safe` which we should minimise when calling from external sources.
> Consolidate presentation of addresses

- app/controllers/electoral_controller.rb
- app/views/electoral/_form.html.erb
- test/functional/electoral_controller_test.rb
- test/integration/electoral_look_up_test.rb
- test/support/election_helpers.rb
Updates the name of the API key variable to reflect what it's for.
Adds a new env var for the URL to allow us to target different end points in different environments
Worth reviewing with a `&w=1` to make the whitespace changes disappear
> Update Elections API environment variables

- app/controllers/electoral_controller.rb
- app/models/election_postcode.rb
- app/models/location_error.rb
- app/models/uprn.rb
- app/views/electoral/_form.html.erb
- app/views/electoral/address_picker.html.erb
- app/views/local_transaction/search.html.erb
- config/locales/en.yml
- config/routes.rb
- test/functional/electoral_controller_test.rb
- test/integration/electoral_look_up_test.rb
- test/unit/models/election_postcode_test.rb
- test/unit/models/uprn_test.rb
This provides us with some local validation for postcodes and uprns before hitting the external service.
> Handle errors for invalid postcode and uprn

- app/controllers/electoral_controller.rb
- app/models/location_error.rb
- app/services/electoral_service.rb
- app/views/electoral/_contact_details.html.erb
- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
- config/locales/en.yml
- test/functional/electoral_controller_test.rb
- test/integration/electoral_look_up_test.rb
- test/support/election_helpers.rb
In this PR we're handling the known 400 and 404 errors as they'll indicate something the user might be able to address.
Other errors will just fall through at present because it either reflects something that we've done wrong (403 would be an incorrect API key) or a problem with the remote service. Either way, the user would be unable to do anything, so we'd need to display an error.
We're considering implementing retries for 5xx errors, but not in this PR.
We add some short-lived caching to help handle spiky loads, and add some metrics around API request duration and logging of error types
> Handle remote errors for elections lookup

- app/assets/stylesheets/application.scss
- app/views/electoral/_contact_details.html.erb
- app/views/electoral/_form.html.erb
- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
- test/integration/electoral_look_up_test.rb
A few adjustments to the elections lookup as detailed in commits. The only thing that may still need improvement are the election dates on the result page (and generally around data that in unstructured in the API), but I wasn't sure if we have any consistency on how that info is stored. We could potentially do some string operations on it, which sounds flakey, but I don't see alternatives.
<table>
</td></tr>
</td></tr>
</table>
> Adjustments to the elections lookup

- app/services/electoral_service.rb
- app/views/electoral/results.html.erb
- test/integration/electoral_look_up_test.rb
Fix the page title on the results page
Fix the name of a key used for measuring the duration of an API call.
> Small fixes for elections

- app/views/calendar/_save_location.html.erb
- app/views/calendar/bank_holidays.html.erb
Currently, the [Welsh version of the bank holidays page](https://www.gov.uk/gwyliau-banc) has `lang='en'` even though most of the main content of the page is in Welsh.
These changes add a `lang` attribute to the main landmark on the page, so that the content is correctly labelled as Welsh when viewing the Welsh version of this page.
Additionally, when viewing the Welsh version, add a `lang=en` attribute to the bank holidays experiment panel as we do not have translations for most of this content. This is to ensure that assistive technologies can read this content in the correct language, which is a WCAG requirement.
**NOTE:** I also hard-coded the bank holidays experiment panel to always use the English language version of the nation names. This is because all the rest of the copy is hard …
> Add lang attributes to bank holidays page

- app/views/place/show.html.erb
We no longer seem to have styles for this class and we currently end up with a list item disc outside the main container. We swap this class with a standard `govuk-list` to remove the disc. Follow up on https://github.com/alphagov/frontend/pull/2743.
<table>
</td></tr>
</table>
> Replace deprecated class for places

- app/views/homepage/_categories.html.erb
TRELLO: https://trello.com/c/h76ocT31/2235-change-visas-and-immigration-browse-description-on-govuk-homepage
CHANGED
Visas, asylum and sponsorship
TO
Apply to visit, work, study, settle or seek asylum in the UK
REASON
This will help people who don't understand the words 'visas' and 'immigration' to understand better what is in this browse section. The new description also matches the new structure of the Visas and immigration browse section.
> Change Visas & Immigration blurb

- app/presenters/machine_readable/yaml_faq_page_schema_presenter.rb
- app/views/transaction/show.html.erb
- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
- test/support/schema_org_helpers.rb
Voting closes at 10pm on 6 May. We want to not show the custom FAQ schema after that point, as it'll be out of kilter from the published content. I've added an expiry date to the yaml which might be something we want to reuse in the future.
The publication of the content update will invalidate the cache for this page, so it'll be pretty up to date.
> Remove the register to vote custom schema once voting closes

- app/controllers/sessions_controller.rb
- test/integration/sessions_test.rb
account-api is also set up to pass this along to the account manager
when authenticating users; but the account-manager has it disabled,
and the account-api isn't enforcing levels yet.
---
[Trello card](https://trello.com/c/G2uYUDuz/716-check-the-level-of-authentication-when-using-attributes-in-the-account-api)
> Pass level_of_authentication parameter to account-api

- app/views/simple_smart_answers/_current_question.html.erb
~🙅🏻‍♀️ Do not merge, depends on https://github.com/alphagov/govuk_publishing_components/pull/2051 🙅🏻‍♀️~ 
Simple smart answers use [the radio component](https://components.publishing.service.gov.uk/component-guide/radio) with the `is_page_heading` parameter. 
Some changes are being made to remove the `is_page_heading` parameter, and achieve the same result using `heading_level` and/or `heading_size` instead. The reasons behind this are described in more detail in [this issue](https://github.com/alphagov/govuk_publishing_components/issues/1953).
In this particular case, `is_page_heading: true` can simply be replaced with `heading_level: 1` without causing any visual changes. …
> Use `heading_level` param instead of `is_page_heading` (radio component)

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/nPAGEeOq
Update travel advice callout box on `/foreign-travel-advice` to show the rule changes from Monday 17th May
|Before|After|
|-------|-----|
|<img width="1648" alt="Screenshot 2021-05-14 at 16 11 50" src="https://user-images.githubusercontent.com/5793815/118291416-7dfe9b80-b4cf-11eb-94af-84339bd228ab.png">|<img width="1648" alt="Screenshot 2021-05-14 at 16 12 15" src="https://user-images.githubusercontent.com/5793815/118291437-8525a980-b4cf-11eb-934d-4a609fc20e64.png">|
The new advice should start to be displayed from 00:00 on Monday 17th May.
> Add travel advice updates for 17th May 2021

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
Now that we have multiple levels of authentication, the user can be
logged in and still get sent to the /sign-in path.  Rather than try to
do anything clever (like extracting the current level of
authentication from the session and comparing it with the desired),
just always send the user to auth.  If they have a valid session for
the account manager they'll get redirected back to the callback path
immediately.
This also fixes an inconsistency where
GET /sign-in?redirect_path=/foo
Would send you to the account manager if logged in; but if not
authenticate you and send you to www.gov.uk/foo.
> Always send the user to authenticate from /sign-in

- app/assets/javascripts/views/save-location.js
On the bank holidays page save nation script, swap the `replaceAll()` string method for the `replace()` method with a global flag.
The `replaceAll()` method is [not supported in any version of IE](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility) which is causing an error. 
As a consequence, on Internet Explorer the save nation panel currently reads "Do you want to save # as your location for bank
holidays" instead of e.g "Do you want to save Scotland as your location for bank holidays".
----- 
> Fix JS crossbrowser compatibility issue

- app/assets/javascripts/views/save-location.js
~~**DON'T MERGE - relies upon a new version of the gem with https://github.com/alphagov/govuk_publishing_components/pull/2041 first**~~ 
Done and rebased
Updates the save location bank holidays experiment code so that if users consent to cookies on that page, the functionality immediately appears. Before, it wouldn't appear unless users refreshed the page, because it depended on cookie consent to work.
None, but you can test that it works properly by loading up the `/bank-holidays` page, clearing cookies and reloading. The cookie banner should be present, the save location option not. Consenting to cookies should …
> Start save location on cookie consent

- app/views/roadmap/index.html.erb
Increase the spacing between list items on the roadmap page by adding the `govuk-list--spaced` class.
To improve readability.
Before | After
------ | ------
> Increase spacing on roadmap lists

- app/views/homepage/index.html.erb
Wrap the `homepage.index.merged_websites` in the `raw` method to avoid the HTML contained in the translated string being sanitised.
> Wrap translation in `raw` to avoid sanitised HTML

- app/views/homepage/index.html.erb
> Fix raw HTML output on GOVUK homepage

- app/views/calendar/bank_holidays.html.erb
- app/views/help/ab_testing.html.erb
- app/views/homepage/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
In #2767, strings containing HTML were moved out of the views and into locale files.
Some have the `raw` method applied, but others do not, so the HTML will be escaped and output to the user.
Changing the locale key suffix to contain `_html` will [mark these as HTML Safe](https://api.rubyonrails.org/classes/ActionView/Helpers/TranslationHelper.html#method-i-translate).
[Trello card](https://trello.com/c/HXNiLKQx)
> Mark locale keys containing links as HTML safe

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
This was used by finder-frontend, but now finder-frontend is
constructing the auth URL itself by calling account-api
directly (rather than redirecting the user via frontend), so this
param is not needed here.
See https://github.com/alphagov/finder-frontend/pull/2524
> Remove state_id param from sessions controller

- app/controllers/application_controller.rb
- app/controllers/save_pages_controller.rb
- app/controllers/sessions_controller.rb
- config/routes.rb
- test/functional/save_pages_controller_test.rb
[Trello](https://trello.com/c/FkH145rh/773-add-endpoints-to-frontend-to-save-and-unsave-a-page)
For an unauthenticated session:
- redirect the user to try and sign in
- on success bring them back to try and save a page
For an authenticated session:
- recieve a get request to `/account/saved-pages/add?page_path=/foo`
- save the page through a PUT request to the account-api
- redirect the user to that page
Then also a remove route:
- recieve a get request to `/account/saved-pages/remove?page_path=/foo`
- save the page through a DELETE request to the account-api
- redirect the user to that page
See also: …
> Add save page routes

- app/controllers/save_pages_controller.rb
- test/functional/save_pages_controller_test.rb
This prevents an exception being thrown by calling `.path` on `nil`.
> Return a 422 error if `params[:page_path]` is `blank?`

- app/controllers/save_pages_controller.rb
- test/functional/save_pages_controller_test.rb
account-api returning a 422 means that the user tried to save an
invalid path.
If this happens to a legitimate user (i.e., they haven't tampered with
the URL trying to break our stuff) then this is a bug in whatever page
had the button, in which case we *want* users to open support tickets
saying "I tried to save a page but got an error!"
If this happens to a user who has tampered with the URL, it's their
own fault.
We might want to return a `page_not_saved` flag to the page if
account-api returns a 5xx error code, because that likely indicates a
transient problem.  Though in that case we should do some more path
validation in this app.
> Return a 422 error when saving a page if the account-api does

- app/views/homepage/index.html.erb
- config/locales/en.yml
We have had to [update this number a lot][1].
Generally I think it looks really bad for our home page to have one
number, that you then click to find out the real number is
different. It's probably not a massive thing, but it bugs me and makes
us appear inaccurate, something to be avoided when we're shooting for
high levels of trust.
I've tried different ways of solving this.
[PR #2692](https://github.com/alphagov/frontend/pull/2692) tried an
approach of getting the number from the content data API for
`/api/government/organisations` and then counting the entries.
This works, but runs into a few issues that are documented on the PR.
The biggest one is that we would then be making two calls to the content
API, one for the home page and one for this. Our Architectual aspiration
here is to …
> Hard code Agencies and other public bodies to 400+

- app/views/homepage/index.html.erb
- config/locales/en.yml
www.gov.uk/transition is now www.gov.uk/brexit
https://trello.com/c/wxR5o06H/1539-implement-brexit-landing-page-url-change
> Update Brexit links

- test/functional/save_pages_controller_test.rb
- test/functional/session_controller_test.rb
- test/support/session_helpers.rb
Version 0.4.0 of the `govuk_personalisation` gem implemented this helper
so we don't need to define it here anymore. We just need to include
`GovukPersonalisation::TestHelpers::Requests` instead.
Trello card: https://trello.com/c/HpMFjE5Q/784-add-test-helpers-to-govukpersonalisation
> Use govuk_personalisation's mock_logged_in_session

- app/views/homepage/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
The non-breaking space in a translation is being exposed to users (albeit visually hidden, so many users don't see it).  Wrapping in `raw` as we know the string is safe.
[Trello card](https://trello.com/c/WcUqwDjJ)
> Fix exposed HTML from translation

- app/controllers/calendar_controller.rb
Calendar controller doesn't need the slimmer_template value, as it's set in the application_controller.
> Remove unnecessary slimmer_template value

- app/views/help/cookie_settings.html.erb
- config/locales/en.yml
Adds information about our use of Speedcurve/LUX Real User Monitoring. 
As a result, I added a key and also renamed a key to reflect it being more general. 
[Trello](https://trello.com/c/j74aBDrA/2555-1-update-cookie-settings-page-following-introduction-of-real-user-monitoring)
> Adds mention of Speedcurve/Lux to cookie settings

- app/controllers/sessions_controller.rb
- test/integration/sessions_test.rb
This validation matches that in account-api, so it will also reject
these paths with a 422 error.  However, we had an incident with
account-api rejecting paths too strictly, and so have decided to start
treating 422 errors from account-api as important for our SLO.
Since we control all the account-api clients (other GOV.UK apps), this
is pretty reasonable, as other GOV.UK apps shouldn't be sending us
invalid data.
However, there are a few places where user input is passed directly to
the account-api, and we need to account for a user tampering with
these:
- redirect_path (or referer) in the sign in controller: we can
duplicate the validation from account-api.
- code & state params in the auth callback controller: if invalid,
these return a 401, not a 422 - so that's fine.
- page_path in …
> Add redirect_path validation to the SessionsController

- app/views/homepage/_categories.html.erb
The translation for the 'Disable people' category description was set to the same as the title - this fixes the typo.
The description was being erroneously omitted.
Before:
After:
> Fix homepage description for 'Disabled people' category

- app/assets/javascripts/application.js
- app/assets/javascripts/test-dependencies.js
- spec/javascripts/support/jasmine.yml
Removes the JavaScript that is already loaded by Static.
Update test dependencies JavaScript.
This duplication meant that the search toggle wasn't working, as the script was being initialised twice. This meant that a single click would open and the instantly close the search.
Tests dependencies have been updated to ensure that the JavaScript that is loaded by Static is still available for the tests in Frontend.
None.
---
> Dedupe JavaScript to stop it being loaded twice

- Gemfile
- Gemfile.lock
This will allow us to export the translation keys that need translating.
[Trello card](https://trello.com/c/ifbyj6pJ)
> Add Rails Translation Manager as development dependency

- .github/dependabot.yml
- Gemfile.lock
This fixes an issue where running `./startup.sh --live` can fail because `pact_broker-client` seems to (rather surprisingly) try to read files from $HOME when a developer is using rbenv - see https://github.com/pact-foundation/pact_broker-client/issues/88 for more information.
As we use pact as a testing framework, I've added the gems for that into the dependabot file to monitor for updates to the gems.
> Bump pact_broker-client to fix $HOME access issues and add it to Dependabot

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
Originally we planned for this to be the only place which construct an
OAuth auth URI, and other apps which need to sign the user in would
redirect via https://www.gov.uk/sign-in?redirect_path=...
We've since changed that approach, with other apps calling account-api
to get a sign in URI directly.  So we can remove these parameters, as
they're unused.
> Remove redirect_path and level_of_authentication from sign in

- app/assets/stylesheets/views/_homepage.scss
The "Popular on GOV.UK" links on the homepage have the govuk grey colour on hover, which is adequate in terms of minimum contrast requirements against the black background.
This text colour is not adequate, however, against the yellow background in the `:focus:hover` state. This makes the CSS more specific, so that the grey colour change only applies when the element is hovered, but not in focus.
> Fix :focus:hover link colour for homepage links

- app/assets/javascripts/views/save-location.js
- app/views/calendar/_save_location.html.erb
- app/views/calendar/bank_holidays.html.erb
- spec/javascripts/unit/save-location.spec.js
Update code for location experiment so that England and Wales tab will be automatically selected when the user nation cookie has been set to "England" _or_ "Wales" (currently `#england-and-wales` will be appended to the URL only when the value of the cookie is "England_and_Wales")
This change is a step towards making the method of remembering a user's location preference more reusable across GOVUK.
https://trello.com/c/s3EMiQXS/845-bank-hols-iterations-for-reuse-by-coronavirus
------
> Adjust bank holidays locations code

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
- test/unit/presenters/local_transaction_presenter_test.rb
If the user has saved cookie preferences, apply them after logging in.
Won't have any effect until https://github.com/alphagov/govuk-puppet/pull/11189 is deployed, as our varnish config removes cookies currently.
> Set cookies_policy after sign in

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_accounts.scss
- app/controllers/account_home_controller.rb
- app/helpers/application_helper.rb
- app/views/account_home/show.html.erb
- app/views/application/_account-navigation.html.erb
- app/views/application/_user-reminders.html.erb
- app/views/layouts/application.html.erb
- config/locales/en.yml
- config/routes.rb
- test/functional/account_home_controller_test.rb
Move the "Your account" page from the account manager to `gov.uk/account/home`.
This is desirable because the account manager prototype will go away when we migrate to Digital Identity, so we'll need this at some point. It is also potentially necessary for upcoming work on saved pages and/or single page notifications – because we're storing the saved pages in the `account-api`, not the attribute service prototype. 
Visually, there should be no difference between this "new" account home page and the "old" one on `govuk-account-manager-prototype`.
-----
https://trello.com/c/lIDQNATi/813-implement-the-govuk-account-home-page
Co-authored-by @barrucadu and @huwd 
----
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/develop …
> Add account homepage 

- app/assets/stylesheets/views/_homepage.scss
The "Popular links" on the homepage are over a blue background on mobile, and a black background otherwise. 
The text has a grey colour on the active state, which [does not meet minimum contrast requirements](https://webaim.org/resources/contrastchecker/?fcolor=B1B4B6&bcolor=1D70B8) against the blue background. 
This eliminates the special styling for `:active` on the mobile variant, which ensures these links are more in line with the way we style white links over a blue background in other areas on GOVUK (for example [here](https://www.gov.uk/coronavirus))
Active on blue background before | Active on blue background after
------------ | -------------
The minimum contrast requirement is also not achieved in the `:active:focus` state on desktop:  the text is grey over a
yellow background …
> Popular links CSS states adjustments

- app/views/application/_user-reminders.html.erb
- test/functional/account_home_controller_test.rb
Change the path from `/confirmation/new` to `/account/confirmation/new` because that's what's correct.
> Update resend confirmation email link path for account home

- app/controllers/application_controller.rb
- test/functional/session_controller_test.rb
Addressable::URI doesn't handle repeated parameters, which we often
get in the Transition Checker:
Addressable::URI.parse("https://www.foo.com?a=1&a=2").query_values
=> {"a"=>"2"}
So this means we've been redirecting users back to the wrong results
page from the post-registration confirmation page, only showing
the *last* criterion.  We're still saving the right results, as that's
done as part of the registration journey, but that is going away
imminently, and so this is about to become a more significant problem.
> Do not use Addressable::URI to manipulate querystring

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_accounts.scss
- app/views/application/_user-reminders.html.erb
- config/locales/en.yml
This updates the email confirmation reminder on the `/account/home` page to use the gov.uk [notice component](https://components.publishing.service.gov.uk/component-guide/notice) instead of the previously used grey banner. 
It also updates the copy to make it clearer for the user. This is another step in the efforts to [unbodge the Brexit checker](https://docs.google.com/document/d/1xRdT56CgAF__c_Yjzdy6UuR0LacXIt0EACRonEgbUiM/edit?ts=60eea456#) 😄.
> Update user reminder to confirm email

- config/locales/en.yml
This updates homepage text for `Employing people` and `Working, jobs and pensions`.
Before
After
[trello](https://trello.com/c/11uTpS9W/2618-update-browse-page-descriptions-on-homepage)
> Update browse page descriptions for homepage

- app/views/local_transaction/devolved_administration_service.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- test/integration/local_transactions_test.rb
Trello: https://trello.com/c/KiHIycIv/505-update-references-to-northern-ireland-in-local-lookups
We have standard content for devolved administration results in local lookups, but we need to change the content for how we refer to the Northern Ireland Government is not technically a government so it is factually incorrect to call it that. Executive is right.
This means we will need to make unique content for the name of each nation.
|Scotand|Wales|Northern Ireland|
|--------|------|----------------|
|<img width="684" alt="Screenshot 2021-07-20 at 10 34 36" src="https://user-images.githubusercontent.com/5793815/126299424-240b574b-7450-4d9d-ba58-95a73b983e5f.png">|<img width="684" alt="Screenshot 2021-07-20 at 10 34 20" src="https://user-images.githubusercontent.com/5793815/126299430-d06717a1 …
> Update local transaction country references

- app/controllers/local_transaction_controller.rb
The missing country name was causing a number of errors in Sentry [1],
leading to the Northern Ireland page [2] returning a generic GOV.UK 503
page:
```
We're experiencing technical difficulties. Please try again later.
```
The change that caused this bug seems to be when we added functionality
for determining a devolved administration availability [3].
[1]: https://sentry.io/organizations/govuk/issues/2535481416/events/latest/?environment=production&project=202225&referrer=slack
[2]: https://www.gov.uk/contact-electoral-registration-office/electoral-office-for-northern-ireland
[3]: https://github.com/alphagov/frontend/commit/3d076052f5a49480fe006458d4cf76b0f2cd5031#diff-8157218d73a5aeabab17ed84e0cf19d850abd378b8c1acccb0bbe80f302e4f31R33-R35
⚠️ This repo is Continuously Deployed: make …
> Adds country name for Northern Ireland

- app/controllers/application_controller.rb
- app/controllers/concerns/explore_menu_ab_testable.rb
- app/controllers/homepage_controller.rb
- test/functional/calendar_controller_test.rb
- test/functional/homepage_controller_test.rb
At present we're only returning Vary response headers when we get a B variant. We want to do this all the time or it's confusing for Fastly to know how to cache.
I've added tests for the other variants to make sure it's working everywhere.
Added a separate test for the home page as it uses a different template.
The template assertion wasn't working - it was doing an `assert` on the template name and ignoring the second param. I've changed that to an `assert_equals` and made the test work.
> Return AB response headers with all variants

- app/assets/javascripts/application.js
Simplify JavaScript imports and follow convention as [documented in the components library](https://github.com/alphagov/govuk_publishing_components/blob/master/docs/install-and-use.md#import-javascript-for-individual-components).
This means:
- we can use `govuk_publishing_components/lib` which contains all the listed `lib` files and `vendor/polyfills`
- since `govuk_publishing_components/analytics` (including `explicit-cross-domain-links`) are already required by static there's no need to add any analytics-related scripts at the application level
Similar to #2499.
> Clean-up JavaScript imports

- app/controllers/account_home_controller.rb
- app/views/account_home/show.html.erb
- test/functional/account_home_controller_test.rb
Set the Account pages template to always be `gem_layout_account`, regardless of
which A/B variant the user is.
The explore menu doesn't have the sign in / sign out / account links - these are needed by the people who want to use their GOV.UK account.
---
> Exclude the Accounts pages from menu A/B test

- README.md
- docs/calendars.md
- startup.sh
Updates README in favour of GOVUK Docker and limits startup script to only operate in live mode.
[trello](https://trello.com/c/Psf7EzPB/204-move-away-from-startupsh)
> Update readme and startup.sh script

- app/views/travel_advice/index.html.erb
**DO NOT MERGE** This change depends upon a new version of the components gem that includes this change: https://github.com/alphagov/govuk_publishing_components/pull/2263
- adds tracking of links only to the foreign advice travel box on /foreign-travel-advice
- should track link clicks using the options on the box and use the link text for the event label
We want to know how effective this box is.
None.
Trello card: https://trello.com/c/Q6kr2nFK/551-add-ga-tracking-codes-to-fcdo-call-out-box-of-covid-info
> Add tracking to the foreign travel advice call out box

- app/views/completed_transaction/show.html.erb
- config/locales/en.yml
- test/integration/completed_transaction_test.rb
Updates the text displayed on specific completed Transaction pages
Removes an unnecessary extra right angle bracket
[Trello](https://trello.com/c/yqxZxXn8/)
BEFORE:
AFTER:
> Update electric car message on specific Done pages

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
When using our account manager, this returns
`Plek.find("account-manager")/sign-out?continue=1`, so the redirect is
unchanged.  But when using DI, it uses the end-session endpoint from
the OIDC metadata.
---
[Trello card](https://trello.com/c/ZvDGaba4/958-use-di-auth-in-integration-give-feedback-on-their-documentation)
> Use new account-api end-session endpoint for logging out

- app/assets/javascripts/modules/track-submit.js
- spec/javascripts/unit/modules/track-submit.spec.js
Trello: https://trello.com/c/Wnq8l7Oo
Removes jQuery from modules/track-submit.js in Frontend.
Also changes the module to be initialised with an `init` method rather than a `start` method.
jQuery is being removed from GOV.UK.
The changes were tested by visiting `/find-local-council` locally. 
The "postcodeSearchStarted" event still fires after the changes:
> Remove jQuery from track-submit.js

- app/views/calendar/bank_holidays.html.erb
Remove redundant `govuk-width-container` class and the associated element.
`govuk-width-container` is already generated by the main layout file. Applying this class to two nested elements results in excessive padding on narrow screens.
[Simplified code diff](https://github.com/alphagov/frontend/pull/2941/files?diff=split&w=1)
[Page preview](https://govuk-fronte-remove-red-723rwb.herokuapp.com/bank-holidays)
No changes on wide screens.
<table>
</td></tr>
</table>
> Remove redundant govuk-width-container class

- app/assets/javascripts/modules/cookie-settings.js
- spec/javascripts/unit/modules/cookie-settings.spec.js
Trello: https://trello.com/c/hKWh8Mjy/590-remove-jquery-from-frontend-modules-cookie-settingsjs-low-js-experience-required
This is part of an ongoing effort to remove jQuery from the GOV.UK
public tech stack. This file was already written largely without a
jQuery dependency so this was a simple conversion.
> Remove jQuery from modules/cookie-settings.js

- app/assets/javascripts/modules/track-smart-answer.js
- spec/javascripts/unit/modules/track-smart-answer.spec.js
Trello: https://trello.com/c/CBfKxNTs
Removes jQuery from modules/track-smart-answer.js in Frontend.
Also changes the module to be initialised with an `init` method rather than a `start` method.
jQuery is being removed from GOV.UK.
The changes were tested by visiting `/settle-in-the-uk` locally. 
The "Completed" event still fires when the outcome is reached with the changes:
> Remove jQuery from track-smart-answer.js

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_homepage.scss
- app/views/homepage/index.html.erb
Applies the [big number component](https://components.publishing.service.gov.uk/component-guide/big_number) to the homepage and removes custom code which handled this pattern previously.
To make use of our new big number component to reduce repeated implementation of this pattern. See https://github.com/alphagov/govuk_publishing_components/issues/2221 for more details.
| --- | --- |
| ![Screenshot 2021-09-23 at 14 46 22](https://user-images.githubusercontent.com/64783893/134540723-c313ca59-6b8d-4e1e-bfe3-c46907337daf.png) | ![Screenshot 2021-09-23 at 14 46 29](https://user-images.githubusercontent.com/64783893/134540773-fa11eb4b-071a-4c9e-9181-ee33bee2dc61.png) |
> Apply the big number component to the govuk homepage

- app/views/place/_option.html.erb
- test/integration/place_test.rb
https://trello.com/c/i5zmwoxs/847-page-result-does-not-have-headings
Change markup for search result place name from `span` to a heading (`h3` to maintain document outline)
- The results of https://www.gov.uk/find-theory-test-centre does not have headings. This makes it hard to understand the structure of the page
- WCAG fail of 1.3.1 Info and relationships (A) - Content structures like tables, lists and headings should be communicated visually and they must also be communicated in ways that assistive technologies can understand
- Ensure headings can be identified visually and with assistive technologies.
<table role="table">
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" …
> Add headings to search results

- config/routes.rb
- test/integration/sessions_test.rb
We're going to publish the sorting hat page at /sign-in, so we need a
different route for the OAuth redirect.
The old route still exists so that we can deploy this change with zero
downtime.
---
[Trello card](https://trello.com/c/P8JbW0T8/1048-move-oauth-sign-in-start-page-from-sign-in-to-sign-in-redirect)
> Add /sign-in/redirect route for sessions#create

- app/views/roadmap/index.html.erb
replaces the values at the bottom of [the govuk roadmap](https://www.gov.uk/roadmap) with instances of the [big number component](https://components.publishing.service.gov.uk/component-guide/big_number).
To ensure we are reducing the number of custom implementations of the big number pattern.
This change has been approved by page designers.
| --- | --- |
| <img width="991" alt="Screenshot 2021-09-29 at 11 42 59" src="https://user-images.githubusercontent.com/64783893/135255117-d868f20f-1d42-47e9-a817-4fa5d22dfaa7.png"> | <img width="1003" alt="Screenshot 2021-09-29 at 11 42 51" src="https://user-images.githubusercontent.com/64783893/135255262-33fd064f-9cb5-4797-93aa-efb67df6bf12.png"> |
> Add the big number component to the govuk roadmap page

- app/views/travel_advice/index.html.erb
[Trello](https://trello.com/c/fzN6TU9L/660-fcdo-top-grey-box-update-to-reflect-new-travel-roles-october-4th)
- Update red list country link
- Update 'return to England' link
Note to reviewer - my local set up is broken and taking a while to fix... so please run locally and add a screen shot. Otherwise we can test on integration...
> Update COVID travel links

- Gemfile.lock
- app/views/local_transaction/search.html.erb
- app/views/transaction/show.html.erb
The previous version of the intervention component would render a banner even if no parameter was passed.
This behaviour has now changed as of govuk_publishing_components v28.1: if no parameter is passed then
then no banner is rendered. Hence previous tests failed.
We've now added the `suggestion_parameter` test to the component usage in the tests so that the component 
still gets rendered as needed
> Update intervention usage

- app/assets/stylesheets/application.scss
- app/controllers/help_controller.rb
- app/views/help/sign_in.html.erb
- config/locales/en.yml
- config/routes.rb
🙏🏼 **_Do not merge for now_** 🙏🏼
-----
Build custom frontend, in the `frontend` app, for the "sign in to a service" (aka "sorting hat") page.
The HTML body will be defined in the content item (so it can appear in search). The body of the content of this page has been added to `account-api` together with a rake task to publish the page: https://github.com/alphagov/account-api/pull/240/
A notable feature of this new page is the search form at the bottom. 
This search form is a regular site search, with the notable difference being that the results should be filtered by content type `services` and `guidance_and_regulation`.
-----
[Preview this page on integration](https://www.integration.publishing.service.gov.uk/sign-in)
----- …
> Sign in to a service page

- .dockerignore
- Dockerfile
This PR streamlines the Frontend image by installing dependencies
etc in a new intermediate `builder` stage, before copying back the build
outputs to the output image.
We add a .dockerignore to omit files and directories which aren't needed
at runtime.
We set RAILS_ENV to production and remove HEALTHCHECK and PORT (since
these are not used in Kubernetes and would only serve to add ambiguity).
For now, the compiled Rails assets are still included in the output
image, even though they're unlikely to be of much use. We'll need assets
to be uploaded to a static serving service as a deployment step,
otherwise rolling updates won't be possible (because each pod would only
have the assets from its own version, not the next/previous version).
Alternatives considered: We tried using the Bitnami …
> Streamline Frontend image

- .github/dependabot.yml
- Gemfile.lock
Trello:
https://trello.com/c/rFcKFuXv/2521-add-railstranslationmanager-to-dependabot-configuration
> Bump Rails Translation Manager version and enable Dependabot

- app/views/help/cookie_settings.html.erb
This PR removes an errant colon from the cookie_setting page
> Correct typo in cookie_settings page

- app/assets/stylesheets/views/_accounts.scss
- app/controllers/account_home_controller.rb
- app/views/account_home/show.html.erb
- config/locales/en.yml
- test/functional/account_home_controller_test.rb
- test/integration/account_home_test.rb
So it shows users' information about their email subscriptions, if they
have any, as well as their Brexit checker results.
Previously, the only service users could use their GOV.UK account for
was the Brexit checker. If they hadn't saved their checker results to
their account, the home page showed a prompt to use the Brexit checker.
Now users will also be able to sign up for email notifications with
their GOV.UK account so it's not correct to show the "You have not used
your account to access any services yet" message if they've not used the
Brexit checker.
We are treating email subscriptions in a slightly different way to other
services that might use the GOV.UK account, which is why I've added a new
helper method to check if a user has subscriptions rather than using the
existing …
> Update account home page for email subscriptions

- README.md
- app/services/electoral_service.rb
- config/routes.rb
- docs/elections-api.md
Tweaks monitoring so that we can track all status codes received from the API
Activates use of the Electoral Commission's API in production by using the real route for the `/contact-electoral-registration-office` page. 
If this route is commented out, then we will fall back to using the standard `LocalTransactionController` for this service again (and therefore uses links from local-links-manager again).
> Activate use of Elections API

- app/assets/stylesheets/views/_homepage.scss
Increase line height of the main title on the homepage.
This makes the title more legible when wrapped onto two lines on small screens.
| Screen size | Before | After |
| - | - | - |
| 320px | ![](https://user-images.githubusercontent.com/1732331/143036389-bc176f8f-71ee-4aa3-a152-ac5a0f3e9032.png) | ![](https://user-images.githubusercontent.com/1732331/143036284-45a2e153-7e02-41b0-b5e7-fb7bcee34115.png) |
| 375px | ![](https://user-images.githubusercontent.com/1732331/143036439-07424e9e-9dee-477b-b3e2-1ebf8aa662fd.png) | ![](https://user-images.githubusercontent.com/1732331/143036234-c8b0825c-430b-4ef0-b4c6-9123229b71e4.png) |
| 768px | ![](https://user-images.githubusercontent.com/1732331/143036488-42387e03-d601-44f2-bc45-8797fae55a42.png) | …
> Adjust line height on homepage title

- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
Pages like:
- [the results page](https://www.gov.uk/contact-electoral-registration-office?postcode=BT1+1AA)
- [the address picker page](https://www.gov.uk/contact-electoral-registration-office?postcode=WV14+8TU)
aren't presenting quite right. There's insufficient padding, and navigation's not showing.
Pages in review app:
- [two results](https://govuk-fronte-update-bas-y8ppnb.herokuapp.com/contact-electoral-registration-office?postcode=IV1+1AH)
- [one result](https://govuk-fronte-update-bas-y8ppnb.herokuapp.com/contact-electoral-registration-office?postcode=w1a1aa)
- [address picker](https://govuk-fronte-update-bas-y8ppnb.herokuapp.com/contact-electoral-registration-office?postcode=wv148tu) …
> Use the shared base_page for electoral pages

- config/locales/cy.yml
This key was corrupted on export and then re-imported in the
translations work [1]. This commit correctly formats the key's list
items with the Welsh translations.
[1]: https://github.com/alphagov/frontend/pull/3040
Trello:
https://trello.com/c/Xz78vNR4/2757-import-newly-sourced-translations-into-locale-files-5
> Fixes corrupt key

- app/controllers/application_controller.rb
- test/functional/transaction_controller_test.rb
- test/integration/homepage_test.rb
The Rails locale is not a request-local property, it's a thread-local
property.  So if two requests are served by the same thread, where the
first request sets the locale to something non-default and the second
does not set it at all, the second request will use the same
non-default locale as the first one.
This is described in the i18n docs:
https://guides.rubyonrails.org/i18n.html
The homepage controller does not set the locale, and so if a user
views a Welsh content item and then the same thread is used to serve
the homepage, the homepage will use the Welsh locale.  This isn't a
new problem, but it didn't cause any issues, because Rails falls back
to the default locale (English in our case) if a translation is
missing, and we didn't have translated content for the homepage.
fe2b0b7 …
> Fix leaky locale assignment

- app/assets/stylesheets/views/_homepage.scss
Removes the duplicate border between topics and government activity / departments and organisations.
The spacing is being sorted out separately.
One border is enough.
Before:
After:
---
> Remove duplicate border

- app/controllers/account_cookies_and_feedback_controller.rb
~**Do not merge**: depends on [release 3906](https://release.publishing.service.gov.uk/applications/static/deploy?tag=release_3906) of `static` which is not in production yet.~
------
A new template has been added in static which allows us the option to render the account layout with "Manage your
account" selected/active in the account nav, instead of the default "Your account".
This updates the cookie and feedback page to request the new template instead of the default **gem_layout_account_manager** one. The only difference should be that "Manage your account" will be selected in the account nav element instead of "Your account".
-------
https://trello.com/c/uDkZ90GE …
> Update account layout on "cookies and feedback"

- app/helpers/application_helper.rb
- app/views/account_home/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- test/integration/account_home_test.rb
The Brexit checker is being retired at the end of the month. Remove the
card about it from the account home page so we're not directing users to
do something that's no longer possible.
Getting this PR ready ahead of time so it can be reviewed and ready to merge when we've decided on the right time.
[Trello](https://trello.com/c/jUukpLeb/1170-remove-brexit-checker-service-card)
> Remove Brexit checker card from account home

- app/views/account_home/show.html.erb
Add data attributes for click tracking on the Manage your GOV.UK email
subscription link on the account homepage.
Attribute values are from the [Events for single page notifications](https://docs.google.com/spreadsheets/d/14ALXXvi6w6a0qmnJJij_pNv7tjyJfuARC2-OAJzguDA/edit?usp=sharing) doc.
> Add missing attributes for tracking

- docs/calendars.md
- Clarify which machine to run the rake task on
- Describe how to run rake task on production, before describing how to run it locally (more likely to need the former than the latter)
- Be explicit about which pages get updated via the task
- Remove general comment about how search indexing works.
Trello: https://trello.com/c/cX3nmA5o/2766-add-bank-holidays-and-clock-change-dates-for-2023
> Update calendar publishing instructions

- app/controllers/account_home_controller.rb
This attribute is no longer relevant since we switched to using DI's SSO
service - they require users to confirm their email address as part of
the account creation journey.
These helper methods aren't being used in the account home view, so
this commit has no affect on the behaviour or appearance of this app.
[Trello](https://trello.com/c/SdkcF8EO/13-remove-hasunconfirmedemail-attribute)
> Remove uses of `has_unconfirmed_email`

- app/views/homepage/_links_and_search.html.erb
Convert the grey links and search section on the new homepage from 3 columns (2 thirds and 1 third) to 2 columns (50/50). 
Additionally updates the tracking dimension for the search box.
So that the search box on small desktop screens (from 850px to 770px approx) doesn't look squashed.
[Card]()
> Convert the links and search section on the new homepage from 3 columns to 2 columns on desktop

- config/locales/en.yml
It's pointing to the wrong finder.
> Fix link to Policy Papers and Consultations

- app/assets/stylesheets/views/_homepage.scss
Change the number of grid items under the government activity section of the homepage from 5 to 6.
On IE11, you need to explicitly specify the number of items in a grid in order for the grid to render properly. This had been missed in a recent addition and was causing IE11 and below to look weird.
> Set the correct number of items for the government activity section on IE11

- app/assets/stylesheets/views/_homepage.scss
Explicitly set the left, right and bottom borders on the `home-promo__image` class to `none`.
On IE10, there's a CSS quirk where if you define a border on one side of an image but don't specify the other sides, it presumes you want borders on every side.
Fixes https://github.com/alphagov/frontend/issues/3083
> Fix borders on homepage promo images on IE10

- app/views/help/ab_testing.html.erb
The page was missing the grid row element
<table>
</td></tr>
</table>
> Fix A/B testing page layout

- config/locales/en.yml
Trello: https://trello.com/c/xq7VxkQE
1. Change the 'Popular on GOV.UK' coronavirus link text from 'Coronavirus (COVID-19): guidance' to 'Coronavirus (COVID-19)'
2. Change the URL from https://www.gov.uk/guidance/covid-19-coronavirus-restrictions-what-you-can-and-cannot-do/ to https://www.gov.uk/coronavirus
> Update coronavirus popular link

- app/views/help/cookie_settings.html.erb
Reworks how the grid is used on the cookie page to be semantically correct.
Fixes https://github.com/alphagov/govuk_publishing_components/issues/2202
> Apply correct grid markup to cookie page

- app/views/help/cookie_settings.html.erb
- config/locales/cy.yml
- config/locales/en.yml
This commit implements changes as requested by the Content team for the Cookies setting page.
Supersedes #3022, which has the same changes but due to the age of the PR, also a number of conflicts. I've opened this separate PR so that we have a proper audit trail of the original intended changes vs the actual changes now we've rebased.
Trello: https://trello.com/c/6wk5iHFW/2776-deploy-17-dec-update-cookies-on-govuk-3
> Update 'Cookies on GOV.UK'

- config/locales/en.yml
Change the text on the COVID-19 vaccinations feature so it becomes more of a call to action for the booster campaign. 
Change: 'Get information about vaccinations on NHS.UK' -> 'Book your coronavirus vaccination and booster dose on the NHS website.'
[Trello](https://trello.com/c/huvOpElN/483-placeholder-booster-campaign-update-text-on-covid-homepage-feature)
> Change text of COVID promo

- app/views/account_home/show.html.erb
- config/locales/en.yml
- test/integration/account_home_test.rb
People were confused in some rounds of usability testing. Add some
explainer text to help them understand what the account is for.
[Trello](https://trello.com/c/bywGnxif/1189-add-explainer-text-to-account-home-to-help-explain-link-between-email-subscriptions-and-govuk)
---
New page (details closed):
---
Details open:
---
> Add explainer text to account home page

- config/locales/cy.yml
Small change to Welsh translated start pages, changing 'ymlaen' to 'ar'.
Trello: https://trello.com/c/o3TcyQ2G/2817-change-wording-on-welsh-translated-start-pages
> Change welsh "will_continue_on" translation

- app/controllers/sessions_controller.rb
- app/views/sessions/first_time.html.erb
- config/routes.rb
- test/functional/session_controller_test.rb
This commit moves the first-time form from the /sign-in/callback
endpoint to a new /sign-in/first-time endpoint, and redirects to it if
needed.
This has a couple of benefits:
1. The callback endpoint is now simpler: it either throws an error or
redirects.
2. Refreshing the form will no longer re-validate the code & state
parameters.
The downside is that we need a way of passing the session header value
from the callback endpoint to the form *without* logging the user in,
as they're not actually logged in until they submit it.  I've solved
this problem by storing the value in the header, but with a prefix,
which means account-api will be unable to decode it if the user
wanders off to another page and tries to use their account.
---
[Trello …
> Move first-time form to a separate page, and redirect to it

- app/views/transaction/show.html.erb
Turn on scroll tracking for the `/find-travel-test-provider` page. 
**NOTE** this change depends on [this change](https://github.com/alphagov/govuk_publishing_components/pull/2546) in the components gem being deployed to `static` at the same time, otherwise duplicate or no scroll tracking events may occur.
We're retiring the old scroll tracker and migrating all pages that use it to the new one.
None.
Trello card: https://trello.com/c/sdugtMbX/37-migrate-to-new-scroll-tracker
> Turn scroll tracking on for find travel test provider

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
This bug was introduced in 59f09bf.  If you look in that commit, you
can see that it was `callback["redirect_path"]` previously.  I've
added a test to check this case.
> Fix not passing redirect path to first_time form

- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
If the redirect path has multiple query parameters, eg:
/email?topic=foo&frequency=bar
Then the URL we construct for the first-time form is:
/path/to/form?_ga=ga-id&cookie_consent=consent&redirect_path=/email?topic=foo&frequency=bar
Which is incorrect.  This is parsed to the following params hash:
{
"_ga"            => "ga-id",
"cookie_consent" => "consent",
"redirect_path"  => "/email?topic=foo",
"frequency"      => "bar",
}
The additional parameters of the redirect path are becoming additional
parameters of the controller, and so are being chopped off the path we
then send the user to after they complete the form.
To fix this, URL encode the redirect path, so any nested "&"s are
handled properly.
---
[Trello card](https://trello.com/c/BHQSCa9D/1213-first-time-form-issue)
> URL encode redirect path passed to first time form

- config/routes.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
Right now we use /sign-in/redirect, which looks a bit weird.  Since we
redirect /account to /account/home already, we should just merge
/account and /sign-in/redirect.
---
[Trello card](https://trello.com/c/1tMOYsbk/1218-change-sign-in-link-to-use-di-domain)
> Make /account the session start route

- config/locales/cy.yml
- config/locales/en.yml
- test/unit/locales_validation_test.rb
Applying new locale checks made in Rails Translation Manager to Frontend
Included some exemptions for some keys so exclude false positives. The `homepage` keys as the frontend experience for users in Welsh is significantly different compared to English, and a direct comparison simply doesn't make sense. Also the `formats.transaction` keys, as some keys named `other` were falsely being flagged as bad plurals.
This functionality was added to Rails Translation Manager here: https://github.com/alphagov/rails_translation_manager/pull/35
Trello: https://trello.com/c/MMvOpCC4/2826-apply-locale-file-validation-to-frontend
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) …
> Apply locale checks to Frontend

- app/views/help/sign_in.html.erb
Seems like the contextual breadcrumb that's defined in the [application
layout](https://github.com/alphagov/frontend/blob/main/app/views/layouts/application.html.erb#L45) works for this page now so I have removed the hard coded bread
crumb from the view file for `/sign-in`
| Before  | After |
| ------------- | ------------- |
|  <img width="1157" alt="Screenshot 2022-01-31 at 15 20 50" src="https://user-images.githubusercontent.com/7116819/151821910-ee55b10d-d7a9-4d2f-a1b2-c9f3b2f12d90.png">   |  <img width="1140" alt="Screenshot 2022-01-31 at 15 24 13" src="https://user-images.githubusercontent.com/7116819/151821945-45fa2a36-23b3-4cd6-a67f-a183f14d4f05.png"> |
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/developme …
> Fix sign in page double breadcrumb issue

- app/controllers/sessions_controller.rb
- test/functional/place_controller_test.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
This also addresses two minor points with the sessions controller:
- If the _ga parameter is present but blank, strip it from the
destination URL.  There's no point passing along an empty GA session
id.
- Gracefully handle the lack of a redirect path for a first-time user.
This is strictly speaking a bug, but it's unlikely that a user would
stumble upon this, as they would have to directly enter the URL for
www.gov.uk/account (or /sign-in/redirect), without clicking a link to
it, despite not already having an account.
These tests don't cover the special request / response header logic.
They just stub it out.  I don't think we can properly handle it
without being able to, eg, run code in between capybara receiving a
redirect response and following it (to update the request headers
based on …
> Flesh out signing in integration tests 

- app/views/sessions/first_time.html.erb
If a user has landed on the first time consent page with a `_ga` parameter
then they've accepted analytics cookies on DI's domain. We always run
Google Analytics in this case, so the linker parameter will be picked
up and a new cookie for www.gov.uk will be written on this page with the client ID.
This means we don't need to pass the parameter on to the next page.
If they haven't got a `_ga` parameter on this page, then they haven't
accepted analytics cookies on DI's domain and we have nothing to pass on
anyway. If they've previously accepted analytics cookies on www.gov.uk,
then they'll already have a client ID cookie on our domain, which will 
continue to work.
In either case, we don't need to pass the param on to the next page in
order to get the behaviour we want.
**To review**
The …
> Don't pass `_ga` param after first time consent page

- app/presenters/content_item/recruitment_banner.rb
- test/integration/recruitment_banner_test.rb
Update survey link for pages tagged to:
/browse/tax
/browse/business
> Update survey url for all pages tagged to browse pages of interest

- test/unit/locales_validation_test.rb
Previously we were telling Rails Translation Manager to ignore
everything under `formats.transaction`. This is too broad; we
actually only want to ignore `formats.transaction.other`.
`:other` is a keyword in Rails i18n; its usage is assumed to refer
to pluralisation rules, and thus Rails Translation Manager
complains when it is not accompanied by `:one` (in English) and
`:few`, `:zero`, `:two` and `:many` in other languages.
In such cases, we can either rename the key, or tell Rails
Translation Manager to ignore it, which we've done here.
> Tighten up locale validation config

- config/locales/en.yml
Done in response to a zendesk ticket as the step by step is being retired.
https://govuk.zendesk.com/agent/tickets/4948778
> Change link on homepage to travel abroad step by step

- spec/support/jasmine-browser.json
Ideally tests would run in a random order so we should remove this
configuration. Other configuration options are setting the default in
any case so can be removed for concision and clarity.
We are only using a `/vendors` directory for our helpers in this app, so we
can remove the `/helpers` directory from the `helpers` block.
> Remove unneeded jasmine-browser-runner configuration

- app/controllers/sessions_controller.rb
- app/views/sessions/first_time.html.erb
- config/routes.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
Reverts alphagov/frontend#3224
This is failing on [the build step](https://ci.integration.publishing.service.gov.uk/job/frontend/job/main/4265/console), so revert it until I've worked out why and fixed.
> Revert "Remove first time sign in page"

- app/presenters/transaction_presenter.rb
- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
- test/unit/presenters/transaction_presenter_test.rb
Preliminary attempt to try to get GTM code working on integration. Note that this should only work on integration, where we have enabled the `dataLayer` using the [GTM component](https://components.publishing.service.gov.uk/component-guide/google_tag_manager_script). Applies to the tabs on the `/renew-driving-licence` and `/bank-holidays` pages.
We want to experiment to see if we can get some data events to work and show up in GA.
None.
Trello card: https://trello.com/c/V0RFrSMK/43-test-technical-approach-to-tracking-on-tabs-and-accordions
> Add GA4 analytics tracking attributes to tabs

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Update the attributes for the GTM experiment on the bank holidays and renew driving licence page tabs.
They were wrong.
None.
> Update GTM analytics attributes

- config/locales/en.yml
Trello: https://trello.com/c/wzekD9yn/97-add-link-to-smart-answer-as-a-popular-link-on-the-govuk-homepage
> Add cost of living checker to popular links

- app/views/application/_location_form.html.erb
- app/views/place/show.html.erb
When there is an error on location form submit, anchor link to where the error message is.
On pages with long content before the location form, if submitting the form resulted in an error then it was not obvious an error had occurred as the page scroll would be reset to the top of the page. 
Related to https://github.com/alphagov/frontend/pull/3254
> Add anchor link to location form on error

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Rename a GA4 attribute on the tabs on `/renew-driving-licence` and `/bank-holidays`.
- part of a change across the site
- applies only to the new GA4 analytics code, not yet used in production
None.
Trello card: https://trello.com/c/BRyCFCVf/334-uistate-should-be-uiaction
> Rename GA4 analytics attribute state to action

- app/assets/stylesheets/application.scss
Adds the stylesheet imports for the document list and inset text components back into the application stylesheet. Also separating their `@import`s in the application stylesheet makes it a bit clearer why they're being included.
These components aren't used within any templates, so the component audit wrongly flagged them as things that were safe to remove - which broke the layout for the sign into a service page.
Adding them back in to fix this.
| - | - |
| ![image](https://user-images.githubusercontent.com/1732331/178488073-be8171f5-1d30-4db6-b1bb-470bdf498933.png) | ![image](https://user-images.githubusercontent.com/1732331/178488424-43b46018-e066-49a8-852c-b44261694927.png) |
--- …
> Add inset text and document list components back

- app/controllers/account_home_controller.rb
- test/integration/account_home_test.rb
Now the `GovukPersonalisation::Urls.your_account` links have all been
updated to point to DI, we can update the redirect on this side to
point to the page that will house the new account home page on the DI
side.
At the moment, this page simply redirects on to the 'manage your
account' page, but setting the GOV.UK links up like this means they'll
work properly once we do build a new account home page.
> GUA-72: Update account home redirect

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Updates the data attributes used on tabs on the `/bank-holidays` and `/renew-driving-licence` pages for GTM analytics. Note that this change depends upon [this change in govuk_publishing_components](https://github.com/alphagov/govuk_publishing_components/pull/2864) being present in the currently installed gem version, but this can be safely merged ahead of that as it doesn't affect live and we're still just testing it anyway.
We updated the schema for how click tracking like this works, which meant that the tracking would no longer work.
None.
Trello card: …
> Update GTM analytics tracking attributes

- app/views/calendar/bank_holidays.html.erb
Fix index on tabs on `/bank-holidays` for GA4 tracking. Index should start at 1, not zero.
None.
Trello card: https://trello.com/c/c7cDVQ79/349-tab-index-should-start-at-1-rather-than-0-on-bank-holidays
> Fix tracking index on tabs

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Rename the calls to the event tracking module for GA4, which was recently renamed. Without this change they won't work anymore.
Note that this code only runs on integration.
None.
> Fix references to GA4 analytics tracking

- config/locales/en.yml
The Cost of living hub was made live and so now the homepage needs to have a link to it.
> Add cost of living support card to homepage

- app/views/homepage/_promotion-slots.html.erb
We discovered we have a problem with the use of srcset on promotion slots for the homepage. They were not being set to the correct paths created by asset pipeline. This resolves that and also switches the image urls from absolute URL's to absolute paths.
Before:
```
<figure class="gem-c-image-card__image-wrapper">
<img
class="gem-c-image-card__image"
alt=""
loading="lazy"
sizes="(max-width: 640px) 100vw, (max-width: 1020px) 33vw, 300px"
srcset="/images/homepage/queen-elizabeth-ii-profile.jpg 610w, /images/homepage/queen-elizabeth-ii-profile-480.jpg 480w, /images/homepage/queen-elizabeth-ii-profile-320.jpg 320w, /images/homepage/queen-elizabeth-ii-profile-240.jpg 240w, /images/homepage/queen-elizabeth-ii-profile-170.jpg 170w"
src="http://127.0.0.1:3005/assets/frontend/homepage/queen-elizabe …
```
> Fix use of srcset on homepage slots

- config/locales/en.yml
We will also need to update the copy of these links in the search bit of the menu bar. These are hardcoded in govuk_publishing_components.
In my view, we should update the links on the homepage first and make the menu bar consistent afterwards.
> Update popular links for London Bridge

- Dockerfile
`WORKDIR` creates its directory anyway, and the mkdir fails now that we're creating `/app` in govuk-ruby-base. Thought I'd fixed all these before merging the change to govuk-ruby-base, but turns out I forgot to actually raise a bunch of the PRs that I'd prepared.
> Remove unnecessary `mkdir /app` from Dockerfile.

- app/controllers/homepage_controller.rb
Set the slimmer template in homepage controller to be `gem_layout_homepage` instead of `gem_layout_full_width`.
As part of the work removing [emergency banner from static](https://github.com/alphagov/static/pull/2788), a new gem layout has been created in static for homepage. This is because the emergency banner has specific styling when it is present on the homepage.
Previously, the emergency banner homepage styles were applied by using a parent class selector but this is against the
isolation principle of components. So the emergency banner component now accepts a parameter which when set to true applies the correct styling. This meant that a new gem layout needed to be created for homepage with this parameter set for the emergency banner (when the emergency banner is displayed).
Until …
> Use New Homepage Gem Layout on Homepage

- docs/update-homepage-promotion-slots.md
Update the homepage promo documentation to provide some indication of the file size that homepage promo images should be.
> Update homepage promo documentation

- app/assets/stylesheets/views/_homepage.scss
Recently, a new card was added to the list of cards that appear on the home page. The number of items in the column mixin used for IE11 layout was not updated however which was causing a visual issue on IE11. This has now been changed to reflect the correct number of cards and this has fixed the visual issue.
In IE11.
> Fix Homepage Cards in Internet Explorer 11

- Gemfile.lock
- app/controllers/random_controller.rb
- test/functional/random_controller_test.rb
See alphagov/gds-api-adapters#1170 for context.
> Use canonical name when connecting to search-api.

- app.json
We are retiring the dummy content store as part of replatforming work, making it easier for us to deploy content schemas in the new world. Switching to using gov.uk/api for PLEK_SERVICE_CONTENT_STORE_URI brings us this application in line with most other applications.
This brings this application in line with most other frontend applications, e.g. [collections](https://github.com/alphagov/collections/blob/e983dc77e4239bff031b33088b54c9f34f387216/app.json#L15)
> switch from using dummy content store to using gov api

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Remove all attributes that are set to `n/a` for all tab component instances.
We have a [shared schema](https://github.com/alphagov/govuk_publishing_components/blob/main/app/assets/javascripts/govuk_publishing_components/analytics-ga4/ga4-schemas.js) where all attributes are initially set to `null`. This means we only need to set the attributes that are needed and have a value when required prior to pushing the event. All other attributes will be sent as `null` by default, so we no longer need to set them on purpose.
> Remove `n/a` attributes on tab components

- app/views/completed_transaction/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
https://trello.com/c/HLmurT4f/1536-add-new-designs-onto-organ-donation-pages
Remove text from completed transaction page "organ donor" promotion.
- You do not have to join the register as you’re automatically opted in now. 
- The second link should be removed because it takes away from the real call to action, which is the register a decision to donate 
- Removing the rhetorical question, because this language is quite odd in this context
- [Give feedback on Book your driving test - organ donor promotion](https://govuk-frontend-app-pr-3434.herokuapp.com/done/book-driving-test)
> Remove text from completed transaction page "organ donor" promotion

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
**NOT TO BE MERGED unless also including the [new version of the components gem](https://github.com/alphagov/govuk_publishing_components/pull/3091) that includes the changes detailed below**
Update references to GA4 event tracker to cope with breaking changes introduced in https://github.com/alphagov/govuk_publishing_components/pull/3057
- GA4 event tracker has been rewritten to use a `data-ga-event` attribute in place of `data-ga4`
- updating for tracking on tabs on /bank-holidays and /renew-driving-licence pages
None.
Trello card: https://trello.com/c/uMgCIdtY/289-update-link-tracking
> Update for event tracker changes

- app/views/licence/_licensify_unavailable.html.erb
- app/views/licence/start.html.erb
- test/integration/licence_test.rb
Remove the negative contraction  and add a full stop.
Negative contractions hard for some people to read and often misintepreted
> Tweak License unavailable view for accessibility

- Gemfile
- Gemfile.lock
- config/locales/cy.yml
- config/locales/en.yml
- config/locales/plurals.rb
We're now using the extra plural rules defined by RTM as a prod
dependency [1]. This will replace the list defined in govuk_app_config
and so the reference has also been removed. RTM's version loads
automatically [2] and so we don't have to explicitly include the file in
the app.
[1]: https://github.com/alphagov/rails_translation_manager/blob/main/config/locales/plurals.rb
[2]: https://github.com/alphagov/rails_translation_manager/blob/f18fd2e178719dd0a103981160f898771957fa43/lib/rails_translation_manager.rb#L24
> Bump Rails Translation manager and use new plural list

- app/controllers/development_controller.rb
- app/views/development/index.html.erb
- config/govuk_examples.yml
- config/routes.rb
Add an info page listing examples of pages the app renders.
Add a page for dev mode to show a list of example pages this app renders.
We have a page like this for `government-frontend`. As we consolidate our rendering apps and they render more and more content types, it's hard to track/remember.
[Trello card](https://trello.com/c/RysOWfk4/68-add-an-index-page-to-frontend-apps-like-in-government-frontend)
> Add development page

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/controllers/find_local_council_controller.rb
- app/models/locations_api_postcode_response.rb
- app/views/application/_location_form.html.erb
- app/views/find_local_council/_base_page.html.erb
- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/multiple_authorities.html.erb
- app/views/find_local_council/one_council.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- test/integration/find_local_council_test.rb
- test/integration/local_transactions_test.rb
- test/integration/place_test.rb
Add support for choosing an address to disambiguate a postcode when looking for a council.
Some postcodes fall into more than one council, and we then need to choose from a list of addresses to get the exact result. This wasn't previously possible, but the move to locations api away from mapit gives us the required information.
[Support split postcodes in Frontend](https://trello.com/c/HjgjrOCq/1580-support-split-postcodes-in-frontend)
When a postcode is initially checked, we determine whether there is more than one unique local custodian code involved. If not, we continue as usual. If there is, we re-query …
> Add support for choosing from a split postcode.

- app/views/completed_transaction/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- test/integration/completed_transaction_test.rb
https://trello.com/c/I98gNHHK/1693-content-change-to-improve-accessibility-of-generic-completed-transaction-page
There is a [generic completed transaction page](https://www.gov.uk/done/transaction-finished) that is linked from a number of services. Its H1 is currently 'Thanks' and the body content is just the organ donation promotion.
We want to make the H1 'You’ve completed your transaction' and add a line of text above the organ donation promotion that says 'Thanks for visiting [GOV.UK](http://gov.uk/).'
**Review URL(s):**
The line of text will show only for `done/transaction-finished`.
- https://govuk-frontend-app-pr-3481.herokuapp.com/done/transaction-finished (organ donor promotion only)
The next two pages include the organ donor promotion and satisfaction survey and do not display …
> Content change to completed transaction page

- .github/workflows/pact-verify.yml
This pact workflow should be checking out the frontend repo, not content store. Also doesn't need mongodb to run.
> Fix pact tests clone wrong repo and remove mongodb

- app/views/homepage/_chevron_card.html.erb
- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_promotion-slots.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/homepage/index.html.erb
Adds GA4 tracking to the homepage links using the `ga4-link-tracker`
It is next on our list of interactions to add.
[Trello card](https://trello.com/c/WAST3s6v/392-add-tracking-homepage)
N/A
> Ga4 homepage tracking

- app/views/calendar/_calendar_footer.html.erb
- app/views/find_local_council/_base_page.html.erb
- app/views/help/index.html.erb
- app/views/shared/_base_page.html.erb
- app/views/simple_smart_answers/flow.html.erb
Turns on tracking for the contextual sidebar and contextual footer on pages throughout `frontend`.
This turns on GA4 tracking for links within the components.
None.
Trello card: https://trello.com/c/IMjw2dHg/382-add-tracking-related-links-contextual-sidebar-and-contextual-footer
> Add GA4 tracking to sidebar

- app/controllers/licence_controller.rb
- app/views/licence/multiple_authorities.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- test/functional/licence_controller_test.rb
- test/integration/licence_test.rb
Adds support for split postcodes to the licence controller so that people whose postcodes sit across multiple local authorities can be prompted to enter their address and get the correct authority returned.
We can now support split postcodes, and since we've successfully added them to the find your council and local transactions endpoints, we need to add them to other endpoints with the same potential problems.
[Trello card](https://trello.com/c/LbhI1Uw0/1769-add-split-postcode-support-for-licences-in-frontend)
Copying the work from here: [alphagov/frontend: Pull Request …
> Update licence controller with split postcode support

- .github/workflows/pact-verify.yml
This updates the pact-verify action so that it can accept from a GitHub Action as part of changes described in: https://github.com/alphagov/gds-api-adapters/pull/1188
I made the pact file to be an input with a default as I noticed that across our suite of apps this filename can vary from something straight forward (gds_api_adapters-publishing_api.json) to something very nuanced (gds_api_adapters-bank_holidays_api.json). For these nuanced one an input seemed useful and I wanted to apply the same approach consistently.
I've updated other aspects of this action to be more consistent with other pact-verify.yml files …
> Update pact-verify action to operate with an artifact

- app/controllers/licence_transaction_controller.rb
- app/presenters/licence_transaction_presenter.rb
- app/views/licence_transaction/_action.html.erb
- app/views/licence_transaction/_authority_details.html.erb
- app/views/licence_transaction/_authority_url.html.erb
- app/views/licence_transaction/_licensify_unavailable.html.erb
- app/views/licence_transaction/authority.html.erb
- app/views/licence_transaction/continues_on.html.erb
- app/views/licence_transaction/multiple_authorities.html.erb
- app/views/licence_transaction/start.html.erb
- config/routes.rb
- test/functional/licence_transaction_controller_test.rb
- test/integration/licence_transaction_test.rb
- test/unit/presenters/licence_transaction_presenter_test.rb
This PR opens up a new endpoint which will service licences published by Specialist Publisher (not yet built). Current licences are published by Mainstream Publisher and serve Licence Finder which we are looking to retire. 
The code is broadly the same as from the existing [Licence code][1]. However, we chose not to modify the existing code due to the introduction of a new base_path (routes) and content_item data structure which results in lots of changes between the old vs new licence code.
This PR will stay in draft until we've created a new licence document type in Specialist Publisher and pointed the licences at Frontend. 
[1]: https://github.com/alphagov/frontend/blob/5ae9cbece197f619277e9f2c534f23b14a670043/app/controllers/licence_controller.rb#L1
If you want to test the branch then …
> Create new endpoint for Specialist Publisher licences

- Gemfile
- Gemfile.lock
- app/controllers/place_controller.rb
- app/models/imminence_response.rb
- app/views/place/multiple_authorities.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- test/functional/place_controller_test.rb
- test/integration/place_test.rb
Adds support for split postcodes to the place controller so that people whose postcodes sit across multiple local authorities can be prompted to enter their address and get the correct authority returned if the place service is local_authority.
We can now support split postcodes, and since we've successfully added them to the find your council and local transactions endpoints, we need to add them to other endpoints with the same potential problems.
[Trello card](https://trello.com/c/C4nLJyVO/1778-add-split-postcode-support-for-places-in-frontend)
Requires an update to how Imminence returns data so that Imminence …
> Update Place controller with split postcode support

- Gemfile
- Gemfile.lock
To allow a seamless deploy, we had to rely on the github version of the gds-api-adapters gem. Now that is published, we can remove the reliance and return to the published rubygem.
Trello card: https://trello.com/c/C4nLJyVO/1778-add-split-postcode-support-for-places-in-frontend
> Remove reliance on github version of gem

- app/views/homepage/_links_and_search.html.erb
This PR adds tracking to the search box on the homepage by adding the `GA4 form tracker` data attributes.
N/A
Trello card: https://trello.com/c/LOMdtYRI/425-add-tracking-search-box-on-the-home-page
> Add GA4 tracking to homepage search box

- app/views/layouts/application.html.erb
Enables GA4 tracking on the contextual breadcrumb by adding a `ga4_tracking: true` attribute.
N/A
Trello card: https://trello.com/c/AM5JCKEd/430-add-tracking-to-super-breadcrumbs
> Add ga4 tracking to contextual breadcrumb

- app/assets/config/manifest.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_calendar.scss
- app/assets/stylesheets/components/_metadata.scss
- app/assets/stylesheets/components/_subscribe.scss
- app/assets/stylesheets/views/_calendars.scss
- app/assets/stylesheets/views/_completed_transaction.scss
- app/assets/stylesheets/views/_cookie-settings.scss
- app/assets/stylesheets/views/_homepage.scss
- app/assets/stylesheets/views/_local-transaction.scss
- app/assets/stylesheets/views/_location_form.scss
- app/assets/stylesheets/views/_report-child-abuse.scss
- app/assets/stylesheets/views/_travel-advice.scss
- app/views/application/_location_form.html.erb
- app/views/calendar/bank_holidays.html.erb
- app/views/calendar/when_do_the_clocks_change.html.erb
- app/views/completed_transaction/show.html.erb
- app/views/components/_calendar.html.erb
- app/views/components/_metadata.html.erb
- app/views/components/_subscribe.html.erb
- app/views/help/cookie_settings.html.erb
- app/views/help/sign_in.html.erb
- app/views/homepage/index.html.erb
- app/views/layouts/application.html.erb
- app/views/local_transaction/devolved_administration_service.html.erb
- app/views/local_transaction/results.html.erb
- app/views/local_transaction/unavailable_service.html.erb
- app/views/place/_option_report_child_abuse.html.erb
- app/views/travel_advice/index.html.erb
- config/application.rb
Update `frontend` to load component and view CSS only when required by the page being viewed - so the CSS for the radio buttons only loads on pages with radio buttons, and the stylesheet for the homepage is only loaded on the homepage.
This reduces the amount of CSS required for each page and increases the ability of a browser to cache the stylesheets - this should mean a faster load time for both first time and repeat visitors.
See [RFC #149][rfc] for more details
None.
---
[rfc]: https://github.com/alphagov/govuk-rfcs/pull/152
> Set up individual component CSS loading

- app/controllers/place_controller.rb
- app/models/imminence_response.rb
- test/integration/place_test.rb
Make the imminence_response_from_data method quick-return if no postcode is supplied
Currently page is 500-ing when the user presses find without entering a postcode. This isn't really causing serious problems for users (because they can just back-button and enter a postcode), but it's not ideal and it's causing sentry noise.
[Trello card](https://trello.com/c/QcVV7Wee/1903-ps-7-fix-empty-imminence-response-bug-in-frontend)
Add postcode.blank? to the guard clause at the top of the method so that it doesn't try to parse missing imminence response data.
N/A
> Fix frontend failing with empty postcode field in places

- Gemfile.lock
- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Change the index parameter on the tabs component to align with recent changes to the index parameter and how we're processing it within GA4.
None.
Trello card: https://trello.com/c/8tNN5gGX/426-change-the-index-parameter
> Update index parameter on tabs

- app/controllers/simple_smart_answers_controller.rb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/simple_smart_answers/show.html.erb
- test/integration/simple_smart_answers_test.rb
This PR adds GA4 tracking to simple smart answers.
[Form start tracking trello card](https://trello.com/c/EakgQopa/409-add-tracking-simple-smart-answers-formstart)
[Form response tracking trello card](https://trello.com/c/lvboBxZD/410-add-tracking-simple-smart-answers-formresponse)
[Form change response tracking trello card](https://trello.com/c/TDlhJCn0/414-add-tracking-simple-smart-answers-formchangeresponse)
[Form start again tracking trello card](https://trello.com/c/F7zMWjqZ/411-add-tracking-simple-smart-answers-formstartagain)
[Information click tracking trello …
> Ga4 simple smart answer tracking

- app/views/application/_location_form.html.erb
- test/integration/simple_smart_answers_test.rb
Remove surplus data attribute `module: "govuk-error-summary"` from error summary component
Previously the module name would be overwritten when the same option is passed to the component. The issue has now been resolved by https://github.com/alphagov/govuk_publishing_components/pull/3308.
> Remove surplus data_attribute module from error summary component

- app/controllers/find_local_council_controller.rb
- test/integration/find_local_council_test.rb
- test/support/local_links_manager_helpers.rb
Allow the upper tier in a 2 tier system to be a unitary authority in the council finder controller.
Although in principle 2 tiers will always be in reality county/district,during merge periods, it is sometimes simpler to mark a county that will turn into a unitary authority as a unitary authority before the actual switchover period. This change allows that (previously the code assumed this could never happen, and would break if it did). If we reengineer LLM after April 2023 we can probably remove this, but we'll need to be mindful of similar future events.
[Trello …
> Add support for District/Unitary pairs

- app/views/homepage/_chevron_card.html.erb
- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_promotion-slots.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/homepage/index.html.erb
Updates the data attributes on the homepage for GA4 link tracking, specifically the `index` parameter, which is no longer a string of numbers but several sub attributes that specifically relate to the number of sections, number of links etc.
Part of the GA4 migration work. Index parameters were inconsistent and hard to parse, so the new index parameter is designed to be much clearer and more specific.
None.
Trello card: https://trello.com/c/16ngDhBP/493-change-the-index-parameter-part-2-indexsectioncount
> Update index parameter on homepage links

- app/services/electoral_service.rb
- test/support/election_helpers.rb
- Replaces basic auth header, by request from Democracy Club (we are now the only people who authenticate with header, and they'd like to introduce some performance optimizations ahead of the upcoming elections).
We call the Electoral Commission API on our [Contact your local Electoral Registration Office](https://www.gov.uk/contact-electoral-registration-office) page. A user enters a postcode, we make a background call to the electoral commission API, and it returns either a picker to choose a specific address (if the postcode is split) or the details of the local authority responsible for electoral registration …
> Authenticate with Electoral Commission with query token

- app/views/licence_transaction/continues_on.html.erb
- app/views/licence_transaction/start.html.erb
Add the publication.description (ie summary) to the rendered licences for the new licence finder. This makes them render more consistently with other specialist publisher documents (which show the summary in the finder preview and then also on the first page of the document).
[Trello card](https://trello.com/c/hCfkg3fC/1957-add-summary-to-licences-in-frontend)
Before:
After:
> Add publication summary to licences.

- app/controllers/completed_transaction_controller.rb
- test/integration/completed_transaction_test.rb
Remove the Photo ID banner from all pages.
The banner needs to be removed at 10:00pm on 04/05/23.
> Remove the Photo ID Banner

- test/integration/licence_transaction_test.rb
Make it clear in this test that the test is for multiple licensing authorities, not multiple local authorities.
- We no longer support them (see https://github.com/alphagov/frontend/pull/3594/commits/f4c10bb352eba283589f36e8be579628bfe0983a)
- Safe behaviour is to choose the first one if we do happen to get multiple.
- Make it explicit that this is about licencing authorities (rather than local authorities, since there is a concept of multiple authorities being returned for a single postcode in the postcode chooser paths).
[Trello card](https://trello.com/c/3AHvfc4d/2002-investigate-first-authority-selected-flow)
> Make explicit that this test is for multiple licensing authorities

- Procfile
- config/unicorn.rb
Remove unicorn to fix Heroku deploys
Review apps are not running in Heroku.  I believe this is because Heroku is still trying to use unicorn as the web server even though we have switched to Puma now [1].
This change also also the component guide to be rendered: https://govuk-frontend-app-pr-3623.herokuapp.com/component-guide
[1]: https://github.com/alphagov/govuk_app_config/pull/286/commits/71f4f2fa3871721e5c8140bcf73d683e09d8d7b2
> Remove unicorn to fix Heroku deploys

- app/controllers/licence_transaction_controller.rb
Deal with this todo: https://github.com/alphagov/frontend/compare/refactor-from-todo?expand=1#diff-ae283b2c68c1a40c881e2dface96a94199f6e9ac40a6e6d64a33a9e8e2206bf6L45 - pointing out that we shouldn't be setting a memoized value somewhere else.
[Trello card](https://trello.com/c/UBxtzqjS/2035-fix-todo-comment-in-licence-transaction-frontend-code)
Move the second get (once we know we need to specify a local authority) into a method called by the memoizing function.
> Refactor licence_details method to ensure memoized value is set at a single point

- app/views/application/_location_form.html.erb
- app/views/local_transaction/index.html.erb
- app/views/local_transaction/results.html.erb
- test/integration/local_transactions_test.rb
Hi @andysellick, would you be able to approve this if all is OK? Thanks :+1:
Adds the following GA4 events to the `local_transaction` flow (https://www.gov.uk/rubbish-collection-day)
- form_submit when clicking the "Find" button
- form_error when submitting an invalid postcode
- form_complete when you land on a results page 
- information_click if you click the result link
https://trello.com/c/2qmN8Wjg/546-form-events-formsubmit-formerror-formcomplete-and-informationclick-on-localtransaction-format
- This relies on this change in `govuk_publishing_components` to make the `form_submit` work, so the following PR …
> Add GA4 tracking to local transactions

- app/views/licence/_authority_details.html.erb
- app/views/licence_transaction/_authority_details.html.erb
- app/views/place/show.html.erb
- test/integration/licence_test.rb
- test/integration/licence_transaction_test.rb
- test/integration/place_test.rb
This PR adds GA4 attributes to place and licence format local lookup templates.
Note: on results pages for licence format local lookups, it is possible that links generated by publishing tools and links that we don't want indexed (e.g. `change_response` and `form_start_again` links) can occur in the same `ga4-link-tracker` data module. This causes issues with indexing because whenever we encounter links generated by publishing tools, we target the parent container they're in and use JS to apply indexing. In this case, links that we don't want indexed have indexes added to them as well because they occur in the …
> Ga4 form events licence and place

- app/views/calendar/bank_holidays.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Replaces custom data attributes for tab tracking with the simpler `ga4_tracking: true` [tab component option](https://components.publishing.service.gov.uk/component-guide/tabs/with_ga4_tracking), which sets all the same data attributes.
Tabs are used on:
- the [bank holiday page](https://www.gov.uk/bank-holidays)
- transaction start pages like [tax your vehicle](https://www.gov.uk/vehicle-tax)
Fewer lines of code, easier to maintain.
None.
> Use tab component built in tracking

- app/controllers/csv_preview_controller.rb
This was originally present in Whitehall, so the fix has been copied straight over from there.
Whitehall fix: https://github.com/alphagov/whitehall/blob/20911ccde160fed879027b1fd03c7cc51a5e8e2d/app/models/csv_preview.rb#L74-L90
> Resolve issue with `\r\n` line breaks and multi-line fields

- config/routes.rb
Rails does not permit dots in dynamic segments (see https://guides.rubyonrails.org/routing.html#dynamic-segments).
Therefore adding a constraint to override this for CSV Previews, as these can contain dots (and other characters other than slashes) in the filename.
> Permit dots in the filename for CSV Previews

- app/views/application/_location_form.html.erb
- test/integration/find_local_council_test.rb
- test/integration/licence_test.rb
- test/integration/licence_transaction_test.rb
- test/integration/local_transactions_test.rb
- test/integration/place_test.rb
[Trello local_transaction](https://trello.com/c/iQXIg0y8/596-add-action-method-to-form-submit-localtransaction)
[Trello special_route](https://trello.com/c/rRmyCOPB/601-add-action-method-to-form-submit-specialroute)
[Trello place](https://trello.com/c/AgiNiNa0/600-add-action-method-to-form-submit-place)
[Trello license](https://trello.com/c/LK951exF/599-add-action-method-to-form-submit-licence)
Sends "action" and "method" data to GA4.
The location_form partial is used by the following formats:
- place
- local_tranaction
- license_transaction
- special_route
The tests for these formats have been updated to reflect the additional values.
I tested this manually for local transactions using the ['How to test it' instructions in this PR …
> Send location_form action and method data to GA4

- config/locales/cy.yml
Add Welsh translation for error summary title `error_summary_title` for simple smart answer.
https://govuk.zendesk.com/agent/tickets/5373614
> Add Welsh translation for error summary title

- test/integration/csv_preview_test.rb
This is an attempt at fixing a flakey test where the tests for the windows-1252 encoding are passing sporadically. My understanding is that the setup step for these tests is incomplete due to the lack of a visit method, however these tests have passed if a previous tests' visit method was called which left the browser in a state where the tests would pass.
> Add missing visit to windows-1252 encoding test

- app/views/licence/_licensify_unavailable.html.erb
Adds GA4 tracking to licence pages where a licence is not available online, such as https://www.gov.uk/skin-piercing-and-tattooing/islington
None.
Trello card: https://trello.com/c/HNCfXrJG/597-formcomplete-not-firing-when-there-is-no-match-for-services-licence
> Add GA4 to licence not online page

- app/views/licence/_authority_details.html.erb
- app/views/licence_transaction/_authority_details.html.erb
- test/integration/licence_test.rb
- test/integration/licence_transaction_test.rb
- On https://www.gov.uk/tattooists-piercing-and-electrolysis-licence-scotland/edinburgh there are three different pages in the contents list.
- If you click on `How to change` or `How to apply`, they will run the `form_complete` event when they shouldn't. It should only run on `1. Overview`. This PR fixes that.
https://trello.com/c/5HzaiU9q/621-formcomplete-event-firing-on-every-page-after-form-completion-on-licence-form-should-only-fire-once-per-formsubmit
I also considered using fancier Ruby to only send a `form_complete` if the user had come from the Postcode form, but I was using Ruby's `request.referrer` to …
> Only send a GA4 form_complete event on the 1. Overview page

- app/views/place/_option.html.erb
This PR adds a `data-ga4-do-not-redact` attribute to email addresses that are publicly available and are surfaced within `place` results ([example](https://www.gov.uk/disabled-students-allowances-assessment-centre#results)).
Requested by PA's (part of the GA4 migration).
[Trello card](https://trello.com/c/nDZmuHH1/622-public-email-address-redacted-on-place-forms)
N/A
> Add data-ga4-do-not-redact attribute to publicly available information

- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_inverse_header.html.erb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_promotion-slots.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/homepage/index.html.erb
Add the GA4 scroll tracker to the homepage. We want to track headings but there are far too many of them so use the 'markers' option for tracking scrolling, applying markers to the main section headings only.
Note that this change depends upon https://github.com/alphagov/govuk_publishing_components/pull/3519 being included in a version of the gem and installed in `frontend`.
None.
Trello card: https://trello.com/c/BEPuXcrG/607-scroll-tracking-heading-type-home-page
> Add scroll tracking to the homepage

- Gemfile.lock
- app/controllers/sessions_controller.rb
- test/functional/session_controller_test.rb
⚠️ **NOTE: To preserve user journey on /email/manage, this requires DI Home to support the login hints parameter in email-alert-frontend. Do not merge until that is confirmed!** (Now confirmed live)
Redirect requests to /account directly to home.account.gov.uk if there is no redirect param supplied.
Request from the OneLogin team - redirecting here prevents a problem where rather than being asked to sign in with 2FA to begin with, an uplift scenario starts (where the user logs in without 2FA, then the 2FA is requested later). This is leading to confusing differences in 2FA prompts, and a situation where people …
> Single redirect /account to home.account.gov.uk rather than session start if no redirect param passed

- app/views/help/sign_in.html.erb
Adds GA4 tracking to the form at the bottom of the page at https://www.gov.uk/sign-in
Uses the GA4 form tracker with fairly standard configuration. Default redaction of the text input into the search is disabled.
None.
Trello card: https://trello.com/c/fnhGH7AZ/626-search-on-https-wwwgovuk-sign-in
> Add GA4 tracking to search on sign in page

- app/views/layouts/application.html.erb
- Adds `ga4_tracking: true` to the Phase Banner which enables GA4 attributes/JS on the banner HTML
https://trello.com/c/d6CHHgco/663-banners-phase-banner-element-visibility-and-navigation
- Added `ga4_tracking: true` to the render of the phase banner. This adds a data module/data attributes to the HTML via govuk_publishing_components
N/A
> Enable GA4 tracking on the phase banner

- app/views/application/_location_form.html.erb
- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/one_council.html.erb
- app/views/licence_transaction/_authority_details.html.erb
- app/views/place/show.html.erb
- test/integration/licence_transaction_test.rb
- [This form](https://www.gov.uk/find-licences/tattooists-piercing-and-electrolysis-licence-scotland) had its `schema_name` changed after the release of specialist finders (it's currently `specialist document` but they want `license transaction`).
- I was asked to change it to use `document_type` instead. However the postcode form partial is shared, so it would've changed the GA4 type across all the forms that are using the partial.
- However we found that `document_type` is the same as `schema_name` for most of the GA4 interactions. Therefore, this changes every reference of `schema_name` to `document_type` but …
> Change GA4 type from schema_name to document_type

- app/views/licence_transaction/_licensify_unavailable.html.erb
- test/integration/licence_transaction_test.rb
Changes the GA4 type from `licence` to `licence transaction` on the `form_complete` event for this page: https://www.integration.publishing.service.gov.uk/find-licences/tattooists-piercing-and-electrolysis-licence-scotland/westminster
https://trello.com/c/I1Wi1Xow/656-switch-type-to-licence-transaction-on-licence-postcode-lookup-forms#comment-65032db031caa529e00435df
> Change GA4 type from licence to licence transaction

- Gemfile.lock
- app/controllers/csv_preview_controller.rb
- config/routes.rb
- test/integration/csv_preview_test.rb
**CSV previews to work with modern urls**
**Context**: Currently whitehall uses a semi-hard-coded url called `legacy-url-path` to identify an asset in asset manager.
This url path looks something like `/government/uploads/system/uploads/attachment_data/*`.
While other publishing services use asset-id to identify an asset in asset manager.
We are working on an epic to make whitehall use the asset-id similar to other publishing service.
For csv-preview: Currently with Frontend preview functionality for csv, it uses legacy-url-path to fetch the asset
from asset manager. When legacy url path is removed from Whitehall then frontend would have to use
the asset-id to fetch the asset.
The changes we have made will allow the controller to retrieve asset using asset-id or legacy url path based on …
> CSV previews to work with modern urls

- app/presenters/content_item/recruitment_banner.rb
- app/presenters/content_item_presenter.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
The banner will be applied on the following pages:
- [/get-information-about-a-company](https://www.gov.uk/get-information-about-a-company)
- [/check-if-you-need-tax-return](https://www.gov.uk/check-if-you-need-tax-return)
- [/view-right-to-work](https://www.gov.uk/view-right-to-work)
- [/trade-tariff](https://www.gov.uk/trade-tariff)
- [/register-for-self-assessment](https://www.gov.uk/register-for-self-assessment)
- [/file-your-confirmation-statement-with-companies-house](https://www.gov.uk/file-your-confirmation-statement-with-companies-house)
Before:
After:
> Add user research banner

- app/controllers/csv_preview_controller.rb
- test/integration/csv_preview_test.rb
Reference issue:https://govuk.sentry.io/issues/4265154142/?alert_rule_id=3654813&alert_type=issue&notification_uuid=8ab09d48-0416-4305-9e3c-0de49561a46a&project=202225&referrer=slack
Currently content item when it returns attachments, it returns modern url hence when it tries to find  for legacy url, it fails and @attachment_metadata is empty this cause @attachment_metadata.first to be nil and hence the error.
With the fix we try to not rely on legacy_url_path, instead we look for the filename.
> Fix for csv preview with legacy_url_path

- app/views/simple_smart_answers/_outcome.html.erb
- test/integration/simple_smart_answers_test.rb
Adds the simple smart answer outcome number to our GA4 `form_complete` event
https://trello.com/c/OAZ9xoEq/676-new-parameter-for-simple-smart-answers-formcomplete-outcome-numbers
> Add outcome number to GA4 form_complete event

- app/controllers/homepage_controller.rb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/index.html.erb
- test/integration/homepage_test.rb
We have temporary logic in this application to toggle new designs on the presence or absence of the new_design parameter. Eg `new_design=foo`, `new_design=false` etc all result in the new design showing. We should make this more specific.
Only toggle the new design if the query string `new_design=impact` is added
Review app
SHOW DESIGN: https://govuk-frontend-app-pr-3786.herokuapp.com?new_design=impact
HIDE DESIGN: https://govuk-frontend-app-pr-3786.herokuapp.com
> Update new_design query string matching to be more specific

- app/views/homepage/index.html.erb
- app/views/layouts/application.html.erb
Enable GA4 tracking on the intervention banner
So that the PAs can check the right data is coming through to their dashboards
[Trello card](https://trello.com/c/dqBVyVTJ/666-banners-interventions-element-visibility-navigation-and-hide-user-interaction)
Adds the `ga4_tracking: true` flag to the component render
> Enable GA4 tracking on the intervention banner

- Dockerfile
As per the documentation for `yarn set version`:
The version specifier can be:
- a tag:
- `latest` / `berry` / `stable` -> the most recent stable berry (`>=2.0.0`) release
So `yarn set version berry` is equivalent to `yarn set version latest`, which will install newly released versions of yarn.
There was a release of yarn v4.0.0 yesterday - https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F4.0.0 which is now breaking the build, because it produces a slightly different lockfile.
The docker build should use whichever yarn version package.json uses, not install the latest version on the fly.
See also: https://github.com/alphagov/government-frontend/pull/2968
> Do not install yarn latest in docker build

- app/views/help/sign_in.html.erb
- app/views/homepage/_homepage_header.html.erb
- app/views/homepage/_links_and_search.html.erb
Adds `data-ga4-form-no-answer-undefined` to the search forms. When this attribute exists, it will send `text: undefined` when the form is empty, instead of `text: "No answer given"`.
https://trello.com/c/WtvEWiS3/592-placeholder-replace-no-answer-given-with-undefined-on-homepage-search-event
> Add data-ga4-form-no-answer-undefined attribute to search forms

- app/assets/stylesheets/views/_homepage_header.scss
- app/views/homepage/_homepage_header.html.erb
Improve the semantics of the new homepage tagline by moving it inside the `<h1>`. 
Anika flagged in her accessibility audit that the tagline had been marked up as a paragraph tag but styled to look like a heading. Visually it was only differentiated from the "GOV.UK" text with the use of colour so it looked like a part of the `<h1>` rather than a paragraph tag. This PR makes it part of the `<h1>` so that the semantics reflect the visual design.
Separate the content of the  `<h1>` using span tags for design purposes. Add the visually hidden colon for punctuation to make JAWS and NVDA leave a pause after "GOV.UK" but before the tagline.
An alternative implementation would have been to move the tagline into its own `<h2>`. However, the feedback from Anika (who consulted other accessibility …
> Move tagline inside `<h1>` to improve semantics

- app/presenters/content_item/recruitment_banner.rb
- app/views/layouts/application.html.erb
- test/integration/recruitment_banner_test.rb
Remove user research banner from
- [/get-information-about-a-company](https://www.gov.uk/get-information-about-a-company)
- [/check-if-you-need-tax-return](https://www.gov.uk/check-if-you-need-tax-return)
- [/view-right-to-work](https://www.gov.uk/view-right-to-work)
- [/trade-tariff](https://www.gov.uk/trade-tariff)
- [/register-for-self-assessment](https://www.gov.uk/register-for-self-assessment)
- [/file-your-confirmation-statement-with-companies-house](https://www.gov.uk/file-your-confirmation-statement-with-companies-house)
Reverts https://github.com/alphagov/frontend/pull/3775
Target sign-ups reached for …
> Remove research banner

- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/one_council.html.erb
- app/views/homepage/_chevron_card.html.erb
- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/travel_advice/index.html.erb
- test/integration/find_local_council_test.rb
- we no longer need to nest GA4 attributes attached to elements, notably the index attributes
- these attributes when collected by trackers are automatically nested based on the structure of the GA4 schema, held in the gem
- flattening them here saves code and complexity
None.
Trello card: https://trello.com/c/IseA05Fd/644-remove-nesting-of-ga4-attributes
> Flatten GA4 attributes

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/views/layouts/application.html.erb
Fixes some issues raised by the component auditing tools. See individual commits for details.
Changes to the related navigation component. I had to copy and paste some test data into the page to demonstrate these changes, which are very small and only apply to H3 elements within the component - I can't actually find an instance of the component in `frontend` that would contain a real H3.
Before | After
------ | ------
> Component auditing fixes

- lib/data/when-do-the-clocks-change.json
Correct End of British Summer Time date for 2024
The year was incorrectly entered as 2023. It was affecting the ICS file that is available to download and consequently a wrong date was imported to calendar applications.
https://govuk.zendesk.com/agent/tickets/5539102
No visual change on the frontend
> Correct end of British Summer Time date for 2024

- app/views/homepage/_homepage_header.html.erb
Use a hyphen in the visually hidden text in the homepage heading.
I've tested that our supported screen readers announce the heading correctly with the hyphen.
This aligns it with the new and existing meta descriptions that use the hyphen for the same copy. 
> Update punctuation in the homepage heading

- app/views/application/_location_form.html.erb
Remove hardcoded fieldset
Hardcoded fieldset seems to be unnecessary, not 
[Trello card](https://trello.com/c/hLWw24uX/1700-ps24-review-and-fix-issues-with-the-postcode-lookup-template-used-in-the-frontend-app)
No visual difference before/after.
> Remove unnecessary hardcoded fieldset

- app/views/homepage/_departments_and_organisations.html.erb
- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_homepage_header.html.erb
- app/views/homepage/_inverse_header.html.erb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_more_on_govuk_new.html.erb
- app/views/homepage/_popular_links.html.erb
- app/views/homepage/_promotion-slots.html.erb
- app/views/homepage/_promotion_slots_new.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/homepage/index.html.erb
Removes scroll tracking for GA4 using markers from the homepage.
Scroll tracking is no longer required.
None.
Trello card: https://trello.com/c/R6z5Hd3d/714-remove-scroll-tracking
> Remove scroll tracking from homepage

- app/views/homepage/_homepage_header.html.erb
We recently swapped the punctuation in the visually hidden text in the new homepage heading from a colon to a dash, but didn't include a space in front of the dash. This wasn't obvious visually or when tested with screen readers since the visually hidden text inserts a space character before it. However if the user turns off their stylesheets, there wouldn't be a space character before the dash and this is the version that search engines receive as well.
(This also makes https://trello.com/c/kroI3kLZ/684-stop-extra-whitespace-being-added-inside-homepage-h1 redundant although as noted on that ticket, we might need to look into being able to control whitespace in templates in the future if another use case for needing this comes up. )
So that search engines and users who turn off …
> Add a space before homepage heading dash

- app/views/homepage/index.html.erb
- for GA4 tracking, change the `index_section` values for the different sections on the homepage
- we now count the search section as `index_section` 1
- so increment all the following sections by 1
- this means that there are now 6 sections, which matches the count from the previous design, so removes the different values set for each
Keeping the analytics up to date with recent design changes.
None.
Trello card: https://trello.com/c/y2GsDL23/697-add-index-section-parameters-to-search-on-homepage
> Change GA4 index_section values on homepage

- test/service_consumers/pact_helper.rb
[Trello card](https://trello.com/c/7f3F6Xij/3338-migrate-from-the-old-paas-based-pact-broker-to-the-new-instance-on-heroku)
We are currently migrating our Pact Broker instance from PaaS to Heroku. `gds-api-adapters` has already been updated to publish pacts to both instances, now we need to update each of our API providers to fetch from the new instance instead of the old one.
> Update Pact Broker URL

- app/views/licence_transaction/authority_interaction.html.erb
- headings on pages such as https://www.gov.uk/find-licences/tattooists-piercing-and-electrolysis-licence-scotland/edinburgh/change have an empty link inside them, with an ID
- this is so that the headings can be linked to directly from the contents links above
- markup is wrong, for an element to be linked to by a jump link/URL hash such as /page#anchor, any element can be given an ID, it doesn't have to be an <A> tag
The <A> tag doesn't serve a purpose and is causing the link tracking on this page to be confused - the empty links are being counted in the index counts for links and producing incorrect values. …
> Fix authority link markup

- Dockerfile
Yarn behaviour had changed at some point in the subsequent releases, so we have to force a global version of 1.22.19 (the last working version) to avoid braking our builds. Further investigation should be made as Yarn continues to upgrade its global version (as of typing, 1.22.21 https://github.com/yarnpkg/yarn/releases )
> Update Dockerfile to force Yarn 1.22.19

- app/views/calendar/_calendar_footer.html.erb
- app/views/calendar/bank_holidays.html.erb
- app/views/find_local_council/_base_page.html.erb
- app/views/help/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_base_page.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
Remove options passed to components for enabling GA4 tracking. All components referenced now have tracking enabled by default, and this option has been removed.
Unneeded code.
None.
Trello card: https://trello.com/c/Xwp7dgJN/294-tracking-auditing-tracking-by-default
> Remove unneeded instances of ga4_tracking: true

- app/views/homepage/_popular_links.html.erb
Updates the instances of the action link component on the homepage to use a slightly different option to pass data attributes to the component.
- the `data` option on this component is being removed, in favour of the `data_attributes` option
- the only difference is that `data` applies attributes directly to the link of the component, whereas `data_attributes` applies it to the parent element of the component
- in this case it makes no difference due to the way that both the link trackers (for UA and GA4) work, i.e. when a link is clicked the tracker looks up through the DOM to find the right attributes to …
> Update action link data option

- app/views/homepage/_homepage_header.html.erb
- adds `index_section` and `index_section_count` attributes to the GA4 event fired on the homepage when a search is performed
- brings the search into line with other tracking on the homepage
None.
Trello card: https://trello.com/c/UThJ4i9e/745-placeholder-add-index-section-to-homepage-search
> Add GA4 index to homepage search

- app/controllers/licence_transaction_controller.rb
- test/functional/licence_transaction_controller_test.rb
- test/integration/licence_transaction_test.rb
For some licences, the council being selected after a user submits their postcode is incorrect and the user sees a licence unavailable message. This is because some licences are managed at the county level vs the district level.
This change adds in the ability to query the different councils returned by Local Links Manager and select the first one that has an actionable licence. District and parent authority can be returned by LLM [1].
[1]: https://github.com/alphagov/local-links-manager/blob/f3f95f0a14c7689d30a05e15f06cc6698a9bf62a/app/presenters/local_authority_api_response_presenter.rb#L13
Trello:
https://trello.com/c/DSGOKUXK/2271-investigate-licence-finder-selecting-incorrect-council-for-certain-licences …
> Adds mechanism to select appropriate licence council

- app/views/licence_transaction/authority_interaction.html.erb
The path was incorrect for the interaction links when viewing from another interaction page. The previous links pointed to the authority route vs authority interaction (/find-licences/authority.interaction vs /find-licences/authority/interaction).
> Update path for interaction links

- app/views/calendar/bank_holidays.html.erb
Adds scroll tracking to https://www.gov.uk/bank-holidays
None.
Trello card: https://trello.com/c/JfkV5NSI/750-add-scroll-tracking-top-100-pages
> Add scroll tracking

- app/controllers/csv_preview_controller.rb
- config/routes.rb
- test/integration/csv_preview_test.rb
We are removing whitehall_asset endpoints from GDS API adapters (for more context please see this [PR](https://github.com/alphagov/gds-api-adapters/pull/1220) ).
Legacy url should not be used anymore in the code so we are cleaning up use cases in this repo.
[Trello card](https://trello.com/c/Kp9nquOr/71-task-remove-whitehallasset-concept-from-asset-manager-and-gds-api-adapters)
> Remove Whitehall asset

- app/assets/stylesheets/views/_homepage.scss
Fix print rendering of chevron cards on home page
Text overlaps as shown in the screenshot below
---
> Fix print rendering of chevron cards on homepage

- Gemfile.lock
- app/views/homepage/_promotion_slots.html.erb
- change how GA4 tracking is called on the image cards on the homepage
- pass the link tracker module to the component, instead of the component already containing it
- depends upon https://github.com/alphagov/govuk_publishing_components/pull/3789 - a new version of the gem containing this change must be included with this change
Markup | GA4 event
------- | --------
Part of the GA4 migration. Previously the image card tracking approach was not ideal, this should help to improve it.
None.
Trello card: https://trello.com/c/IymJPytQ/762-sort-out-image-card-component-tracking
> Preserve homepage image card tracking

- app/assets/stylesheets/components/_metadata.scss
- app/views/components/_calendar.html.erb
- app/views/components/_metadata.html.erb
- app/views/components/docs/calendar.yml
- app/views/components/docs/metadata.yml
- app/views/components/docs/subscribe.yml
- test/component_test_helper.rb
- test/components/all_components_test.rb
- test/components/calendar_test.rb
- test/components/metadata_test.rb
- test/components/subscribe_test.rb
- test/integration/bank_holidays_test.rb
- test/integration/gwyliau_banc_test.rb
Improve component testing. Specifically:
- add component test helper, to allow components to be tested
- add tests for components in this application (calendar, metadata, subscribe)
- improve documentation for some of these components
- add a test to check that component files follow conventions
If you want to run a single test, you can do e.g. `bundle exec rake test TEST=test/components/calendar_test.rb`
Work relates to https://github.com/alphagov/govuk_publishing_components/issues/3369
None, although some minor improvements to the component documentation.
> Add component testing

- app/views/calendar/bank_holidays.html.erb
- app/views/simple_smart_answers/show.html.erb
- app/views/transaction/show.html.erb
Removes GA4 scroll tracking from bank holidays, simple smart answers and transactions pages.
No longer needed.
None.
Trello card: https://trello.com/c/DC9sw3jR/772-remove-scroll-tracking-top-100-pages
> Remove scroll tracking

- app/views/transaction/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Fixes video tracking on https://www.gov.uk/self-assessment-ready-reckoner
Note that this appears on the B variant of the A/B test, use the GOVUK browser extension to switch between them or use a mod header extension.
Frontend components should be implemented in templates or helpers, using the code examples found in https://components.publishing.service.gov.uk/component-guide. Injecting pre-rendered component markup into a page like this causes the following problems:
- component is not kept up to date with any changes upstream
- component JavaScript may not work properly (in this case the …
> Fix video tracking on AB test

- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_popular_links.html.erb
- app/views/homepage/_promotion_slots.html.erb
- app/views/homepage/_services_and_information.html.erb
- app/views/homepage/index.html.erb
Remove GA4 scroll tracking from the homepage.
No longer needed.
None.
Trello card: https://trello.com/c/4SsfCyET/777-placeholder-remove-scroll-tracking-from-homepage
> Remove homepage scroll tracking

- app/controllers/local_transaction_controller.rb
- config/environments/test.rb
- test/integration/local_transactions_test.rb
This may be temporary!
Reverts https://github.com/alphagov/frontend/pull/1277 to see if this is still an issue. If it is, then I will reinstate with some instrumentation to permit inspection of the use of this feature.
We'll be able to see new instances of this occurring in the logs for locations-api. We short circuit the request before making API calls at present, hence the need for this change.
> Remove "banned postcode" feature

- app/views/help/cookie_settings.html.erb
- test/integration/help_cookies_test.rb
Set the options on the `/help/cookies` cookie settings page to be off by default in the HTML. They're currently not set in the HTML.
- this was previously handled by JavaScript, which would set the default reject consent cookie on page load, then set the radio buttons to match, or read the user set consent cookie, and set the radio button options accordingly
- now the radio buttons will appear as 'off' and then if the cookie says otherwise, the JS will update them, so this could be briefly visible (but the buttons are mostly below the fold anyway)
- when JS is disabled these radio buttons don't appear
Defaulting …
> Default cookie settings page to reject

- app/views/components/_calendar.html.erb
- test/integration_test_helper.rb
Affects [www.gov.uk/bank-holidays](http://www.gov.uk/bank-holidays) and [www.gov.uk/when-do-the-clocks-change](http://www.gov.uk/when-do-the-clocks-change)
- https://govuk-frontend-app-pr-3982.herokuapp.com/bank-holidays
- https://govuk-frontend-app-pr-3982.herokuapp.com/when-do-the-clocks-change
- https://govuk-frontend-app-pr-3982.herokuapp.com/gwyliau-banc
The year and the month/day are spaced apart in the current implementation. The year is the caption to the table in which the month/day are listed. 
By using the `time` tag, we can [make this easier for machines to interpret](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time).
```
<th class="govuk-table__header" scope="row">29 March</th>
```
```
<th class="govuk-table__header" scope="row">
<time datetime="2024-03-29">29 …
```
> Use a time tag to include the full date

- app/views/calendar/bank_holidays.html.erb
- test/integration/bank_holidays_test.rb
Adds GA4 tracking to the `.ics` download links on https://www.gov.uk/bank-holidays
https://trello.com/c/Ov4XJdDr/813-file-download-event-to-fire-on-calendar-downloads
> Add GA4 tracking to /bank-holidays .ics files

- app/controllers/csv_preview_controller.rb
- app/services/csv_preview_service.rb
- test/integration/csv_preview_test.rb
- test/unit/services/csv_preview_service_test.rb
Some CSV previews (eg [this one](https://assets.publishing.service.gov.uk/media/5d0b821ae5274a06930754b6/Cabinet_Office_ministerial_meetings__January_to_March_2019.csv/preview "‌")) are raising `"\x8D" to UTF-8 in conversion from Windows-1252 to UTF-8 (Encoding::UndefinedConversionError)` and showing an unformatted ugly error page to users.
So users can see the preview they are expecting to see
[Trello card](https://trello.com/c/uiiCSOcC/2498-sentry-errors-fix-frontend-undefinedconversionerror-m)
We already have the functionality to show that the CSV preview is not supported for this file. …
> Sentry Errors: Fix Frontend UndefinedConversionError

- .github/workflows/deploy.yml
- Dockerfile
This switches Frontend over to use the Multi-arch build process to start giving us ARM-compatible container images.
This also makes sure we're on at least Ruby 3.2.4, to give us ARM supported Ruby Images (and fix a recent CVE).
Paging @hannako for visibility.
> Enable Multiarch, Bump to Ruby 3.2.4

- app/views/csv_preview/show.html.erb
- test/integration/csv_preview_test.rb
Update logo links in CSV previews to be absolute urls on www.gov.uk (or appropriate for environment)
Because previews appear on the assets.publishing.service hosts, the relative logo links go to those hosts and 404
https://govuk.zendesk.com/agent/tickets/5817577
Use Plek.website root and add logo path to that.
> Change logo links on CSV previews to be absolute

- Gemfile.lock
- app/views/homepage/_homepage_header.html.erb
Disable corrections for homepage search field
As part of our work on site search, we've discovered a pain point where mobile browsers' autocorrection features mess up user queries, especially when it comes to domain specific terminology. For example, searches for "HMRC" are frequently autocorrected to "Hercules", or searches for "SORN" to "sworn".
See: https://github.com/alphagov/govuk_publishing_components/pull/4112
- Bump `govuk_publishing_components` to 40.1.0
- Set `disable_corrections` parameter for `search` component in homepage header
> Disable corrections for homepage search field

- app/views/travel_advice/index.html.erb
- Adds the `ga4-focus-loss-tracker` to this page: https://www.gov.uk/foreign-travel-advice because it was missed when we worked on GA4.
- This tracker is the one that sends an event to GA4 when focus is removed from the element in question, which was our solution for tracking client side filter search boxes.
- The attributes on this element are the same as the ones on this page's filter input: https://www.gov.uk/government/organisations
- Trello card: https://trello.com/c/Tx2CZZvS/836-add-filter-tracking-to-https-wwwgovuk-foreign-travel-advice
> Add GA4 tracking to filter on travel advice index page

- app/assets/stylesheets/components/_subscribe.scss
Fixes the following Sass compilation warning:
```
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.
More info: https://sass-lang.com/d/mixed-decls
┌──> app/assets/stylesheets/components/_subscribe.scss
5   │     margin-bottom: govuk-spacing(8);
│     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
╵
┌──> /root/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/govuk_publishi …
```
> Fix sass compilation warnings

- app/controllers/favicon_controller.rb
- config/routes.rb
- spec/requests/favicon_spec.rb
This allows us to move the /favicon special route from static to frontend, removing the icon redirect controller from static in preparation for its retirement.
- Remove favicon.ico in public directory as it's not copied to the S3 bucket and it short-circuits matching the route.
- Route high up in the routes file so that we don't have to check for/load a content item to do this redirect.
> Handle root favicon requests

- app/controllers/help_controller.rb
- app/controllers/sessions_controller.rb
- app/models/election_postcode.rb
- app/models/locations_api_postcode_response.rb
- app/presenters/licence_details_presenter.rb
- app/presenters/place_presenter.rb
- app/presenters/travel_advice_index_presenter.rb
- spec/models/election_postcode_spec.rb
- spec/models/uprn_spec.rb
- spec/requests/sessions_spec.rb
- spec/system/developer_root_spec.rb
- spec/system/sign_in_spec.rb
- spec/unit/presenters/content_item_presenter_spec.rb
- spec/unit/presenters/place_presenter_spec.rb
Various updates to improve coverage, plus bug fixes discovered while improving coverage:
- fix sessions controller always ignoring referer when deciding if a redirect was valid
Current improvement in line coverage: 97.99% -> 98.47%
Current improvement in branch coverage:  86.36% -> 89.39%
As we move the routes from government-frontend over, the better our existing coverage the easier it will be to spot coverage problems in the new code. Ideally if we have 100% line coverage, any lack of coverage in the new code will stick out like a sore thumb. We should also strive for 100% branch coverage as a secondary goal. …
> Improve coverage

- app/controllers/landing_page_controller.rb
- app/helpers/block_helper.rb
- app/models/block/base.rb
- app/models/block/columns_layout.rb
- app/models/block/layout_base.rb
- app/models/block/two_column_layout.rb
- app/models/block_factory.rb
- app/models/content_item_factory.rb
- app/models/landing_page.rb
- app/views/landing_page/blocks/_big_number.html.erb
- app/views/landing_page/blocks/_columns_layout.html.erb
- app/views/landing_page/blocks/_govspeak.html.erb
- app/views/landing_page/blocks/_tabs.html.erb
- app/views/landing_page/blocks/_two_column_layout.html.erb
- app/views/landing_page/show.html.erb
- config/routes.rb
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/sub_page_1.yaml
- spec/fixtures/landing_page.yaml
- spec/helpers/block_helper_spec.rb
- spec/models/block/layout_base_spec.rb
- spec/models/block/two_column_layout_spec.rb
- spec/models/landing_page_spec.rb
- spec/requests/landing_page_spec.rb
- spec/system/landing_page_spec.rb
Add the scaffolding required to render flexible "blocks", where the type of block, and the order of the blocks can be controlled by the user.
A new flexible content type called a landing page is being created.
The content type will allow publishers to pick the "blocks" that should be included on the page, e.g. govspeak, tabs, image, video, and decide on the order of these "blocks".
The publishing app doesn't exist for these blocks yet, nor does a content schema. 
Therefore, for the time being dummy content is being hard-coded. This will be replaced by actual hard-coded content when the first landing page is ready …
> Landing pages backend scaffold

- app/models/block/hero.rb
- app/models/block/layout_base.rb
- app/models/block_factory.rb
- spec/models/block_factory_spec.rb
We're finding there are lots of places where we want to take a list of block hashes and turn them into a list of blocks (not all of these have hit main yet, but the need is there)
Currently we're duplicating the bit mapping code, and it's a bit ugly. This helper method DRYs things up a bit.
> Add a build_all helper method to BlockFactory

- app/models/content_item.rb
- app/models/content_item_factory.rb
- app/models/landing_page.rb
- spec/models/landing_page_spec.rb
The code was sometimes passing GdsApi::Responses into the ContentItem constructor, and sometimes Hashes.
GdsApi::Response behaves enough like Hash to be confusing, but it's not exactly the same. For example, it doesn't have a deep_merge method. It's also missing things which aren't to do with the body, like a cache_control method.
Technically the ContentItem constructor requires a GdsApi::Response, because it delegates the cache_control method to that object. So we shouldn't have been passing it a Hash.
This commit adds a temporary `override_content_store_hash` parameter, which we can use to override the bits we …
> Fix content store response type

- app/assets/stylesheets/views/_landing_page/featured.scss
- app/models/block/featured.rb
- app/views/landing_page/blocks/_featured.html.erb
- config/initializers/dartsass.rb
- lib/data/landing_page_content_items/landing_page.yaml
- spec/models/block/featured_spec.rb
Adds the featured block for the landing page.
Uses code copied from the hero block to provide the text content, including more flexibility than we probably currently need. Might be good to consolidate this code - there's potentially a third block going to use the same approach.
Image handling is also copied from the hero block, using a picture element and screen pixel density detection to display an appropriate image for the current device.
Required for the landing page.
Appearance on desktop. The image should be a set height, and it will determine the minimum height of the box and be centred within it. This …
> Add featured block

- lib/data/landing_page_content_items/landing_page.yaml
Now that the designs don't call for a fancy video collection block, I think we can just use govspeak for the video.
This is consistent with the approach taken on the current number 10 org page:
https://github.com/alphagov/collections/blob/main/app/views/organisations/_videos.html.erb#L22-L24
If we need more configurability than govspeak gives us we can add a video block. But if we don't need it, let's not implement it!
[Trello card](https://trello.com/c/J3TRzA4R/51-build-video-collection)
Check out the preview app.
> Add an example video using the govspeak block

- spec/requests/landing_page_spec.rb
Modifies the request tests to use the new example landing page from content-schemas, and adds a test to check that the page renders when the fake data in the controller is used.
There are two ways that a landing page can be loaded. One is from a content item, and one is by using the fake data in the controller. We were only testing data from a content item.
> Add landing page request tests to increase test coverage

- app/assets/stylesheets/views/_landing_page/hero.scss
Improve the frontend code for the hero block. Specifically:
- set padding correctly on the text box
- improve position of text box on mobile
- set a minimum height of the picture element, to reduce CLS and stop the text box from hitting the bottom of the page before the image loads
FE added with initial block code was prototype.
The image is now in a container with a fixed height and we'll have to make the images be the right height. This is to avoid cumulative layout shift and also to prevent the negative top margin text block from overflowing into the site header if the image fails to load for some reason.
The …
> Improve the FE for the hero

- app/views/landing_page/blocks/_action_link.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
Fix the appearance of the action link on a dark background on the landing pag.e
- previously had an override to convert the generally used `inverse` option to `light_text`, which the action link component required
- however the action link has now been modified to use `inverse` so this code is no longer needed
Before | After
----- | ------
Trello card: https://trello.com/c/GYhdvFfi/45-create-hero-block
> Fix the action link inverse option

- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/views/landing_page/blocks/_main_navigation.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- Makes the "Service name" heading a link, instead of just text
- This change is part of fulfilling our design requirements, similar to this component: https://design-system.service.gov.uk/components/service-navigation/with-service-name-and-navigation/
For visual reference, I'm referring to the service name heading here
> Make the service name heading a black link

- Gemfile.lock
- app/models/block/share_links.rb
- app/views/landing_page/blocks/_share_links.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- Adds the share links variant from https://github.com/alphagov/govuk_publishing_components/pull/4292/ to the landing page
- https://trello.com/c/LNOqGMgZ/49-build-social-media-links
> Add share links variant to landing page

- app/helpers/contents_list_helper.rb
- app/views/landing_page/blocks/_main_navigation.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/sub_page_1.yaml
- spec/fixtures/landing_page.yaml
- spec/helpers/contents_list_helper_spec.rb
- spec/system/landing_page_spec.rb
DRY-up the [contents list helper](https://github.com/alphagov/frontend/pull/4264/commits/d1a9563e6f2c74264196a1e7e5f6b6b5cf5ef2dc) that is being created for side navigation so that it can be used in both the side and main navigation blocks.
The helper also supports nested links.
Both the “side navigation” and “main navigation” blocks need to know which page the user is on to set one of the links to active.
A helper was created for the side navigation block. This [code](https://github.com/alphagov/frontend/pull/4264/commits/d1a9563e6f2c74264196a1e7e5f6b6b5cf5ef2dc) should be DRY-ed up to be used in both.
[Trello …
> Add a helper to get active links

- app/helpers/block_helper.rb
- app/views/landing_page/blocks/_action_link.html.erb
- app/views/landing_page/blocks/_blocks_container.html.erb
- app/views/landing_page/blocks/_card.html.erb
- app/views/landing_page/blocks/_featured.html.erb
- app/views/landing_page/blocks/_govspeak.html.erb
- app/views/landing_page/blocks/_grid_container.html.erb
- app/views/landing_page/blocks/_hero.html.erb
- app/views/landing_page/blocks/_two_column_layout.html.erb
- app/views/landing_page/show.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- spec/fixtures/landing_page.yaml
- spec/helpers/block_helper_spec.rb
Add a helper to hide missing blocks on the landing page
Some times blocks are configured in the YAML files before the block partials have been created. Or blocks are misspelled in the YAML. When this happens, we don't want the page to error. Instead that block should fail silently and be ignored.
The inverse property that some of the partials expect had to be moved into the block config so that it would be available to the block helper.
No visual changes
> Hide missing blocks on landing page

- app/models/content_item.rb
- spec/models/content_item_spec.rb
Exposes .schema on the content item, and adds (via metaprogramming) methods like content_item.is_a_landing_page? which allow us to query schema tidily in views, etc, without having to put .schema == " whatever" or add instance variables in controllers.
- returns true if called with the schema name of the
document, so is_a_landing_page? is true for landing
pages, but false for anything else.
- is_an_xxxx? also works, for the nicer feel of being able to
say is_an_organisation? when we move other document
types into frontend.
> Expose schema name and query

- lib/data/landing_page_content_items/homepage.yaml
Build a demo page for each of the landing page type to demo a potential arrangement of blocks. Uses dummy content.
[Trello card](https://trello.com/c/eIueNNk9)
Video content is added via a govspeak block.
> Adds a demo of a homepage type of landing-page

- app/assets/stylesheets/views/_landing_page.scss
- app/helpers/application_helper.rb
- app/views/landing_page/show.html.erb
- app/views/layouts/application.html.erb
- config/initializers/dartsass.rb
- spec/helpers/application_helper_spec.rb
This PR adds the landing page header. It is dependent on [PR #4284](https://github.com/alphagov/govuk_publishing_components/pull/4284) in the components gem being released.
[Trello card](https://trello.com/c/W2Jk6Qka/46-build-landing-page-header)
> Add header

- app/models/block/side_navigation.rb
- app/views/landing_page/blocks/_side_navigation.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/links/side_navigation.yaml
- spec/fixtures/landing_page.yaml
- spec/fixtures/landing_page/links/side_navigation.yaml
- spec/models/block/side_navigation_spec.rb
Adds the side navigation block for the landing page.
Uses the same list of links on every page that uses this block. That's fine for now because the first set of landing pages being built are linked together.
Another solution will need to be considered if landing pages start needing different sets of links in the side navigation.
[Trello card](https://trello.com/c/l9yaSdmV)
> Scaffold for Side Navigation block on landing pages

- lib/data/landing_page_content_items/tasks.yaml
Build a demo page for each of the landing page types to demo a potential arrangement of blocks. Uses dummy content.
[Trello card](https://trello.com/c/eIueNNk9)
The blocks that haven't been added yet have been commented out.
> Add a demo of a tasks (plural) type of landing-page

- app/models/content_item.rb
- app/views/landing_page/show.html.erb
- spec/helpers/application_helper_spec.rb
- spec/models/content_item_spec.rb
This PR addresses the duplication of breadcrumbs on the landing page.
[Trello card](https://trello.com/c/GXta8M1o/92-remove-duplicate-breadcrumbs)
> Fix breadcrumb duplication

- app/views/landing_page/blocks/_heading.html.erb
- lib/data/landing_page_content_items/homepage.yaml
- When a `govspeak` paragraph only contains a YouTube video, it removes the paragraph tag entirely, and therefore the spacing we gain from the `<p>` styles are lost. Therefore, the heading was right against the video. Both the heading and video were in a govspeak block. Instead, we can create a basic heading block that can be used here, instead of relying on a `govspeak` paragraph to give us spacing. Our gem heading component has a `padding` option which will  be used to give us the spacing from the video instead.
- Alternatively, I could make a `video` block that then renders `govspeak` and a `heading` gem …
> Add basic heading block

- README.md
- Placeholder route is only served on assets.publishing.service.gov.uk
> Update example for placeholder in readme

- Gemfile.lock
```
bundle update govuk_publishing_components
```
> Update govuk_publishing_components to 44.4.2

- app/views/landing_page/blocks/_heading.html.erb
Switch from the heading option to provide padding top and bottom to using margin bottom only.
We're trying to make spacing consistent by using a margin bottom approach for blocks, and having top padding on the video block like this will make making the spacing consistent more complicated.
Before | After
----- | ------
> Change video block heading spacing

- app/controllers/calendar_controller.rb
- config/routes.rb
- spec/system/icalendar_spec.rb
Improve / Simplify bank holiday routing
Routing for bank holiday pages currently relies on a side-effect of other (correctly written) FormatRoutingConstraint blocks above it, has unnecessary explicit routes for the Gwyliau-banc pages, and always loads the content item twice from the API.
Fix the parameter from scope to slug and translate to scope only in the controller, remove the explicit gwyliau-banc routes that existed only to set the locale to Welsh on those pages and simply use the locale from the relevant content item. Finally, remove the overridden content_item method to use the ContentItemController …
> Fix calendar param names

- app/assets/javascripts/dependencies.js
- app/models/block/statistics.rb
- app/views/landing_page/blocks/_statistics.html.erb
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/statistics/data_one.csv
- lib/data/landing_page_content_items/statistics/data_two.csv
- spec/fixtures/landing_page.yaml
- spec/fixtures/landing_page_statistics_data/data_one.csv
- spec/fixtures/landing_page_statistics_data/data_two.csv
- spec/models/block/statistics_spec.rb
Adds a statistics block to display CSV data on landing pages
[Trello card](https://trello.com/c/gvLYQCUp)
Rendered version: https://govuk-frontend-app-pr-4261.herokuapp.com/landing-page
> Scaffold for Statistics block on Landing pages

- app/helpers/link_helper.rb
- app/views/landing_page/blocks/_heading.html.erb
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/sub_page_1.yaml
- lib/data/landing_page_content_items/task.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/fixtures/landing_page.yaml
- spec/helpers/link_helper_spec.rb
- spec/system/landing_page_spec.rb
Replace of use of \<h2> elements in govspeak blocks with the heading block.
At the moment we have two ways of adding headings. It’s confusing to know which version should be used under which circumstances.
During a standup we decided to use the heading block as standard as that has to be used for video blocks.
[Trello card](https://trello.com/c/O7CmnQo6)
There shouldn't be any visual changes
|Original|Updated|
|-------|----------|
|[Homepage](https://govuk-frontend.herokuapp.com/landing-page/homepage)|[Homepage](https://govuk-frontend-app-pr-4308.herokuapp.com/landing-page/homepage)| …
> Use heading block in landing page demos

- lib/data/landing_page_content_items/landing_page.yaml
- spec/fixtures/landing_page.yaml
- spec/models/block/statistics_spec.rb
- use the built in functionality of the chart component to output a link to the original data
- remove unneeded data_source_text value, as the component provides text
Charts will now have the 'download chart data' link shown below.
Trello card: https://trello.com/c/t0DlqDkW
> Change statistics data

- app/views/landing_page/blocks/_share_links.html.erb
- Uses the new `flexbox` option for share links
- For better design consistency
- https://trello.com/c/mK8f3WMQ/93-adjust-share-links
> Use flexbox option for share links

- app/assets/stylesheets/views/_landing_page/card.scss
- app/helpers/block_helper.rb
- app/models/block/card.rb
- app/views/landing_page/blocks/_action_link.html.erb
- app/views/landing_page/blocks/_card.html.erb
- app/views/landing_page/blocks/_featured.html.erb
- app/views/landing_page/blocks/_govspeak.html.erb
- app/views/landing_page/blocks/_heading.html.erb
- app/views/landing_page/blocks/_hero.html.erb
- app/views/landing_page/blocks/_statistics.html.erb
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/task.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/fixtures/landing_page.yaml
- add small charts to /landing-page/homepage
- updates the card block to have the image be optional (we might want to remove the image option entirely at some point, but leaving it for now)
- modifies the data for the card blocks to have statistics as an extra block after heading
- make some changes to how the card block outputs these blocks for style purposes by wrapping each block in an appropriate wrapper (heading needs to be in a blue box, chart needs to be in a box with a border round it)
- change the heading block to accept a margin parameter, so that 0 can be passed when it's inside a card text box …
> Add small charts

- config/routes.rb
- lib/format_routing_constraint.rb
- lib/full_path_format_routing_constraint.rb
- spec/requests/calendars_spec.rb
- spec/routing/calendars_spec.rb
- spec/routing/landing_pages_spec.rb
- spec/system/sessions_spec.rb
- spec/unit/full_path_format_routing_constraint_spec.rb
Update routing constraints so that we can put landing pages on arbitrary paths.
Landing pages may be on any path, so we need a way to match them by routing constraint. The existing FormatRoutingConstraint was designed for items where an initial slug served multiple paths, and cached at 
the slug level, meaning it could never match a full path.
Add a new class to handle format constraints from full paths, which does not cache its calls to the content store or
rely on preexisting cached calls. This isn't optimal, but acceptable for the moment given that there is currently only one 
schema_name being matched this …
> Update routing constraints

- app/views/landing_page/blocks/_share_links.html.erb
- Use `margin_bottom: 6` instead of `padding: true` for the share links heading
- Prevents extra spacing above the heading, and makes it consistent with the existing heading block.
- I guess this heading could be a heading block, but that would introduce duplication across each template, and the heading is wrapped in an if statement. Happy to change if it to use the heading block if that's preferred, but if so I will hold off until the overall yml refactor PR is done.
> Use margin bottom instead of padding on share links heading

- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/models/block/main_navigation.rb
- app/views/landing_page/blocks/_main_navigation.html.erb
- spec/models/block/main_navigation_spec.rb
- Makes the margin between the `Service name` (black link) and the menu items (blue links) the same.
- Adds more spacing to the mobile menu, and adds left padding to the list items so that they are staggered away from the menu button, as per the designs.
- Adds a `border_bottom` to the block. This required turning it into a proper block, so that `full_width?` could be used, otherwise the border would only go up to the width limits of the `govuk-width-container` class. 
- Renames the `children:` variable for child links to `items:`. I tried to get it work with `children:` as thats more readable, but for some …
> Tweak main_navigation block to align with designs

- app/models/block/share_links.rb
- app/views/landing_page/blocks/_share_links.html.erb
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
- Links the hero and featured blocks to pages
- Changes the `share_links` heading so that it's about social media pages, rather than "sharing". As the component is called "Share Links" I think it led to this wording being used, whereas I think they should be shown as links to social media profiles. 
- Enables GA4 tracking on the social media links
- Renames the dummy links and adds `hidden_text` to the social media links, so that it's shown that they're follow links.
[Trello card](https://trello.com/c/hzfHN1fI)
> Tweak content and links

- app/assets/javascripts/modules/app-b-main-navigation.js
- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/views/landing_page/blocks/_main_navigation.html.erb
- spec/javascripts/unit/modules/app-b-main-navigation.spec.js
This PR makes the collapsible menu only appear on mobile as per the designs.
I’ve also potentially spotted some other things -  I’ve kept them as separate commits (please see the commit messages for further details) so they’re easy to undo in case I’ve misunderstood things and removed/changed them in error.
[Trello card](https://trello.com/c/Ef2HNA2a/108-finalise-page-c-our-priorities-for-change-landing-page)
> Show collapsible menu on mobile only

- app/helpers/block_helper.rb
- spec/helpers/block_helper_spec.rb
Enable two-thirds column layout from desktop only (i.e. use full width on mobile and tablet).
As per design review.
> Only use two-thirds layout from desktop

- app/views/landing_page/blocks/_image.html.erb
This PR adds some bottom margin to the image block via a govuk spacing override class.
I opted for `govuk-!-margin-bottom-6` as that's what the `h2` above the image has.
As per design review.
> Add bottom margin to image blocks

- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/views/landing_page/blocks/_main_navigation.html.erb
This PR aligns the main navigation block styling with the [service navigation component](https://design-system.service.gov.uk/components/service-navigation/).
As per design review.
[Trello card](https://trello.com/c/Ef2HNA2a/108-finalise-page-c-our-priorities-for-change-landing-page)
The indentation has been removed and the focus/hover/active states now align with the service navigation component. I haven't added screenshots here as there would be quite a few and I thought it might be less cumbersome to review using the [preview link](https://govuk-frontend-app-pr-4335.herokuapp.com/).
If screenshots would make …
> Main nav design fixes

- app/views/landing_page/blocks/_main_navigation.html.erb
- Adds an aria-label called `Secondary` to the main navigation block
- Requested by accessibility specialist because it just said "navigation" in VoiceOver before this.
- https://trello.com/c/IRWqtcxu/119-missing-label-for-secondary-menu-navigation-landmark-info-and-relationships-131
- To test in VoiceOver, run `Ctrl + Option + U` in voiceover, then use the arrow keys until you see the list of Landmarks. This one will say "Secondary navigation" (couldn't figure out how to screenshot while VoiceOver was running)
> Add aria label to main nav

- app/views/landing_page/show.html.erb
- Add `<main>` HTML element
- For accessibility reasons
- https://trello.com/c/ZIIk6smn
> Add main html tag

- app/views/homepage/_homepage_header.html.erb
Fix the URL for the homepage search form
The form points to the wrong path for search - `/search` is a landing page, not the actual all content finder (which is `/search/all`). This means users searching from the homepage have to go through an unnecessary redirection:
See also: https://github.com/alphagov/govuk_publishing_components/pull/4341
- Changes URL in the form
- Cleans up the form code by using Rails's tag helper for neater data attributes
> Homepage: Fix search form path

- app/views/homepage/_homepage_header.html.erb
Set explicit field name for search input on homepage
This is coming through as the default name of `q`, which Finder Frontend implicitly converts so it's not causing problems for users, but it's slightly messing with our analytics racking.
> Homepage: Set explicit field name for search input

- app/models/content_item.rb
- app/models/landing_page/block/statistics.rb
- app/views/landing_page/blocks/_statistics.html.erb
- spec/factories/content_items.rb
- spec/factories/landing_pages.rb
- spec/models/content_item_spec.rb
- spec/models/landing_page/block/statistics_spec.rb
- spec/requests/landing_page_spec.rb
- spec/system/landing_page_spec.rb
Allow landing_page statistics blocks to use attachments linked from the content item.
https://trello.com/c/bUVC9hYD/123-csv-data-as-attachments-in-whitehall
> Statistics from attachments

- docs/adr/0002-flexible-landing-pages.md
Add ADR for flexible landing pages.
Rendered Version: https://github.com/alphagov/frontend/blob/2c6784b34370d314e42adf4480508f1e7f88fa26/docs/adr/0002-flexible-landing-pages.md
> Add ADR for flexible landing pages.

- CONTRIBUTING.md
- README.md
This pulls out the agreed code structure from RFC 175
Add contribution guidelines for frontend
Now that we're starting to move routes from government-frontend we should document the code structure that was agreed in RFC 175.
> Add contribution guidelines for frontend

- app/models/content_item.rb
- Some content items rendered by frontend (eg. licences) turn out to have non-standard structures for attachments, so fail if you try to make them as a data item (which requires the inputs to match the structure exactly).
Related:
https://govuk.sentry.io/issues/6030737250/events/f86bf91ae0ee41e28002c43d7e1b5de4/
Example failing page:
https://www.gov.uk/find-licences/the-beef-carcase-classification-scheme-work-as-a-classifier
> Use OpenStruct rather than Data

- Gemfile.lock
- app/views/homepage/_homepage_header.html.erb
This replaces the existing use of the generic form tracker for the homepage search field with the new search tracker from GOV.UK Publishing Components.
GOV.UK Publishing Components now offers a bespoke tracker for all search fields across GOV.UK, which will allow us to track new search features consistently across GOV.UK going forwards.
> Homepage: Use new GA4 search tracker

- Gemfile.lock
- app/views/landing_page/blocks/_statistics.html.erb
- lib/data/landing_page_content_items/tasks.yaml
- Upgrade govuk_publishing_components to 44.11.0 which gives us access to `hide_heading` in the chart component.
- Update some of the chart data now that validation in place requires a `chart_heading` value.
- Fixes the `/tasks` page which is currently crashing.
- `chart_heading` is needed for accessibility, but these charts were getting their headings from outside the component so they did not have this value populated. Therefore the page that these charts were on was crashing.
- Therefore we needed a way to give them a heading, but not show the heading on the page. 
- The resulting gem upgrade and the updated …
> Upgrade govuk_publishing_components and fix crashing charts

- spec/support/meta_tags.rb
- spec/system/take_part_spec.rb
- With the current system of asking for a base_path and then tagging on /some-page, we can't use this for singleton pages like /get-involved, but we can simplify the tests to make them take the entire path.
- Update take_part_spec calls to pass a full path.
> Simplify shared examples for meta tag tests

- spec/support/meta_tags.rb
- RandomExample doesn't generate valid examples for  (at least) the get-involved schema, and it's not really necessary for this set of tests, so change this to use the standard named schemas.
> Use Example rather than RandomExample

- app.json
- remove explicit stack setting
- add nodejs buildpack - Review apps arre failing when installing yarn-v1.22.22. The error message from Heroku suggested specifically adding a buildpack for node.js before the ruby buildpack is fetched.
> Update heroku configuration

- app/assets/stylesheets/views/_landing_page/hero.scss
Adjust hero image behaviour on large desktop by adding a new breakpoint, so the image will always be full width. We retain the height though to prevent the page from being pushed down, so image content will be lost at large screen sizes.
Note: I was going to more on this but other stuff is calling, so I'm passing it on. Currently the heights for the different breakpoints aren't finalised (you'll notice that the desktop and large desktop are the same) but that will be addressed shortly.
Trying to accommodate feedback.
Trello card: https://trello.com/c/F6n5lNH7
> Adjust hero images

- app/views/landing_page/blocks/_statistics.html.erb
- switch to vertical data for the table by default, as this works much better for all of the data we have
- include the 'point_size' option for later use, as this will also allow improved appearance to the charts
This is ahead of changes to the chart component in this PR: https://github.com/alphagov/govuk_publishing_components/pull/4405
Nothing yet apart from the vertical table, as shown here: https://components.publishing.service.gov.uk/component-guide/chart/vertical%20table
Trello card: https://trello.com/c/aKI3YGL4
> Change statistics block

- app/assets/stylesheets/views/_landing_page.scss
- app/assets/stylesheets/views/_landing_page/featured.scss
- app/assets/stylesheets/views/_landing_page/hero.scss
- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/models/landing_page/block/base.rb
- app/views/landing_page/blocks/_document_list.html.erb
- app/views/landing_page/blocks/_govspeak.html.erb
- app/views/landing_page/blocks/_heading.html.erb
- app/views/landing_page/show.html.erb
- lib/data/landing_page_content_items/homepage.yaml
- adds a general spacing model for all blocks, with a margin bottom of 60px
- some blocks don't want this, so we have specific overrides e.g. share links and main navigation
- this allows us to add a coloured background to blocks a bit more easily, although there are still slightly complex CSS rules around backgrounded blocks following others, where we need to do that (a heading preceding a govspeak block, for example, where they need to look like they're part of the same thing)
- also changes the main block layout, so that all blocks can now have a full width background, and any blocks that should be page width …
> Add block spacing model and background

- app/views/landing_page/show.html.erb
- Adds a `metadata` block for the landing page
- These meta tags make social share previews look better
- It grabs the `title` and `description` from the content item by default, but these can be overridden in the `yml` body.
- You can use the [Social share preview](https://chromewebstore.google.com/detail/social-share-preview/ggnikicjfklimmffbkhknndafpdlabib?hl=en) plugin to see how it will look to users
- The [Machine readable data](https://components.publishing.service.gov.uk/component-guide/machine_readable_metadata) component crashes when I import it into PfG, and doesn't allow featured image customisation, …
> Add metadata block

- app/helpers/application_helper.rb
- app/presenters/content_item_presenter.rb
- app/presenters/travel_advice_index_presenter.rb
- app/services/electoral_service.rb
- app/views/layouts/application.html.erb
- app/views/shared/_publication_metadata.html.erb
- spec/helpers/application_helper_spec.rb
- spec/system/phase_banner_spec.rb
- spec/unit/presenters/content_item_presenter_spec.rb
A small code tidy to move towards getting rid of the current ContentItemPresenter
We want to simplify/standardise how Frontend treats content items, and having the content item presenter in its current form is blocking that.
> Tidy code 3

- app/assets/stylesheets/views/_landing_page.scss
- app/assets/stylesheets/views/_landing_page/helpers/_backgrounds.scss
- app/assets/stylesheets/views/_landing_page/helpers/_borders.scss
- app/assets/stylesheets/views/_landing_page/helpers/_colours.scss
- app/helpers/mission_type_helper.rb
- spec/helpers/mission_type_helper_spec.rb
Add mission type style helpers
To create a shared helper for generating border and background style colors that highlight mission specific content
To use, add the helper within a block view where needed to select the mission name, and then concatenate it with the style name e.g.
```rb
class: "border-top--#{MissionTypeHelper.style(4)}" if block.data["mission_type"]"
```
> Add mission type style helpers

- app/assets/javascripts/modules/app-b-main-navigation.js
- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/views/landing_page/blocks/_main_navigation.html.erb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/fixtures/landing_page.yaml
- spec/javascripts/unit/modules/app-b-main-navigation.spec.js
- spec/models/landing_page_spec.rb
- spec/system/landing_page_spec.rb
- Redesigns the navigation block
- [Trello card](https://trello.com/c/M6GlNVyd)
> Rebuild landing page menu

- docs/building_blocks_for_flexible_content.md
- Update `navigation groups` docs for content blocks.
- The structure for these has changed.
> Update navigation groups docs

- app/assets/stylesheets/views/_landing_page/card.scss
- app/helpers/link_helper.rb
- app/models/landing_page/block/card.rb
- app/views/landing_page/blocks/_card.html.erb
- app/views/landing_page/blocks/_govspeak.html.erb
- app/views/landing_page/blocks/_statistics.html.erb
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/models/landing_page/block/card_spec.rb
- first bit, changing cards in 3 columns on the homepage
- use new branding styles for boxes
- remove link cover as no longer needed
- second bit, reworking progress page
- mainly just adjusting example blocks to match new layout
New design.
Before | After
------ | ------
> Change design for cards

- config/environments/production.rb
We don't set the MEMCACHE_SERVERS environment variable in draft-frontend, so it defaults to trying to access memcached on 127.0.0.1:11211, which doesn't work.
Specifically, we see a bunch of these errors:
127.0.0.1:11211 failed (count: 5) Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 11211
It's not completely clear whether these errors cause user-facing issues, but the draft stack is definitely very flakey in integration based on recent testing, and at worst these logs are noise / red herrings.
It seems sensible to only try to use the mem_cache_store if the servers are configured. There's never a case where we have memcache running on 127.0.0.1:11211
We'll need similar commits in at least government-frontend, finder-frontend and collections.
> Avoid using memcached in the draft stack

- app/models/landing_page/block/main_navigation.rb
- app/views/landing_page/blocks/_main_navigation.html.erb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/factories/landing_pages.rb
- spec/fixtures/landing_page.yaml
- spec/models/landing_page/block/main_navigation_spec.rb
Currently we hardcode "Landing Page Menu" in the button, which is definitely not what we want the menu to be called.
> Allow menu names to be specified in YAML

- lib/content_item_loader.rb
- spec/spec_helper.rb
- spec/support/content_item_loader_helpers.rb
- spec/support/meta_tags.rb
- spec/unit/content_item_loader_spec.rb
The @cache field was being set on the ContentItemLoader class object, not on an instance of it.
The class object will be created once per process, and reused by every request made to that process.
Because our web server (puma) is multithreaded, each process will handle many HTTP requests. In practice, we set WEB_CONCURRENCY=2 and RAILS_MAX_THREADS=5 by default, and run between 2 and 4 replicas.
This combination means each instance of frontend has two content item caches (one for each process), and since there's no mechanism to clear the caches, once they're set there's no way to update them (other than restarting the process, which we only do during deployments / scaling events).
This leads to very confusing behaviour. Content items don't update as expected, but even the same frontend pod …
> Do not cache content items in content item loader

- app/models/landing_page/block/press_notices.rb
- app/views/landing_page/blocks/_press_notices.html.erb
- lib/data/landing_page_content_items/tasks.yaml
- spec/models/landing_page/block/press_notices_spec.rb
Add a new block to handle Press Notices. This combines two gem components, `heading` and `document_list`. [Trello card?](https://trello.com/c/Mi5AaGpo/156-change-our-progress-page)
The Press Notices design has some custom spacing and a top border, which isn't covered by any of the current blocks. Creating a new block therefore allows us to add those custom elements and keep them self contained.
> Add Press Notices block

- app/views/landing_page/blocks/_hero.html.erb
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/fixtures/landing_page.yaml
Add default empty alt text when no placeholder text provided
For accessibility, hero images are decorative and assigned null (empty) alt text using `alt=""`. However, if no placeholder text is provided in the YAML file, the `alt` attribute is currently omitted
> Add default empty alt text when no placeholder text provided

- app/controllers/concerns/search_autocomplete_ab_testable.rb
- app/controllers/homepage_controller.rb
- app/views/homepage/_homepage_header.html.erb
- app/views/homepage/index.html.erb
- spec/spec_helper.rb
- spec/system/homepage_spec.rb
This adds an AB test to the homepage, replacing the `search` component with the new `search_with_autocomplete` one for the B variant.
The same AB test will be running across Frontend and Finder Frontend to allow us to measure whether providing users with autocomplete suggestions as they type will lead to better outcomes from interacting with site search.
Following the usual conventions for setting up AB tests in GOV.UK frontend apps. The AB test is already live on Fastly (with 100% traffic to Z).
> Add AB test for search autocomplete

- app/assets/javascripts/dependencies.js
This is needed for the homepage search field autocomplete AB test.
> Add `search-with-autocomplete` JS dependency

- app/models/landing_page/block/statistics.rb
- spec/models/landing_page/block/statistics_spec.rb
The statistics block should fail gracefully if the csv data can't be found.
[Trello card](https://trello.com/c/7QtWoAXL)
The page was crashing if there was a typo in the `csv_file`, or if the file or attachment doesn't exist.
Shows a gap where the chart should be:
> Make statistics block fail gracefully

- app/assets/stylesheets/views/_landing_page/columns_layout.scss
- app/helpers/block_helper.rb
- app/models/landing_page/block/columns_layout.rb
- app/views/landing_page/blocks/_box.html.erb
- app/views/landing_page/blocks/_columns_layout.html.erb
- config/initializers/dartsass.rb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/homepage.yaml
- spec/helpers/block_helper_spec.rb
- spec/models/landing_page/block/columns_layout_spec.rb
Improved `columns_layout` block that uses CSS grid to create 2 or 3 columns. We now use a single container class for basic styling, with a `data-columns` attribute containing the user specified number of columns. This avoids the need for multiple class names. The old behaviour using design system rows/columns was removed. [Trello](https://trello.com/c/VGg9r3b6/151-create-missions-layout-blocks)
To support the new design for landing pages that use 2 or 3 column sections.
| Two columns | Three columns | Four columns |
| -------- | ------- | ------- |
| <img width="831" alt="image" …
> Landing page better columns

- app/controllers/content_items_controller.rb
- app/controllers/error_controller.rb
- app/controllers/landing_page_controller.rb
- lib/api_error_routing_constraint.rb
- lib/content_item_loader.rb
- lib/format_routing_constraint.rb
- spec/unit/api_error_routing_constraint_spec.rb
- spec/unit/content_item_loader_spec.rb
Re-add the cache that was removed in a previous fix. The original cache was too aggressive (it mistakenly relied on the ContentItemLoader being reloaded per request, but the threaded nature of the server in fact causes that not to happen, and the loader's cache was then preserved across requests causing instability). Reinstate it as an object-level cache, and attach that object to the request object (in its `.env` map) so that it's explicitly rebuilt for each request.
> Content item loader cache

- app/controllers/travel_advice_controller.rb
- spec/requests/travel_advice_spec.rb
Return a 404 if the requested part does not exist.
Fixes an error recorded in Sentry where the page was erroring as the current part title didn't exist.
https://govuk.sentry.io/issues/6088961126/?alert_rule_id=3654813&alert_type=issue&notification_uuid=70a47213-11d7-402f-a327-685adaa02e0f&project=202225&referrer=slack
> Return a 404 if the requested part does not exist

- app/controllers/travel_advice_controller.rb
- spec/requests/travel_advice_spec.rb
Rather than raising a 404 we should redirect people back to the country home page. This replicates the behaviour from government-frontend:
https://github.com/alphagov/government-frontend/blob/dfecd13f3c24edd0ba24eef87b0d7fc149031ab1/app/controllers/content_items_controller.rb#L177-L180
> Redirect travel advice to base path if part doesn't exist

- app/helpers/govuk_chat_promo_helper.rb
- app/views/shared/_base_page.html.erb
- spec/helpers/govuk_chat_promo_helper_spec.rb
- spec/requests/simple_smart_answers_spec.rb
- spec/requests/transactions_spec.rb
- spec/support/concerns/govuk_chat_promo.rb
We are setting up [GOV.UK](http://gov.uk/) Chat promo banners in the frontend application. This should follow a similar approach to that taken for [Government Frontend](https://github.com/alphagov/government-frontend/pull/3303) and [Collections](https://github.com/alphagov/collections/pull/3742) of adding a helper, modifying views, adding an env var to govuk-helm-charts and having appropriate tests.
This follows the pattern established in [Collections](https://github.com/alphagov/collections/pull/3742) and [Government Frontend](https://github.com/alphagov/government-frontend/pull/3303) …
> Render GOV.UK chat promotional banner on specific pages

- app/controllers/content_items_controller.rb
- spec/requests/content_loading_problems_spec.rb
- Controllers derived from ContentItemController which are on fixed routes (ie which aren't format-constraint-based routes) can be routed to directly, bypassing the error constraint. This means that the content item loader might return an error (for instance, a forbidden if a draft page is accessed), and we're currently not checking for one. This change adds a raise if the response for the loader is a standard error, and adds a test for it.
> Fix non-format-constraint routes error behaviour

- app/assets/stylesheets/views/_landing_page/helpers/_colours.scss
- app/helpers/theme_type_helper.rb
- app/views/landing_page/blocks/_hero.html.erb
- spec/helpers/theme_type_helper_spec.rb
- Fallback to a black border when `theme_colour` is not passed to a block, or the value passed is incorrect. 
- Also removes a hardcoded brand style in the `hero` blocks.
- Previously, the styles would default to one of the brand colours, which made it more difficult to see when the theme colour value was incorrect.
- https://trello.com/c/gf86I9Kh/175-elements-with-branding-shouldnt-have-a-default
> Fallback to a default brand colour on blocks

- app/views/landing_page/blocks/_statistics.html.erb
Expand the statistics block to allow it to use new options on the chart component, to set the format of axes to "date" to force correct axis labels on some of the data we're using. We're not using this option yet but we will shortly.
Also includes the `hide_legend` option, as legend may not be required on graphs with a single line.
None.
Trello card: https://trello.com/c/cqG0SoNT
> Allow statistics block to set further options

- app/assets/stylesheets/views/_landing_page/hero.scss
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
A fix to set a minimum height on the text box within a hero block. This is to prevent a gap between the textbox and the bottom of the image when there's too little content in the text box. This also contains an adjustment to the amount of overlap on tablet and desktop for better visual balance, and to reveal more of the hero image. [Trello](https://trello.com/c/elnXVZR1/174-hero-block-text-box-needs-height-adjustment)
The gap beneath the textbox is a visual bug and inconsistent with the proposed design.
| -------- | ------- |
| <img width="975" alt="image" …
> Fix hero block text box height

- app/models/landing_page/block/document_list.rb
- spec/models/landing_page/block/document_list_spec.rb
Allow the document-list to fail gracefully
The document-list was failing if nothing is tagged to the taxon and no items were explicitly configured. This is not the ideal behaviour, the document-list should just not render if no items are provided.
> Allow the document-list to fail gracefully

- app/views/landing_page/blocks/_lead_paragraph.html.erb
- lib/data/landing_page_content_items/homepage.yaml
Create a new block type to wrap the `lead-paragraph` gem component. [Trello](https://trello.com/c/ghZbq2mQ/178-create-a-lead-paragraph-block-type-for-hero-block-textbox)
To support the revised designs, text in the hero block at the top of the page needs to be bigger. This can be achieved with the `lead-paragraph` component from the gem, which needs to be wrapped within a block type.
> Add block to wrap the lead_paragraph component

- app/views/landing_page/blocks/_image.html.erb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/goals.yaml
- Adds the `theme_colour` option to the image blocks
- So we can put the border top colours on the images
> Add theme_colour option to image block

- app/models/landing_page/block/image.rb
- app/views/landing_page/blocks/_image.html.erb
- spec/models/landing_page/block/image_spec.rb
Otherwise the image size will just be the file size, which at small resolutions can push the content outside the edge of the viewport leading to a horizontal scrollbar.
We might want some other themes in future (e.g. two-thirds width images), but we haven't got a use case for those yet, and it feels like taking the whole width of the container is a good default.
(Note: draft while we're building on top of https://github.com/alphagov/frontend/pull/4474)
> Make image blocks width: 100% by default

- app/views/landing_page/blocks/_lead_paragraph.html.erb
- lib/data/landing_page_content_items/homepage.yaml
Remove the `lead_paragraph` block as it's now redundant.
We're exploring how to add larger text more generally which will be a different piece of work.
[Trello](https://trello.com/c/ghZbq2mQ/178-remove-lead-paragraph-block-type-for-hero-block-textbox-was-create)
> Remove lead_paragraph block

- app/helpers/govuk_chat_promo_helper.rb
We're adding the promotional banner to some more pages. This is the only one that is rendered on Frontend.
To drive more users to chat.
> Add additional URL for GOV.UK Chat

- app/views/landing_page/blocks/_heading.html.erb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/exercise_more.yaml
Update heading block to take optional parameter so headings can have an ID to link to.
[Trello card](https://trello.com/c/H9YR6ZCg)
The heading component already accepts an id parameter for this purpose.
The id has to be configured in the YAML so that they can be easily made to be unique.
https://govuk-frontend-app-pr-4487.herokuapp.com/landing-page/exercise-more#anchor-one
> Allow heading blocks to accept an id for an anchor link

- app/assets/stylesheets/views/_landing_page.scss
- app/helpers/block_helper.rb
- app/models/landing_page/block/two_column_layout.rb
- app/views/landing_page/blocks/_two_column_layout.html.erb
- docs/building_blocks_for_flexible_content.md
- spec/helpers/block_helper_spec.rb
- spec/models/landing_page/block/two_column_layout_spec.rb
Rework the two column block.
- remove option to have four columns
- rewrite logic to support a two_thirds_right variant, where we want a 2/3rds right hand column but nothing in the left hand column
Currently in order to achieve this layout we have to put an empty block into the left hand column, which is both messy and also creates a spacing issue on mobile, where an empty govspeak block causes extra space where we don't want it.
Screenshot of an example use including the markup. Note that the left hand grid column is empty and therefore won't occupy any vertical space on mobile - currently this would represent a …
> Rework two column block

- app/assets/stylesheets/views/_landing_page/hero.scss
- app/models/landing_page/block/hero.rb
- app/views/landing_page/blocks/_featured.html.erb
- app/views/landing_page/blocks/_heading.html.erb
- app/views/landing_page/blocks/_hero.html.erb
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
- spec/models/landing_page/block/hero_spec.rb
Updates the hero component so that in its default state, any child heading blocks will have large text.
It does this by passing params down to the heading component.
This removes the need for `position: top` on the hero block YAML, as we just use the fact that they have the default theme to infer they're at the top. That means we can replace the `position` param in headings with a `font_size` param, which is much clearer. The featured block may not need big headings, and we're not using it currently, so I'm just removing the option from that.
When Andy and I first worked on this, we discussed setting the heading …
> Big hero headings

- app/assets/stylesheets/views/_landing_page/hero.scss
- above 1200px, used to expand hero image to full width but retain a fixed height, so on very large screens the bottom of the image could be lost
- changing as per request to keep large desktop to behave as regular desktop i.e. fixed width, no further scaling, leave a gap left/right if screen is too wide
- have also increased the height of the hero on large desktop to help make it look a bit better and be a little wider
Before
After
> Modify large desktop hero image behaviour

- app/views/landing_page/blocks/_box.html.erb
- govuk_styled_link returns the unstyled text by default, so the guard here is unnecessary
> Remove unused || block

- app/assets/stylesheets/views/_landing_page/block-error.scss
- style from error-alert.css in publishing components
Adds padding and margin-bottom and beefs up the border a bit
> Add nicer styling for error boxes

- app/views/landing_page/show.html.erb
- spec/system/landing_page_spec.rb
https://trello.com/c/PP8jCxFB/210-meta-description-missing
> Add meta description to landing pages

- app/views/travel_advice/show.html.erb
Add meta description to travel advice pages
The machine readable metadata component only adds the `og` tag i.e. `<meta name="og:description" content="description">`
It doesn't add `<meta name="description" content="description"> to the Head.
Adds the meta tag directly to the show view for travel advice pages. It seems that all of content item pages are adding this tag in their templates rather having it appear once in the layout so travel advice is follows the same pattern for now.
> Add meta description to travel advice pages

- app/assets/javascripts/dependencies.js
This javascript is now provided by static [1] and is thus removed from this repo to ensure that we don't send the same asset to users multiple times unnecessarily.
It continues the convention of applications only adding the JS of components which are not provided by static [2].
[1]: https://github.com/alphagov/static/pull/3532
[2]: https://github.com/alphagov/frontend/pull/3281
> Remove require of search-with-autocomplete JS

- app/controllers/travel_advice_controller.rb
- spec/system/travel_advice_spec.rb
Show a breadcrumb on the travel advice index page.
Follows on from: https://github.com/alphagov/frontend/pull/4511
It's not clear if this was purposefully left off, or was overlooked because the travel advice controller didn't set the `@publication` variable, however it is odd that the travel advice index page doesn't have a breadcrumb. It is the only page in the travel advice flow that doesn't have a breadcrumb. The other comparable page is the list of departments, and that page does have a breadcrumb.
|Before|After|
|-------|-----|
|![Screenshot 2024-12-13 at 17 20 …
> Show a breadcrumb on the travel advice index page

- app/assets/stylesheets/views/_landing_page.scss
- app/assets/stylesheets/views/_landing_page/themes/prime-ministers-office-10-downing-street.scss
- app/models/landing_page.rb
- app/views/landing_page/show.html.erb
- app/views/landing_page/themes/_default.html.erb
- app/views/landing_page/themes/_prime-ministers-office-10-downing-street.html.erb
- config/initializers/dartsass.rb
- docs/building_blocks_for_flexible_content.md
- spec/models/landing_page_spec.rb
- spec/system/landing_page_spec.rb
Adds theme support to landing pages. 
Currently all landing pages have the Number 10 header. We don't want that on all landing pages, so we add a top-level `theme` element, which can be omitted or set to `default` to get a landing page without that header. The existing mission pages will have to be updated with the theme `prime-ministers-office-10-downing-street`, but since it's a top-level element we can do that once in the homepage and republish all, and the others will pick it up due to their `extends` values)
> Landing page themes

- app/controllers/simple_smart_answers_controller.rb
- app/models/simple_smart_answer.rb
- app/presenters/simple_smart_answer_presenter.rb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/simple_smart_answers/show.html.erb
- spec/models/simple_smart_answer_spec.rb
- spec/requests/simple_smart_answers_spec.rb
- spec/unit/presenters/simple_smart_answer_presenter_spec.rb
Move modelling code from SimpleSmartAnswerPresenter to a SimpleSmartAnswer model.
We currently have two ways to model content items and two content item presenters.
* ContentItem models the response from content store
* ContentItemModelPresenter takes a ContentItem object and adds a presentation layer to it.
* ContentItemPresenter does both, it models the response from content store and adds presentation to it.
Ideally there would be content item models that inherit from ContentItem and content item presenters that inherit from ContentItemModelPresenter.
And when the original ContentItemPresenter is finally …
> Add simple-smart-answer model

- config/initializers/govuk_publishing_components.rb
Adds `config/initializers/govuk_publishing_components.rb`
- according to https://github.com/alphagov/govuk_publishing_components/blob/main/docs/install-and-use.md#3-configure-the-gem this file should exist
- it didn't, which wasn't a disaster, but it meant the component guide didn't have the correct title
None, apart from the [component guide](https://govuk-frontend.herokuapp.com/component-guide) has the right title now:
> Configure components gem

- app/views/landing_page/blocks/_columns_layout.html.erb
- app/views/landing_page/blocks/_main_navigation.html.erb
- app/views/landing_page/themes/_prime-ministers-office-10-downing-street.html.erb
- lib/data/landing_page_content_items/homepage.yaml
- spec/fixtures/landing_page.yaml
- spec/models/landing_page_spec.rb
- spec/system/landing_page_spec.rb
- Adds GA4 tracking to some missions page blocks as this was missing in the initial release
- Adds the link tracker for the Menu, Boxes and Org logo links
- Adds the event tracker for the Menu button
- See the [implementation guide](https://docs.google.com/document/d/1LGLRb6zMvJBjzMYPgLAcBWbS-GsKGUzLcumCsZgiUhM/edit?tab=t.0#heading=h.gtmw0pgvmi0n) if you'd like to verify the JSON values.
- I had to create a new container block for the boxes to give me a nice way to track them. This is because they're rendered separately from each other in the code, and for the purposes of GA4 indexes I needed to capture all of them in one `<div>` so the indexes could be set. Therefore there's a new `box_container` block. (I didn't want to add the tracking on to the existing `columns_layout` `<div>` that …
> Add GA4 tracking to some missions page blocks

- app/views/landing_page/blocks/_heading.html.erb
- lib/data/landing_page_content_items/be_kinder.yaml
Allow heading blocks to receive font-sizes from block config data. [Trello](https://trello.com/c/7h3VaqOI/214-post-launch-design-change-ensure-h2-and-h3-elements-look-different-from-each-other)
Headings appearing in landing pages have mismatched sizes. The H2 and H3 for example all appear at 27px, which is not our normal standard. Heading blocks therefore needed to accept a `font_size` parameter.
A before and after screenshot showing `font_size` parameters of "m" and "s" applied to the H2 and H3.
> Allow heading blocks to receive font-sizes from data

- app/assets/stylesheets/views/_landing_page.scss
- app/views/landing_page/themes/_prime-ministers-office-10-downing-street.html.erb
Remove redundant CSS for the organisation logo on landing pages: this is now handled by a variant option in the gem component. [Trello](https://trello.com/c/TT6qZYWG/216-org-logo-component-has-app-level-styling)
On the new [Missions](https://www.gov.uk/missions) landing page served by the frontend app, the organisation logo in the header has the underline removed. This was achieved using some localised override CSS, which is against our principle of component isolation.
> Remove redundant CSS for organisation logo on landing page

- app/controllers/transaction_controller.rb
- app/models/transaction.rb
- app/presenters/transaction_presenter.rb
- app/views/transaction/_additional_information_single.html.erb
- app/views/transaction/_additional_information_tabbed.html.erb
- app/views/transaction/show.html.erb
- spec/models/transaction_spec.rb
- spec/requests/transactions_spec.rb
- spec/unit/presenters/transaction_presenter_spec.rb
Move modelling code from TransactionPresenter to a  Transaction model.
We currently have two ways to model content items and two content item presenters.
* ContentItem models the response from content store
* ContentItemModelPresenter takes a ContentItem object and adds a presentation layer to it.
* ContentItemPresenter does both, it models the response from content store and adds presentation to it.
Ideally there would be content item models that inherit from ContentItem and content item presenters that inherit from ContentItemModelPresenter.
And when the original ContentItemPresenter is finally removed, to …
> Add transaction model

- app/assets/stylesheets/views/_landing_page/box.scss
Remove the extra mobile spacing beneath the six missions boxes on the Plan for Change homepage. [Trello](https://trello.com/c/9bj0hyd4/211-post-launch-design-change-remove-vertical-gap-from-homepage-boxes-on-mobile)
The `box` blocks used for these elements have their own bottom margin on mobile, but are contained within a grid with its own grid gap. This means the amount of space is doubled and must be reduced.
| -------- | ------- |
| ![image](https://github.com/user-attachments/assets/4daf8454-95d2-484c-8432-274a992b6bb4) | ![image](https://github.com/user-attachments/assets/83dd898a-ef29-4bfc …
> Remove mobile spacing on box blocks

- lib/tasks/consolidation.rake
- #dig returns nil if a tree couldn't be found or if a tree was found but the value of it is nil, which is fine normally but we do want to know the difference, so add the key_tree_exists? method to handle that case.
> Fix handling of individual empty keys

- app/assets/stylesheets/views/_landing_page/image.scss
- app/views/landing_page/blocks/_image.html.erb
- config/initializers/dartsass.rb
- lib/data/landing_page_content_items/be_kinder.yaml
Replace the `govuk-frontend` override classes with styles scoped to the image block. [Trello](https://trello.com/c/FZ5GjGAm/220-add-margin-styling-for-image-block)
The `govuk-frontend` spacing override classes should only be used in situations where styling cannot be applied directly, and instead must be overridden. This is not one of those situations.
No visual changes.
> Add block level styles for images and remove govuk overrides

- spec/models/content_item_spec.rb
- spec/models/travel_advice_spec.rb
Move where the withdrawn shared example is called
It's a bit odd to have a shared example that's called on the generic content item model, but that's using an example for a specific document type.
Not all of the schema examples will contain a `withdrawn_notice` so it's not appropriate to use a random example. Therefore the shared example is being called from model tests for the example being used.
> Move where the withdrawn shared example is called

- lib/data/bank-holidays.json
The Summer Bank Holiday 2027 for Scotland appears to be incorrect?  It should be the first Monday in August, not the last.  The date for 2026 is correct.  See https://www.legislation.gov.uk/ukpga/1971/80/schedule/1
A member of the public discovered this issue and contributed this PR to fix it. Thank you very much @ian123net.
> Correct date for Summer Bank Holiday 2027 for Scotland

- app/controllers/licence_transaction_controller.rb
- app/models/content_item_factory.rb
- app/models/licence_transaction.rb
- app/views/licence_transaction/_authority_base.html.erb
- app/views/licence_transaction/_licensify_unavailable.html.erb
- app/views/licence_transaction/authority.html.erb
- app/views/licence_transaction/authority_interaction.html.erb
- app/views/licence_transaction/continues_on.html.erb
- app/views/licence_transaction/licence_not_found.html.erb
- app/views/licence_transaction/multiple_authorities.html.erb
- app/views/licence_transaction/start.html.erb
- spec/models/content_item_factory_spec.rb
- spec/models/licence_transaction_spec.rb
Move modelling code from LicenceTransactionPresenter to a  LicenceTransaction model.
We currently have two ways to model content items and two content item presenters.
* ContentItem models the response from content store
* ContentItemModelPresenter takes a ContentItem object and adds a presentation layer to it.
* ContentItemPresenter does both, it models the response from content store and adds presentation to it.
Ideally there would be content item models that inherit from ContentItem and content item presenters that inherit from ContentItemModelPresenter.
And when the original ContentItemPresenter is finally …
> Add licence transaction model

- spec/helpers/application_helper_spec.rb
Remove pipe test for page_title from Application Helper
The `page_title` hasn't run the risk of containing unnecessary pipes in 12 years:
https://github.com/alphagov/frontend/commit/ed0a43069ffaa0064282f31f981f59fb93042487
N/A - No visual changes
> Remove pipe test for page_title from Application Helper

- app/views/shared/_base_page.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
Replace hard coded heading contexts with the new context option on the heading component.  Applies to these two types of page:
- https://www.gov.uk/sold-bought-vehicle/y/no/sold-it/sold-it-privately-to-a-person-or-business
- https://www.gov.uk/find-licences/premises-licence
Follows on from work done in https://github.com/alphagov/frontend/pull/4550
None.
> Use heading context option

- app/controllers/place_controller.rb
- app/models/place.rb
- app/presenters/place_presenter.rb
- app/views/place/_place.html.erb
- app/views/place/multiple_authorities.html.erb
- app/views/place/show.html.erb
- spec/models/place_spec.rb
- spec/unit/presenters/place_presenter_spec.rb
Move modelling code from PlacePresenter to Place model
We currently have two ways to model content items and two content item presenters.
- ContentItem models the response from content store
- ContentItemModelPresenter takes a ContentItem object and adds a presentation layer to it.
- ContentItemPresenter does both, it models the response from content store and adds presentation to it.
Ideally there would be content item models that inherit from ContentItem and content item presenters that inherit from ContentItemModelPresenter.
And when the original ContentItemPresenter is finally removed, to rename …
> Add place model

- README.md
- app/controllers/calendar_controller.rb
- app/models/calendar.rb
- app/presenters/faq_presenter.rb
- docs/calendars.md
- spec/unit/presenters/faq_presenter_spec.rb
Replace all references to scope in calendars with type, and remove scope validation.
Scope is just calendar type, there's no need for an additional term for it. And the scope validation in the controller is never going to catch anything (the validation has already happened as a part of loading the content item).
> Tidy calendar

- app/views/landing_page/blocks/_document_list.html.erb
- Adds the GA4 section attribute to the Plan for Change document lists, e.g. the "Latest updates" section on https://www.gov.uk/missions/strong-foundations
- [Trello card](https://trello.com/c/V3oB4hvS/862-add-section-to-document-list-on-missions-pages)
> Add GA4 section to plan for change document list

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_place-list.scss
- app/assets/stylesheets/views/_roadmap.scss
- app/views/calendar/bank_holidays.html.erb
- app/views/roadmap/index.html.erb
- config/initializers/dartsass.rb
- spec/system/bank_holidays_spec.rb
Tidy up application.scss by moving styles that are only used by specific views into view-specific stylesheets.
Random styles in application.scss are harder to maintain (if a view is removed, it's not always obvious that you have to remove a system-wide style), and lead to a bigger download on unrelated pages.
> Tidy styles

- spec/support/meta_tags.rb
- spec/system/case_study_spec.rb
- spec/system/get_involved_spec.rb
- spec/system/help_page_spec.rb
- spec/system/take_part_spec.rb
Pass in example name to meta tags shared examples
Not all content schema examples have an example that matches the document type. Rather the shared examples should take the example name as a parameter and then use that to calculate the path value.
N/A
> Pass in example name to meta tags shared examples

- app/assets/stylesheets/components/_back-to-top.scss
- app/views/components/_back_to_top.html.erb
- app/views/components/docs/back_to_top.yml
- config/initializers/dartsass.rb
- spec/components/back_to_top_spec.rb
Copies back-to-top component from government-frontend
This component is used by both [specialist documents](https://github.com/alphagov/frontend/pull/4600) and [corporate information pages](https://github.com/alphagov/frontend/pull/4608) which are in the middle of being consolidated
> Add back to top component

- app/models/concerns/updatable.rb
- app/views/case_study/show.html.erb
Make `initial_publication_date` method public
This method will be required by the specialist documents view and it removes the duplicated logic from the view.
> Make initial_publication_date method public

- spec/support/concerns/updatable.rb
Sort expected results in Updatable history test
The change history is sorted into reverse chronological order, therefore if there is more than one item in the change history, the order the change history appears in the content store response will not match the order in the content item, causing the `eq` expectation to fail. The only options were to either only check the number of history items matched and that the first and last expected element appear in the change history  or to replicate the code in the
`reverse_chronological_change_history` method (the option chosen).
N/A
> Sort expected results in Updatable history test

- app/helpers/link_helper.rb
- spec/helpers/link_helper_spec.rb
> Add inverse flag to govuk_styled_links_list helper

- app/helpers/link_helper.rb
- app/models/case_study.rb
- app/models/content_item.rb
- app/presenters/content_item_presenter.rb
- app/presenters/specialist_document_presenter.rb
- app/views/case_study/show.html.erb
- app/views/specialist_document/show.html.erb
- spec/helpers/link_helper_spec.rb
- spec/models/case_study_spec.rb
- spec/models/content_item_spec.rb
Update `ContentItem#contributors` so that it returns a list of contributor content item objects rather than an array of hashed link values.
The hashes are presentational (they're to be passed into the govuk_styled_links_list helper method), so better that they're in presenter code. This lets us simplify how things are passed around a little, and is extensible to allow individual presenters to handle unorthodox additions to contributor lists (eg speaker_without_profile in speech items)
> Update contributors handling

- docs/calendars.md
- this was missed when the last set of calendar rendering changes were made.
> Update documentation around calendars

- app/models/specialist_document.rb
- app/presenters/specialist_document_presenter.rb
- spec/models/specialist_document_spec.rb
- spec/presenter/specialist_document_presenter_spec.rb
- spec/system/specialist_document_spec.rb
There's a case where a facet could have an array of allowed values but
not be filterable, so a link to a finder shouldn't be rendered.
This was not being picked up so rather than rendering:
```
Reason for protection: Application to UK scheme from 2021
```
A hash was rendered instead:
```
Reason for protection:
{:label=>"Application to UK scheme from 2021", :value=>"uk-gi-after-2021"}
```
This case was missed when the specialist documents were moved over.
A new type is added to account for this case "preset_text". This is
"text" that the publisher selected from a redefined set of options, but
is not filterable so …
> Render non filterable text facets in a list

- docs/local-content-items.md
Update the documentation for local content items, including fixing an unclear path and adding an example data file.
Documentation improvement.
> Update local content items documentation

- app/queries/graphql/edition_query.rb
- lib/content_item_loader.rb
- spec/unit/api_error_routing_constraint_spec.rb
- spec/unit/content_item_loader_spec.rb
- spec/unit/full_path_format_routing_constraint_spec.rb
Adds the ability for content items to be loaded from the GraphQL endpoint on publishing-api. For news_articles only, frontend will default to loading from the content store as usual unless the param `graphql=true` is appended to the path. If the env var `GRAPHQL_FEATURE_FLAG=true`, if will default to loading from GraphQL unless the param `graphql=false` is appended to the path. 
The publishing platform team are testing GraphQL as an option for querying content at the moment (as per [RFC-172](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-172-graphql-for-govuk.md)). The only schema they currently support is …
> (Re-)Enable GraphQL Trial support for news_article documents

- spec/system/service_toolkit_spec.rb
- Remove `puts` from a `service_toolkit` test
- Was left in by accident after a test failed after rebasing the service toolkit migration PR before merging
> Remove puts statement from test

- app/controllers/specialist_document_controller.rb
- app/models/specialist_document.rb
- app/presenters/specialist_document_presenter.rb
- spec/models/specialist_document_spec.rb
- spec/presenter/specialist_document_presenter_spec.rb
- spec/system/specialist_document_spec.rb
Recommend commit by commit review
Nested facets are being added to Specialist Publisher. This new facet type consists of a main-facet and a nested sub-facet for some or all of its allowed values. Both the main-facet and sub-facet need to be surfaced to the end user, and the sub-facet requires the metadata to be rendered differently. Mainly that it has an associated main-facet. When the label is rendered, the sub-facet needs to be prefixed with the main-facet, and the link generated to the finder should contain both sub-facet and related main-facet filters.
As an example, here is an excerpt from a specialist …
> Adding nested facets for specialist document

- lib/content_item_loader.rb
- spec/unit/content_item_loader_spec.rb
The content item returned from Publishing API's GraphQL endpoint has a `schema_name` field which is what we should check against our list of GraphQL-allowed schemas.
The list of fields that the `Graphql::EditionQuery` requests confirms the naming.
(In case the consequences aren't obvious, `graphql_response["schema"]` will always be `nil` which will always result in an additional request for the content item from Content Store regardless of the response from Publishing API's GraphQL endpoint.)
> Use content item's `schema_name`, not `schema`

- app/controllers/specialist_document_controller.rb
- app/models/contents_outline.rb
- app/models/specialist_document.rb
- app/presenters/contents_outline_presenter.rb
- app/presenters/specialist_document_presenter.rb
- app/views/specialist_document/show.html.erb
- spec/models/contents_outline_spec.rb
- spec/models/specialist_document_spec.rb
- spec/presenter/contents_outline_presenter_spec.rb
- spec/presenter/specialist_document_presenter_spec.rb
Add a ContentsOutline model and a presenter that will convert it into a format useful for the ContenstList component.
Specialist Documents, Corporate information pages, and the upcoming Flexible Page trial all have a concept of a list of links within the page generated from the content in some way (currently Specialist Documents have a nested list of headers passed to it, CI pages have to extract it directly from the content body , and Flexible Pages will define it in Flexible Section). This adds a model and presenter for the concept to simplify working with them.
https://trello.com/c/H2TSoDLE/
> Contents outline

- app/views/calendar/bank_holidays.html.erb
Fix bunting alignment and spacing
When the show_bunting flag is true, the `govuk-!-padding-top-0` class is added to the `main` element to ensure the spacing between the breadcrumbs and bunting is correct
The `govuk-!-padding-bottom-8` class is used to ensure the spacing between the between the bunting and heading is correct.
| --- | --- |
| <img width="373" alt="Screenshot 2025-04-11 at 11 37 37" src="https://github.com/user-attachments/assets/7cea29f9-31e4-410e-9ad7-97bb40d59ea8" /> | <img width="373" alt="Screenshot 2025-04-11 at 11 34 57" src="https://github.com/user-attachments/assets/3af9d190-7a07-4d2f-89a8-ec61d3136d27" /> |
| --- | --- |
| <img width="988" alt="Screenshot 2025-04-11 at 11 37 55" …
> Fix bunting alignment and spacing

- app/queries/graphql/edition_query.rb
This isn't syntactically meaningful, but it helps a human parse it
> Fix GraphQL query indentation

- app/models/finder.rb
- app/presenters/specialist_document_presenter.rb
- spec/models/finder_spec.rb
- spec/presenter/specialist_document_presenter_spec.rb
- spec/system/specialist_document_spec.rb
This change will make rendering the table of contents component in specialist documents dependent on a value defined in the schema of each finder. We [recently implemented a similar feature for the metadata block ](https://github.com/alphagov/frontend/pull/4735). 
Tests in this PR depend on example schemas from the Publishing API repository, which may cause CI failures until the related changes are merged.
New HRMC document:
> ![Screenshot 2025-04-25 at 13 07 36](https://github.com/user-attachments/assets/e7dbe32e-b9b0-4be6-a91f-62eb211d2cd3)
Preexisting document type (CMA case):
- **all documents will require a republish to set the field to true as default**
> ![Screenshot 2025-04-25 at 13 12 45](https://github.com/user-attachments/assets/2bb0e63a-ebce-483c-aa1a-2e960f73e90d) …
> Add conditional check for contents list

- app/queries/graphql/edition_query.rb
This field is [required to render](https://github.com/alphagov/govuk_publishing_components/blob/64c9843849d0c48b654f4d6fd06ab3b4d5db0d1e/lib/govuk_publishing_components/presenters/machine_readable/creative_work_schema.rb#L87-L98) the creative work schema on news articles, when the data is retrieved from GraphQL.
As with my previous similar PRs (https://github.com/alphagov/frontend/pull/4824 and https://github.com/alphagov/frontend/pull/4829), I haven't added any tests, as there's nothing to test directly here, since it's just a hardcoded string.
[Trello card](https://trello.com/b/NHxZVLsg)
> Add `web_url` for GraphQL `document_collections` links

- app/controllers/content_items_controller.rb
- app/views/shared/_published_dates_with_notification_button.html.erb
- app/views/shared/_single_page_notification_button.html.erb
- spec/views/shared/_published_dates_with_notification_button.html.erb_spec.rb
Simplify the partials that render a single page notification button component.
In the original partials copied from government-frontend, we used various different ways to determine if a one-login or non-one-login link should be the action of the button, and whether or not the js_enhancement flag should be set., including local_assigns and class-level variables passed into the partials. In fact, in government-frontend none of the views that use these partials actually require customisation, so it's possible to just check the logged in status and set js_enhancement to match it, and skip_account to an inverted …
> Simplify single page notification button calls in partials

- app/models/service_manual_service_toolkit.rb
- app/models/specialist_document.rb
Update initialize methods to use .`dig`.
Using the `dig` method allows `nil` values to be handled gracefully (originally reported via https://govuk.sentry.io/issues/6736267026/?project=202225&query=is%3Aunresolved&referrer=issue-stream&stream_index=0)
> Update initialize methods

- config/locales/en.yml
- config/locales/zh-hk.yml
- config/locales/zh-tw.yml
- config/locales/zh.yml
- the previous translations for these values were confused, and didn't really reflect a useful differentiation. Cantonese is really the spoken language, and the written version of it is Traditional Chinese, but it differs slightly from the written form used in Taiwan. The mapping we want is:
-  zh = 简体中文 
- zh-hk = 繁體中文（香港）
- zh-tw = 繁體中文（臺灣,
which is equivalent to:
- Simplified Chinese 
- Traditional Chinese (Hong Kong) 
- Traditional Chinese (Taiwan)
See also: https://github.com/alphagov/government-frontend/pull/3767
> fix: improve language names for chinese languages

- config/locales/zh-hk.yml
- config/locales/zh-tw.yml
> fix: use correct closing bracket on chinese language names

- app/models/detailed_guide.rb
- app/presenters/detailed_guide_presenter.rb
- app/views/detailed_guide/show.html.erb
- app/views/shared/_publisher_metadata.html.erb
- spec/models/detailed_guide_spec.rb
- spec/presenter/detailed_guide_presenter_spec.rb
Refactor to make logo a presenter model, and to have it as a local passed into the publisher_metadata partial. This will be useful when adding logos in the publication migration.
> Small refactoring of detailed_guide logo support

- app/assets/stylesheets/views/_cookie-settings.scss
- app/views/help/cookie_settings.html.erb
On https://www.gov.uk/help/cookies
- adds margin bottom to the success alert component to provide spacing between it and the page H1 when user has changed cookie settings
- remove unnecessary CSS
Before | After
------ | -----
> Fix spacing around cookie changes confirmation

- app/views/service_manual/service_standard.html.erb
Remove additional "govuk-width-container" from service standard template
The `govuk-width-container` class is already included on the page wrapper, the additional width container was adding extra unwanted spacing at mobile and tablet screen sizes
Jira: https://gov-uk.atlassian.net/browse/NAV-1223
Preview link: https://govuk-frontend-app-pr-4994.herokuapp.com/service-manual/service-standard
| --- | --- |
| <img width="714" height="958" alt="service-standard-before" src="https://github.com/user-attachments/assets/16a369a0-9425-407e-9b46-862d07bc672f" /> | <img width="713" height="957" alt="service-standard-after" src="https://github.com/user-attachments/assets/af55c833-186c-4900-8325-803edf163968" /> |
> [!TIP]
> I would recommend applying "Hide whitespace" when looking …
> Remove additional "govuk-width-container" from service standard template

- Gemfile.lock
- app/assets/stylesheets/views/_homepage.scss
Upgrade to the latest version of `govuk_publishing_components` and fix the associated breaking change. This was causing a sass compilation error for the homepage.
Changes made in https://github.com/alphagov/govuk_publishing_components/pull/4969 have caused this breaking change.
> Bump components gem

- app/views/csv_preview/show.html.erb
Restore spacing between top of inverse header and header on CSV preview pages e.g. https://www.gov.uk/csv-preview/68c7f2238dd3590c7dd7ae60/dvsa-earned-recognition-vehicle-operators-accredited-list.csv
- title component was replaced with heading component a while back, and title used to have default top margin
- thought we'd fixed all the instances where spacing was needed above headings with alternative methods, but apparently missed this one
- spacing at the top of the blue box on CSV previews is provided by the padding_top option on the inverse header component
Reported in …
> Add padding to the top of csv preview box

- app/assets/stylesheets/views/_travel-advice.scss
Ensure the correct selector is used on travel advice pages, updated from `.travel-advice` to `.travel_advice`.
Fix travel_advice page styles, noticed the issue when working on https://github.com/alphagov/frontend/pull/5030
Preview link: https://govuk-frontend-app-pr-5031.herokuapp.com/foreign-travel-advice/afghanistan
| --- | --- |
| <img width="426" height="930" alt="mobile-before" src="https://github.com/user-attachments/assets/90fddc61-9588-4010-bda9-51fd03132b39" /> | <img width="422" height="931" alt="mobile-after" src="https://github.com/user-attachments/assets/de0af990-4449-429c-9a05-162ee7e0931d" /> |
> Fix `travel_advice` page styles
