app/presenters/publication_presenter.rb, app/views/root/transaction.html.erb, test/fixtures/register-to-vote.json, test/integration/transaction_rendering_test.rb
www.agileplannerapp.com/boards/173808/cards/8805
As a content designer
I want a better way to indicate on start pages when a service is down for planned maintenance
So that I don't have to re-edition multiple pages and push these through workflow, then repeat the process again once the downtime is over
related:
https://github.com/alphagov/govuk_content_models/pull/277
https://github.com/alphagov/publisher/pull/340
https://github.com/alphagov/govuk_content_api/pull/209
=> Display a callout for downtime message

app/assets/javascripts/jquery.localscroll-1.2.7-min.js
There was an attempt to remove this when the feature was removed ff50102
however due to a merge conflict it got left behind 882a5fb. It isn't
used so we can get rid of it.
=> Remove unused jQuery localscroll plugin

app/controllers/search_controller.rb, app/models/search_parameters.rb, app/presenters/search_result.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_list.mustache, test/functional/search_controller_test.rb, test/unit/presenters/government_result_test.rb, test/unit/presenters/search_result_test.rb, test/unit/presenters/search_results_presenter_test.rb
Parameters for search requests were being parsed in bits of code spread
across presenters and the search controller.  Instead, gather this
parsing together into a single SearchParameters class.
This makes further search improvements much easier (I have some patches
which depend on this tidyup).
Some notes to help with reading the diff:
- `SearchResultsPresenter.search_parameters` moves to
`SearchParameters.combine_parameters` as a private method.  It was
only being used for building links to other search pages, and has
some special case rules which only really make sense in that context.
- The presenter used to produce a parameter called "debug" for the view
to use to control whether to display score debugging information with
the search results.  This is quite distinct from the "debug" …
=> Separate out search parameter parsing

app/views/search/no_search_term.html.erb
The classes were to add some styling to previous design elements which
have been removed from this page.
Tidy the content_for tags up so they are clearer and together.
=> Remove unused classes and tidy content_for

app/assets/javascripts/live-search.js, app/models/search_parameters.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_block.mustache, test/functional/search_controller_test.rb, test/javascripts/unit/live-search-test.js, test/unit/presenters/search_results_presenter_test.rb
This is a "hidden" feature for now.  If `filter_topic[]=foo` is added to
the search query parameters, a second filter box is shown in the search
results, and the results are filtered to show only those matching the
requested topics.
The internal field name used for these is "specialist_sectors", but we
don't want to expose that name since it's misleading, and we're moving
to call these "topics" everywhere.  The search index will probably be
moved to the new field name when we rebuild it to listen to the
messaging queue.
There are a few rough edges, which I don't think need to block this
being deployed:
- If filters are selected in one of the filter boxes, the options shown
for the other field (in the other filter box) should update.
- If all filters are removed from the "topics' filter …
=> Enable search filtering by topic

app/presenters/search_results_presenter.rb, app/views/search/_form.html.erb, app/views/search/index.html.erb, test/functional/search_controller_test.rb
When a user clicks on one of our spelling suggestions, we were dropping
any filters which were active on the search.  This is generally
unhelpful, but particularly problematic if the search had filters
automatically added (for example, due to searching from one of the
organisations for which scoped search is automatically enabled).
Instead, we now preserve the filters.
Also, record the original query that was manually entered in the "o"
query parameter.  This matches the parameter used (at least
historically) by other search engines such as Google for this purpose.
This parameter is ignored by frontend, but we can use it in analytics to
track how often the suggestions are being used (and which result is
eventually clicked on when it is used).
=> Preserve active filters with spelling suggestions

app/assets/stylesheets/views/_search.scss, app/models/search_parameters.rb, app/presenters/search_result.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_list.mustache, test/unit/presenters/search_result_test.rb
This is the frontend half of some work to group search results by facets
such as topics, mainstream browse pages, or organisations.  It will have
no visible effect without corresponding changes in rummager, so is safe
to merge and deploy before the rummager changes are made.
After this change, Rummager can suggest groupings of search results in
the search responses.  These are represented by a result document with
an extra member, "examples", containing a list of example items in the
group.
Rummager may also suggest a filter along with a search result, which
will be converted to a link to apply that filter.  This allows users to
see everything in a group matching a search.
I'd like to get this merged so that I can experiment with the support in
rummager (under the control of a feature …
=> Show groups in search results

app/models/search_parameters.rb, app/presenters/non_edition_result.rb, app/presenters/search_results_presenter.rb, test/functional/search_controller_test.rb, test/unit/presenters/non_edition_result_test.rb
Previously there were two classes of search results: results from the mainstream index, typically things like guides and smart answers which have browse sections as metadata, and results from the government index which have date, organisation and format as metadata.
We're slowly moving towards a model where everything is added to the mainstream index, and the new existing metadata approach doesn't work for these new content items. These new results are being added with a specific `document_type`, instead of having everything lumped together as an `edition`.
This commit adds a third type of search result presenter which is used for any results that are in the mainstream index and have a type other than `edition`. It shows a date, a humanized version of the document format, and the …
=> Add metadata to non-edition search results

app/models/search_parameters.rb, test/unit/presenters/search_result_test.rb, test/unit/presenters/search_results_presenter_test.rb
When we generate links to search results, if the calculated start value
is 0 don't add a start parameter (since this is the default anyway).
This makes URLs nicer, but also helps caching.  For example, if someone
paginates to page 2, then the link to page 1 would go to a cached page.
I've checked with Tara, and this won't make any analytics significantly
more awkward.
=> Avoid linking to search parameters with start=0

app/presenters/publication_presenter.rb, app/views/root/transaction.html.erb, test/fixtures/register-to-vote.json
www.agileplannerapp.com/boards/173808/cards/8806
the artefact has an associated downtime object in the JSON representation that indicates when a transaction will be unavailable. the artefact downtime details are now moved under the details hash in the artefact JSON.
=> Read downtime from the artefact details

app/presenters/group_result.rb, app/presenters/search_results_presenter.rb, test/unit/presenters/search_results_presenter_test.rb
For groups of results returned from Rummager (not yet in production),
the format is "group", but we don't want to show this as part of the
result.  Add a class for GroupResults (it currently has nothing that
SearchResult doesn't have, but it's useful to mark it as different,
since it has a very different look), and use this class instead of the
NonEditionResult for group results.
Before:
After:
=> Don't add metadata to group results

app/assets/stylesheets/views/_campaigns.scss, app/assets/stylesheets/views/_check-vehicle-tax.scss, app/assets/stylesheets/views/_homepage.scss, app/assets/stylesheets/views/_make-a-sorn.scss, app/assets/stylesheets/views/_search.scss, app/assets/stylesheets/views/_tour.scss, app/assets/stylesheets/views/_travel-advice.scss, app/assets/stylesheets/views/_vehicle-tax.scss, app/controllers/root_controller.rb, app/controllers/search_controller.rb, app/controllers/travel_advice_controller.rb, app/views/layouts/application.html.erb, app/views/root/tour.html.erb
Now that by default the main element takes up 2/3rds of the page and the
related links take up 1/3rd there is extra padding which isn't needed on
a collection of elements. Remove this extra padding so the pages don't
change.
This is the change needed to go with https://github.com/alphagov/static/pull/530
=> Update to work with slimmer wrapper layout

Gemfile, Gemfile.lock, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/helpers/_beta-label.scss, app/controllers/application_controller.rb, app/views/help/index.html.erb, app/views/root/_beta_label.erb, app/views/root/_publication_metadata.html.erb, app/views/root/check-vehicle-tax.html.erb, app/views/root/make-a-sorn.html.erb, app/views/root/vehicle-tax.html.erb, app/views/root/view-driving-licence.html.erb, app/views/search/index.html.erb, app/views/simple_smart_answers/_outcome.html.erb, app/views/travel_advice/country.html.erb, app/views/travel_advice/index.html.erb, test/integration/answer_rendering_test.rb, test/integration/campaign_page_test.rb, test/integration/guide_rendering_test.rb, test/integration/help_pages_test.rb, test/integration/licence_lookup_test.rb, test/integration/local_transactions_test.rb, test/integration/page_rendering_test.rb, test/integration/places_test.rb, test/integration/programme_rendering_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_rendering_test.rb, test/integration/travel_advice_test.rb, test/test_helper.rb
Use the component for all the beta labels. This means we can remove the
bespoke styling for the old beta label.
=> Use component for beta-label

app/controllers/root_controller.rb, config/routes.rb, lib/tasks/router.rake, test/functional/root_controller_test.rb
- Based on https://github.com/issyl0/govuk-random-page - if Wikipedia
can have a random page link, why can't we? It will allow people to
find out about stuff that they may never normally find out about.
- I was going to add a link to the footer for ease of repeatedly
finding random pages, but that might be too prominent.
:fire:
=> Add a `/random` route that redirects to a random page on GOV.UK

app/presenters/non_edition_result.rb
We were showing "Hmrc manual" and "Hmrc manual section".
=> Tweak the "metadata" presentation for HMRC manuals

app/controllers/application_controller.rb, app/controllers/root_controller.rb, config/initializers/content_security_policy.rb, test/functional/root_controller_test.rb
**This pull request is open for feedback only, not to be merged (yet).**
Add `Content-Security-Policy-Report-Only` to the homepage in development only.
Whitelist:
- static and assets hostnames for loading anything
- Google Analytics for loading JavaScript
- Inline JavaScript and styles (we have a lot of existing inline JavaScript and inline styles loaded with jQuery)
- Reporting to the event-store app
There is still one report firing for me that I haven't been able to get rid of:
> Refused to load plugin data from ''
This is related to the accessible video player, which tests Flash on every pageload in JavaScript. I don't think there's a way to allow this behaviour.
=> Add a Content-Security-Policy reporting header

app/views/root/_base_page.html.erb, app/views/root/answer.html.erb, app/views/root/business_support.html.erb, app/views/root/completed_transaction.html.erb, app/views/root/guide.html.erb, app/views/root/help_page.html.erb, app/views/root/jobsearch.html.erb, app/views/root/legacy_completed_transaction.html.erb, app/views/root/licence.html.erb, app/views/root/local_transaction.html.erb, app/views/root/place.html.erb, app/views/root/programme.html.erb, app/views/root/simple_smart_answer.html.erb, app/views/root/transaction.html.erb, app/views/root/video.html.erb
Lots of the templates use the same base template. Merge them into a
single base page which everything can then extend from. This would make
updating global page layouts much easier.
This will let us iterate aspects of all pages in one go. Like using a component
for all the titles.
=> Merge all the common template parts into a base

app/controllers/root_controller.rb
- Following on from the 130 requests in 5 minutes it got at its peak
tonight, Brad suggested we add a small cache to discourage bots. Five
seconds is small enough not to affect users being shown a different
page every time.
=> Cache /random for 5 seconds instead of 0 seconds

app/assets/stylesheets/views/_help.scss
Now that we are using standardised grid mixins to manage the layout on
these pages we don't need this extra Sass to define some padding. This
makes the page indented like the rest of the site.
=> Remove extra padding on help page content

jenkins.sh, lib/tasks/test.rake
This means that jenkins runs the same command that's mentioned in the
README, and is the idiomatic way to run the test suite for a ruby app.
Also remove overrides from the buildin test task.
=> Update jenkins.sh to use default rake task.

app/assets/stylesheets/views/_campaigns.scss, app/assets/stylesheets/views/_completed-transaction.scss, app/views/campaign/uk_welcomes.erb, app/views/licences/_authority.html.erb, app/views/licences/_continues_on.html.erb, app/views/licences/_introduction.html.erb, app/views/root/_base_page.html.erb, app/views/root/business_support.html.erb, app/views/root/campaign.html.erb, app/views/root/guide.print.erb, app/views/root/index.html.erb, app/views/root/programme.print.erb, app/views/root/tour.html.erb, app/views/simple_smart_answers/_outcome.html.erb, app/views/travel_advice/country.html.erb, app/views/travel_advice/country.print.erb, test/integration/answer_rendering_test.rb, test/integration/campaign_page_test.rb, test/integration/guide_rendering_test.rb, test/integration/help_pages_test.rb, test/integration/programme_rendering_test.rb, test/integration/travel_advice_test.rb
Use article tags in a more semantic manor. There are two parts to this.
In the first instance I have removed a whole collection of questionable
article tags. The category for questionable was do they contain a
heading. The second was add a `content-block` to any article tags which
I couldn't make an easy decision on. Adding this class will enable us to
keep the styling when we remove the article tag from the CSS selector.
This is reliant on this pull request being merged and deployed first: https://github.com/alphagov/static/pull/540
=> Remove article tags and reliance on them

app/controllers/root_controller.rb, test/integration/places_test.rb
- Following a request from Liz Lutgendorff over the firebreak, and a
story in the Core team's backlog.
=> Increase the displayed number of Imminence results from 5 to 10

app/controllers/root_controller.rb, test/functional/root_controller_test.rb
- Rummager is faster than the Content API and is better designed for
this purpose of loading non-cached pages in quick succession.
=> Use the Rummager API instead of the Content API for /random

app/controllers/root_controller.rb, test/functional/root_controller_test.rb
By default `expires_in` will generate a `Cache-Control` header with the
`private` instruction, which allows the client to cache the response but not
any intermediate proxies such as our Varnish nodes or CDN:
- http://apidock.com/rails/ActionController/ConditionalGet/expires_in
- https://github.com/alphagov/cdn-acceptance-tests/blob/e4ee66728c99cedb8b510c7736df35b4ee5b6bd4/cdn_nocache_test.go#L71-L81
This means that we would probably see the same amount of traffic at and
within origin, especially from bots. Change the instruction to `public`
which will allow the response to be cached by those layers and soak up any
brief increases in traffic.
I've moved the comment about why we're doing this, minus the specific value,
to an additional test which asserts this behaviour is happening. This …
=> Change /random cache from private to public

app/assets/stylesheets/views/_campaigns.scss, app/views/root/campaign.html.erb, test/integration/campaign_page_test.rb
• Remove breadcrumb - only ever has home link in it
• update banner to not use 3 background images and only use large banner image in markup
• move banner image to top as this is simply that a branding, banner image
• make banner inline and responsive, no image cropping, therefore no loss of content
• Center h1 and increase font size to make heading more prominent
• Increase width of content to max width of 75% and center. Makes better use of space and layout.
• For desktop right align org logo (when present) to flow within the content. This fits in with the 'F' pattern reading structure of content promoted by our content designers as discussed Elena Findley-de Regt
Before and after images for mobile, tablet and desktop -
mobile before
mobile after
tablet before
tablet after
desktop …
=> Campaign page iteration

app/assets/stylesheets/views/_completed-transaction.scss
Last updated paragraph below the send feedback button on pages like https://www.gov.uk/done/tax-disc breaks because the form above is floated with a width of 95%. Removing this float and width fixes this layout issue.
@benilovj can you remember why the float and 95% width was added in the first instance and do you have any opinion on me removing them?
https://www.pivotaltracker.com/story/show/87918506
Before -
After -
=> Fix Last updated on Done page

app/helpers/campaign_helper.rb, app/views/root/campaign.html.erb, test/unit/helpers/campaign_helper_test.rb
Organisation HTML was being included in the page even for campaigns without an organisation, showing a blank organisation logo and link with coloured bar (see https://www.gov.uk/yourvotematters).
To fix this we added a `has_organisation?` method which checks if any of the organisation values are present.
It's still possible to get weird HTML included on the page, if the organisation details contain some values but not all of them. We've spoken to the content team and they're happy to ensure organisationless campaigns have no values set for organisation.
Before (orange circle and arrow added to highlight issue) -
After -
=> Fix empty tag capmaign pages

app/views/root/index.html.erb
The "Services and information" heading above the links to mainstream browse
isn't particularly illuminating, and makes the mainstream
browse entry points appear further down the page than they need to.
We also use the phrase "Services and Information" on (some) organisation
pages to mean something quite different (a link to a set of subtopics
containing documents related to the organisation), so it's good to avoid
labelling this section on the homepage in the same way.
Before:
After:
Since this is a highly visible change, I would like this reviewed and
approved by the following before merging:
=> Remove services and information heading from homepage

app/views/root/index.html.erb
Remove outdated reference to 1 October 2014, add link to the transaction.
Before:
After:
=> Homepage vehicle tax promo: update copy

app/views/root/_publication_metadata.html.erb
When working on something else, as an aside, I noticed this commented
out div which has been commented out since May 2013**. My guess is that
we can remove this as it's not being used. I have searched frontend
repo for .inner styles nested inside .meta-data or .group classes
and couldn't find any that required deleting along with the removal
of this commented out code.
This removal will not change anything and does not require any before
and after screenshots
** https://github.com/alphagov/frontend/blame/master/app/views/root/_publication_metadata.html.erb
=> Removing div with inner class from _publication_metadata

app/views/root/index.html.erb
'Apprenticeships' is frequently searched from the homepage (in the top 10 searches from the GOV.UK home page for the last month)
[zendesk #942523]
=> Changing Education category description to include apprenticeships

app/assets/javascripts/live-search.js
We are currently in the process of moving over to use universal
analytics. This change updates live search to use both classic and
universal. The plan is to get universal analytics monitoring exactly
what classic currently does.
This change uses GOVUK.analytics from Paul hayes recent work on static
https://github.com/alphagov/static/pull/549
As suggested by Paul we removed the last figure of 3 because that is
the default figure for that and is not needed.
https://www.pivotaltracker.com/story/show/87738926
=> Send virtual pageview through the GOV.UK Analytics API

app/assets/javascripts/transactions.js, app/assets/javascripts/views/travel-advice.js, test/javascripts/unit/foreign-travel-advice-test.js, test/javascripts/unit/transactions-test.js
https://www.pivotaltracker.com/n/projects/1261204/stories/88175032
This change wraps the GA event in the [newly introduced](alphagov/static#549)
analytics API. This will aid in the migration from GA Classic to Universal Analytics, while
remaining functionally equivalent during the migration.
/cc @fofr
=> Send analytics events through the GOV.UK Analytics API

app/views/root/make-a-sorn.html.erb, app/views/root/vehicle-tax.html.erb, test/integration/vehicle-tax_start_page_test.rb
- Tax discs aren't used anymore!
- Remove the words on Make a SORN and Vehicle Tax pages.
=> Remove the words "tax disc" from titles of sections and links

app/views/root/_transaction_cross_domain_analytics.html.erb
The Universal analytics libraries are already loaded via static.
* Remove library loading
* Anonymise IPs in keeping with our other trackers
(diff best viewed with `?w=1`)
=> Don't load universal analytics libraries twice

Gemfile, Gemfile.lock, app/controllers/search_controller.rb, test/functional/search_controller_test.rb
This commit does two things:
1. Support for the proposition header was removed from slimmer v8.0.0 so remove it from the codebase and remove the test for it.
2. Bump gem version.
This work needs to be done in advance of another PR which will make use of further changes to slimmer in this PR:  https://github.com/alphagov/slimmer/pull/121
=> Bump Slimmer

app/views/root/index.html.erb
- This extra text and where to put the link got lost in the move
between the old User Formats backlog and the current Core backlog.
=> Update the wording of the Budget 2015 promo description text

Gemfile, Gemfile.lock, app/assets/stylesheets/views/_homepage.scss, app/assets/stylesheets/views/_search.scss, app/controllers/root_controller.rb, app/controllers/search_controller.rb
This pull request:
1. Bumps the slimmer gem to 8.1.0 (the version that has support for the new header)
2. Removes the CSS that overwrites the search box in the places we don't want it (the homepage and http://gov.uk/search)
3. Adds the code to send the slimmer header `remove_search`, which will remove the search box from the HTML.
=> Make use of remove_search header in Slimmer

app/assets/stylesheets/views/_completed-transaction.scss, app/helpers/completed_transaction_helper.rb, app/presenters/publication_presenter.rb, app/views/root/completed_transaction.html.erb, test/integration/completed_transaction_rendering_test.rb
https://trello.com/c/caDndyIX
Completed transaction pages need to optionally show organ donor registration promotion. Display is toggled, and 'Join' link URL is configured from Publisher: https://github.com/alphagov/publisher/pull/371
=> Organ donor promotion on completed transaction pg.

app/views/root/completed_transaction.html.erb, test/integration/completed_transaction_rendering_test.rb
Revert to the original organ donor promotion text and button text. Fixed the tests to check the page when promotion is both on and off.
=> Revert to original organ donor promotion text

app/assets/javascripts/search.js
__Do not merge until https://github.com/alphagov/static/pull/560 is deployed__
Rather than a Classic Google Analytics implementation (which Static has a shim for), use the new `callOnNextPage` method to indicate that the search position dimension should be set on the following page.
This method does occasionally produce bad data, as explained by @rboulton, but this is something we hope to address separately:
> One problem we've seen with the existing implementation of this is that sometimes the cookie data gets loaded on the wrong page (presumably due to the target page failing to load, etc). I've wondered if it would be good to include the expected target page url (or a hash of it, for brevity) in the cookie data, and only perform the action on the target page if the url matches, to …
=> Use analytics’s `callOnNextPage` to set search position

app/assets/stylesheets/views/_search.scss, app/controllers/search_controller.rb, app/models/search_parameters.rb, app/presenters/scoped_result.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_list.mustache, app/views/search/index.html.erb, config/initializers/rummager.rb, lib/search_api.rb, test/functional/search_controller_test.rb, test/unit/presenters/search_results_presenter_test.rb, test/unit/search_api_test.rb
Pivotal: https://www.pivotaltracker.com/story/show/88435634
(before)
(After)
This PR enables searching within a single document format (in the first instance, a manual, but this could be widened to other multi-page formats)
This PR contains (in order of commit (more info on in the commit messages)):
- Technical implementation to respond to `filter_manual[]=manuals/manual-link` with only results from that manual
- Removal bits of interface (filters, search result meta-data about the format/organisation it appears in)
- Format way of displaying the scoped result count and a way to de-scope that count to show all results on GOV.UK
- Wrap the rummager api so that we can hide the multiple requests needed to rummager to build this page
**Dependencies**
This work should not be deployed until …
=> Add scoped search view

app/assets/stylesheets/views/_search.scss, app/models/search_parameters.rb, app/presenters/government_result.rb, app/views/search/_results_list.mustache, test/functional/search_controller_test.rb, test/unit/presenters/government_result_test.rb
When a search result is flagged as `historic` we want to highlight
this to a user browsing search results, so they know that result
may not be up to date and may not reflect the views of the current
government.
`historic` is defined as `political` content published under a
previous government. This only applies to Whitehall Editions
currently.
=> Add history mode note to search results

Gemfile, Gemfile.lock
This is done to not fall too far behind the latest gem version.
The tests all pass, and `rake asset:precompile` runs successfully as well.
=> Bump govuk_frontend_toolkit to 3.4.1

app/assets/javascripts/frontend.js, app/assets/javascripts/help-aa-test.js
The A/A test assigns users to cohort "variant_0" or "variant_1". We want to roll it out to a small subset of pages and see if the updated multivariate test framework interferes with analytics.
Before merging:
=> Google Content Experiment A/A test

app/models/search_parameters.rb, test/functional/search_controller_test.rb, test/unit/presenters/search_results_presenter_test.rb
Since the introduction of pagination there is no need to show an
excessive amount of results on the search page.
This commit changes the maximum number of results to 20.
Some tests had to be updated to reflect this, because they either
relied on the default value (they don't anymore) or relied on the fact
that when searching with the default number of results we don't show
the `count` in the URL.
From now on, changing the default number of results to anything but 50
wil *not* make the tests fail.
=> Display 20 results on search page

test/integration/local_transactions_test.rb, test/unit/models/search_parameters_test.rb, test/unit/presenters/search_results_presenter_test.rb
Follow up to https://github.com/alphagov/frontend/pull/794#discussion-diff-29268651
Some tests in search_results_presenter_test.rb are currently duplicated. They are supposed to verify the bounds on `count` and `start` are being enforced by `SearchParameter`.
However, after this the `SearchResultsPresenter` is tested with the changed params. This is unnecessary because there are other tests with the exact same input.
Example: 
```
SearchParameters.new(count: 50, start: -1) == SearchParameters.new(count: 50, start: 0)
```
A search with those params [is already tested in search_results_presenter_test.rb#L104](https://github.com/alphagov/frontend/blob/master/test/unit/presenters/search_results_presenter_test.rb#L104)
Tests inside a `describe` block are not actually not run by minitest. …
=> Fix/refactor tests for search presenter and transaction services 

app/assets/stylesheets/views/_vehicle-tax.scss
The HTML was removed in b2e1e4b but we didn't remove the CSS as well.
Refs #799
=> Remove .you-will-need CSS

app/views/root/check-vehicle-tax.html.erb, app/views/root/index.html.erb, test/integration/check_vehicle_tax_start_page_test.rb
- These were hanging around on the homepage and on the
check-vehicle-tax page. Thanks to the content team for checking that
these definitely had to go.
=> Tax discs don't exist anymore, so remove references to them

app/views/root/_transaction_cross_domain_analytics.html.erb
The analytics tracker now includes a method for adding a cross domain analytics tracker. Use this instead. The implementation is identical.
See also:
https://github.com/alphagov/govuk_frontend_toolkit/pull/185
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/docs/analytics.md#tracking-across-domains
=> Use `addLinkedTrackerDomain` for cross domain analytics

app/assets/stylesheets/views/_search.scss, app/views/search/_results.mustache, test/functional/search_controller_test.rb
These should be styled in the same was as all the other search results
(except with the standard external link icon on the actual link).
Trello: https://trello.com/c/XJsHhfZV/85
Before:
After:
=> Remove outline box from recommended links.

app/presenters/government_result.rb, test/unit/presenters/government_result_test.rb
Trello: https://trello.com/c/miNh5OBv/106-bug-united-kingdom-displayed-in-search-result-metadata
> Content tagged to the United Kingdom world location displays the slug 'united-kingdom' in search results. The search API only has the slug for united-kingdom, whereas for other world locations it has the link and title as well (see the attached images).
Currently we display the slug for a World Location when there's no acronym or title. This looks a bit odd in the search results.
Note the reason that rummager returns no title for the United Kingdom location is that it's set to `inactive` in Whitehall.
=> Don't show slugs for world locations

app/presenters/search_result.rb, app/views/search/_results.mustache, test/functional/search_controller_test.rb
Trello card: https://trello.com/c/TJKCNQXE/84-user-facing-in-search-results-from-mainstream-remove-the-browse-section-metadata
> The browse section metadata is currently a shortened form of the description, which can be very confusing.  For example, the "Having a child, parenting and adoption" section is abbreviated to "Child adoption", which leads to the "Parental rights and responsibilities" page appearing to be in a category about adoption.
=> Remove the "browse" metadata from search results

app/assets/javascripts/frontend.js
The ordering of how we include JavaScript dependencies matters. For now,
revert this change until we have better dependency management in place.
=> Revert ordering cleanup of frontend includes

app/assets/javascripts/search.js
This code isn't using the correct naming, and wasn't tracking the search
results shown either, so we're disabling it so other frontend changes
can be deployed.  It is going to come back in a fixed form shortly, so
I'm not removing the implementation of `extractSearchURLs`, which seems
to be working fine (and has tests), but won't be being run after this is
merged.
=> Remove tracking of search results and suggestions

app/helpers/cross_domain_analytics_helper.rb, app/views/root/_transaction_cross_domain_analytics.html.erb, app/views/root/transaction.html.erb, test/unit/helpers/cross_domain_analytics_helper_test.rb
HMRC will be promoting https://www.gov.uk/renewtaxcredits which sends people to their service at
https://www.tax.service.gov.uk/tax-credits-service/start. Attempt to follow users from the paid-for promotions through to the completion of the service.
https://www.pivotaltracker.com/story/show/95971198
=> Cross domain tracking for HMRC renew tax credits

app/assets/javascripts/search.js, test/javascripts/unit/search-test.js
Track the full list of search URLs and any spelling suggestions. This is now in a single event request, because:
1. We'll be processing the data outside of Google Analytics
2. It's one less request from a user's browser
Story: https://trello.com/c/TBJyZJDp/67-record-which-documents-were-shown-for-a-search
=> Track the search results and suggestions

app/assets/javascripts/search.js
Google Analytics expects labels to be Strings instead of JSON
objects. Stringiy the data we send them otherwise the values will be
converted to null values.
Docs: https://developers.google.com/analytics/devguides/collection/analyticsjs/events
=> Stringify JSON we send to Google Analytics

app/assets/javascripts/search.js
The JavaScript in this file was being triggered in multiple places
across the site. We only want it to occur on pages where the
`#results .results-list` element exists. Use a conditional to enforce
this behaviour.
=> Only run search tracking when the results element exists

app/assets/javascripts/search.js, test/javascripts/unit/search-test.js
Separate out the building of the search result object into a separate function so that it can be tested seperately from the sending of the event.
Previously, the event was sending a JSON obect which contained an Array of URLs that were JSON.stringified jQuery objects. `buildSearchResultsData` converts these into a simpler Array so that the URLs are easier to parse.
=> Extract out how the search event object is built

app/views/root/index.html.erb
The homepage is split by sections anyway and doesn't need extra
splitting. In a screen reader it announces 'group services and
information, horizontal rule, group department and policy, horizontal
rule...". The horizontal rules are extra noise which are just
distracting.
=> Add aria-hidden to horizontal rules

app/views/root/index.html.erb
This link still goes to /visas-immigration which redirects
to /browse/visas-immigration.
This breaks the In-Page Analytics view in Google Analytics,
because the next page tracked doesn't match the link.
Updated to go directly to /browse/visas-immigration.
=> Update visa-immigration link

app/assets/javascripts/live-search.js, app/assets/javascripts/search.js, test/javascripts/unit/search-test.js
When a user filters the search results by organisation, trigger a new GA
event to record the search results on the filtered results page.
Story: https://trello.com/c/NuwDBZEz
=> Track search results when filtered by organisation

app/views/root/index.html.erb
Because the treasury has renamed it. The title in the linked page has been renamed already. The URL slug remains the same though.
=> Rename 'July 2015 Budget' to 'Summer Budget'

app/presenters/government_result.rb, app/presenters/search_result.rb, test/unit/presenters/government_result_test.rb, test/unit/presenters/search_result_test.rb
Some descriptions for content can be very long and the full description
is shown to the user. This has the effect of obscuring other search
results by moving them further down the page
https://trello.com/c/GKDjmzlW/209-truncate-long-descriptions-in-search-results
=> Restrict description displayed in search results

app/views/root/index.html.erb
"Childcare and parenting" is our newest mainstream browse page. It deserves a place on the homepage. The new placement of browse links was [decided in this Trello ticket](https://trello.com/c/KRe96Tvd/236-add-links-to-childcare-and-parenting-to-homepage-and-footers).
Trello: https://trello.com/c/KRe96Tvd/236-add-links-to-childcare-and-parenting-to-homepage-and-footers
:no_entry_sign: Don't merge until this new page has been published (scheduled for today).
=> Add Childcare and parenting browse page on home

app/assets/javascripts/search.js, test/javascripts/unit/search-test.js
If a search returns no results, but does have a spelling suggestion, a searchResults event should be sent to GA including the spellingSuggestions (but no urls). Currently, no event is sent to GA in this case.
Ticket: https://trello.com/c/zJ5wo5rc/183-no-results-logged-for-a-search-with-a-suggestion-but-0-results
~~PS: I've added an empty string for the suggestion parameter for searchResultData, this because I did not want to overcomplicate the IF clause in trackSearchResultsAndSuggestions. I am assuming that an empty string sent to GA is not going to be logged. Am I right? If not, I can renounce to this modification and make that IF clause even uglier.~~ (see comments)
PPS: this is the first time I write JS for GOV.UK. Be nice. :metal:
=> Log search with zero results and suggestion

app/views/root/index.html.erb
As requested by colleagues in the performance platform.
=> Add a link to the performance page to the homepage

app/views/root/check-vehicle-tax.html.erb, app/views/root/make-a-sorn.html.erb, test/integration/check_vehicle_tax_start_page_test.rb, test/integration/make_a_sorn_test.rb, test/integration_test_helper.rb
`check-vehicle-tax` and `make-a-sorn` render using a custom template.
This adds the cross-domain tracking option to the template.
/cc @jamiecobbett
=> Add cross-domain tracking to exceptional pages

app/presenters/publication_presenter.rb, app/views/root/_publication_metadata.html.erb, test/integration/guide_rendering_test.rb, test/integration_test_helper.rb
Most mainstream formats don't have a meta description tag in the HTML, for use by external search engines, social media etc.
The lack of a meta-description tag makes some search result snippets unhelpful, confusing or misleading. Yet the content does have handwritten descriptions, which we display in site search, so we should also make them available externally.
https://trello.com/c/gYpErB1T/241-add-meta-description-tag-to-mainstream-content-pages
=> Add meta description tag to mainstream content pages

app/assets/javascripts/live-search.js, app/assets/javascripts/search.js
(Don't merge yet, here for feedback.)
[From Trello](https://trello.com/c/zOts34TQ/184-old-url-is-logged-when-search-filters-are-changed):
> It looks like the GA events sent on ajax page changes in the search results use the original URL of the page, not the updated URL.
> - If I go to https://www.gov.uk/search?q=tax and then add an organisation filter, a GA tracking event is sent for the filtered page, but it uses the unfiltered URL as the url of the event.
> - If I do a full page refresh (eg, of https://www.gov.uk/search?q=tax&filter_organisations%5B%5D=hm-revenue-customs), the filter parameter is recorded, but if I then remove the filter, an event is recorded with the filter still applied.
GA sends the original URL because by default it uses the `window.location` during page load. …
=> Set GA page variable before sending events

app/assets/javascripts/search.js, app/assets/stylesheets/views/_checkbox-filter.scss, test/javascripts/unit/search-test.js
Some users frequently search GOV.UK by editing the URL and keeping their
choice of organisation filters in place, e.g.
https://www.gov.uk/search?q=Housing&filter_organisations%5B%5D=land-registry
However, when no results are returned for a query, the organisation filter
(land registry in the example) is still selected and it's no longer possible
to use the "Remove filters" link to easily clear them, e.g.
https://www.gov.uk/search?q=Immigration+Rules&filter_organisations%5B%5D=land-registry
The "Remove filter" is driven by the `GOVUK.CheckboxFilter` JavaScript.
However, when there are no results, the component is not being activated.
The bug has been fixed by removing the bounds check within the
`GOVUK.search.enableLiveSearchCheckbox`.
Story: …
=> BUGFIX: Enable liveSearchCheckbox with 0 results

app/views/simple_smart_answers/_current_question.html.erb
As per http://govuk-elements.herokuapp.com/#guide-forms use radio buttons
with a large hit area indicated by a grey square. These are easier to select
with a mouse or touch devices.
Before/After
=> Use preferred radio button styles in simple smartanswers

app/views/simple_smart_answers/_current_question.html.erb, app/views/simple_smart_answers/flow.html.erb
Issue: simple smartanswers questions are not aligned with the
prominent in mobile view.
This is because section.content does not have any styles applied.
Change to `main.content` (that is used all around the application) that adds
correct padding. Remove `.current` css class from `.step` as it doubles the padding.
Before/After:
Reported by @alextea
=> Fix simple smartanswers layout

lib/data/new_window_transactions.json
This list was created in 2012 to force some legacy transactions to open in new windows when the “start now” button was clicked. This was because some of those transactions had either been designed to be opened in new windows or broke when opened with toolbars enabled.
This pull request cleans up the list of transactions by removing those which no longer exist in their original form. These transactions have either been rebuilt or closed down.
=> Clean up list of transactions which are forced to open in new windows

app/controllers/root_controller.rb, test/functional/root_controller_test.rb
- It turns out that sometimes Rummager returns results that are links to
external websites, starting therefore with "http://". Random used to
use these like www.gov.uk/http://somewhere_else.com, and this would
return a 404 to users.
- Fix this by redirecting the user to /random once again if the previous
result began with "/http". The odds of this happening twice in a row
are very low.
- This required some reworking of the tests because the code to choose a
result chose the first result, therefore the first result in the bad
case needed to be ie "http://somewhere_else.com" in our test data.
Thanks to David Singleton for his help with this.
- We don't want to cache the redirect to /random over again, so test
that we don't, as well.
(Bug reported at: …
=> Don't let /random attempt to redirect to paths starting with "/http"

app/views/root/_option.html.erb
This commit goes alongside changes in the static application (see https://github.com/alphagov/static/pull/630).
To conform with https://github.com/alphagov/govspeak/wiki/Using-govspeak-on-GOV.UK#contacts I am removing labels for email and website, as these are links and are also
formats that should be widely recognised by users.
This should either be merged together with https://github.com/alphagov/static/pull/630 or not at all I guess.
=> Improve contact information layout for place options

app/presenters/government_result.rb, app/presenters/search_result.rb, app/views/search/_result.mustache, test/unit/presenters/government_result_test.rb, test/unit/presenters/search_result_test.rb
Generation of sensible descriptions/snippets gas is now rummager's responsibility. This PR makes the search results use this snippet and removes old code.
Trello: https://trello.com/c/AM4LQ2i3
=> Use rummagers snippet in search results

app/presenters/government_result.rb, app/presenters/search_result.rb, app/views/search/_result.mustache, test/unit/presenters/government_result_test.rb, test/unit/presenters/search_result_test.rb
Reverts alphagov/frontend#846.
Work on rummager has progressed a lot in the last week, making this interim change less useful. This PR will be superseded by a new one, directly implementing highlighted snippets.
@rboulton
=> Revert "Use rummagers snippet in search results"

app/presenters/government_result.rb, test/unit/presenters/government_result_test.rb
Currently, Frontend is in charge of appending the prefix to open organisations. We want Whitehall to take care of its data. This will also allow us to highlight the organisation description correctly.
The work for that is in: https://github.com/alphagov/whitehall/pull/2314
To prevent double prefix when Whitehall is migrated, we add a temporary guard here. This can be removed entirely once Whitehall has been migrated.
=> Add guard against double prefixes in org description

app/presenters/search_result.rb, test/unit/presenters/search_result_test.rb
Topics (formerly "specialist_sectors") didn't use to have their own description. They do have them since
https://github.com/alphagov/collections-publisher/pull/125 was deployed, so the code removed in this commit will never be run.
To verify all descriptions are set for topics:
https://www.gov.uk/api/search.json?filter_format[]=specialist_sector&count=1000
=> Remove fallback for topic description

app/presenters/government_result.rb, test/unit/presenters/government_result_test.rb
The app currently crashes when the organisation doesn't have a description. This commit adds a test for that situation and fixes the code.
Note that the `GovernmentResult#description` now returns an empty string instead of nil, which is better.
@alext
=> Fix exception when organisation doesn't have description

app/views/root/_publication_metadata.html.erb, app/views/travel_advice/country.html.erb, test/fixtures/foreign-travel-advice/turks-and-caicos-islands.json, test/integration/travel_advice_test.rb
To improve the search result snippets show on external search engines.
Ticket: https://trello.com/c/hBKYMcPO/294-add-meta-description-tag-to-foreign-travel-advice-frontend
=> Add metadata to Foreign Travel Advice country pages

app/views/travel_advice/index.html.erb, test/fixtures/foreign-travel-advice/index1.json, test/integration/travel_advice_test.rb
To improve the search result snippets show on external search engines.
Ticket: https://trello.com/c/hBKYMcPO/294-add-meta-description-tag-to-foreign-travel-advice-frontend
=> Add metadata to Foreign Travel Advice index page

app/models/search_parameters.rb, app/presenters/non_edition_result.rb, app/presenters/search_result.rb, test/functional/search_controller_test.rb, test/unit/presenters/non_edition_result_test.rb
`public_timestamp` is exactly equivalent to `last_update`, because rummager copies the value from `last_update` whenever `public_timestamp` is missing: [`Index#prepare_public_timestamp_field `](https://github.com/alphagov/rummager/blob/80ea29b5ef26d6e83f3eec6834c8ab18adab575f/lib/elasticsearch/index.rb#L490).
More backstory at https://github.com/alphagov/hmrc-manuals-api/pull/94#discussion_r36610679:
> Historically, public_timestamp was populated by documents from whitehall, and last_update was populated by documents from specialist-publisher. We noticed the duplication when implementing the rummager schemas, and made specialist-publisher populate both fields, with an aim to remove the last_update field at some point - but never got to the point where we're certain that nothing is still …
=> Don't request `last_update` from rummager

app/models/search_parameters.rb, test/functional/search_controller_test.rb
`topics` can refer to two concepts in the GOV.UK stack:
1. Something in Whitehall we've renamed to "policy area" (https://trello.com/c/KMOhcErO)
2. A kind of tag which used to be called "specialist sector"
The `topics` we are removing here refer to the whitehall-kind. We're not using those in this application, so we can stop requesting these from rummager. This will allow us to update rummager to rename `topics`
to `policy_areas` and `specialist_sectors` to `topics`.
Who said naming was hard?
Trello: https://trello.com/c/N0dU4k3G
=> Don't ask rummager for "topics"

app/models/search_parameters.rb, test/functional/search_controller_test.rb
`section` / `subsection` was used to display the primary mainstream browse page in the search results. This was removed in PR https://github.com/alphagov/frontend/pull/806, but we're still requesting the fields from rummager. 
This commit stops us from requesting the fields so that we might be able to remove them from
rummager entirely.
Trello: https://trello.com/c/N0dU4k3G/296-clear-up-naming-in-rummager
=> Don't request section fields from rummager

app/views/root/campaign.html.erb, test/fixtures/britain-is-great.json, test/integration/campaign_page_test.rb
Part of improving search result snippets shown on external search engines.
The lack of a meta-description tag makes some search result snippets
unhelpful, confusing or misleading. Ticket: https://trello.com/c/S6VUwRWQ/273-follow-up-add-meta-description-tag-to-custom-content-types
=> Add meta description tag for campaigns

app/views/root/_transaction_cross_domain_analytics.html.erb, app/views/root/check-vehicle-tax.html.erb, app/views/root/make-a-sorn.html.erb, app/views/root/transaction.html.erb
Cross-domain tracking uses a magic _ga parameter appended to the link with a value that identifies the user.
The argument we were passing - with the value 'service.gov.uk' - is used to do a substring match for the links on the page to rewrite.
By changing it to use the domain in the Transaction's link, we should be able to support any destination, not just ones on *.service.gov.uk, for example `online.hmrc.gov.uk` or `petition.parliament.uk`.
Tested successfully in development.
/cc @bradleywright
=> Make cross domain tracking support any destination

app/views/root/_location_form.html.erb, test/integration/local_transactions_test.rb
When a user enters an invalid postcode we should redisplay the
input they gave, so they can alter the input to make corrections/
see what caused a problem.
Firstly, this is a basic pattern of form error-handling, repopulating
fields, and we should be doing it regardless.
Secondly looking at invalid input to these forms we see many cases
of small typos, eg non-alphanumeric characters, and partial postcodes.
Both cases where editing/expanding the postcode will help the user
vs making them retype it.
=> Repopulate invalid input for location transaction

Gemfile, Gemfile.lock
Adds `better_errors` for web-console debugging, and `pry` for console-console debugging.
We use both on these on lots of other apps, it's better to specify them in the `Gemfile` so they're available as consistently as possible.
=> Add some debugging gems

lib/search_api.rb, test/unit/search_api_test.rb
We recently added the missing leading slash to the `id` and `link` fields sent
to Rummager for all manuals and manual sections. At the time we thought that we
should not do the same for the `manual` field in manual sections, because it
would break searching within a manual.
However, at the moment although the correctly scoped search results are
returned when searching within a manual, the standard search layout is used
rather than the layout for scoped searches. manuals-frontend is using the
manual's path without the first character as the filter parameter [1] which
currently matches the values in the sections' `manual` field, so the correct
results are returned. The Searcher in Frontend uses that same value (without
the leading slash) to filter on the `link` field in Rummager, and if no …
=> Temporary workaround to fix search within a manual

app/assets/stylesheets/views/_search.scss, app/models/search_parameters.rb, app/presenters/search_result.rb, app/views/search/_result.mustache, app/views/search/_search_field.html.erb, test/unit/presenters/scoped_search_results_presenter_test.rb
This commit adds support for highlighting to the search results. This is still under a debug flag to more easily review the changes.
cc @alextea 
--
=> Show highlighting in search results

test/integration/local_transactions_test.rb, test/test_helper.rb
Some tests set the locale to `:cy` without cleaning up after themselves,
resulting in transient failures. So to fix this, we set the locale to `:en` 
before each test.
=> Leaky test fix

app/assets/stylesheets/views/_search.scss
As suggested by Alex Torrance (https://github.com/alphagov/frontend/pull/858/files#r38406652) - this has better contrast than pale yellow.
Image of the result in that PR.
(Note - I've not actually run this locally)
=> Use $focus-colour for search highlighting

config/application.rb, config/environments/production.rb
This was used as a workaround for apps that have their assets compiled
once on Jenkins then rsynced to the servers. frontend has its assets
compiled on each machine, so this isn’t needed and we can safely let
Rails generate a manifest filename itself.
Tekin did an excellent writeup of the issue here: https://github.com/alphagov/whitehall/commit/2f468927c5f8933cdbb7946786e
Also fix a missed deprecation warning
=> Remove configuration of asset manifest file

app/assets/stylesheets/views/_search.scss
This is less intrusive than the yellow background highlighting previously
used, which is desirable because the highlights shouldn't get in the way
of reading the actual text.  Also, using a font weight instead of a
background colour means that the gaps between highlighted words aren't
visible.
The bold doesn't show up in titles, because titles are already bold.
However, keeping the html markup in there seems desirable, because then we
can easily try out other visual markup options.  It also lets us build debug
tools to help us understand why things are matching the query.
=> Use bold for search highlights

app/models/search_parameters.rb, test/functional/search_controller_test.rb, test/unit/models/search_parameters_test.rb
This new parameter will make rummager return spelling a spelling suggestion for the search term. 
Trello: https://trello.com/c/P0tJYcUH
The first commit removes some tests which didn't test anything from the controller file and adds the missing coverage to the unit test for SearchParameters. 
These controller tests used to test verify that for a given user-search, the correct query were sent to rummager. However, since a002cae / PR #781 the `expect_search_client_is_requested` method doesn't actually test the parameters: https://github.com/alphagov/frontend/commit/a002cae6389af091f29a4b924ce5424af8ae1212#diff-2f586f9e871e5cf90962f20a38553e75L85.
=> Add spelling suggestion search parameter

app/models/search_parameters.rb, app/presenters/search_result.rb, app/views/search/_result.mustache, app/views/search/_search_field.html.erb, test/functional/search_controller_test.rb, test/javascripts/unit/live-search-test.js, test/unit/presenters/scoped_search_results_presenter_test.rb
Remove the enable_highlighting parameter - now that we're happy with the
highlighting, we always want to highlight results:
https://trello.com/c/GPInH4fj/303-remove-search-highlighting-feature-flag
Looks like:
=> Always highlight search results

app/models/search_parameters.rb, app/presenters/government_result.rb, app/presenters/search_result.rb, test/unit/presenters/government_result_test.rb, test/unit/presenters/scoped_search_results_presenter_test.rb, test/unit/presenters/search_result_test.rb
Frontend previously modified the titles and descriptions of search results. To enable us to highlight the search description and title, we've moved this logic to the publishing apps. For example, Whitehall
now correctly prepends "The home of HMRC on GOV.UK" to HMRC's search description (alphagov/whitehall#2314).
`description` is no longer needed, so we don't request that from rummager. `title` is still used to generate nice looking metadata. 
The truncation of the description is now the responsibility of rummager (alphagov/rummager#492).
Since turning on highlighting for all users on this app we no longer need this special case code. However, in making this PR we've discovered that for closed organisations, "Closed organisation:" is prepended to the title. This will be fixed in a PR on …
=> Remove code to modify search descriptions and titles

app/assets/javascripts/transactions.js
This behaviour means that a selected tab retains the default fragment behaviour, i.e. people can copy links to a particular section of a site. An example url would be http://frontend.dev.gov.uk/view-driving-licence#other-ways-to-apply  - loading the page will jump to the tab strip with the correct tab selected and its content showing below.
=> Scroll to the selected tab on page load

config/application.rb, test/integration/search_test.rb
We use an iframe to show the search result in search-admin. This stopped working since the upgrade to Rails 4 (https://github.com/alphagov/frontend/pull/873), because Rails sends the `X-Frame-Options: SAMEORIGIN` header by default now (https://github.com/alphagov/whitehall/pull/2080).
Trello: https://trello.com/c/1hGnjzaO
=> Allow pages to be framed

lib/search_api.rb
This reverts commit ef9e4dc as we've fixed the problem properly now
in https://github.com/alphagov/hmrc-manuals-api/pull/109,
https://github.com/alphagov/manuals-frontend/pull/159 and
https://github.com/alphagov/specialist-publisher/pull/564.
=> Revert "Temporary workaround to fix search within a manual"

lib/data/external-links.yml
I don't think this has been used since: 9bbc50c6d813b91ced9a7f11cf5547942eb9c110
=> Remove unused external-links file

app/controllers/root_controller.rb
`present?` is defined as `! blank?`, so this code was particularly
peverse in doing it how it was. Removing the double-negative makes it
much easier to read.
=> Remove some double-negatives.

app/views/travel_advice/_country_summary.html.erb, test/integration/travel_advice_test.rb
This special case was added when this feature was introduced to avoid
presenting unhelpful messages to the user while the content was being
updated.
Every published edition in the database has been updated after
this date, so there's no longer a need for this special case. Removing
this so as to simplify the upcoming migration work.
=> Remove special case for travel-advice before 2013-04-22

app/views/root/_location_form.html.erb, test/integration/local_transactions_test.rb
Adds the Royal Mail's Postcode Finder as link to the location form for local transactions. It also adds the Finder to 'licences' pages (https://www.gov.uk/house-to-house-collection-licence) and 'places' pages (https://www.gov.uk/number-plate-supplier), as they use the same partial.
One of the ACs mentions to set up exit link tracking. It appears this comes free from the `static` app, which includes the gem `govuk_frontend_toolkit` and thereby JS code for [tracking clicks on external links](https://github.com/alphagov/govuk_frontend_toolkit/blob/master/javascripts/govuk/analytics/external-link-tracker.js#L6-L9). We've manually tested successfully that the CSS selector includes the new link to the Postcode Finder. We also used the [Google Analytics Debugger Chrome …
=> Add postcode finder link to local transactions

Gemfile, Gemfile.lock, app/controllers/root_controller.rb, lib/postcode_sanitizer.rb, test/functional/local_transactions_controller_test.rb, test/unit/postcode_sanitizer_test.rb
- We were seeing lots of errors for postcodes entered with obvious
typos, eg. hyphens instead of spaces, 0 instead of O, I instead of 1,
etc, so this is an attempt at fixing most common ones. Strip most
non-alphanumerics and trailing whitespace. Also use the uk_postcode
gem to fix transposition of I/1, O/0.
- This was originally done in Imminence, thought it would be better in
GDS API adapters (https://github.com/alphagov/gds-api-adapters/pull/384) for a consistent experience everywhere, but then
reverted to do it again not centrally, but in each app, as there are
(at the moment) only two (Imminence and Frontend) that deal with
user-inputted postcodes.
- Sometimes in frontend, `params[:postcode]` can be nil, so I've made
`PostcodeSanitizer` not try to sanitize a nil postcode, so that …
=> Autocorrect obvious typos in postcodes before sending to MapIt

Gemfile, Gemfile.lock, app/controllers/root_controller.rb, app/models/mapit_postcode_response.rb, app/views/root/local_transaction.html.erb, test/functional/local_transactions_controller_test.rb
In order to improve the experience for users on local transactions we need to log the error states from the Postcode form. In order to know if the difference between a bad Postcode and a good Postcode with no Mapit match I've bumped `gds-api-adapters to `25.0.0` to include the change in https://github.com/alphagov/gds-api-adapters/pull/381. This means that when entering a bad postcode, the API adapter will return a exception with a 400 code. We can then use this to log the error state.
This PR does that by unfortunately duplicating the code in the `publication` action and added setting an instance var with the error of the variable state. This is also sent to Google Analytics in the template. These error state strings came from our Analyst. The idea is we will be able to scale back …
=> Log postcode errors

app/controllers/root_controller.rb, app/models/location_error.rb, app/views/root/_location_form.html.erb, app/views/root/local_transaction.html.erb, config/locales/en.yml, test/functional/local_transactions_controller_test.rb
Previously the JavaScript would break in the script tag inside the `location_transaction` view, as when `@location_error` was `nil`, running `I18n.translate` on `nil` creates a span with missing translation and does not use the second argument of the `||` expression.
To fix this, we refactor by adding a new LocationError class to group the two error related variables set from the root controller and move the logic out of the view and into the class. We also add a locale definition for the 'invalid postcode' error case.
=> Add LocationError class to encapsulate error logic

Gemfile, Gemfile.lock, app/controllers/root_controller.rb, app/models/location_error.rb, app/views/root/local_transaction.html.erb, config/environments/production.rb, config/initializers/logstasher.rb, config/locales/en.yml, test/functional/local_transactions_controller_test.rb, test/integration/local_transactions_test.rb, test/unit/models/location_error_test.rb
Adding postcode error code `laMatchNoLink` for where a postcode has a location from MapIt and a Local Authority but no Location Interaction/Link.
Also implements tracking in Kibana by using `LogStasher` gem to log postcode errors in JSON format. Had to upgrade `LogStasher` to release version `0.6.2` to get notification subscriptions to work. Latest version of the gem is `0.8.6` but various things break or change (see commit message for details).
=> Log postcode error for missing interaction

app/assets/stylesheets/views/_homepage.scss
The grid alignment was off 1020px and 640px, not aligned with the rest of the page and with no left/right gutter - so sitting against the edge of the page.
Use the FET grid helpers, which handles gutters/breakpoints in a standard way and avoid re-implementing it here. The FET helper also provides IE support by default, so we can drop that too.
I tested this locally with using the [example notification template](https://github.com/alphagov/frontend/blob/master/app/views/root/_campaign_notification.html.erb.example) copied to the ['live' notification template](https://github.com/alphagov/frontend/blob/master/app/views/root/_campaign_notification.html.erb), if you want to replicate.
| --- | --- |
|  ![homepage-before](https://cloud.githubusercontent.com/assets/63201/1150876 …
=> Fix emergency notification banner on homepage

app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_local-transaction.scss, app/assets/stylesheets/views/_location_form.scss, app/controllers/root_controller.rb, app/models/location_error.rb, app/views/root/_location_form.html.erb, app/views/root/local_transaction.html.erb, config/locales/en.yml, test/functional/local_transactions_controller_test.rb, test/integration/licence_lookup_test.rb, test/integration/local_transactions_test.rb, test/integration/places_test.rb, test/unit/models/location_error_test.rb
[Trello card](https://trello.com/c/fT1OKmgb/228-make-changes-to-the-shared-content-of-local-transactions-based-on-the-postcode-prototype)
1. Changes to wording/structure of the shared postcode lookup form based on [this prototype](http://local-gov-links.herokuapp.com/pay-council-tax_2)
- Emphasises "Enter a postcode" text
- Removes placeholder and places example above instead
2. Changes to "Start now" (or "happy path") page based on [this prototype](http://local-gov-links.herokuapp.com/start-now-simple_2)
- Emphasises which service provider we've matched to
- Change "Start now" wording to "Go to their website"
3. Changes to errors / non-happy paths
In general, we've changed the wording and appearance of the error information to match the following prototypes:
- [Invalid postcode …
=> Update to Local transactions based on prototype

app/controllers/root_controller.rb, app/models/location_error.rb, app/presenters/local_authority_presenter.rb, app/views/root/local_transaction.html.erb, config/locales/en.yml, test/integration/local_transactions_test.rb, test/unit/presenters/local_authority_presenter_test.rb
In #907 we changed most of the result pages for local transactions based on [the prototype](http://local-gov-links.herokuapp.com/), this PR changes the [remaining page](http://local-gov-links.herokuapp.com/la-match-no-link).
We did this page separately because it relies on changes to be made elsewhere to support it:
1. https://github.com/alphagov/govuk_content_models/pull/356 - to give LocalAuthority models a homepage_url attribute
2. https://github.com/alphagov/publisher/pull/443 - to have publisher import that attribute from the local directgov feed.
3. https://github.com/alphagov/govuk_content_api/pull/237 - to make govuk_content_api put the homepage_url into the JSON representation
**While reviewing this PR check for defensive coding - we should be able to merge and deploy this PR …
=> Rework local transaction result pages for "LA found, but no transaction url present" result

app/controllers/root_controller.rb, app/models/location_error.rb, app/views/root/_ga_postcode_error_tracking.html.erb, app/views/root/local_transaction.html.erb, app/views/root/place.html.erb, config/locales/en.yml, test/integration/local_transactions_test.rb, test/integration/places_test.rb, test/unit/models/location_error_test.rb
For certain locations, such as the Channel Islands, the Find My Nearest postcodes searches using the Mapit API in Imminence were returning results having found the postcode but would not have found any locations. This resulted in a error below:
Frontend now shows a more descriptive message for the user:
The work in Imminence related to this is [here](https://github.com/alphagov/imminence/pull/124).
[Trello card](https://trello.com/c/TC6mZatW/265-imminence-errors-on-jersey-postcodes-for-find-my-nearests).
=> Handle No Location Exception from Imminence

app/assets/javascripts/frontend.js, app/assets/javascripts/modules/track-submit.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_report-child-abuse.scss, app/controllers/root_controller.rb, app/helpers/phone_number_helper.rb, app/views/root/_ga_postcode_error_tracking.html.erb, app/views/root/_location_form.html.erb, app/views/root/_option_report_child_abuse.html.erb, app/views/root/local_transaction.html.erb, app/views/root/place.html.erb, test/integration/places_test.rb, test/javascripts/unit/modules/track-submit.spec.js, test/unit/helpers/phone_number_helper_test.rb
For https://trello.com/c/l4RcbEfd/300-front-end-report-child-abuse-changes
This PR prepares the frontend app to display search results for "Report Child Abuse" with a customised view and will only take full effect once the 'report-child-abuse' page has been turned into a `place` format (known as 'find-my-nearest') in [this story](https://trello.com/c/ycz55OuN/292-back-end-report-child-abuse-changes). We also implement GA tracking for clicking the submit button on the postcode search location form, as well as for if any results get shown.
Screenshots below with dummy data to show the visual changes:
=> Add report child abuse views

app/assets/stylesheets/views/_completed-transaction.scss
- Users were reporting a bug on IE11 where the first done page
feedback question was overlapping the related links on the left.
This change fixes it with some new CSS for the `legend` HTML, and
applies it everywhere. It makes it no worse in Chrome etc., but a
lot better in IE11.
Before:
After:
Trello: https://trello.com/c/sQQiAeyy/309-done-page-ie11-rendering-issue-5
=> Fix IE11 text overlapping bug on done pages

app/controllers/root_controller.rb, test/functional/root_controller_test.rb, test/integration/campaign_page_test.rb, test/integration/check_vehicle_tax_start_page_test.rb, test/integration/make_a_sorn_test.rb, test/support/integration_test_helpers.rb
This fixes the bug where 'campaign' pages were not displayed at full width as intended. The reason was that `RootController` did not discern between custom slugs and custom formats correctly, as it only ever checked if a publications 'slug' was in the keys of the CUSTOM_FORMATS hash. In the case of 'campaign' pages, it's the actual 'format' (not the 'slug') that's different.
Besides updating `RootController` to account for the bug, we add integration tests to check that the appropriate pages like 'campaign' format pages are displayed at full width. We also add functional tests to check that `RootController`'s calls the `render` method with the correct parameters for custom cases.
=> Fix full width for campaign pages

Gemfile, Gemfile.lock, app/controllers/root_controller.rb, config/initializers/imminence.rb, test/integration/places_test.rb
- Bumped gds-api-adapters gem to 28.3.1. This contains an additional `imminence_has_places_for_postcode` test helper which was added [here](https://github.com/alphagov/gds-api-adapters/commit/34be7baf9bc798149edec3c0687649885dd9830d)
- Places test has been changed to use the above. The reasoning for this was that there was already a test helper for areas but not for places.
=> Use test helper for places for postcode

app/views/root/completed_transaction.html.erb
Reverts alphagov/frontend#901.
There's a lot of confusion about the word 'automatic', which needs resolving between different bits of gov. Remove in the meantime.
=> Revert "Organ donation: there's a new law in Wales that is opt-out, not opt-in"

app/views/help/index.html.erb
We're adding a new bullet to the help page to try to reduce the number of support questions that we get from people asking about email subscriptions.
It looks like this:
https://trello.com/c/3U2bPsgy/329-link-to-help-page-for-email-subscriptions-small
=> Add email notifications bullet to help page

Gemfile, Gemfile.lock
Seems like alphagov forked rails-i18n to customise the Welsh translations of months, which were merged into the rails-i18n repo with [PR #283](https://github.com/svenfuchs/rails-i18n/pull/283).
=> Update rails-i18n gem from a forked v0.7.1 to v4.0.8

config/application.rb, config/environments/production.rb, config/environments/test.rb
This application does not send emails. Presumably the action_mailer framework with SES config was added to support error notification (we used to use a email-based thing, but that has all been replaced by
Errbit/Airbrake).
This will speed up the load time for the app slightly.
Previously: https://github.com/alphagov/frontend/pull/929
=> Remove ActionMailer

lib/data/authorities.json
Recent Northern Irish authorities have no SNAC code which breaks compatibility
with several of our applications.  We will use the GSS code as a SNAC as a temporary fix until GOV.UK moves wholesale to GSS codes.
Note that this PR does not change Belfast because its slug (which must match with Licensing) do not change and we don't want to stop sending traffic to Belfast before we switch over to use the new mapit database that will include these GSS codes (see: https://github.com/alphagov/mapit/pull/13)
This is for https://trello.com/c/kjurG3i8/302-support-new-northern-ireland-local-authorities-for-licensing
=> Use GSS code in place of (non-existent) SNAC codes for new NI councils (except Belfast)

app/views/root/make-a-sorn.html.erb, test/integration/make_a_sorn_test.rb
- Removed one of the contact phone numbers from the Others ways to apply section, as requested in the [Zendesk ticket](https://govuk.zendesk.com/agent/tickets/1288330)
[Trello card](https://trello.com/c/bVphkJRo/353-change-hardcoded-text-on-make-a-sorn-start-page)
=> Remove make-a-sorn contact phone number

app/views/root/index.html.erb
PT story: https://trello.com/c/ZHKtYh1P/80-4-april-update-homepage-promo
Replaces Bank Holidays promotion with Register to vote.
[URL on gov.uk](https://www.gov.uk)
* Removes promotion "UK Bank Holidays"
* Adds promotion "Register to vote"
=> Replace UK bank holidays promo with Register to vote

lib/data/authorities.json, test/functional/licence_location_test.rb
This finishes the work in #918 and aligns the Belfast council with the rest of the NI councils to use GSS code in place of the SNAC.  This assumes we have switched over to use the new mapit database.
This includes the commits for #918, once that's merged we'll rebase.
For: https://trello.com/c/ilFPO330/90-switch-over-to-use-new-mapit-in-production
Background: https://trello.com/c/kjurG3i8/302-support-new-northern-ireland-local-authorities-for-licensing
=> Use GSS code as SNAC for Belfast

app/assets/stylesheets/views/_homepage.scss, app/views/root/index.html.erb
**Promo slot**
The homepage has a number of promotional slots, used to highlight important things like dates (eg, self assessment), changes to policy (eg, paper counterpart) or topical events (eg, budget).
These are quite smaller, and further down the the page, so don't work as well for more prominent items. This adds a new full width promo slot to try and improve visibility of high importance items.
It's not intended to be used permanently, but for the duration of important events. Eg, things like elections, referendums.
**EU Promo**
Adds an EU referendum to the new slot.
**Screenshot**
CC @boffbowsh, @fofr, @daibach
=> Add new promo banner slot to the GOV.UK homepage

app/assets/stylesheets/views/_homepage.scss
Somewhat unintuitively `external-link-19` doens't apply all external link styling on it's own, it
also needs the `external-link-default` mixins to get the image.
=> External link icon wasn't rendering

app/views/root/index.html.erb
Add to the browse categories as a short term highlight.
As there are alreadys some register-to-vote links on the page
add a query param to distinguish which was used when looking
at traffic analytics.
=> Add register-to-vote callout to homepage

app/views/root/index.html.erb
According to our analytics teams this isn't super helpful and can
actually cause some problems once the links with source tracking
are copied/used elsewhere.
The source tracking is still needed for RTV links as we have 3 on the
same page, at least while we establish which perform better.
Tracking for the other popular links was added at the same time, but
isn't needed right now, so i'm removing it to avoid potential issues.
=> Remove source tracking on non RTV links

app/views/root/index.html.erb
Screen reader users have the option to navigate by jumping between anchor tags and reading out the content. "More information" does not provide a lot of context about what the link does.
=> Improve EU referendum homepage link copy for SRs.

app/presenters/travel_advice_index_presenter.rb, app/views/travel_advice/index.html.erb, test/integration/travel_advice_test.rb
Revert changes from alphagov/add-request-id-to-travel-advice-index, as we don't need to monitor the request id on the index page.
This reverts commit 994ac2ff27590d8a7d4c7d363565e56fd6f7b55e, reversing
changes made to 869f334f3289e5841cc89e8826fd4a5712527509.
=> Revert 'add request id to travel advice index'

app/assets/javascripts/modules/track-click.js, app/presenters/publication_presenter.rb, app/views/root/completed_transaction.html.erb, test/integration/completed_transaction_rendering_test.rb, test/javascripts/unit/modules/track-click.spec.js
For: https://trello.com/c/dXgKpUBZ/340-register-to-vote-promotion-on-done-pages-3
In publisher we allow choosing the organ donation promo or the register to vote promo.  This PR changes frontend to understand this choice and show the appropriate promo.  It has to handle two ways of an artefact storing that choice, as seen in https://github.com/alphagov/govuk_content_models/pull/374 and https://github.com/alphagov/publisher/pull/468.
=> Add register to vote done page promotion

lib/data/authorities.json
- Our upgrade of MapIt meant that these GSS codes changed.
(Trello: https://trello.com/c/iVFolVCb/376-gss-code-fixes-3.)
=> Update GSS codes for Northumberland, East Herts and Gateshead councils

app/views/root/index.html.erb
We've seen some issues with users mistakenly thinking they need to register
for the referendum specifically. Be clearer.
=> Make register-to-vote callout copy clearer

app/views/root/index.html.erb, test/integration/homepage_test.rb
* Add basic home page integration test
* Takes into account 15 min cache time to coincide with the 4pm cut-off for the global banner
=> Hide EU referendum banner after 4pm 26 May (accounting for cache time)

app/views/root/_transaction_additional_information_single.html.erb, test/integration/transaction_rendering_test.rb
Transactions have blocks of text that follow the main content. The main content has a `<h1>` level header already, and HTML5 limits the total suggested number of those to just 1.
The styling for `<h1>`s inside the transactional blocks are all overriden to look almost identical to `<h2>`s anyway, so it seems like they should have been `<h2>`s to begin with.
Will affect pages such as http://frontend.dev.gov.uk/register-to-vote.
=> Change <h1> to <h2> for transaction additional info block

app/views/root/completed_transaction.html.erb
- A while ago (#901 and #925), we added some text about organ donation
in Wales being opt-out, then removed it because the wording was
confusing. This is different wording, as requested in
https://govuk.zendesk.com/agent/tickets/1333304.
=> Update the organ donation registration text with info about Wales

README.md, config/initializers/mapit.rb
As we now have our own mapit app running as part of the development stack, we can stop making requests to mysociety's mapit.
When running `bowl frontend` in the dev VM, Mapit will need to be started manually. A PR is incoming for making dev Mapit a dependency of Imminence (which is already started by `bowl frontend`)
For https://trello.com/c/T1Md03fc/381-use-our-mapit-in-dev-consistently
=> Remove calls to mysociety mapit

app/assets/stylesheets/views/_homepage.scss, app/views/root/index.html.erb, test/integration/homepage_test.rb
__Deploy after May 26 4pm__
https://trello.com/c/npd5H4IW/405-sitewide-banner-remove-supporting-banner-code
Reverts PRs #936 #952 #938
We don’t intend to use this again soon.
=> [Do not merge] Remove banner promo slot from homepage

lib/tasks/publishing_api.rake
The `/help` page is currently in panopticon, rummager but not in publishing-api. It should be so that we can tag it.
The title/description come from [panopticon.rake](https://github.com/alphagov/frontend/blob/1c7cae6c0ee6007b775eef397819c378c0c6215d/lib/tasks/panopticon.rake#L12-L17).
=> Add `/help` to the publishing-api

app/presenters/local_authority_presenter.rb, test/functional/local_transactions_controller_test.rb, test/functional/root_controller_test.rb, test/integration/local_transactions_test.rb, test/unit/presenters/local_authority_presenter_test.rb
- Stop falling back to the local authority contact URL if there's no homepage URL on local transaction result pages (this fallback isn't used in practice anyway)
- Delete all references to local authority contact details
See the [story](https://trello.com/c/asuAAsR6/399-delete-code-related-to-local-authority-contact-details) and individual commit messages for more details.
This is the first in a series of PRs to remove local authority contact details, and this one should be merged and deployed first.
=> Remove all references to local authority contact details

app/controllers/application_controller.rb
`register-to-vote` slug needs reduced cacheing to allow rate limiting.
=> Set cache expiry to 5 minutes

app/controllers/application_controller.rb
Reverts alphagov/frontend#964
This is no longer required
=> Revert "Set cache expiry to 5 minutes"

app/assets/stylesheets/views/_homepage.scss
The links surrounding the images on the homepage are `display: inline`. Different browsers treat this in different ways with our default focus styles. Most look really ugly; Chrome doesn’t show anything, which is why I assume it’s gone unnoticed. Making it `display: block` fixes this. Before / after screenshots:
Browser | Before | After
------- | ------ | -----
Chrome | ![chrome_before](https://cloud.githubusercontent.com/assets/7414/15993169/98f521b2-30d5-11e6-9689-7b34d79a6faa.jpg) | ![chrome_after](https://cloud.githubusercontent.com/assets/7414/15993167/98f1a578-30d5-11e6-9bd9-687137e3ec3a.jpg)
Firefox | ![firefox_before](https://cloud.githubusercontent.com/assets/7414/15993172/98fb2fee-30d5-11e6-8b3f-ba5b83d0c2de.jpg) | ![firefox_after](https://cloud.githubusercontent.com/assets/7414/ …
=> Fix focus outlines on homepage images

app/helpers/completed_transaction_helper.rb, app/presenters/publication_presenter.rb, test/integration/completed_transaction_rendering_test.rb
There were two api's relating to promotion data. This removes one
leaving the single api from govuk_content_models.
Corresponding PR's:
https://github.com/alphagov/govuk_content_models/pull/387
https://github.com/alphagov/publisher/pull/484
https://github.com/alphagov/govuk_content_api/pull/248
[Trello card](https://trello.com/c/QEjTaHBW/408-clean-up-legacy-promo-storage)
=> Remove legacy organ donor promotion code

app/models/search_parameters.rb, test/unit/models/search_parameters_test.rb
This disables the spelling suggestion feature.
In the last couple of weeks we've seen a couple of instances where elasticsearch's spelling suggester returns an unfortunate replacement for a valid search term (for example, "chillos" for "chilcot"). With a ministerial reshuffle imminent, we'd like to avoid embarrassing suggestions. When we know all the names of new cabinet members, we'll add those to the ignore list in rummager, which will make sure that the names won't get corrected.
The root cause of this issue is that elasticsearch suggestion feature doesn't work well with the way we use it. I'll do a write up in rummager about that.
=> Temporarily disable spelling suggestions

app/views/root/index.html.erb
Here I have replaced the /manage-your-tax-credits path with /renewing-your-tax-credits-claim.
This affects only the url on the promo image.
=> Cosmetic change: renewing-your-tax-credits-claim

app/models/search_parameters.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_block.mustache, app/views/search/_search_field.html.erb, test/functional/search_controller_test.rb
The finder on the search results page is normally shown closed, unless at least one filter has been selected, in which case it is shown open. This adds a search parameter that forces the finder to be shown open even if no filters are selected. If the parameter is not present, then the logic on whether or not to display the finder reverts to the previous behaviour.
This feature has been added to allow searches originating from Whitehall (and possibly other applications in future) to always display the finder.
Trello: https://trello.com/c/t9R5QDCf/42-when-a-search-happens-from-whitehall-content-open-the-organisation-filter-by-default
=> Add search parameter to display the finder as open

app/models/search_parameters.rb, app/presenters/search_results_presenter.rb, app/views/search/_results_block.mustache, app/views/search/_search_field.html.erb, test/functional/search_controller_test.rb
In https://github.com/alphagov/frontend/pull/984, the `show_filter_organisations` search parameter was added. The naming of this parameter may cause difficulties with using Google Analytics since the name is too close to `filter_organisations`. Therefore, the name has been changed to `show_organisations_filter`.
Trello: https://trello.com/c/t9R5QDCf/42-when-a-search-happens-from-whitehall-content-open-the-organisation-filter-by-default
=> Change show_filter_organisations to show_organisations_filter

Gemfile, Gemfile.lock, app/controllers/root_controller.rb, config/initializers/local_links_manager.rb, lib/frontend.rb, test/functional/local_transactions_controller_test.rb, test/functional/root_controller_test.rb, test/integration/local_transactions_test.rb
We don't want to use content api for this because local links manager is the new canonical source of link data.
Requires https://github.com/alphagov/gds-api-adapters/pull/542 so the tests will fail on jenkins until we merge that and bump it in the gemfile here.
Note: PR should only be merged/deployed on Wednesday 03/08/2016 after we mention it at tech lead standup and to give us a chance to do any other sort of communication.
=> Fetch links for local transactions from local links manager api

app/views/root/completed_transaction.html.erb
The rails API for defining data attributes on a tag doesn't walk through nested
hashes so if we want:
<a href="http://hi.com" data-nested-attributes="please">Hi</a>
we might expect to be able to write:
link_to 'Hi', 'http://hi.com/', data: { nested: { attributes: 'please' } }
but that doesn't work, and would instead produce:
<a href="http://hi.com" data-nested="{attributes: \"please\"}">Hi</a>
Which is obviously wrong.  It will however translate underscores to dashes so we
are able to use ruby symbols as follows:
link_to 'Hi', 'http://hi.com/', data: { nested_attributes: 'please' }
and this generates what we want.
I don't think any documents actually use the register to vote promo so it's unlikely this has ever broken in production, but this acts as an example of how to set data …
=> Use correct rails api for data attributes on register to vote promo

app/views/root/index.html.erb
As per https://govuk.zendesk.com/agent/tickets/1380377, the number of
Ministerial departments should now be 25, and the number of agencies and
public bodies should be 374.
=> Update department and agency numbers on homepage

Rakefile, lib/tasks/lint.rake
Inspired by similar setup in local-links-manager and specialist-publisher-rebuild. Allows for catching style violations before running the linter on Jenkins.
Strangely, when adding the default task last, govuk-lint-ruby does not get run. That's why the task is added before `load_tasks` is run, so that the linter runs first.
=> Add govuk-lint-ruby to Rakefile

app/models/search_parameters.rb, test/unit/models/search_parameters_test.rb
Reverts alphagov/frontend#975.
To be deployed after https://github.com/alphagov/rummager/pull/691.
https://trello.com/c/iDCoSabY/55-re-enable-search-suggestions
=> Re-enable spelling suggestions

app/views/application/_beta_label.erb, app/views/find_local_council/_base_page.html.erb, app/views/find_local_council/district_and_county_council.html.erb, app/views/find_local_council/index.html.erb, app/views/find_local_council/one_council.html.erb, test/integration/find_local_council_test.rb
For: https://trello.com/c/i3tw83rV/451-2-of-2-add-a-link-to-the-survey-on-the-beta-label-for-find-your-local-council-1
Note that this merges into the branch for #986.
=> Add survey links to find local council

app/helpers/place_helper.rb, app/views/find_local_council/district_and_county_council.html.erb, app/views/find_local_council/index.html.erb, app/views/find_local_council/one_council.html.erb, app/views/root/place.html.erb, test/integration/find_local_council_test.rb, test/integration/places_test.rb
We add Google Analytics tracking in the case that no results are returned from Imminence for a valid postcode. We add integration tests to ensure that the correct GA parameters are being set.
We also update the track category for Find local council with the correct value. It was previously set to 'placeSearch' which in the context of this app refers to the 'find-my-nearest' format.
For https://trello.com/c/ZWX0Apjj/469-add-ga-tracking-in-frontend-for-when-find-my-nearest-shows-no-results-2
Paired with @surminus
=> Add GA tracking for no results shown for place format

app/controllers/find_local_council_controller.rb, test/functional/find_local_council_controller_test.rb
We set the cache headers to expire after 30 mins. This follows the same approach as other controllers in the Frontend app.
For https://trello.com/c/kdgRAWRp/477-allow-find-your-local-council-responses-to-be-cached-haven-t-talked-about-in-planning
Paired with @surminus
=> Set cache headers for find local council

app/controllers/application_controller.rb, app/controllers/find_local_council_controller.rb, app/controllers/random_controller.rb, app/presenters/travel_advice_index_presenter.rb, config/environments/production.rb, config/initializers/gds_api.rb, config/initializers/imminence.rb, config/initializers/local_links_manager.rb, config/initializers/mapit.rb, config/initializers/rummager.rb, config/initializers/website_root.rb, lib/frontend.rb, lib/tasks/rummager.rake, test/functional/application_controller_test.rb, test/integration/content_api_response_test.rb, test/integration/find_local_council_test.rb, test/integration/page_rendering_test.rb, test/integration_test_helper.rb, test/support/content_api_helpers.rb
For: https://trello.com/c/R4wibPPq/478-make-find-your-local-council-breadcrumbs-and-related-links-link-to-current-environment-2
We cache `Plek.new.website_root` in `Frontend.govuk_website_root` and use that when building the links.  Also we tidy up all the other places using Plek.new.website_root to use the new thing.  Some extra notes in the commits if you're interested.
=> Fix hardcoded links to understand deployed environment

app/assets/javascripts/frontend.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_error-summary.scss, app/views/application/_location_form.html.erb, test/integration/find_local_council_test.rb
A small number of changes to meet accessibility standards as per an informal review. They are all related to the location form. While the review was specifically for the new 'Find local council' page, the location form partial is also used by the licence, place and local transaction formats so those formats will benefit from the changes as well.
See commits for individual updates.
For https://trello.com/c/ldjGC28P/476-fix-the-things-from-the-accessibility-review
=> Add accessibility changes to find local council

app/assets/stylesheets/views/_homepage.scss
The focus style looked a bit off in Firefox (Robin mentioned it), here is a fix :)
Before:
After:
Checked in: Chrome 52 & Firefox 48
=> Correcting weird focus style in firefox

Gemfile, Gemfile.lock, app/controllers/random_controller.rb, lib/search_api.rb, test/functional/random_controller_test.rb, test/integration/search_test.rb, test/unit/search_api_test.rb
This commit changes all instances of unified_search to search when using the GDS API Adapters to access rummager. This provides consistency between the internal and external APIs in terms of naming.
Trello: https://trello.com/c/cj8UX2jX
=> Change all instances of unified_search to search

app/controllers/root_controller.rb, lib/licence_location_identifier.rb, lib/location_identifier.rb, test/unit/licence_location_identifier_test.rb
For https://trello.com/c/qmFcJTJo/474-investigate-how-licences-use-localservices-3
In the story linked to above, we identified 9 licences, where users with postcodes within counties would be incorrectly sent to their district council rather than their county council. The tier data for these Licences was stored in LocalService model entries in the content api, but these have recently been removed. The tier data will soon live inside the Licensing application (Licencify), at which point this fix can be reverted (once Frontend is made to interpret the tier information).
=> Add hardcoded fix for county tier licences

app/controllers/root_controller.rb, app/helpers/place_helper.rb, app/views/root/place.html.erb, config/locales/en.yml, test/integration/places_test.rb
- Currently when a user searches for a 'find-my-nearest' place and gets
no results, they see the "Sorry, no results were found near you."
message underneath the location form.
- This fixes that by making an error message in the same style as the
local transactions ones: red box above the postcode input.
- The existing validPostcodeNoLocation message wasn't that informative,
so make it tell the user more about what the error actually was.
Trello: https://trello.com/c/YNKOcWqr/485-show-no-results-alert-above-location-search-form-for-find-my-nearest-2
=> Find my nearest: show 'no results' alert above the postcode form

app/models/location_error.rb, config/locales/en.yml, test/integration/places_test.rb
- Mark thought this was confusing when we were going through the result
of #1006, so simplify it. This makes it even more consistent with
local transactions.
=> The validPostcodeNoLocation error message shouldn't mention PO Boxes

app/assets/javascripts/all.js, app/assets/javascripts/modules/ukvi-ab-test-september-2016.js
This commit sets up AB test for the following ukvi page sections:
* /eea-registration-certificate/apply
* /eea-registration-certificate/permanent-residence
Cohorts across the aforementioned ukvi pages section fall under the following.
* original (with a 90% weighting)
* applyTextAndLink (with a 10% weighting)
The isSection checks that the current path matches the the given path that has
been defined for A/B testing.
It basically does an (string based) equality check.
The AddtoApplySection and AddtoPermanentResidenceSection function inserts
the given html before the respectively identified html tags.
*NB: Factcheck was carried out on integration after deploying just this branch.*
=> Add (UKVI) AB testing setup for September 2016 session

app/views/campaign/uk_welcomes.erb, app/views/help/index.html.erb, app/views/root/tour.html.erb, app/views/search/index.html.erb, app/views/search/no_search_term.html.erb
This commit adds meta description tags to all pages that are current missing them, the contents of which are set to either the title/description associated with the page, or a static description. This adds descriptions to external search engine results when the pages are re-indexed.
Trello: https://trello.com/c/bbAwFAQ1/108-add-meta-descriptions-to-pages-missing-them
=> Add meta descriptions

app/controllers/find_local_council_controller.rb, app/controllers/root_controller.rb, config/initializers/gds_api_adapters.rb, lib/authority_lookup.rb, test/functional/search_controller_test.rb
This opts-in to the new recommended behaviour of gds-api-adapters, which always raises a `GdsApi::HTTPNotFound` exception when it encounters a 404 or 410 - instead of returning nil.
=> Use new GDS API Adapters behaviour

app/assets/javascripts/modules/ukvi-ab-test-september-2016.js
Trello: [card 1](https://trello.com/c/S1Q1fvMy/344-change-proportion-of-users-who-see-online-route-for-eea-forms), [card 2](https://trello.com/c/coReIsGY/334-a-b-testing-for-prove-your-right-to-live-in-the-uk-as-an-eu-citizen)
As a follow-up work of #1009, we have been asked to increase the cohort 
weight from 10% to 40%, so we increase the proportion of users who see 
online route for EEA forms.
=> Update cohort weight in UK Visa A/B test

app/controllers/root_controller.rb, app/controllers/travel_advice_controller.rb, config/initializers/gds_api.rb, lib/artefact_retriever.rb, lib/frontend.rb, test/integration/travel_advice_test.rb, test/unit/artefact_retriever_test.rb
In response to the comments in https://github.com/alphagov/frontend/pull/1012, we had a look through the app to determine if any more work needed to be done relating to the change in gds-api-adapters to raise exceptions for 404s and 410s. 
We looked at imminence, mapit, content-api and content-store. We could not find any problems and think that the behaviour of the code should stay unchanged. We made some minor updates as we went along. These are mostly changes to rescue the HTTPGone and HTTPNotFound exceptions explicitly.
Paired with @sihugh
=> Clean up gds api adapter exception handling

app/views/application/_beta_label.erb, app/views/find_local_council/_base_page.html.erb, app/views/find_local_council/district_and_county_council.html.erb, app/views/find_local_council/index.html.erb, app/views/find_local_council/one_council.html.erb, test/integration/find_local_council_test.rb
- Removed the beta labels from the Find Your Local Council Pages as part of this [Trello Card.](https://trello.com/c/csPx42xJ/515-remove-the-beta-label-from-find-your-local-council-pages-1)
=> Remove Beta label from Find Local Council pages

config/locales/cy.yml, test/integration/transaction_rendering_test.rb
This commit updates the welsh translation (Cod post, Tref neu lle) on this page http://www.gov.uk/chwilio-am-swydd.
i.e
From
Cod post, Tref neu lle
To
Cod post, tref neu lle
=> Update welsh form label in locale (cy.yml

README.md, app/controllers/travel_advice_controller.rb, app/presenters/travel_advice_country_presenter.rb, app/views/travel_advice/_country_summary.html.erb, app/views/travel_advice/_travel_advice_navigation.html.erb, app/views/travel_advice/country.atom.builder, app/views/travel_advice/country.html+print.erb, app/views/travel_advice/country.html.erb, app/views/travel_advice/index.html.erb, config/routes.rb, test/fixtures/foreign-travel-advice/afghanistan.json, test/fixtures/foreign-travel-advice/luxembourg.json, test/fixtures/foreign-travel-advice/turks-and-caicos-islands.json, test/functional/travel_advice_controller_test.rb, test/integration/travel_advice_atom_test.rb, test/integration/travel_advice_test.rb, test/unit/presenters/travel_advice_country_presenter_test.rb
Reverts alphagov/frontend#1020.
Apparently FCO is still using these pages via `private-frontend`.
cc @danielroseman @jennyd @boffbowsh
=> Revert "Remove travel advice country page code"

app/controllers/application_controller.rb, lib/artefact_retriever.rb
The optional location param was only previously used to specify
longitude and latitude for imminence request in content_api.
We [have since removed that functionality](https://github.com/alphagov/govuk_content_api/pull/268) so the location param
is not needed here anymore.
=> Remove optional location param from #fetch_artefact

app/controllers/homepage_controller.rb, app/controllers/search_controller.rb
`set_slimmer_dummy_artefact` was used to configure slimmer to send appropriate analytics tags. This has long ago been replaced by the slimmer headers (and will be replaced again by the analytics component from govuk-components).
Removing this has no effect on the analytics tags.
=> Remove set_slimmer_dummy_artefact usage

app/models/search_parameters.rb, app/presenters/search_result.rb, app/presenters/search_results_presenter.rb, test/javascripts/unit/live-search-test.js, test/unit/models/search_parameters_test.rb, test/unit/presenters/search_result_test.rb, test/unit/presenters/search_results_presenter_test.rb
This feature wasn't being used by anyone and should be deleted. In the
future we want to move search out of frontend, so deleting unused code
helps reducing the amount of code related to search.
I still left `specialist_sectors in the list of rummager fields [here](https://github.com/alphagov/frontend/blob/master/app/models/search_parameters.rb#L79).
Trello:
https://trello.com/c/wLlCUvi6/229-remove-facetting-by-specialist-sector-in-frontend-search
=> Delete faceting by specialist sectors

app/assets/javascripts/live-search.js, test/javascripts/unit/live-search-test.js
Currently the message 'You can only apply 15 filters at once' appears when you try to select the 15th filter, so you can actually only have 14 filters applied.
Fixes https://trello.com/c/CB6sSZ4V
=> Fix maximum number of filters

README.md, app/controllers/application_controller.rb, app/controllers/find_local_council_controller.rb, app/controllers/help_controller.rb, app/controllers/root_controller.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/travel_advice_controller.rb, app/views/layouts/application.html.erb, test/functional/campaign_controller_test.rb, test/functional/root_controller_test.rb, test/functional/travel_advice_controller_test.rb
The Content Store will be used to render meta tags instead of the Content API. This commit changes meta tags to be rendered with data from the Content Store.
Trello: https://trello.com/c/FBmZSc1J/177-render-meta-tags-from-content-store-in-frontend
=> Replace Content API with Content Store for meta tags

app/views/root/_base_page.html.erb, app/views/root/business_support.html.erb
Business support pages (like https://www.gov.uk/apprenticeshipsni) explicitly don't have a sidebar. This is redundant, because the sidebar won't show anyway when there's nothing to show (like related mainstream pages and external links).
I haven't found any good reason in the commit history why this page is a special case, so I think it would make sense to remove it. This means that if we'd ever want something in the sidebar here we could make it so.
🚫❄️
=> Remove special case for business support pages

app/controllers/application_controller.rb, app/controllers/find_local_council_controller.rb, app/controllers/root_controller.rb, test/integration/travel_advice_test.rb
Currently in most controllers we raise an error (`GdsApi::HTTPNotFound`) when a page isn't found in the content store.
This was done so that we would know when we by mistake request the wrong thing from the content store.
We made an exception for the rootcontroller, which is also used by private-frontend, which displays unpublished content which may or may not have a content item.
This commit now implements that behaviour everywhere, so that we're more resilient to missing content items. In particular this fixes a bug on private-frontend that prevents people from previewing simple smart
answers (https://govuk.zendesk.com/agent/tickets/1448901).
cc @jennyd
=> Don't raise error when content item is missing

lib/tasks/publishing_api.rake
The related links for /find-local-council are currently hardcoded because the page doesn't exist in the content-api.
From https://github.com/alphagov/frontend/pull/1031 we will start using the content-store to render the sidebar with related links. This means we can set the links in the content-store and don't have to hard code it.
Of course managing the links here is also a form of hardcoding. Once we have an application that manages all related links (probably content-tagger) we'll remove it here.
cc @rubenarakelyan @jennyd
=> Set the related link for /find-local-council

Gemfile, Gemfile.lock, app/assets/stylesheets/helpers/_govuk-component-helpers.scss, app/controllers/find_local_council_controller.rb, app/views/find_local_council/_base_page.html.erb, app/views/layouts/application.html.erb, app/views/root/_base_page.html.erb, app/views/travel_advice/country.html.erb, test/integration/answer_rendering_test.rb, test/integration/find_local_council_test.rb, test/integration/guide_rendering_test.rb, test/integration/help_pages_test.rb, test/integration/programme_rendering_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_rendering_test.rb, test/integration_test_helper.rb
The Content Store will be used to render related items instead of the Content API.
Trello: https://trello.com/c/jU26h0TG/178-render-sidebar-from-content-store-in-frontend
=> Replace Content API with Content Store for related items

app/views/root/local_transaction.html.erb, test/integration/local_transactions_test.rb
This was previously removed by accident. This commit adds tracking for when an local interaction link is missing. For missing links, the default behaviour is to link to the local authority homepage instead. We also track if there is no homepage url available (which should be extremely rare).
I checked the GA behaviour with Tim and he okayed it.
For https://trello.com/c/q5HKVhFR/536-fix-ga-tracking-for-local-transactions-for-missing-link-results-2
=> Add tracking for missing local interaction link

app/controllers/application_controller.rb, app/controllers/campaign_controller.rb, app/controllers/root_controller.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/travel_advice_controller.rb, test/functional/root_controller_test.rb, test/functional/simple_smart_answers_controller_test.rb, test/functional/travel_advice_controller_test.rb
We no longer need to set the artefact, because slimmer is not used for the related links anymore since https://github.com/alphagov/frontend/pull/1031.
https://trello.com/c/95kYhQcM
=> Remove old slimmer "artefact" configuration

app/views/root/local_transaction.html.erb, test/integration/local_transactions_test.rb
Changing to 'userAlerts' from 'user_alerts' for tracking missing local interaction links as that matches the other alerts in the app.
=> Change GA category to userAlerts

app/controllers/help_controller.rb, app/views/help/show.html.erb, app/views/shared/_base_page.html.erb, app/views/shared/_publication_metadata.html.erb, config/routes.rb, lib/artefact_retriever_factory.rb, lib/format_routing_constraint.rb, test/unit/format_routing_constraint_test.rb
The goal of the refactoring is to speed up and de-risk the process of migrating formats to publishing-api. It would be challenging to unroll all the logic in the `RootController#publication` catch-all handler so instead we re-route requests on a per-format basis. By enabling us to write idiomatic controllers that wrap the rendering cycle of each format, we should drive out the specific rendering requirements for each format making it easier to migrate them to new content-store schemas when the time comes.
=> Pre-Migration Frontend Refactor - Help format

app/views/homepage/index.html.erb
[Trello card](https://trello.com/c/l5HRa2Iu/298-update-popular-on-gov-uk-homepage-links)
- Removed 'Employment and support allowance' link
- Added 'Personal tax accounts' link
After changes:
=> Change homepage popular links

app/views/homepage/index.html.erb
This makes it consistent with the other links.
=> Correct link to "Personal tax account"

app/controllers/answer_controller.rb, app/controllers/help_controller.rb, test/integration/answer_test.rb
- The PR was merged before we got the chance to deal with https://github.com/alphagov/frontend/pull/1043#discussion_r88240341 and https://github.com/alphagov/frontend/pull/1043#discussion_r88241206. They're
tiny, but so they don't hang around forever, I'm fixing them now.
- The `answer_controller.rb` change was a copy/paste, so fix it at source as well in `help_controller.rb`.
=> Deal with some style comments hanging over from PR 1043

app/controllers/root_controller.rb, app/controllers/video_controller.rb, app/helpers/application_helper.rb, app/views/video/show.html.erb, config/routes.rb, test/fixtures/test-video.json, test/functional/video_controller_test.rb, test/integration/answer_test.rb, test/integration/help_pages_test.rb, test/integration/page_rendering_test.rb, test/integration/video_test.rb, test/unit/helpers/application_helper_test.rb
This PR moves video pages to their own controller, following the same pattern as Help pages (https://github.com/alphagov/frontend/pull/1036).
The first two commits do a bit of clean up for things that we came across while implementing this. Have a look at the commit messages for more details.
=> Move video pages to own controller

app/controllers/simple_smart_answers_controller.rb, app/views/simple_smart_answers/show.html.erb, config/routes.rb, test/functional/simple_smart_answers_controller_test.rb, test/integration/simple_smart_answers_test.rb, test/routing/simple_smart_answers_routing_test.rb
This PR moves simple smart answer start pages to their own controller, following the same pattern as Help pages (https://github.com/alphagov/frontend/pull/1036).
The first commit does a bit of clean up for things that we came across while implementing this. Have a look at the commit message for more details.
=> Move smart answer start pages to own controller

app/presenters/travel_advice_index_presenter.rb, test/integration/travel_advice_atom_test.rb, test/integration/travel_advice_test.rb, test/unit/presenters/travel_advice_index_presenter_test.rb
The pre-exisitng sort method did not take utf-8 characters such as
a-tilde into account. This commit uses a method [1] to sort by utf-8.
1. http://stackoverflow.com/a/17172055
Note that this PR follows updates to the associated `gov_uk_content_schemas` test fixture (https://github.com/alphagov/govuk-content-schemas/pull/439)
=> Sort countries by utf-8

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_govuk-component-helpers.scss, app/controllers/application_controller.rb, test/test_helper.rb
Finding Things has been working on migrating related links, part of that
work was to replace the breadcrumbs on a number of different frontend
applications like:
- calendars
- calculators
- business-support-finder
- frontend
- licence-finder
- smart-answers
That work has already been done, this commit aims to clean up things we
have missed during the migration.
This includes
- upgrading Slimmer to 10.0.0
- deletion of govuk-component-helpers.scss
- rename [Slimmer::SharedTemplates to Slimmer::GovukComponents](https://github.com/alphagov/slimmer/pull/173)
Trello: https://trello.com/c/5Utjs9qw/300-related-links-cleanup
=> Bump Slimmer and update code

app/assets/stylesheets/views/_search.scss, app/assets/stylesheets/views/_tour.scss
As part of https://github.com/alphagov/govuk_frontend_toolkit/pull/293
we removed external link icon styles as there is not an obvious
user need.
However frontend still has spacing with these icons in mind.
=> Remove deprecated rel="external" styling

app/controllers/root_controller.rb, config/routes.rb, test/functional/guide_controller_test.rb, test/functional/programme_controller_test.rb, test/functional/root_controller_test.rb, test/integration/answer_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/video_test.rb
This PR aims to fix the following issues:
- more comprehensive test coverage for 'parts' for Guides and Programmes
- avoid ['refactored' formats](https://trello.com/c/phpe3PAO/546-refactor-frontend-overview-card-5) accidentally being handled by RootController 
- 500 errors for POST requests that actually 'GET' content ([as seen in Errbit](https://errbit.publishing.service.gov.uk/apps/53611a4b0da1151271001055/problems/583454d5657863164c0d0000))
- update RootController tests to no longer use refactored formats as test data
- reinstate functionality for certain formats to reroute to the base slug when a 'part' is requested
=> Fix error handling for unsupported routes

app/controllers/completed_transaction_controller.rb, app/controllers/root_controller.rb, app/views/completed_transaction/legacy_completed_transaction.html.erb, app/views/completed_transaction/show.html.erb, config/routes.rb, test/functional/completed_transaction_controller_test.rb, test/functional/root_controller_test.rb, test/functional/transaction_controller_test.rb, test/integration/completed_transaction_test.rb, test/integration/page_rendering_test.rb
This PR moves completed transaction pages to their own controller, following the same pattern as Help pages (#1036).
We also move legacy completed transactions to the completed transaction controller as they are similar.
Paired with @davidbasalla
=> Move completed transaction to controller

app/controllers/travel_advice_controller.rb, test/functional/travel_advice_controller_test.rb, test/integration/travel_advice_test.rb
As part of refactoring formats out of the RootController, we make some small changes to the travel advice format. We update the controller to redirect for api requests via a before filter, so that it matches the other controllers.
We also update the integration test context descriptions to be more intention revealing. Previously there were two contexts with descriptions "a single country page preview" and "previewing a country page". It was difficult to understand the difference at first glance. Our confusion was in part due to the fact that Frontend is only used to render preview travel advice content. Actual content is already being rendered through multipage frontend. 
See https://www.gov.uk/foreign-travel-advice/afghanistan
=> Update travel advice controller and tests

app/controllers/answer_controller.rb, app/controllers/business_support_controller.rb, app/controllers/campaign_controller.rb, app/controllers/guide_controller.rb, app/controllers/help_controller.rb, app/controllers/root_controller.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/transaction_controller.rb, app/controllers/video_controller.rb, app/views/business_support/show.html.erb, config/routes.rb, test/fixtures/business-support-example.json, test/functional/business_support_controller_test.rb, test/functional/root_controller_test.rb, test/integration/business_support_test.rb, test/integration/page_rendering_test.rb
This PR moves business support pages to their own controller, following the same pattern as Help pages (#1036).
=> Move business support to own controller

app/controllers/place_controller.rb, app/controllers/root_controller.rb, app/views/application/_location_form.html.erb, app/views/find_local_council/index.html.erb, app/views/licences/_introduction.html.erb, app/views/place/_option.html.erb, app/views/place/_option_report_child_abuse.html.erb, app/views/place/show.html.erb, app/views/root/local_transaction.html.erb, app/views/root/place.html.erb, config/routes.rb, test/functional/place_controller_test.rb, test/functional/root_controller_test.rb, test/integration/place_test.rb
This PR moves place/find-my-nearest pages to their own controller, following the same pattern as Help pages (#1036).
This is the first of the interactive formats so the controller is a bit more complex. Previously it supported GET and POST (for the LocationForm) requests, we've removed the POST as we're not updating any data.
=> Move places to separate controller

app/controllers/root_controller.rb, app/views/application/_location_form.html.erb, app/views/find_local_council/index.html.erb, app/views/licences/_introduction.html.erb, app/views/place/show.html.erb, app/views/root/local_transaction.html.erb, config/routes.rb, test/integration/place_test.rb
Previously we thought we could simplify the routing behaviour for postcode submission to be a GET request since we don't alter any data. However it's GOV.UK policy to not put confidential data such as postcodes into URLs as query parameters, so we need to revert to use a POST method. 
It's not ideal that the 'place#show' method now supports both GET and POST but it seems to be the most pragmatic solution at the moment.
=> Set postcode submit for place to be POST request

app/controllers/application_controller.rb, app/controllers/root_controller.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/travel_advice_controller.rb, test/functional/root_controller_test.rb, test/functional/travel_advice_controller_test.rb
There's no need for this anymore. The functionality was extracted into
a middleware component years ago. While there is an argument for some
way of improving the quality of URLs that get passed to upstream systems
this partial and confusing implementation isn't it.
=> Remove the `application_controller#validate_slug_param` method

Gemfile, Gemfile.lock, app/controllers/place_controller.rb, app/presenters/publication_presenter.rb, config/initializers/gds_api_adapters.rb, lib/format_routing_constraint.rb, test/functional/licence_location_test.rb, test/functional/local_transaction_controller_test.rb, test/unit/format_routing_constraint_test.rb
Reverts alphagov/frontend#1074
We're getting errors like https://errbit.publishing.service.gov.uk/apps/53611a4b0da1151271001055/problems/5852b2d86578632369530000 so we'll revert until we've had a chance to consider the problem properly.
=> Revert "Update GdsApiAdapters to 38.0.0"

config/routes.rb, test/integration/search_test.rb, test/integration/travel_advice_test.rb
Now the wildcard POST handler for the ex-RootController has been
removed, we can tidy up these bits.
As with any other un-configured route, Rails will respond with a
405 header if a user attempts to post to it.
=> Remove legacy route handlers

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/place_controller.rb, app/presenters/publication_presenter.rb, config/initializers/gds_api_adapters.rb, lib/format_routing_constraint.rb, test/functional/local_transaction_controller_test.rb, test/integration/error_handling_test.rb, test/support/content_api_helpers.rb, test/unit/format_routing_constraint_test.rb
Due to the unusual way in which this app parses URL fragments, it is
possible for it to construct an invalid URL for a backend resource.
Invalid URLs will be caught by the version of GdsApiAdapters referenced
here, and now the application controller can handle this case like any
of the other failure cases and return a cacheable 404.
=> Invalid URL fragment handling

Gemfile
It was well out of hand.  Nothing has changed here except for the order of the gems, which should now be sorted alphabetically.
=> Tidy up the Gemfile

app/controllers/search_controller.rb, config/initializers/rummager.rb, lib/search_api.rb, lib/services.rb, test/functional/search_controller_test.rb
In #1082 the `SearchApi` class was refactored. The internal `Searcher` class was inlined into `SearchApi`. However, we didn't realise that `SearchApi` isn't a normal class, but an object that is only instantiated in an initialiser.
This caused the instance variables to be persisted between requests, which in turn caused very odd behaviour, since the scoped search results would be remembered (but differently on different
machines/rails processes).
This PR makes a number of changes that fixes the issue will hopefully prevent it from happening again.
=> Fix bug with scoped search results

app/controllers/place_controller.rb
In our refactoring, we prevented this page from rendering correctly when
provided with a postcode in the query string. This change is to prevent
the page from erroring given same. As for any other unexpected query
string parameter, it will just ignore the provided info, rendering the
page as if the params were simply not there.
=> Fixes the NoMethodError: undefined method `places' error

lib/tasks/rummager.rake
In https://github.com/alphagov/frontend/pull/1091 we removed a rake task, but
unfortunately didn't find all the places it was called from.  This is hopefully
the last one.
=> Remove vestiges of panopticon:register

app/controllers/help_controller.rb, app/views/help/ab_testing.html.erb, config/application.rb, config/routes.rb, lib/tasks/publishing_api.rake, test/functional/help_controller_test.rb
Adds a new help page which acts as an example of an A/B test and provides a way to manually and automatically check that A/B testing is working. The main concern is that A/B testing cookies are being correctly converted to custom headers by the CDN.
This simple example gives us a way to check A/B testing before we create a real (and more complicated) A/B test of the navigation.
alphagov/smokey#222 adds regression tests for this page.
There are a couple of FIXMEs around the wording on the page which I need to update before this can be merged.
https://trello.com/c/23lOrO6h/308-create-a-test-page-for-a-b-testing
=> Add example page for A/B testing

app/views/help/ab_testing.html.erb, test/functional/help_controller_test.rb
This adds an easily-parsable tag to the page which specifies which A/B bucket the user is in. The plan is to read this in the govuk Chrome extension to make it easy for devs, testers and support staff to identify which bucket they're in and switch between them.
Requests which go through the CDN will also pick up a cookie identifying the A/B bucket, but on dev and integration (or when bypassing the CDN on staging and production) we need an extra marker like this meta tag.
Trello: https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments
Note that this is hard-coded into the example page for now, but the plan is to try to create a gem to make it simple to add all the A/B components to a page.
=> Add A/B test meta tag to A/B example page

Rakefile
`'ci/reporter/rake/rspec` is being required in rake tasks on production, but the gem is not included in the production gems (it's in `development, :test` groups).
https://deploy.staging.publishing.service.gov.uk/job/Deploy_App/2804/console
Previous attempt: https://github.com/alphagov/frontend/pull/1105
=> Only require ci_reporter in development and test

app/views/help/ab_testing.html.erb, test/functional/help_controller_test.rb
This makes the casing of `ABTest-Example` consistent with the cookie name set in `govuk-cdn-config`. These need to be consistent because the GOVUK Chrome extension uses the meta tag to update the cookie value, and cookie names are case-sensitive.
https://trello.com/c/jra1OClm/320-make-it-easy-to-test-experiments-in-non-prod-environments
=> Fix casing of A/B test meta tag

app/controllers/help_controller.rb, config/application.rb
Move the `Vary: GOVUK-ABTest-Example` header from every response to just the A/B testing page, since this is the only page with variants that should be cached separately.
This will save Varnish and the CDN from having to cache _every_ frontend page twice.
As far as I know, this is isn't currently causing a problem, but it's such a small change that it seemed worth just doing. It might be more helpful in the future when there are more A/B tests going on, since each `Vary` header on a page multiplies the cache size for that page.
=> Prevent duplicate caching of non-AB-tested pages

app/views/help/index.html.erb
In static we removed the CSS for the old sidebar, but the help page index was stilling using it:
https://www.gov.uk/help
It should have looked like this:
http://webarchive.nationalarchives.gov.uk/20151109153250/https://www.gov.uk/help
Using the govuk-component fixes this.
Before:
After:
Trello: https://trello.com/c/QFUjiqHs/449-fix-related-links-for-help-pages
Paired with @klssmith @Davidslv 
We've left out the "return to top" link as it wasn't there beforehand, and it doesn't seem to serve any purpose.
=> Use govuk-components for help page related links

app/views/help/ab_testing.html.erb, test/functional/help_controller_test.rb
Reformat the meta tag which specifies user's bucket for the A/B example test so that it matches the format expected by the analytics JavaScript code in `static` (see alphagov/static#888)
The previous format was only parsed by `govuk-toolkit-chrome`, but that code has not been released yet so it's safe to change this tag and then update the Chrome plugin.
Trello: https://trello.com/c/g9OyC7Pn/310-tell-google-analytics-about-a-b-tests
Once this is merged:
=> Make A/B test meta tag consistent with Google Analytics JS

config/routes.rb
The segment constraint `slug: %r{help/.+}` was matching on the entire
path including the .json format identifier. This caused an issue where
JSON requests were being interpreted as if for HTML content and would
404 as the slug would not be available in the content-api.
=> Fix a bug in the routing of Help Page JSON requests

lib/tasks/rummager.rake
When deploying to draft-frontend we do not want errors raised because Rummager is missing to stop deployments.
https://trello.com/c/TOdNOEDQ/627-migrate-help-page-use-draft-stack-for-preview-2-3-3
=> Catch errors caused by missing Rummager in draft stack

Jenkinsfile
These stages don't actually do anything on branch builds, but they appear in the branch build history, which is confusing.
=> Skip tag and deployment Jenkins stages in branch builds

Gemfile, Gemfile.lock
So we can take advantage of the JWT auth bypass for draft content
we need to bump the version of the gds-api-adapters gem.
=> Upgrade API Adapters version

app/controllers/application_controller.rb, test/functional/transaction_controller_test.rb
The content schema locales include some locales which are not supported by Rails by default, such as `tk` and `zh`. This triggers an exception in ApplicationController when it attempts to set the application locale from the content locale.
I think this is an edge case of #1117, which fixed the way the application locale was extracted from the content.
This was causing flaky tests when a random content item was generated. For example, help_controller_test would fail about 20% of the time when a content item with an unsupported language was generated. Example seed: 47089.
This fix checks whether the content's locale is in the list locales supported by the Rails application, and falls back to English if not.
A better long-term fix might be to align the locales in govuk-content-schemas with …
=> Fall back to English when content is in an unsupported locale

app/views/layouts/application.html.erb, test/integration/homepage_test.rb
The new functionality introduced by the new navigation adds breadcrumbs
to every page. This shouldn't be the case for the home page, though.
This makes sure no markup is added to the homepage.
=> Don't show breadcrumbs in home page

app/controllers/help_controller.rb, test/functional/help_controller_test.rb
The name of the example needs to match the CDN cookie config exactly, including casing.
The A/B test name used to be capitalized by the A/B test gem, but this produced inconsistent names with multi-word tests like 'EducationNavigation' so it was removed.
=> Fix casing of example A/B test name

lib/content_format_inspector.rb
Errors thrown by the `GdsApiAdaptors` are being caught and rethrown by the `ArtefactRetriever` class. This meant that the error handling code in `ContentFormatInspector` was missing these errors, and they failed to be handled gracefully.
Ref: https://errbit.publishing.service.gov.uk/apps/53611a4b0da1151271001055/problems/58a1cf9a6578630d22460000
=> Handle content-api errors

app/controllers/answer_controller.rb, app/controllers/help_controller.rb, lib/content_format_inspector.rb, test/functional/answer_controller_test.rb, test/integration/answer_test.rb, test/integration/help_test.rb
We removed the ability to render draft editions in `private-frontend` for Answers and HelpPage content. Now we have a working draft-stack, this seems redundant.
=> Frontend can now render migrated Answers from the content-store

app/controllers/answer_controller.rb, app/controllers/application_controller.rb, app/controllers/help_controller.rb, app/controllers/local_transaction_controller.rb, app/presenters/answer_presenter.rb, app/presenters/content_item_presenter.rb, app/presenters/help_page_presenter.rb, app/presenters/local_transaction_presenter.rb, lib/content_format_inspector.rb, lib/local_transaction_location_identifier.rb, test/functional/local_transaction_controller_test.rb, test/integration/local_transactions_test.rb, test/support/content_store_helpers.rb, test/unit/local_transaction_location_identifier_test.rb, test/unit/presenters/answer_presenter_test.rb, test/unit/presenters/content_item_presenter_test.rb, test/unit/presenters/help_page_presenter_test.rb, test/unit/presenters/local_transaction_presenter_test.rb
Switch frontend to render local transactions from the content store (instead of content api).
Should only be merged once https://github.com/alphagov/publisher/pull/560 has been merged and all LocalTransaction content has been republished
=> Render migrated local transaction

app/controllers/concerns/education_navigation_ab_testable.rb, test/functional/answer_controller_test.rb, test/functional/guide_controller_test.rb, test/functional/licence_controller_test.rb, test/functional/local_transaction_controller_test.rb, test/functional/programme_controller_test.rb, test/functional/simple_smart_answers_controller_test.rb, test/functional/transaction_controller_test.rb
The name of the A/B test must match the cookie name exactly. The name of this test is defined as EducationNavigation in alphagov/govuk-cdn-config#17.
=> Fix casing of A/B test name

lib/content_format_inspector.rb
Errbit reports 100s of content-store 404s and timeouts a day, through the Frontend app. It's noisy and there's not much we can do about them, so let's not log these errors, eh.
=> Stop logging every. single. network. error. to Errbit

app/controllers/application_controller.rb, app/views/application/_draft_fields.html.erb, app/views/application/_location_form.html.erb, test/functional/local_transaction_controller_test.rb, test/support/location_helpers.rb
For content that is in fact check a JWT token is generated and the authentication proxy will pass that through with the request to the frontend.
This token needs to be carried through on the get and post requests for those formats that are a little more interactive.
The authentication proxy no longer strips the token itself as a result of [this PR](https://github.com/alphagov/authenticating-proxy/pull/21)
https://trello.com/c/RoHFOwid/646-enable-postcode-search-for-local-transactions-in-factcheck
=> Set token in default url options for fact check content

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/slimmer.rb
This bumps slimmer to make it use the rails cache and send a user agent:
- https://github.com/alphagov/slimmer/pull/184
- https://github.com/alphagov/slimmer/pull/183
It will probably not have much effect on this app, because the cache is configured correctly here.
https://trello.com/c/D9HmkJwI
=> Bump slimmer to use Rails' cache

Gemfile, Gemfile.lock, app/controllers/concerns/education_navigation_ab_testable.rb, app/controllers/help_controller.rb, test/functional/help_controller_test.rb, test/integration_test_helper.rb, test/test_helper.rb
Main changes are:
- passing in the request headers to the variant checker;
- setting the acceptance testing framework in the configuration of the
gem.
Gem changes: https://github.com/alphagov/govuk_ab_testing/pull/20
Trello: https://trello.com/c/t4n8kPpx/434-make-sure-collections-can-be-toggled-with-the-a-b-test-and-react-to-it
=> Upgrade govuk_ab_testing to 1.0.0

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/views/shared/_base_page.html.erb, test/functional/answer_controller_test.rb, test/functional/guide_controller_test.rb, test/functional/licence_controller_test.rb, test/functional/local_transaction_controller_test.rb, test/functional/programme_controller_test.rb, test/functional/simple_smart_answers_controller_test.rb, test/functional/transaction_controller_test.rb, test/support/education_navigation_ab_test_helper.rb
This will add related links to the taxonomy sidebar.
### Trello  
https://trello.com/c/EJXC60k1/429-add-more-like-this-results-to-side-navigation-in-frontend-apps
=> Bump navigation helpers

app/controllers/completed_transaction_controller.rb, app/presenters/completed_transaction_presenter.rb, app/presenters/publication_presenter.rb, app/views/completed_transaction/show.html.erb, lib/content_format_inspector.rb, test/functional/completed_transaction_controller_test.rb, test/integration/completed_transaction_test.rb
This format has now been migrated.
https://trello.com/c/unTNbCHi/658-migrate-completed-transaction-format-to-rendered
Mobbed with @emmabeynon @binaryberry
=> Render completed transactions from content store

lib/tasks/publishing_api.rake
Related links like this are now manageable in content-tagger.
=> Stop sending related link for /find-local-council

Gemfile, Gemfile.lock, app/controllers/concerns/education_navigation_ab_testable.rb, app/controllers/homepage_controller.rb, app/views/homepage/_categories.html+new_navigation.erb, app/views/homepage/_categories.html.erb, app/views/homepage/index.html.erb, test/integration/homepage_test.rb, test/integration_test_helper.rb, test/test_helper.rb
In the new navigation, which is the B variant of the education navigation A/B test, link directly to the Education taxon rather than the Education browse page, and use the title and description of the taxon.
The layout of the homepage has been changed slightly to accommodate the longer taxon description: 'Housing and local services' has been moved from the second column into the third. This matches the prototype that has been tested in user research.
The variants are cached separately using the `Vary` header, but unlike on other A/B-tested pages, the `meta` tag is not added. This is because we do not want to include *all* journeys through the homepage in the A/B test analytics; we are only concerned with user journeys which include education content.
This requires a release of …
=> Link from the homepage to the Education taxon in the B variant

app/controllers/concerns/education_navigation_ab_testable.rb, test/functional/answer_controller_test.rb, test/functional/guide_controller_test.rb, test/functional/licence_controller_test.rb, test/functional/local_transaction_controller_test.rb, test/functional/programme_controller_test.rb, test/functional/simple_smart_answers_controller_test.rb, test/functional/transaction_controller_test.rb, test/integration/homepage_test.rb, test/support/education_navigation_ab_test_helper.rb
This means we can toggle the A/B variant in production via the chrome
extension. When we rollout the new navigation with a Fastly
configuration change, the % of users we select will start seeing these
new pages.
Trello: https://trello.com/c/940kowVa/484-remove-enable-new-navigation-check-from-repos-and-from-puppet
=> Remove the New Navigation feature flag

app/views/layouts/application.html.erb
https://trello.com/c/rAUEFO28/367-add-beta-survey-banner-to-new-education-navigation-pages
=> Add survey link and copy changes to banner on new nav pages

app/views/layouts/application.html.erb
Like the banner-notification it replaces, this will ensure that the
standard site survey isn't displayed when we're showing the taxonomy
one. Using a custom ID means we don't have to try and reverse styling
applied to banner-notification. The existing use of display:none doesn't
actually work as expected because survey.js in static looks for a
visible element when deciding whether or not to show the site survey.
https://trello.com/c/rAUEFO28/367-add-beta-survey-banner-to-new-education-navigation-pages
=> Use banner ID specific to the taxonomy survey

app/presenters/travel_advice_index_presenter.rb, test/integration/travel_advice_atom_test.rb, test/integration/travel_advice_test.rb
Travel-advice-publisher will soon stop sending the countries data
explicitly in the details hash; it will be expanded automatically by
publishing-api, which means they will be in the "children" element of
the details hash, and have a slightly different structure.
This should not be merged until the data is fully populated and publishing-api is expanding the links correctly.
=> [DO NOT MERGE] Render travel advice index from expanded links.

app/presenters/licence_details_presenter.rb, test/integration/licence_test.rb
We [recently refactored Licences](https://github.com/alphagov/frontend/pull/1141) and missed this edge case where a location specific licence search (eg for a postcode in Greenwich) could return multiple licence authorities. We found this for the licence "street-collection-licence". The code previously would return the first of the authorities, so we do the same here. In the case of this licence it doesn't seem like the right thing to be doing as the start page advises to contact the Metropolitan Police for London (which is the second authority which would not get rendered), but at this point we're just concerned with restoring the original functionality of the code.
=> Fix location specific licences with multiple authorities

app/assets/stylesheets/views/_homepage.scss, app/helpers/promo_banner_helper.rb, app/views/homepage/_promo_banner_example.html.erb, app/views/homepage/index.html.erb, test/functional/homepage_controller_test.rb
This allows us to deploy a partial containing copy to be placed below the search bar on the GOV.UK homepage. The example at `app/views/homepage/_promo_banner_example.html.erb` should be copied to `app/views/homepage/_promo_banner.html.erb` and deployed. `app/views/homepage/_promo_banner.html.erb` should be left empty if the banner is not in use.
Example:
=> Add support for displaying a banner on the GOV.UK homepage

app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_truncated-url.scss, app/controllers/place_controller.rb, app/presenters/place_presenter.rb, app/views/place/_option.html.erb, lib/content_format_inspector.rb, test/functional/place_controller_test.rb, test/functional/simple_smart_answers_controller_test.rb, test/integration/place_test.rb, test/unit/presenters/place_presenter_test.rb
Migrate the Place format, such that it is rendered through the Publishing API.
Do not merge yet, as the merging/release of this needs to be coordinated with Publisher.
https://trello.com/c/t3DXuS2t/660-migrate-place-format-to-rendered
=> Migrate Place

app/presenters/completed_transaction_presenter.rb, app/views/completed_transaction/show.html.erb, test/integration/completed_transaction_test.rb
When this document type was migrated we incorrectly changed the view to use the slug of the publication for the field used for feedback forms.
This returns a slug of the form `done/a-completed-transaction` which is then munged for sending to feedback as `www.gov.ukdone/a-completed-transaction`. 
We now use the base_path which looks like `/done/a-completed-transaction` which should now send the correct url to the feedback app.
https://trello.com/c/8xALJ6OT/687-fix-done-page-feedex-problem
cc @h-lame
=> Send correct url to feedex

startup.sh
this enables the repo to be run off of the live api servers
this makes it consistent with
[government frontend](https://github.com/alphagov/government-frontend/blob/master/startup.sh)
[contacts frontend](https://github.com/alphagov/contacts-frontend/blob/master/startup.sh)
[specialist frontend](https://github.com/alphagov/specialist-frontend/blob/master/startup.sh)
and a few others i can't remember off the top of my head
=> add live flag to be consistent with other repos

app/views/layouts/application.html.erb, test/support/education_navigation_ab_test_helper.rb
Pass `collapse_on_mobile` parameter to enable the collapse of the taxonomy breadcrumbs to a single back link.
https://trello.com/c/Y7OirowB/472-mobile-version-of-breadcrumbs-should-only-show-previous-link
=> Enable taxonomy breadcrumb back link on mobile

app/controllers/licence_controller.rb, app/presenters/licence_presenter.rb, app/views/licence/_authority_details.html.erb, lib/content_format_inspector.rb, test/functional/licence_controller_test.rb, test/integration/licence_test.rb, test/unit/presenters/licence_presenter_test.rb
- This feels too easy... we'll deploy the branch to Integration tomorrow for more testing.
- Related to and dependent on https://github.com/alphagov/govuk-content-schemas/pull/566 and https://github.com/alphagov/publisher/pull/584.
https://trello.com/c/snr7tKmR/677-migrate-licence-format-to-rendered
=> Render licences from content store

app/presenters/travel_advice_index_presenter.rb, test/integration/travel_advice_atom_test.rb
Now that travel-advice-publisher is no longer sending this data and the page has been republished, we can remove the backwards compatibility.
=> Remove support for countries hash in travel index.

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/homepage_controller.rb, app/controllers/search_controller.rb, lib/tasks/publishing_api.rake, test/functional/homepage_controller_test.rb, test/functional/search_controller_test.rb, test/integration/homepage_test.rb, test/integration/search_test.rb, test/support/rummager_helpers.rb
Load the content item for the homepage and search page so that it is used to populate the analytics meta tags.
This will enable us to track these pages as `finding` rather than `thing` in the navigation analytics. Currently they make the user journey analytics rather misleading because the appear to be content pages.
Delete the old slimmer configuration, since it will be replaced by the meta tag from govuk-components.
https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing
cc @tijmenb: this is the approach we discussed this morning.
=> Add analytics meta tags to homepage and search page

app/controllers/application_controller.rb, app/controllers/homepage_controller.rb, app/controllers/search_controller.rb, lib/tasks/publishing_api.rake, test/functional/homepage_controller_test.rb, test/functional/search_controller_test.rb, test/integration/homepage_test.rb, test/integration/search_test.rb, test/support/rummager_helpers.rb
This reverts commits b30542cb8cd675cc8998ad09b176ef91201e5b29 and a15580db1a7de5109ef0243f4a55e1f9c5c0aa15.
The custom document types are currently not allowed for content items in the `special_route` schema. This was causing integration deployment to fail.
These changes will be reapplied once the content schemas have been updated.
Note that the gds-api-adapters gem update has not been reverted because there were no breaking changes in it - it's safe to use the latest version from frontend.
https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing
=> Revert adding doc types and analytics to homepage and search

README.md
Add documentation for localhost alias when bowling on vagrant.  This is using the same wording and conventations found in the finder-frontend documentation.
=> Add documentation for localhost alias

app/controllers/concerns/cacheable.rb, test/functional/answer_controller_test.rb, test/functional/business_support_controller_test.rb, test/functional/campaign_controller_test.rb, test/functional/help_controller_test.rb, test/functional/licence_controller_test.rb
Now that Frontend is used as a draft app reading content from the
draft content store, the caching configuration is no longer something
it should manage.
Previously the existence of the `edition` parameter was used to detect
if a draft was being requested, but this no longer works, as it is not
possible for Frontend to request a specific edition from the
relevant (draft or live) Content Store service.
https://trello.com/c/THjwpcKs/695-remove-cache-busting-in-frontend-and-publisher
=> No longer selectively set the Cache-Control header

lib/special_route_publisher.rb, lib/tasks/publishing_api.rake, test/test_helper.rb, test/unit/special_route_publisher_test.rb
Add tests to check that all special routes are valid content items.
This was part of #1186, but it requires some changes to the content schemas and it would be good to have these tests in place _before_ making those changes.
https://trello.com/c/u1H1rgDA/525-some-finding-pages-are-still-being-tracked-as-thing
=> Test special route publishing

app/views/transaction/_additional_information_single.html.erb
A bug was discovered whereby "More information" was displaying on Welsh
Transaction pages instead of the Welsh translation for "Before you start".
`/register-to-vote` was also displaying "More Information" instead of in the
house style lower case "information". This fixes those bugs.
https://trello.com/c/4zLU8Ptn/707-english-heading-on-welsh-start-pages
=> Fix English heading on Welsh Transaction pages

README.md, app/controllers/application_controller.rb, lib/artefact_retriever.rb, test/unit/artefact_retriever_test.rb
Private-frontend is being turned off, so we remove references to it in this application.  Also the foreign-travel-advice override in ArtefactRetriever is not required as it is no longer a custom-application format.
[Trello](https://trello.com/c/JYT9roQm/709-turn-off-private-frontend)
Paired with @brenetic
=> Remove references to private frontend

app/views/homepage/index.html.erb
The number of agencies / public bodies has changed from **374** to **376** - this has been approved by policy and engagement.
Trello - https://trello.com/c/PFdiVCxN/10-2-named-contact-about-government-organisations
Updated this number in the homepage template.
=> Update number of other agencies and public bodies on homepage

config/locales/cy.yml, config/locales/en.yml
The translation key `more_information` does not exist in the translation files, this causes a `span.missing-translation` to be added to the mark-up when it's called as well as Welsh pages to use the english fallback of `More Information`. 
The `span` causes strange rendering on mobile, while Welsh pages get English text for the tab heading.
**Note:** this translation is only found in start pages that render `tabs` below the start button.
**Examples:**
https://www.gov.uk/view-driving-licence
https://www.gov.uk/gweld-neu-rannu-eich-gwybodaeth-trwydded-yrru
**Additional context:**
https://github.com/alphagov/frontend/pull/1197
Adds the `more_information` translation to the `yaml` files.
=> Fix non-existent translation key

app/controllers/local_transaction_controller.rb, test/functional/local_transaction_controller_test.rb
We're in the process of making lgil_code mandatory and retiring lgil_override.
In the meantime, we'd like to be able to use either.
https://trello.com/c/RnJC1d7a/5-assign-lgil-codes-to-all-local-transactions
=> Use either lgil_code or lgil override

app/controllers/travel_advice_controller.rb, test/functional/travel_advice_controller_test.rb
https://trello.com/c/SEGfmX1v/912-1935680-enable-access-control-allow-origin-header-in-rss-feeds
Allow users to call the data in the Travel Advice atom feed via an AJAX request.
We've had a specific user request to add this header in order to allow third party
sites to make valid requests for this data.
See https://govuk.zendesk.com/agent/tickets/1935680
=> Add Access-Control-Allow-Origin header to TA atom index

Gemfile, Gemfile.lock, app/controllers/homepage_controller.rb, app/views/homepage/index.html.erb, lib/emergency_banner.rb, test/functional/homepage_controller_test.rb, test/unit/emergency_banner_test.rb
The emergency banner implementation is currently being re-written such that instead of using a fabric script to add content to some partials in Frontend and Static, we will populate a hash in Redis with values needed for the emergency banner.
This will mean that should we need to deploy an emergency banner, Static and Frontend deploys are no longer blocked.
This PR depends on c8db3a2ba86acc71753dd0b4f7a79275104abb28
In doing this work, we have also identified that the actual display of the emergency banner can be consolidated into Frontend (see the [Trello card](https://trello.com/c/3eq0AeHA/30-consolidate-emergency-banner-templates-in-static-and-frontend)). However, we are no consolidating the display of the promo banner at this point, so we still need to selectively display the promo …
=> Use redis to determine promo banner display state

lib/homepage_publisher.rb, lib/special_route_publisher.rb, lib/tasks/publishing_api.rake, test/unit/homepage_publisher_test.rb
Update the schema of `/` to the new `homepage` schema. It's just like the old `special_route` schema, but with a great new `links['root_taxons']` taste.
To do this without changing a boat-load of projects, it's easier and safer to create a new Homepage publisher tool. 
[Trello](https://trello.com/c/wHZQz5Yk/64-build-joe-s-designs-to-allow-publishers-to-tag-across-multiple-themes-in-whitehall)
=> Change the schema of the gov.uk homepage

Gemfile, Gemfile.lock, test/functional/local_transaction_controller_test.rb, test/integration/help_test.rb
This PR bumps both gems ( gds-api-adapters & govuk_navigation_helpers )
This also fixes testing functionality that has been deprecated in gds-api-adapters
Trello:
https://trello.com/c/I4rs80n1/80-remove-duplicated-related-links-across-all-parent-taxons
=> Bump gds api adapters & govuk_navigation_helpers

test/functional/search_controller_test.rb
As far as I can tell, individual tests are adding the `filter_organisations` query param where appropriate, so the `organisations` parameter can be deleted.
=> Delete unused parameter in test setup

config/mainstream_content_with_curated_sidebar.json
We have recently ported `answers` to government frontend, which means
these content items are not rendered by this app. They can be deleted.
Trello: https://trello.com/c/U6JKZN6s/115-make-sure-we-override-the-related-links-on-some-mainstream-content-that-was-recently-moved-to-government-frontend
=> Remove answers from curated related links

config/mainstream_content_with_curated_sidebar.json
Guides have been ported to `government-frontend`, which means we don't
need to have the overrides in place in this application.
This commit removes all `guides` from the list of mainstream pages that
should show the old related links.
Links:
- https://github.com/alphagov/government-frontend/pull/355
Trello: https://trello.com/c/U6JKZN6s/115-make-sure-we-override-the-related-links-on-some-mainstream-content-that-was-recently-moved-to-government-frontend
=> Remove Guides from curated mainstream config

Gemfile, Gemfile.lock, app/controllers/search_controller.rb, app/views/search/index.html.erb, lib/search_api.rb, test/functional/help_controller_test.rb, test/functional/search_controller_test.rb
We are about to start testing changes to match length for search results. This needs to be tracked by GA as well.
https://trello.com/c/43eBQfwf/80-prepare-the-infrastructure-for-the-minimum-should-match-a-b-test
=> [DO NOT MERGE] Add Search Match Length AB test

app/assets/javascripts/live-search.js, app/assets/javascripts/search.js
We are making the Analytics tracking interface more explicit in which
methods are used external to the module. This involves:
- removing the methods that set custom dimensions at a session level,
and instead explicitly setting custom dimensions on the pageview
- removing the `callOnNextPage` method, which allowed arbitrary running
of any public methods on the analytics interface, where we just need
to set options for the next page
https://trello.com/c/5dIbwHvU/120-tidy-up-tracking-changes
=> Use new analytics JavaScript interface

app/views/search/index.html.erb
Search result pages are excluded from robots.txt, but search engines can still
index the page.
This means it's possible to see results with the query prefilled with spam from
other websites.
A meta tag should do a better job at preventing indexing. See https://support.google.com/webmasters/answer/93710?hl=en
Trello: https://trello.com/c/AMj9IOuV/92-don-t-let-search-engines-index-site-search-results
=> Don't index search result pages

app/assets/javascripts/live-search.js
Google Analytics custom dimensions expect a String as their value.
This change wraps the result count (an integer) as a String.
=> Track search result count as String

app/helpers/application_helper.rb, app/views/local_transaction/results.html.erb, app/views/local_transaction/search.html.erb, app/views/shared/_base_page.html.erb, app/views/shared/_publication_metadata.html.erb, app/views/travel_advice/index.html.erb, test/integration/licence_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/travel_advice_test.rb
Pages have a `rel=alternate` link linking to the JSON version of the
page. That link was pointing to the Content API, but that API is being
deprecated. This commit removes those links from the pages.
Trello: https://trello.com/c/Uo9tfmSE/139-investigate-who-is-using-travel-advice-endpoints-on-content-api-in-production
=> Remove references to the Content API JSON endpoint

app/controllers/application_controller.rb, app/controllers/concerns/benchmarking_contact_dvla_title_ab_testable.rb, app/controllers/simple_smart_answers_controller.rb, app/views/shared/_base_page.html.erb, app/views/simple_smart_answers/flow.html.erb, app/views/simple_smart_answers/show.html.erb, test/functional/simple_smart_answers_controller_test.rb
- We're changing the `contact-the-dvla` page title from "Contact DVLA"
to "Find out how to contact DVLA", as an A/B test.
- This will also display the B variant on all pages whose path starts with "contact-the-dvla"
**Do not merge until Wednesday 7th June, we want to deploy this then (along with the Fastly changes).**
=> A/B test the title on `/contact-the-dvla` page

app/views/simple_smart_answers/_current_question.html.erb, test/integration/simple_smart_answers_test.rb
For: https://trello.com/c/aFMEbvlj/166-error-messages-on-simple-smart-answers
We follow the pattern than rails checkbox helper uses to ensure we always
have a response param when submitting the form by adding a hidden field
tag with an empty value.  When given two params with the same name Rails
will choose the last one as the value reported when asking for a param
in the controller, so when the user makes a choice we get two response
params; the blank one from the hidden field, and the choice they made
from the radio buttons.  The radio button one will be last and so it's
the value that Rails will report for the response param.
This means we can tell the difference between someone visiting the
smart-answer part way through with a direct url and someone on the
previous step pressing the …
=> Show error messages for empty submissions on simple smart answers

app/views/place/_option.html.erb, test/integration/place_test.rb
For: https://trello.com/c/PrPGF1Pa/165-imminence-formatting-spike
Some imminence users requested more formatting options for notes and
using the rails `simple_format` is an easy first attempt at allowing
this.  There's precedent for doing this already as we do the same for
some details of licence and travel advice API details.  Adding
something like govspeak would be possible but we'd have to do the
rendering in imminence as no frontend apps handle rendering govspeak
themselves, and it would require changing the schema.
=> Apply simple_format to access_notes and general_notes in places

app/controllers/concerns/benchmarking_contact_dvla_ab_testable.rb
- This wasn't setting the headers correctly, because each one was named the same.
=> Name the @ab_test variable differently per test

app/controllers/search_controller.rb, app/views/search/index.html.erb, test/functional/search_controller_test.rb
Stop paying attention to the match length A/B test and pass through
buckets for the new format boosting A/B test.
We intend to reuse the existing GA custom dimension.
Caveat: at the moment we're not changing the GA dimension values.
Before merging:
Trello: https://trello.com/c/lyMXwkq0/128-configure-format-weighting-a-b-test
=> Change search A/B test

app/views/shared/_base_page.html.erb
Because we reused the AB variant name for the currently running test, this was still being
shown as part of the B variant.
=> Revert the title from the last AB test

app/models/search_parameters.rb, app/presenters/search_result.rb, app/views/search/_result.mustache, app/views/search/_results_list.mustache
This adds the required classes to the search results to support ecommerce tagging.
https://trello.com/c/WlBZo8Sl/118-move-ecommerce-ga-to-use-govukfrontendtoolkit
=> Add ecommerce tag

app/assets/stylesheets/views/_completed-transaction.scss, app/views/completed_transaction/_assisted_digital_help_with_fees_satisfaction_survey.html.erb, app/views/completed_transaction/_assisted_digital_satisfaction_survey.html.erb, app/views/completed_transaction/_standard_satisfaction_survey.html.erb, app/views/completed_transaction/show.html.erb, lib/assisted_digital_satisfaction_survey.rb, test/integration/completed_transaction_test.rb
This survey is specifically about help with fees and we only want to show
it on certain done pages.  For now this is a bit experimental, so we don't
want to add it to the documents themselves as a toggle selectable in
publisher.  We've left it as a hardcoded list in
lib/assisted_digital_satisfaction_survey.rb.
Note that the backend for this is handled by the feedback app (see https://github.com/alphagov/feedback/pull/179 and https://github.com/alphagov/feedback/pull/189 and https://github.com/alphagov/feedback/pull/190 - all of these should be merged and deployed before this is).
Trello: https://trello.com/c/kZCX6dGB/53-assisted-digital-support-on-done-page-survey
=> Add a new assisted digital satisfaction survey

app/controllers/search_controller.rb, app/views/search/index.html.erb, lib/search_api.rb, test/functional/search_controller_test.rb
The A/B test is successful and statistically significant. 🎉 
One commit also removes all the A/B test parameters from the search API since we're not planning to run another A/B test immediately. It should be easy to revert when we want to start a new one.
https://trello.com/c/Z5KURpnB/147-deploy-format-boosting-%F0%9F%9A%80
Paired with @brenetic.
=> Remove search format boosting A/B test

app/presenters/transaction_presenter.rb, app/views/transaction/show.html.erb, test/integration/transaction_test.rb
As part of moving smart answer start pages to be rendered from
alphagov/frontend, we need to allow transactions to render a custom
start now button (as seen in some smart answers)
I've also added this custom start now behaviour in our tests, and confirmed the other tests still check that 'Start now' is rendered if a custom one is not specified
https://trello.com/c/arlZczQO/423-2-republish-smart-answer-part-year-profits-to-finalise-your-tax-credits-start-page-as-a-transaction-page
=> Add custom start now rendering logic

config/mainstream_content_with_curated_sidebar.json, test/integration/old_related_links_test.rb, test/support/content_store_helpers.rb
Recently, some transaction pages have been moved from smart-answers
into this application. Two of those pages had overrides to show the old
related links instead of the new taxonomy related links when presented
in the B variant of the Education Navigation A/B test.
This commit adds those 2 pages to the static list of pages with
overrides, and adds an integration test to explain why that list exists.
This was picked up by Smokey tests.
There is more context in:
- https://trello.com/c/J8ofEnrt/167-display-curated-related-links-in-the-sidebar
- https://docs.google.com/document/d/1k1nlQOpFwjaUNoNtizAnsDr5z9O5uUMIOlgDSUCbwj4/edit#
Related to:
- https://github.com/alphagov/smart-answers/pull/3134
Trello: https://trello.com/c/2ZGxOt0I/17-build-backlog-for-finalising-education-navigation-work
=> Add transaction pages to list of mainstream links

Gemfile, Gemfile.lock, lib/homepage_publisher.rb
Sending it on publish has been deprecated in favour of including it when sending a put content.
[Trello Card](https://trello.com/c/LnJlkb9e/987-5-deprecate-the-usage-of-updatetype-in-publish-for-publishing-api-and-update-usage-across-govuk)
=> Send update type with put content

app/assets/javascripts/modules/track-smart-answer.js, app/views/simple_smart_answers/_outcome.html.erb, test/integration/simple_smart_answers_test.rb, test/javascripts/unit/modules/track-smart-answer.spec.js
For: https://trello.com/c/gH1ZH27k/181-event-tracking-completion-of-simple-smart-answers-investigate
In the [smart-answers app](https://github.com/alphagov/smart-answers) we track when the user reaches the final outcome
stage of the smart answer by sending a message to GA.  This commit adds
the same functionality to simple smart answers.
We do it via a JS module for tracking smart answers.  Currently it only
tracks the outcome node type and sends a "Smart Answer", "Completed" event
to GA with the path and smart answer name, but there is scope to extend
the module to track other node types and events if we need to.  Note that
the standalone smart answers app only tracks completion at the moment too
so any extra tracking would need to happen there too.
=> Track simple smart answer completion in GA

app/views/homepage/_categories.html.erb
[Trello card](https://trello.com/c/yluvvATh/697-1-update-description-under-benefits-on-govuk-homepage)
According to the content design team, 'Universal Credit’ was the most searched for term from the GOV.UK homepage from 1 July 2016 30 June 2017.
This has been anticipated to grow, especially as Universal Credit is rolling out  to more people who are on existing benefits and the UC availability is becoming available in more areas to new claimants.
Our stats show that users aren’t finding their way through Benefits browse categories or related links on pages. Hence the reason behind this content update.
- Content update to benefits section on the home page
- https://deploy.integration.publishing.service.gov.uk/job/Deploy_App/1890/console
- …
=> Content update to benefits section on GOV.UK homepage

app/presenters/government_result.rb, test/unit/presenters/government_result_test.rb
This commit removes the “section” links below world location results in search. These sections no longer exist in the new world location navigation pages.
=> Remove search sections for world locations

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, test/unit/helpers/application_helper_test.rb
For: https://trello.com/c/Bo5SQrIm/215-add-page-tracking-custom-dimension-into-education-beta-survey-banner
This lets the survey team know where each response has come from and
allows them to filter by section of the site.
=> Add current path to beta banner survey

app/views/find_local_council/_base_page.html.erb, app/views/travel_advice/index.html.erb, test/functional/find_local_council_controller_test.rb, test/integration/find_local_council_test.rb, test/integration/travel_advice_test.rb
Other pages append [" - GOV.UK"][1] to the [page title][2].  Hardcoded pages
such as `/find-local-council` and `/foreign-travel-advice` should be no
exception.
Tara spotted these omissions last week.
[1]: https://github.com/alphagov/frontend/blob/ef7ce45cfe71aacf03fdf8a3e7d99feae50a21bd/app/helpers/application_helper.rb#L4
[2]: https://github.com/alphagov/frontend/blob/ef7ce45cfe71aacf03fdf8a3e7d99feae50a21bd/app/views/layouts/application.html.erb#L5
=> Add GOV.UK suffix to page titles

app/controllers/local_transaction_controller.rb, test/integration/local_transactions_test.rb
We're currently getting around a million requests per week for this "postcode".
The requests come from the same IP address and we're pursuing a P&E resolution
to this.  In the meantime, short circuit this one so we don't spend time on API
requests when we know the result.
The source IP does send reasonable requests as well and appears to be affiliated
with local gov, so we don't want to ban it at this point.
The requests are only coming in to the /get-on-electoral-register URL so we
don't need to worry about licence/find local council or other postcode lookup
end points at the moment.
https://kibana.publishing.service.gov.uk/kibana#/dashboard/elasticsearch/MapIt%20requests%20with%20ENTERPOSTCODE
=> Short circuit "ENTERPOSTCODE" requests

app/views/homepage/index.html.erb
"
HI folks,
could the Hurricane Irma homepage promo please be updated as soon as possible so that it reads:
Title: Hurricanes Irma and Maria
Text: Advice for British nationals affected by Hurricanes Irma and Maria.
Because: FCO has updated the news article this links to similarly to include information on Maria. 
Many thanks
best
Gavan
"
https://govuk.zendesk.com/agent/tickets/2414424
=> Update Hurricane information to include Maria

lib/local_transaction_location_identifier.rb
We support Northern Ireland councils now, but we need to allow them to be found.
This area type is already supported in [find-local-council](https://github.com/alphagov/frontend/blob/master/app/controllers/find_local_council_controller.rb#L8) and by adding it to the list here, will be activated in local transactions as well.
We should have done this a while ago; it seems to have been an oversight.
=> Enable Northern Ireland councils in local transactions

config/unicorn.rb
This lived in alphagov-deployment (https://github.com/alphagov/alphagov-deployment/pull/2). Moving it so that we can retire that repo.
=> Add unicorn config from alphagov-deployment

app/controllers/find_local_council_controller.rb
In 490d01f1bdc46be64a0e8ba6ef67ccb81a94dafb we replaced the hardcoded
content item response in the `FindLocalCouncilController` with a version
that spoke to the content store.  However, we also inlined our own
`setup_content_item_and_navigation_helpers` method instead of re-using
the version in `ApplicationController`.  This means we stopped setting
the `govuk:section` meta tag, but also means we'll miss out on any
other changes that we want to apply globally.  We revert back to using
the `ApplicationController` version to avoid this.
=> Remove custom helper for content item in find local council

app/controllers/homepage_controller.rb, app/views/homepage/_categories.html+new_navigation.erb, test/integration/homepage_test.rb
We're holding off deploying the removal of the Education AB test until all parts are ready.
Reverts alphagov/frontend#1288
=> Revert "Remove Education AB from homepage"

lib/special_route_publisher.rb
These will be moved to rummager now that frontend is no
longer responsible for the search page.
https://trello.com/c/4CscCsGa/377-remove-old-site-search-code-form-frontend
=> [DO NOT MERGE] Remove special routes for search endpoints

app/presenters/transaction_presenter.rb, config/locales/cy.yml, config/locales/en.yml, test/integration/transaction_test.rb, test/unit/presenters/transaction_presenter_test.rb
For [Trello](https://trello.com/c/uQuBPfYU/153-fix-welsh-translation-issues-for-start-now-button)
A bug has occurred where Welsh content displays “Start now” as start button
text instead of the Welsh translation “Dechrau nawr” (see Zendesk tickets [1](https://govuk.zendesk.com/agent/tickets/2430403) and [2](https://govuk.zendesk.com/agent/tickets/2498433)).
While investigating this issue we also found that publishers are able to select "Sign in" as start button text, but there was not a Welsh translation available, so this has been added in as well.
=> Fix Welsh start button translation bug

app/views/transaction/show.html.erb
Was added originally in
- https://github.com/alphagov/frontend/pull/419
- https://github.com/alphagov/static/pull/310
And removed in https://github.com/alphagov/static/pull/323
But I think we forgot to remove this attribute from frontend.
Doing this means we wont have to add data attributes to our button component :)
=> Remove unused data-transaction-slug attribute

app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_task-list-title.scss, app/controllers/application_controller.rb, app/controllers/concerns/tasklist_ab_testable.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/transaction_controller.rb, app/views/shared/_base_page.html.erb, app/views/shared/_tasklist_sidebar.html.erb, app/views/simple_smart_answers/show.html.erb, app/views/transaction/show.html.erb, config/tasklists/learn-to-drive-a-car.json, lib/tasklist_content.rb, test/functional/transaction_controller_test.rb, test/integration/transaction_test.rb, test/test_helper.rb, test/unit/tasklist_content_test.rb
This is for the tasklist public beta.  The first theme is learning to drive a
car.  This commit adds a tasklist sidebar to content served by Frontend that
is listed in app/controllers/concerns/tasklist_ab_testable.rb.
The content in Frontend that is relevant is limited to transactions and
simple_smart_answers at present.
The tasklist is configured using the file at config/tasklists/learn-to-drive-a-car.json
Testing of the component itself is limited as testing components from static is
not currently possible (as noted in https://github.com/alphagov/slimmer#testing-components)
This limitation is subject to an RFC at present.  What we can do is test the
json that Slimmer emits in the test - which is what we've done.
We need to get a design review on this before merging.
Screenshots:
=> Add task list sidebar with AB test

app/presenters/transaction_presenter.rb, app/views/transaction/show.html.erb, test/integration/transaction_test.rb, test/unit/presenters/transaction_presenter_test.rb
Proposal to remove this so we don't need to add it as a feature when consuming the [button component](https://govuk-static.herokuapp.com/component-guide/button/start_now_button_with_info_text)
It's not clear why this was added, but it's wildly inconsistent since we don't seem to be updating it.
Be good to get any input in on if this is a good idea to remove.
Originally added in https://github.com/alphagov/frontend/pull/43
=> Remove open in new window feature for transactions

app/controllers/concerns/tasklist_ab_testable.rb
This pages can be found in the chapter links of some of the pages.
We want to keep them looking the same on all pages.
Trello:
https://trello.com/c/dGeTlJXu/278-add-sidebar-to-all-chapters-of-a-given-page
=> Add missing pages into TaskListSidebar A/B Testing

app/controllers/concerns/tasklist_ab_testable.rb
We want to show the tasklist sidebar in the chapters of /pass-plus
It's not rendered in Frontend, but we want to keep the list in sync with government-frontend
https://github.com/alphagov/government-frontend/pull/519
=> Add pass-plus chapters to tasklist content

app/views/shared/_base_page.html.erb, app/views/shared/_tasklist_header.html.erb
This has been agreed with @andysellick
I've also removed the dependency of the tasklist in case we turn
off the TaskListSidebar A/B test.
=> Use default text for "skip link"

app/views/layouts/application.html.erb, app/views/shared/_base_page.html.erb
The tasklist header was not showing fullwidth and this commit fixes this.
=> Move position of tasklist header

app/controllers/concerns/tasklist_ab_testable.rb, app/controllers/concerns/tasklist_header_ab_testable.rb, app/controllers/concerns/tasklist_pages.rb
The tasklist header also needs to be shown on secondary pages that are part of the A/B test.
Some refactoring has been done to improve dependency issues.
=> Add tasklist header A/B test to secondary pages

app/controllers/concerns/taxonomy_navigation.rb, test/functional/taxonomy_navigation_test.rb
Same as https://github.com/alphagov/government-frontend/pull/533.
We now determine which navigation to show according to a complex decision tree:
When we rolled it out we thought that it would be good to always show the new navigation if the content is tagged to the world wide taxonomy (https://github.com/alphagov/government-frontend/pull/510), because it would be closest to what the B-variant was.
This had unintended effects of showing the world wide navigation on some mainstream pages, because they're tagged to the "generic" taxons in the world wide taxonomy.
https://trello.com/c/TqnWwFif
=> Don't show new nav for world wide mainstream pages

app/views/homepage/index.html.erb
https://www.gov.uk/government/publications?publication_filter_option=statistics redirects to https://www.gov.uk/government/statistics, so this just updates the link to remove the redirect request, and also make the visited style appear correctly if you've visited that section.
=> Update link to statistics

app/controllers/application_controller.rb, config/tasklists/learn-to-drive-a-car.json, test/integration/transaction_test.rb, test/unit/tasklist_content_test.rb
This commit fixes the implementation as it was changed during
https://github.com/alphagov/static/commit/c36c0b7d217750bea8f355d428c022bf74af615e
Trello:
https://trello.com/c/fFItiXlt/299-fix-accordion-functionality-on-learning-to-drive-in-sidebar-navigation
=> Fix "open step" on TaskList Sidebar

app/views/transaction/_cross_domain_analytics.html.erb, app/views/transaction/show.html.erb, test/integration/transaction_test.rb
Depends on https://github.com/alphagov/static/pull/1193
Allows us to remove inlined JavaScript in favour of the global approach
that we'll be using elsewhere.
Trello: https://trello.com/c/ppqXaGPk/122-create-a-govspeak-component-for-buttons
=> Update transaction start button to use data attrs

Jenkinsfile
Hey :wave: !
This PR will enable a set of [end-to-end tests](https://github.com/alphagov/publishing-e2e-tests) to run every time a commit is made to this repo. :boom:
You can read through the scenarios at a [high level](https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1AUYU4n4GN_XGdqUJdONN2pbQnVEC5o8s--59IipeFjY/edit?usp=sharing), and the capybara [here](https://github.com/alphagov/publishing-e2e-tests/tree/master/spec/publisher).
Look at the merge box below and you'll see a new check performed against this PR.
Enabling these tests will give increased confidence when making changes to this repo that the change doesn't break the publisher in an end-to-end environment.   Downside is that running these tests takes time, with build times between 6 - 11 minutes currently.
=> Run the end to end tests which go through the publisher app

app/controllers/application_controller.rb
For: https://trello.com/c/hpS5pFQe/237-investigate-new-navigation-impact-on-surveys
We stripped organisation info from the content item presented to the
view because it would result in the govuk:analytics:organisations meta
tag being set and this would be sent to Google Analytics (GA) as a custom
dimension. We did this because the tag was mostly used by whitehall and
departmental users wouldn't expect to see mainstream content appearing
in their GA reports for their department.
During migration the mainstream formats ported to government-frontend
started sending this info to GA and it didn't cause any problems. This
means we're happy to stop stripping this data and have all content items
that have organisation info send it to GA.
=> Stop stripping organisation info from content item

app/views/homepage/index.html.erb
Trello: https://trello.com/c/YRSePZfr/266-update-the-number-of-depts-and-orgs-on-the-homepage
This updates the number of "Other agencies and public bodies" on the homepage
to 385, which matches the number on "/government/organisations".
=> Update number of agencies and public bodies

README.md
Search was removed in https://github.com/alphagov/frontend/pull/1293
=> Remove site search from README

app/views/layouts/application.html.erb
This should have been removed as part of 360b11bcb31e85706a5b1b24d755e1a4d772797d but I somehow missed it.
=> Remove last bit of mustache

Gemfile, Gemfile.lock, config/environments/production.rb
cdn_helpers appears to have last been used before being removed in c10fd32450ee45d760e0a80d126501e5061912db
The [cdn_helpers repo](https://github.com/gds-attic/cdn_helpers) has now been moved to the attic
gelf is a logging gem and appears to have last been used before being removed in c906edc8bf20eb1cbe46988cd619b7bde73137c0.  We now use logstasher.
govuk_app_config causes the js tests to hang when we move to 1.*.  In the meantime, just bump to the last known working version.
=> Remove cdn_helpers and gelf gems and bump govuk_app_config

app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_title-context-reset.scss, app/views/find_local_council/_base_page.html.erb, app/views/help/index.html.erb, app/views/help/tour.html.erb, app/views/licence/continues_on.html.erb, app/views/licence/start.html.erb, app/views/shared/_base_page.html.erb, app/views/simple_smart_answers/flow.html.erb, app/views/travel_advice/index.html.erb, test/integration/completed_transaction_test.rb, test/integration/find_local_council_test.rb, test/integration/help_test.rb, test/integration/licence_test.rb, test/integration/local_transactions_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_test.rb, test/integration/travel_advice_test.rb, test/support/component_helpers.rb
https://trello.com/c/gFJzv4R4/255-use-title-component-in-frontend-formats
These changes should make no visual difference to the rendered pages:
Before:
After:
=> Use title component from static

app/assets/javascripts/frontend.js
Step by step navigation needs the current-location module to be included.  We
currently have script errors occurring on pages where the step nav is displayed.
We will address this dependency in govuk_publishing_components.
=> Add current location dependency

app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_simple-smart-answer.scss, app/views/application/_location_form.html.erb, app/views/completed_transaction/_assisted_digital_satisfaction_survey.html.erb, app/views/completed_transaction/_standard_satisfaction_survey.html.erb, app/views/completed_transaction/show.html.erb, app/views/help/tour.html.erb, app/views/licence/_action.html.erb, app/views/licence/continues_on.html.erb, app/views/licence/start.html.erb, app/views/local_transaction/results.html.erb, app/views/simple_smart_answers/_current_question.html.erb, app/views/simple_smart_answers/show.html.erb, app/views/transaction/jobsearch.html.erb, app/views/transaction/show.html.erb, test/integration/completed_transaction_test.rb, test/integration/find_local_council_test.rb, test/integration/licence_test.rb, test/integration/local_transactions_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_test.rb, test/support/component_helpers.rb
Reverts alphagov/frontend#1402
Reverting due to styling differences, the component is needs to include the `.button` css class styles
Component:
Production:
=> Revert "Use button component"

app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_simple-smart-answer.scss, app/views/application/_location_form.html.erb, app/views/licence/_action.html.erb, app/views/licence/continues_on.html.erb, app/views/licence/start.html.erb, app/views/local_transaction/results.html.erb, app/views/simple_smart_answers/_current_question.html.erb, app/views/simple_smart_answers/show.html.erb, app/views/transaction/jobsearch.html.erb, app/views/transaction/show.html.erb, test/integration/find_local_council_test.rb, test/integration/licence_test.rb, test/integration/local_transactions_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_test.rb, test/support/component_helpers.rb
https://trello.com/c/3VwTvDrj/256-use-button-component-in-frontend-formats
Another attempt at https://github.com/alphagov/frontend/pull/1402 adds the start button styling missed in the previous PR.
=> Use button component

app/presenters/licence_details_presenter.rb, app/views/licence/_action.html.erb, app/views/licence/_authority_details.html.erb, app/views/licence/authority.html.erb, test/integration/licence_test.rb, test/support/component_helpers.rb, test/unit/presenters/licence_details_presenter_test.rb
For: https://trello.com/c/QswdEVKO/69-2-changes-to-licensing-controller-for-licensify
It was pointed out that some licenses are showing up incorrectly as available in licensify,
with the user being offered the option to start applying for it, although they cannot continue
further than the first step. This is frustrating because the user gets the feeling of being stuck
when in fact they should've never been offered the option in the first place.
The API response already tells us whether the licence should be using Licensify, in a param called
`usesLicensify` so we now check it before showing a start page to the user.
If the param is set to false, we now display a "License unavailable" page instead.
=> Makes use of usesLicensify API param

config/unicorn.rb
For: https://trello.com/c/5qhHri2F/87-2-increase-server-resource-serving-government-frontend
We are now using the unicorn config in `govuk-puppet`, which was created in this PR: https://github.com/alphagov/govuk-puppet/pull/7255
There's no need to set a default inside the `frontend` app anymore.
=> Remove default unicorn setting

test/unit/presenters/travel_advice_index_presenter_test.rb
This commit fixes the travel advice test because the content schemas example it depends on has also changed.
Trello: https://trello.com/c/VK18GrmW/736-clean-up-all-remaining-govdelivery-references-across-all-repos
=> Fix travel advice test

app/views/help/index.html.erb
Zendesk request to streamline content request paths ahead of GDPR
related publishing.
https://govuk.zendesk.com/agent/tickets/2772634
=> Remove FOI link on help page

app/controllers/transaction_controller.rb, app/views/transaction/jobsearch.html.erb, config/routes.rb, test/functional/transaction_controller_test.rb, test/integration/transaction_test.rb
Reverts alphagov/frontend#1503
https://trello.com/c/XmgHVATH/135-change-format-of-start-page-jobsearch-find-a-job-with-universal-jobmatch-3
This needs to be deployed on 14th May
=> Revert "Make /jobsearch a standard transaction"

app/assets/stylesheets/application.scss, app/views/simple_smart_answers/_current_question.html.erb
This replaces the old-style radio button blocks with the component, which uses the [new pattern for radio buttons][blog].
https://govuk-frontend-app-pr-1509.herokuapp.com/sold-bought-vehicle/y
https://govuk-frontend-app-pr-1509.herokuapp.com/settle-in-the-uk/y
https://govuk-frontend-app-pr-1509.herokuapp.com/exchange-foreign-driving-licence/y
| --- | --- |
| ![screen shot 2018-05-08 at 21 19 31](https://user-images.githubusercontent.com/233676/39802881-2da00e70-5367-11e8-9e7f-3576301cfea8.png) | ![screen shot 2018-05-08 at 21 19 33](https://user-images.githubusercontent.com/233676/39802889-304df182-5367-11e8-8f79-8b0ed2b6daa2.png) |
| ![screen shot 2018-05-08 at 21 19 48](https://user-images.githubusercontent.com/233676/39802925-4e3bed98-5367-11e8-8820-b0e33b3146c1.png) …
=> Use component for radio buttons in simple smart answers

app/views/homepage/index.html.erb
The name of Universal Jobmatch has changed to Find a job.
Update the link from the homepage to reflect this.
[Trello](https://trello.com/c/CgNQhHoN/399-homepage-text-change)
=> Update Universal Jobmatch to be Find a job

app/views/homepage/index.html.erb
In dac755b89626755274ac1313f50d5a333c06fbd9 we updated the text in the
"Popular" box that sits next to the search bar. However there is another
occurance under the "Most active" section just above the footer.
=> Update another occurance of Universal Jobmatch text

app/views/local_transaction/results.html.erb, app/views/local_transaction/search.html.erb
These are hangovers from content-api days.  The json page from the local transaction search pages (eg https://www.gov.uk/pay-council-tax.json) return `410`s, however the individual results pages (eg https://www.gov.uk/pay-council-tax/camden.json) return `404`s
Having checked Kibana, it doesn't look like anyone's trying to use these, which is not surprising given that they don't work.
I'd like to resurrect this one day, perhaps when we "API the sheep out of everything".
=> Remove json endpoints for local transactions

app/views/local_transaction/search.html.erb, app/views/place/show.html.erb, app/views/simple_smart_answers/show.html.erb, app/views/transaction/show.html.erb
This adds schema.org data for places, local transactions, simple smart answers and transactions. It uses the machine readable metadata component: alphagov/govuk_publishing_components#318.
- [Place](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fgovuk-frontend-app-pr-1514.herokuapp.com%2Fregister-offices)
- [Local transaction](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fgovuk-frontend-app-pr-1514.herokuapp.com%2Fcheck-school-closure)
- [Simple smart answer](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fgovuk-frontend-app-pr-1514.herokuapp.com%2Fsold-bought-vehicle)
- [Transaction](https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fgovuk-frontend-app-pr-1514.herokuapp.com%2Fvehicle-tax) …
=> Add schema.org data via the new component

lib/special_route_publisher.rb, test/unit/special_route_publisher_test.rb
This is currently [hard coded][1]. If we use `ordered_related_items` we might be able to switch out the hard coded solution with the contextual sidebar, which will make it possible to remove the `related_items` component from Static.
https://github.com/alphagov/frontend/blob/fe86e5e33ac468eb14e41d84beb19dcfeaf7d4b9/app/views/help/index.html.erb#L59-L74
https://trello.com/c/pU7YINt1
=> Link /help to /contacts in links

app/views/help/index.html.erb
The help page currently uses a hard coded sidebar. Now that we've added a link from the help page in https://github.com/alphagov/frontend/pull/1529, we can use the contextual sidebar.
https://trello.com/c/jyqWJuwq/34-remove-the-relateditems-component-from-static
=> Use contextual sidebar for /help

app/controllers/application_controller.rb, app/views/application/_beta_label.erb, test/integration/licence_test.rb, test/integration/local_transactions_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/test_helper.rb
This makes the app use the phase banner from the gem (https://trello.com/c/qtXCDGQI). Since this is the last usage of Static components, we can clean up the code and test helpers.
https://trello.com/c/pU7YINt1
=> Use phase banner from gem

app/views/homepage/index.html.erb
This hasn't been the case for a while now so we don't need to include this text.
[Trello Card](https://trello.com/c/bTQqoWTm/511-change-link-text-on-the-homepage)
=> Remove previous universal jobmatch

app/controllers/transaction_controller.rb, app/views/transaction/show.html.erb, app/views/transaction_variant/_additional_information_single.html.erb, app/views/transaction_variant/_additional_information_tabbed.html.erb, app/views/transaction_variant/show.html.erb, test/integration/transaction_test.rb
We're running an AB test where Verify is the primary option and NINO is in the 'Other ways'
This commit creates a new B variant which is hardcoded and served for user with B cookie.
This test is due to be started on the morning of Tuesday 17th and initially run for 3 days.
The cookie name is 'ABTest-ViewDrivingLicence'.
Co-Authored-By: Rachel Smith <rachel.smith@digital.cabinet-office.gov.uk>
=> HUB-194: AB test for DVLA View Driving Licence

app/views/simple_smart_answers/flow.html.erb
As a user who has completed a service
I want to know what the next step is that I need to complete
So that I can finish the thing I am trying to do
If a user is routed to a service from the step-by-step, they are sent away from GOV.UK to the service which is run and hosted by another department.
They don't return to GOV.UK until they complete the service and are routed to the done page.
e.g. https://www.gov.uk/done/apply-for-divorce
Done pages are created by content designers on GOV.UK, and should be created alongside a start page, so every service should have one.
Done pages were originally created to be used with [performance platform](https://www.gov.uk/performance/vehicle-tax) to make it possible to track whether users "complete" the service.
If we don't add the side-nav to the done …
=> Add step-by-step navigation sidebar to simple smart answers "done" pages

Gemfile, Gemfile.lock, app/controllers/local_transaction_controller.rb, lib/local_transaction_location_identifier.rb, test/functional/local_transaction_controller_test.rb
Currently if a user enters a NI postcode, they are taken to a page linking to their local authority.  This is incorrect as electoral registration in NI is handled by a central body (Electoral Office for Northern Ireland).
If we were to update this the URL in Local Links Manager it would still display the LA name in place of EONI.
Therefore this PR uses the constituent country name from MapIt to determine if a postcode is in NI.  If it is, the user is redirected to `/get-on-electoral-register/electoral-office-for-northern-ireland` instead of `/get-on-electoral-register/local_authority`.
Note also that we cannot add EONI into Local Links Manager since it is not a LA and does not have the various codes associated with a LA (e.g. GSS code).
Current:
Updated: …
=> Redirect NI postcodes to EONI instead of local authority for /get-on-electoral-register

app/helpers/travel_advice_helper.rb, app/presenters/travel_advice_index_presenter.rb, app/views/travel_advice/index.html.erb, test/unit/presenters/travel_advice_index_presenter_test.rb
https://trello.com/c/wnoGa6X0/346-spike-changing-the-travel-advice-page-to-list-countries-beginning-with-the-under-the-letter-of-the-next-word-in-their-name-05-da
Ignores **The** definite article when grouping and sorting countries by name.
Example: https://govuk-frontend-app-pr-1570.herokuapp.com/foreign-travel-advice
Do not merge as this needs content review.
=> Ignore definite article when ordering countries

app/presenters/licence_details_presenter.rb, app/views/licence/_action.html.erb, app/views/licence/_authority_details.html.erb, app/views/licence/_authority_url.html.erb, test/integration/licence_test.rb, test/unit/presenters/licence_details_presenter_test.rb
Currently a link to "find your local council" will be shown when the local authority does not use licensify.  This changes the behaviour to display a link to the local authority's own website when this is available.
A new value in the API has been added (`usesAuthorityUrl`) which tells us whether we should display a local authority URL or not.
Before:
After:
Trello card: https://trello.com/c/MnhOjdCb/433-show-local-authority-url-to-licensing-users
=> Show the local authority URL when available in licensing API

app/views/homepage/index.html.erb
The GOV.UK homepage currently has a relative canonical URL meta tag:
`<link rel="canonical" href="/">`
It should have an absolute URL, like our other pages: 
`<link rel="canonical" href="https://www.gov.uk/">`
This would encourage Google to choose our preferred 'www' subdomain in search results, rather than displaying 'https://gov.uk/' when you search for 'gov.uk'.
It's also recommended by Google as part of implementing the Sitelinks Searchbox schema (https://trello.com/c/L31BqRox/60-add-sitelinks-searchbox-schema-to-allow-a-search-box-to-appear-on-the-google-serps-for-govuk).
(We're unable to set our preferred subdomain through Search Console, because we don't have the root https://gov.uk/ domain verified as a site we own.)
No measurable user impact expected.
Review whether the URL …
=> Fix the canonical tag for the homepage

config/environments/production.rb
It seems we're not minifying the Javascript in this application, while other apps do do that.
https://assets.publishing.service.gov.uk/frontend/frontend-94ffbabf50d2ec5b12950258a60a5a4f30124cd10bbd0782a20c8a7b837b6f70.js
vs
https://assets.publishing.service.gov.uk/collections/application-c8e1d43207b84a7024edfcc1d3817c69838349c8fdd51006729a19b4fd27f08c.js
The `collections` app has this line in `production.rb`, which might solve our issue here.
https://trello.com/c/qFgPsvNL
=> Attempt to minify the javascripts

app/presenters/travel_advice_index_presenter.rb
The format of these kind of links has changed since https://github.com/alphagov/publishing-api/pull/1351 so we need to update this code to support both kind of links.
This was missed in the above PR because they are automatically generated reverse links. The travel advice pages link to the index page as a parent, not the other way around.
=> Take child country information from the details hash

app/presenters/travel_advice_index_presenter.rb, test/test_helper.rb, test/unit/presenters/travel_advice_index_presenter_test.rb
In https://github.com/alphagov/frontend/pull/1643 we supported the situation where the fields are in the details hash and when they are not, now we only want to support the new style where they are only in the details hash.
=> Fetch country child link details from details hash

app/controllers/transaction_controller.rb, app/presenters/transaction_presenter.rb, app/views/transaction/show.html.erb, config/routes.rb, test/functional/transaction_controller_test.rb, test/integration/transaction_test.rb
Update TransactionPresenter and TransactionController to support variants.
Update routes to include a optional `variant` slug on the transaction route.
=> HUB-384: Add Variant Support to transaction renderer

app/presenters/content_item_presenter.rb, test/functional/licence_controller_test.rb, test/integration/licence_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/unit/presenters/content_item_presenter_test.rb
`public_updated_at` is set when a major version is published.  We want to show this date on content, rather than `updated_at` which is updated when anything is changed on the item.
https://github.com/alphagov/publishing-api/blob/73d85593b41d149de74ac435b5a11a297ee1b28c/doc/api.md#L131
> For an update_type of "major" the public_updated_at field will be updated to the current time
Government Frontend uses public_updated_at too.
=> Use public_updated_at dates instead of updated_at

app/assets/javascripts/transactions.js, app/assets/stylesheets/application.scss, app/views/transaction/_additional_information_tabbed.html.erb, spec/javascripts/unit/transactions.spec.js
After [updating the calendars frontend](https://github.com/alphagov/calendars/pull/483) to use [the new tabs component from the gem](https://content-publisher.integration.publishing.service.gov.uk/component-guide/tabs) this is the only other place where we use the jQuery-based tabs.
This PR replaces the jQuery-based tabs with the tabs component in an effort to [remove legacy scripts from static](https://github.com/alphagov/static/tree/master/app/assets/javascripts) (in this case `jquery.tabs.js` and `jquery.history.js` with a cumulative potential save of ~16kb).
=> Replace jQuery-based tabs with component

app/controllers/application_controller.rb, app/controllers/concerns/aa_testable.rb, app/views/layouts/application.html.erb, test/functional/homepage_controller_test.rb
This PR adds a new concern `AATestable`, which will be used to run an A/A test to determine
variance in our metrics and help guide metrics to use for upcoming A/B tests on related links.
Solo: @karlbaker02
=> Add related links A/A test to all routes

app/assets/stylesheets/application.scss
This PR fixes recent overwrites that weren't properly scoped to the tabs component elements and, as a result, were affecting content inside the tabs component.
Thanks @keithiopia and @thomasleese for quickly flagging this in https://github.com/alphagov/frontend/pull/1726/files/58cf8e88ff09846239285134334eee6033e5e9ff#r249080587
=> Scope overwrites to tabs component

app/views/homepage/_categories.html.erb, app/views/homepage/index.html.erb
Change ordered lists for categories and large numbers on the homepage to unordered lists as their order is not important and can confuse screen reader users.
This doesn't change anything visible.
I was tempted to also merge the 3 category lists into 1 single list. But that needs a bit more thought.
=> Improve homepage list semantics

app/views/shared/_publication_metadata.html.erb, test/integration/licence_test.rb, test/integration/place_test.rb, test/integration/simple_smart_answers_test.rb, test/integration/transaction_test.rb
"Do a thing" content is our best content and is aimed at the majority of GOV.UK users. When it's updated though, it is rarely a major update which means the "last updated" date on the content is often something like 2013.  This does not add anything to the user's comprehension or confidence that they're looking at something that is current and relevant.
We're about to publish a "Services" finder which allows users to find this sort of content more easily, however we won't be adding a date sort to the finder because it's just not relevant for this sort of content.
cc @keithiopia
=> Remove updated date information

app/controllers/application_controller.rb, app/controllers/concerns/ab_testable.rb, test/functional/homepage_controller_test.rb, test/functional/transaction_controller_test.rb
This PR adds support for the Related Links A/B test, showing a different set of related links on the B variant from the content item's `suggested_ordered_related_items`, where it exists. It also updates the current `RelatedLinksAATest` to be `RelatedLinksABTest`.
Trello: https://trello.com/c/byNrHEMw
=> Update related links A/B test and add tests

app/views/homepage/index.html.erb
https://trello.com/c/CvwsYUuD/341-replace-announcements-link-in-header-footer-and-on-homepage
This switches the link from `/government/announcements` to `/news-and-communications`  on the homepage.
This is a new finder replacing an old finder. View the new finder: https://www.gov.uk/news-and-communications.
=> Change link from Announcements to News and communications

app/controllers/concerns/ab_testable.rb, test/functional/homepage_controller_test.rb, test/functional/transaction_controller_test.rb
This commit updates the A/B test variant for related links from `RelatedLinksABTest1` to `RelatedLinksABTest2`. This is to support the second iteration of the A/B test which is using a new set of related link data.
Trello: https://trello.com/c/H6dFvnsH
=> Update related links A/B test variant

app/controllers/concerns/ab_testable.rb, test/functional/homepage_controller_test.rb, test/functional/transaction_controller_test.rb
This PR updates the A/B test variant for related links from `RelatedLinksABTest2` to `RelatedLinksABTest3`. This is to support the third iteration of the A/B test which is using a new set of related link data.
=> Update related links A/B test variant for test #3

app/controllers/application_controller.rb, app/controllers/concerns/ab_testable.rb, test/functional/homepage_controller_test.rb, test/functional/transaction_controller_test.rb
This PR adds an additional `C` variant for the upcoming related links A/B test iteration v3. In the previous test we saw some users who had the control variant cookie, yet navigated via the related links which are only shown on the `B` variant.
In order to check if there are any problems with our A/B testing framework, in addition to making the data collection easier for later analysis, we are introducing the new `C` variant which will become our test variant. How the variants now work are as follows:
- `A` variant: No users should ever end up in this variant, as our CDN will be configured it to assign 0% of users. If users do end up in this variant, we may have issues with our A/B testing framework which will require further investigation.
- `B` variant: Our control variant, where …
=> Add additional variant for Related Links A/B test v3

app/views/homepage/index.html.erb
Replace consultations link and remove publications link on homepage.
Trello: https://trello.com/c/1qYHVZgS/515-replace-consultations-link-and-remove-publications-link-on-homepage
=> Update consultations link and remove publication link

app/views/homepage/index.html.erb
- update to point to new finder-frontend statistics finder
Trello card: https://trello.com/c/EEJupWMu/516-replace-stats-link-on-homepage
=> Replace statistics link on homepage

app/controllers/concerns/ab_testable.rb, test/functional/homepage_controller_test.rb, test/functional/transaction_controller_test.rb
This PR updates the A/B test variant for related links from `RelatedLinksABTest3` to `RelatedLinksABTest4`. This is to support the fourth iteration of the A/B test which is using a new set of related link data.
=> Update variant for Related Links A/B test v4

app/views/homepage/index.html.erb
The new statistics finder is currently not showing the right things, so we'll revert to the old one in the meantime.
=> Change statistics link

app/presenters/licence_details_presenter.rb, startup.sh, test/unit/presenters/licence_details_presenter_test.rb
This is a bugfix to ensure we display the correct issuing authority when rendering pages such as https://www.gov.uk/house-in-multiple-occupation-licence/hartlepool/apply.
We currently display a different (incorrect) local authority on some pages, such as the one above.
This is because when we request a licence from the Licensify API, we receive multiple issuing authorities. If the license we receive has the `location_specific=true` flag, then we assume that the first issuing authority in the issuingAuthorities array is the correct one.
The licensify API will respond with multiple authorities when you request a licence; the authority array order cannot be depended upon. E.g. this license for cheshire east is also used by other authorities, but we only care about cheshire east: …
=> Display correct licence authority on license pages

app/controllers/licence_controller.rb, test/integration/licence_test.rb, test/unit/presenters/licence_details_presenter_test.rb
This will ensure that we use the correct licence authority in the view.
Trello: https://trello.com/c/U90O3XXg/565
=> Provide authority slug to license details presenter

config/routes.rb
https://edgeguides.rubyonrails.org/routing.html#using-root states:
> You should put the root route at the top of the file, because it is the
> most popular route and should be matched first.
This is especially pertinent for Frontend because we use routing constraints that request content items to check the schema of the page to determine where to send it.
The homepage doesn't need to worry about this stuff, so let's not slow it down by unnecessarily checking things.
In a similar vein, the component guide is not routed to in production, so it kind of makes more sense to put it at the bottom of the routes file so that it doesn't have to be compared with any requests for matching.
=> Move root route to the top of the routes.rb file

lib/homepage_publisher.rb, test/unit/homepage_publisher_test.rb
Currently the homepage does not have a `primary_publishing_organisation`
or any other organisations.
We want to be able to filter on `primary_publishing_organisation`
in `content-data-api' so want this to be populated.
This commit adds GDS to `organisations` and `primary_publishing_organisation`
in `links` with a call to `patch_links` when the homepage is updated.
The existing `publishing_api:publish_special_routes` rake task will
make this happen.
=> Homepage: patch_links with GDS as organisation

app/views/homepage/index.html.erb
The homepage section about government departments has two adjacent links that both link to the same page, but have different text.
**How does this affect users**
Confusing for screen readers and confusing for cognitive issues
WCAG 2.4.4 (A)
To mitigate against this, we should amend both links and the page they point to, so that links anchor to the relevant section.
This work needs to follow https://github.com/alphagov/collections/pull/1134
Side note: shouldn't the "Agencies and other public bodies" number be updated as well?
=> Update homepage 'department and policy' section links

app/assets/stylesheets/views/_homepage.scss, app/views/homepage/index.html.erb
Adjust departments and bodies list alignment using govuk-frontend styling.
IMHO looks better this way. Preview: https://govuk-frontend-app-pr-1857.herokuapp.com/
**Before:** 
**After:**
=> Adjust departments list alignment on gov.uk homepage

app/assets/stylesheets/views/_cookie-settings.scss, app/views/help/cookie_settings.html.erb, config/locales/en.yml
Updating content on the new cookie settings page. Content has already been approved by a content designer.
=> Update content for the new cookie settings page

app/assets/javascripts/modules/cookie-settings.js, app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_cookie-settings.scss, app/controllers/help_controller.rb, app/views/help/cookie_settings.html.erb, config/locales/en.yml, config/routes.rb, lib/special_route_publisher.rb, spec/javascripts/unit/modules/cookie-settings.spec.js, test/functional/help_controller_test.rb, test/integration/help_cookies_test.rb
New page at `/help/cookies` which will allow users to adjust their cookie preferences (opt in/out of the different categories)
The page needs to be published as a special route using the `publish_special_routes` rake task - this will be done after this PR is merged. 
Page can be viewed here: https://new-cookie-banner.herokuapp.com/help/cookies
=> Add cookie settings page

app/controllers/application_controller.rb, app/controllers/completed_transaction_controller.rb, app/controllers/error_controller.rb, app/controllers/find_local_council_controller.rb, app/controllers/help_controller.rb, app/controllers/licence_controller.rb, app/controllers/local_transaction_controller.rb, app/controllers/place_controller.rb, app/controllers/simple_smart_answers_controller.rb, app/controllers/transaction_controller.rb, app/controllers/travel_advice_controller.rb
This moves the config to use the `wrapper` layout to the controllers. This makes it easier to start converting all the templates one by one by removing the line and fixing issues.
https://trello.com/c/jmKImOgK
=> Move slimmer template config to controllers

app/assets/stylesheets/views/_cookie-settings.scss, app/views/help/cookie_settings.html.erb
Hide the cookie settings form when Javascript is not available. Instead, display a message to the user informing them.
This change ties in with https://github.com/alphagov/govuk_publishing_components/pull/948
At the moment, when Javascript is not enabled the cookie settings page looks no different. However, the form does not work without Javascript - our cookie consent mechanism is based on Javascript at the moment. We therefore want to hide the form and show a different message instead.
**Link:** https://govuk-frontend-app-pr-1881.herokuapp.com/help/cookies
=> Hide cookie settings form when Javascript not available

app/views/homepage/index.html.erb
Change mentions of "EU Exit" to "Brexit" since this is what most people refer to it as.
[Trello](https://trello.com/c/2iQ09yYJ/1106-change-mentions-of-eu-exit-to-brexit)
=> Change EU Exit to Brexit

app/assets/stylesheets/application.scss
Remove an old styling fix for radio inputs.
This was a temporary fix until a [permanent solution was implemented within the gem](https://github.com/alphagov/govuk_publishing_components/pull/301). This has been implemented and the component [now uses GOVUK Frontend styles](https://github.com/alphagov/govuk_publishing_components/commit/1d4971449e0f4d95a5ac9250cb667a31798a8c69#diff-fe62b3a78b7005dd4f069f961652b72cL23) anyway, so the `gem-c-radio__input` class is no longer in use (it has been replaced by govuk-radios__input).
=> Remove old radio input styling fix

app/assets/stylesheets/application.scss
Removes the tab styles that were added to fix the overriding styles set by `.content-block`. These fixes are [now included in the CSS for the tab component within the gem](https://github.com/alphagov/govuk_publishing_components/pull/978)
These 'fix styles' for the tabs were broken on mobile and needed updating. It makes sense to move them into the component styles so there is more visibility of them when it comes to updating the component.
=> Remove tab overrides within the app

config/brakeman.ignore
Brakeman wants us to use :json and not :marshal or :hybrid, but
switching straight to :json from :marshal breaks existing sessions.
ref: https://github.com/alphagov/specialist-publisher/pull/1471
=> Ignore warning for cookie type

app/views/homepage/index.html.erb
Update statistics link on homepage to point to the shiny new finder `search/research-and-statistics`
https://trello.com/c/EEJupWMu/516-replace-stats-link-on-homepage
=> Update Statistics link on homepage

app/views/homepage/index.html.erb
/news-and-communications redirects to /search/news-and-communications,
it's not a great user experience to click a link which immediately
redirects.
=> Link directly to /search/news-and-communications

app/views/completed_transaction/_standard_satisfaction_survey.html.erb
We've stopped using negative contractions on GOV.UK
=> Replace text to reflect change in style guide

app/views/homepage/index.html.erb
Add a non-breaking space.
(An alternative fix might be to reduce the font size at an earlier breakpoint)
=> Stop single word in campaign from wrapping on iPad

app/assets/stylesheets/views/_homepage.scss
Fix erroneous underline and focus state on homepage promotion link for bank holidays.
Changes this (normal):
And this (focus):
To this (normal):
And this (focus):
=> Fix homepage promo link

app/views/find_local_council/_base_page.html.erb, app/views/shared/_base_page.html.erb, app/views/simple_smart_answers/flow.html.erb
Looks like I missed a few pages when I removed toolkit recently - fortunately this hasn't been deployed to live yet.
- fixes simple smart answers (e.g. /settle-in-the-uk), find local council (/find-local-council) and content pages (e.g. /change-driving-test)
Example of the broken:
Is fixed in this PR to look like this:
=> Fix layout with govuk-frontend grid

app/views/help/index.html.erb, lib/special_route_publisher.rb
Changes the link and description for the Privacy Notice - which was previously called the Privacy Policy. 
[Trello card](https://trello.com/c/xJMeKsoR/1348-update-privacy-policy-ref-on-govuk-help-page)
=> Change path and description of Privacy Notice

app/assets/stylesheets/views/_homepage.scss, app/views/homepage/index.html.erb, config/locales/en.yml
Updates the following content to match the campaign:
- Heading text above the checker chevron
- Promo box
=> Update homepage content to match campaign

app/controllers/application_controller.rb, test/integration/error_handling_test.rb
Trello: https://trello.com/c/BFSkOY22
Follows on from: https://github.com/alphagov/collections/pull/1324
At the moment frontend is throwing a 500, when it receives an error code it doesn't recognise
from content-store. That means that users are shown a "Problem has occurred" page.
We need to handle this error properly so that in the case of a 403, the user will be properly routed
to signon and asked to login if there is any form of access limiting on the content item (e.g. hosted on draft stack, access limited to organisation etc)
=> Rescue 403 errors from content-store

app/assets/stylesheets/views/_homepage.scss, app/views/homepage/index.html.erb
- Remove: “get ready arrow”
- Change: Content in call to action area
- Add text link to landing page
Co-Authored-By: Alex Jurubita <alexandru.jurubita@digital.cabinet-office.gov.uk>
=> Change call to action section of homepage

app/controllers/application_controller.rb, app/controllers/licence_controller.rb, lib/content_format_inspector.rb, lib/services.rb, test/support/content_store_helpers.rb, test/unit/content_format_inspector_test.rb
This simplifies the code by using `GdsApi` directly and avoids us having to maintain a `Services` module.
=> Use GdsApi

Gemfile, Gemfile.lock, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/mailer.rb, config/secrets.yml, lib/notify_delivery_method.rb, spec/lib/notify_delivery_method_spec.rb
This will allow us to send out emails using ActionMailer via GOV.UK Notify.
This is heavily based on https://github.com/alphagov/content-publisher/pull/881 and https://github.com/alphagov/content-publisher/pull/889.
[Trello Card](https://trello.com/c/ieb0fLIY/15-add-notify-client-to-frontend)
=> Add a Notify delivery method for ActionMailer

config/routes.rb
We used `/funding-form` as a placeholder.  This should be changed to `/brexit-eu-funding`.
=> Change path for EU Funding Registration form

app/jobs/application_job.rb, app/jobs/email_delivery_job.rb, app/mailers/funding_form_mailer.rb, config/application.rb, config/sidekiq.yml
This configures ActiveJob and creates an email delivery job which retries on Notify failures.
[Trello Card](https://trello.com/c/W3s3IVUg/20-deal-with-error-response-from-notify)
=> Use ActiveJob for sending emails

app/controllers/funding_form/contact_controller.rb, config/routes.rb, spec/controllers/funding_form/contact_controller.rb
This implements the submission behaviour for the EU Funding Registration form.  Entry is stored in the session variables and user is redirected to the next step.
Trello card: https://trello.com/c/76etZtff
=> Add controller methods for contact details submission

Procfile
At the moment Sidekiq automatically infers the tag using the basename of the application. In the draft stack this ends up being `draft-frontend` even though `GOVUK_APP_NAME` remains as `frontend`. This means our alerting in the draft stack doesn't work because it's looking for a Sidekiq process called `frontend`, not `draft-frontend`.
=> Set the tag on the Sidekiq worker process

app/controllers/funding_form/grant_agreement_number_controller.rb, app/controllers/funding_form/programme_controller.rb, config/routes.rb, spec/controllers/funding_form/grant_agreement_number_controller.rb
This implements the submission behaviour for the EU Funding Registration form.  Entry is stored in the session variables and user is redirected to the next step.
Trello card: https://trello.com/c/YsmQB2RF
=> Add controller methods for grant agreement number submission

app/controllers/funding_form/organisation_details_controller.rb, spec/controllers/funding_form/organisation_details_controller.rb
This implements the submission behaviour for the EU Funding Registration form.  Entry is stored in the session variables and user is redirected to the next step.
Views are left blank since they are being implemented in other PRs.
Trello card: https://trello.com/c/tl4ZPGhd
=> Add controller methods for organisation details submission

app/views/funding_form/organisation_details.html.erb, config/locales/en.yml
Specifically, this view allows the capture of details of the organisation registering 
Trello card - https://trello.com/c/816FhrcN
=> added Organisation details form

app/controllers/funding_form/contact_information_controller.rb, app/views/funding_form/contact_information.html.erb, config/locales/en.yml, config/routes.rb
Specifically, this view allows the capture of contact details of the grant recipient registering 
Trello card - https://trello.com/c/OoPp9gsm
=> Contact information

app/controllers/funding_form/grant_agreement_number_controller.rb, app/views/funding_form/grant_agreement_number.html.erb, config/locales/en.yml
Specifically, this view requires the response to a yes/no question if an agreement number is available, if so then requests user to enter it
Trello card - https://trello.com/c/SK3tPHua
=> Added do you have a grant agreement number view

app/views/funding_form/programme.html.erb, config/locales/en.yml
Specifically this view is to allow selection of the body that the grant recipient receives their funding from, from a specified list
trello card - https://trello.com/c/bMJh0VOu
=> Added what programme funding is from form

app/assets/stylesheets/application.scss, app/assets/stylesheets/helpers/_overwrites.scss, app/controllers/funding_form/check_answers_controller.rb, app/controllers/funding_form/project_details_controller.rb, app/views/funding_form/organisation_details.html.erb, app/views/funding_form/organisation_type.html.erb, app/views/funding_form/project_details.html.erb, config/locales/en.yml, spec/features/funding_form_spec.rb
Specifically, this view allows the capture of project details for the funding  
Trello card - https://trello.com/c/myzVfpOo
=> added project details view

app/controllers/funding_form/partners_controller.rb, app/controllers/funding_form/project_details_controller.rb, config/routes.rb, spec/controllers/funding_form/project_details_controller.rb, spec/controllers/partners_controller.rb
This new step was added to the prototype yesterday, and sits between the final question and the check your answers page.
=> Add a new step (external partners/participants) to funding form

app/controllers/funding_form/organisation_type_controller.rb, spec/controllers/funding_form/organisation_type_controller.rb
Whilst the organisation_type_other input field is hidden to the user when an option other than "Other" is selected, it is still submitted with an empty value.  This change ignores a blank value so the value is always set correctly.
=> Deal with organisation_type_other being an empty string

app/controllers/funding_form/confirmation_controller.rb, app/views/funding_form/confirmation.html.erb, config/locales/en.yml
Specifically, this view feeds back to the use the confirmation status of the journey
Trello card - https://trello.com/c/2oeo2Rsp
=> added confirmation page at end of the journey

app/views/funding_form_mailer/confirmation_email.text.erb, app/views/funding_form_mailer/department_email.text.erb, spec/mailers/funding_form_mailer_spec.rb
ActiveJob turns the symbols into strings.
[Trello Card](https://trello.com/c/6KjmXDuL/65-send-emails-after-submitting-the-form)
=> Use strings in email templates

app/views/transaction/show.html.erb, test/integration/transaction_test.rb
This PR adds schema.org `GovernmentService` schema to transaction pages via the machine readable metadata component of `govuk_publishing_components`. By adding this schema to transaction pages, we will mark government services as such to search engines, as well as increasing search relevancy and enabling rich snippets to be created from this data.
=> Add schema.org GovernmentService schema to transaction pages

app/views/funding_form/partners.html.erb, config/locales/en.yml
Specifically, this view allows the selection of a yes/no answer to the question "Does the project have partners or participants outside the UK?"
Trello card - https://trello.com/c/KnvwRmhf
=> added non uk participants page

app/views/funding_form_mailer/department_email.text.erb
This will reduce the amount of scrolling required by the Cabinet Office Grants Management Function team when they receive these emails.
=> Move 'copy and paste' to top of EU funding department email

app/controllers/funding_form/check_answers_controller.rb, app/views/funding_form/confirmation.html.erb, spec/controllers/funding_form/check_answers_controller_spec.rb
Adds reference number to the confirmation screen, and reduces length of the reference number.
=> Show reference number on EU Funding form confirmation

app/views/homepage/index.html.erb
I thought this looked a bit weird,
On the [home page](https://www.gov.uk/) scroll down to the `<section>` `departments-and-policy` and we tell users there are 405 currently.
Click though on that number and immediately you see a different number...
This PR brings them back into alignment.
As an aside, I expect this number changes frequently. I'm not quite sure how best to deal with that. I was thinking of writing an e2e test that stores this number, clicks through and then assets equal with the number on whitehall?
Is there a good reason why this number doesn't dynamically update already?
Happy to open an issue or extend an existing one if this discussion has already been had?
=> Update count of agencies and public bodies to 407

app/views/funding_form/companies_house_number.html.erb
After testing the end-to-end tracking for the "Register as an organisation getting funding directly from the EU" application we've found that the "Companies House Number" page was missing data. This PR fixes it by adding the appropriate data attributes to the form.
[Trello card](https://trello.com/c/hjttLYj6)
=> Add tracking for the companies house number page

app/assets/stylesheets/views/_homepage.scss
This originates from #1653 (thanks!), but has to be in a HEAD branch to trigger CI.
Fixes #1268.
Before:
After:
=> Bumped homepage popular title from 14 -> 24px

app/views/completed_transaction/show.html.erb
- The government has a goal to reach zero carbon emissions by 2050, and
electric cars are part of that.
Related PRs: https://github.com/alphagov/publisher/pull/1149 and https://github.com/alphagov/govuk-content-schemas/pull/929.
https://trello.com/c/FmE5xU1p/1478-3-add-new-bespoke-message-to-specific-completed-transaction-pages
=> Add text for the new done page promo on electric vehicles

Gemfile, Gemfile.lock
Bumps govuk_publishing_components to version 21.9.0. This includes a change which adds a related link to the Brexit landing page on pages tagged to /brexit, /world/brexit, or any child taxon of /brexit.
Examples to check:
https://govuk-frontend-app-pr-2093.herokuapp.com/staying-uk-eu-citizen
https://govuk-frontend-app-pr-2093.herokuapp.com/get-ready-brexit-check
**Note: positioning of the related links sidebar is incorrect, but this is present on live. I'll address this as a separate piece of work.**
=> Update to govuk_publishing_components 21.9.0

app/assets/stylesheets/views/_homepage.scss
It was initially 14px, then updated to 24px (which is too big), now 19px — which is in line with the rest of the text in the header.
=> Update home top links title size

config/initializers/gds_api.rb
The comment in the file lies, as it's [not overwritten by anything else](https://github.com/alphagov/govuk-app-deployment/blob/master/frontend/config/deploy.rb). We don't need to log these interactions because we can link them together using `govuk_request_id` anyway.
[The default in gds-api-adapters is the null logger](https://github.com/alphagov/gds-api-adapters/blob/e3a0aa6f795df158e88df3e825207d785c7ac32f/lib/gds_api/base.rb#L39)
These logs aren't ingested into Logit, so it's likely that no one uses them.
Should we wish to turn these back on, [logging api interactions is documented in the gds-api-adapters README](https://github.com/alphagov/gds-api-adapters#logging)
=> Remove GdsApi logger configuration

app/controllers/funding_form/check_answers_controller.rb, app/controllers/funding_form/companies_house_number_controller.rb, app/controllers/funding_form/contact_information_controller.rb, app/controllers/funding_form/grant_agreement_number_controller.rb, app/controllers/funding_form/organisation_details_controller.rb, app/controllers/funding_form/organisation_type_controller.rb, app/controllers/funding_form/programme_controller.rb, app/controllers/funding_form/project_details_controller.rb, spec/controllers/funding_form/check_answers_controller_spec.rb, spec/controllers/funding_form/companies_house_number_controller_spec.rb, spec/controllers/funding_form/contact_information_controller_spec.rb, spec/controllers/funding_form/grant_agreement_number_controller_spec.rb, spec/controllers/funding_form/organisation_details_controller_spec.rb, spec/controllers/funding_form/organisation_type_controller_spec.rb, spec/controllers/funding_form/programme_controller_spec.rb, spec/controllers/funding_form/project_details_controller_spec.rb
EU Funding users can edit their responses from the Check Your Answers page, but they have to go through the entire questions workflow again.  This change will return them to the Check Your Answers page if they have seen this page before.
Trello card: https://trello.com/c/rw4sT1l4
=> Allow EU Funding form users to edit responses without going through full workflow

app/helpers/mandatory_field_helper.rb, config/locales/en.yml, spec/helpers/mandatory_field_helper_spec.rb
Several changes:
- Removes the "Enter a real date" error when user has entered an incomplete date (they will continue to receive an error for the missing part of the date)
- Sentence cases all error messages that are generated using the field label
- Adds custom error messages for a number of fields in the registration form
- Adds tests for the mandatory fields validation helper
Trello card: https://trello.com/c/BkN0FoAR
=> Fix validation messages for EU Funding Form

config/machine_readable/register-to-vote.yml, test/integration/transaction_test.rb
We're adding a query param to the links in the FAQPage schema to help us measure when traffic is being referred from links parsed from the schema, and when it's coming from more traditional means.
[The query param (`?foo=bar`) should go before the fragment (`#baz`)](https://tools.ietf.org/html/rfc3986#section-4.2) where applicable.
We've also removed "your name" from a sentence to match recently updated content.
Before:
> Register to get `your name` on the electoral register. You need to be on the electoral register to vote in elections and referendums.
After:
> Register to get on the electoral register. You need to be on the electoral register to vote in elections and referendums.
=> Add query params and fix content

app/helpers/currency_helper.rb, app/helpers/date_time_helper.rb, app/views/funding_form/check_answers.html.erb, spec/features/funding_form_spec.rb, test/unit/helpers/currency_helper_test.rb, test/unit/helpers/date_time_helper_test.rb
Update check your answers/summary page to avoid errors when content is not provided. This includes:
- format a number only if provided to the helper
- format a date only when provided to the helper
- output address fields even when not all presented (e.g. 2nd Building and street input)
- fix town on the summary page
Fixes for https://trello.com/c/X5DUZQA6 and https://trello.com/c/OyJykI3u after validation updates.
=> Fix formatting on check your answers page

app/controllers/funding_form/companies_house_number_controller.rb, app/controllers/funding_form/grant_agreement_number_controller.rb, app/views/funding_form/check_answers.html.erb, app/views/funding_form/companies_house_number.html.erb, app/views/funding_form/grant_agreement_number.html.erb, app/views/funding_form_mailer/department_email.text.erb, spec/controllers/funding_form/companies_house_number_controller_spec.rb, spec/controllers/funding_form/grant_agreement_number_controller_spec.rb
There were a number of issues around the conditional reveal questions in the EU Funding Form:
- "Yes" was always pre-selected with a blank value in the text field when the user had not previously answered the question
- If the user left the field blank but returned to check their answers, the text field would be populated with the word "Yes"
- If the user selected "No" but returned to check their answers, the free text field would be populated with the word "No"
This resolved the issue by storing the boolean value separately from the free text response.  Additionally, the logic has been fixed for determining whether to check the boxes, and whether to display text value.
Trello card: https://trello.com/c/QmvBxA8k
=> Fix conditional reveal for EU Funding Form

app/controllers/funding_form/contact_information_controller.rb, app/controllers/funding_form/organisation_details_controller.rb, app/helpers/mandatory_field_helper.rb, config/locales/en.yml, spec/features/funding_form_spec.rb, spec/helpers/mandatory_field_helper_spec.rb
Update validations to:
- check for email address to contain `@` symbol
- check postcode to have a valid format
and raise appropriate errors.
[Trello card](https://trello.com/c/m2RqJ3Tr)
=> Validate email and postcode

app/controllers/funding_form/organisation_type_controller.rb, app/mailers/funding_form_mailer.rb, app/views/funding_form/check_answers.html.erb, app/views/funding_form/organisation_type.html.erb, app/views/funding_form_mailer/department_email.text.erb, spec/controllers/funding_form/organisation_type_controller_spec.rb
Previously when users selected "Other" for the organisation type on the EU Funding form and did not enter a value, they saw an error message but the Other button was deselected.  This fixes the logic so the option remains selected.
Additionally, I have refactored the code for the copy and paste line in the departmental email.  This was getting quite lengthy, with the pipe delimiter specified between each value, so have moved this out of the view, put it over several lines and used `join` to remove the multiple delimiters.
Trello card: https://trello.com/c/TUZXUOgK
=> Fix "other" options on EU Funding Form organisation type question

config/machine_readable/register-to-vote.yml, test/integration/transaction_test.rb, test/unit/helpers/currency_helper_test.rb, test/unit/helpers/date_time_helper_test.rb
The postal voting deadline in Northern Ireland has now passed.
This should match the changes in https://publisher.publishing.service.gov.uk/editions/5dd5755ce5274a0acb7cb8e3/diff
Also resolves messages like:
> DEPRECATED: Use assert_nil if expecting nil from test/unit/helpers/date_time_helper_test.rb:12.
> This will fail in Minitest 6.
=> Update register to vote schema

app/controllers/funding_form/contact_information_controller.rb, app/controllers/funding_form/organisation_details_controller.rb, app/controllers/funding_form/project_details_controller.rb, app/helpers/error_items_helper.rb, app/helpers/mandatory_field_helper.rb, app/views/funding_form/_validation_error.html.erb, app/views/funding_form/companies_house_number.html.erb, app/views/funding_form/contact_information.html.erb, app/views/funding_form/grant_agreement_number.html.erb, app/views/funding_form/organisation_details.html.erb, app/views/funding_form/organisation_type.html.erb, app/views/funding_form/partners.html.erb, app/views/funding_form/programme.html.erb, app/views/funding_form/project_details.html.erb, spec/helpers/mandatory_field_helper_spec.rb, test/unit/helpers/currency_helper_test.rb, test/unit/helpers/date_time_helper_test.rb, test/unit/helpers/error_items_helper_test.rb
This PR updates the way error messages are presented on the page:
- store validation errors as hashed to associate each error item with its field
- update error summary component so that each error item links to the associated input
- update each input component to have the associated error item next to it
[Trello card](https://trello.com/c/B9VCSviL)
=> Highlight invalid inputs

app/controllers/transaction_controller.rb, app/helpers/locale_helper.rb, app/views/shared/_base_page.html.erb
The base template is sometimes used for pages that aren't in English (for example, https://www.gov.uk/cofrestru-i-bleidleisio). Since the `html` element is set to be `lang="en"`, the non-English content should be wrapped with an element that has an appropriately set `lang` attribute.
The `lang_attribute` method in the locale helper will return a lang attribute to be used in the template if the language is different from the default langauge - nothing is returned if the language is the same as the default language. This can then be passed to the template to be used.
This has been added to the `_base_page.html.erb` template on the `main` element, which wraps the content that is in a different language.
No visual differences - but under the hood:
=> Add helper for adding `lang` attribute to templates

config/machine_readable/register-to-vote.yml, test/integration/transaction_test.rb
The registration deadline is at midnight tonight.  We want to make it clear what you are still able to do.
This PR will go live once the deadline has passed.
=> Prepare for register to vote deadline

app/assets/stylesheets/application.scss, app/assets/stylesheets/views/_homepage.scss, app/views/homepage/index.html.erb
Changes to the homepage to make it ready for the new higher contrast colour scheme. This has been checked with the new colours turned on, but since the colours are a global setting across all of Frontend they've been turned off. Once all of the views have been checked with the new colours this setting can be turned on.
Also added in lazy-loading of images, since it's a trivial change to make with a positive impact.
To allow GOV.UK to use the more accessible, higher contrast colour scheme.
Trello card: https://trello.com/c/wIvM9an9/113-switch-to-new-colours-in-frontend
---
=> New colours on homepage

app/assets/javascripts/views/travel-advice.js, app/assets/stylesheets/views/_travel-advice.scss, app/views/travel_advice/index.html.erb, spec/javascripts/unit/foreign-travel-advice.spec.js, test/integration/travel_advice_test.rb
Changes to the foreign travel advice page with the list of countries to make it ready for the new higher contrast colour scheme. 
The biggest visual difference is that the text size for the countries has been increased with the use of `govuk-body-s`. This should make it more readable.
The input and subscription links are now components, as the hardcoded versions before weren't picking up the new focus states.
I ran Standard lint with the `--fix` option for the JavaScript that shows and hides the list of countries, which is a reasonably big diff with no real change. A couple of things, such as a purposeful use of `==` instead of `===`, meant that the linting needed to be turned off for specific lines.
This has been checked with the new colours turned on, but since the colours are a global …
=> New colours on travel advice

app/assets/stylesheets/views/_travel-advice.scss
On the [Foreign Travel Advice search page](https://www.gov.uk/foreign-travel-advice), the `line-height` of the large letters was causing an invisble overlap with any links directly below it. This meant that the links were not clickable, as the large box of the large letter was being clicked.
Removing the bottom margin reset fixes this, as the default bottom margin pushes the content below the letter down enough to stop any overlap.
(Letter highlighted to show element box.)
(Letter highlighted to show element box.)
=> Fix box overlap causing links to be non-clickable

app/views/find_local_council/district_and_county_council.html.erb, app/views/find_local_council/index.html.erb, app/views/find_local_council/one_council.html.erb
Changes to the council results view to make it ready for the new higher contrast colour scheme. 
A couple of the links weren't using the `govuk-link` class, so weren't using the new focus styles.
The 'back' link wasn't using the back component - I don't think that this is the correct place for the back link, but that's a design decision for another day.
This has been checked with the new colours turned on, but since the colours are a global setting across all of Frontend they've been turned off. Once all of the views have been checked with the new colours this setting can be turned on.
To allow GOV.UK to use the more accessible, higher contrast colour scheme.
Trello card: https://trello.com/c/wIvM9an9/113-switch-to-new-colours-in-frontend
* gov.uk/find-local-council
* …
=> New colours on find council

config/machine_readable/register-to-vote.yml, test/integration/transaction_test.rb
This is an update to the content in the FAQPage schema for /register-to-vote
which should match https://publisher.publishing.service.gov.uk/editions/5de4e3a2ed915d11631fe499/diff
=> Update to /register-to-vote for proxy deadline

app/views/layouts/application.html.erb
=> Enable breadcrumbs for start pages

README.md, app/assets/stylesheets/application.scss, app/views/transaction/_additional_information_single.html.erb, app/views/transaction/show.html.erb
Adding the new focus states to the transaction view - which is used for:
* https://www.gov.uk/register-to-vote
* https://www.gov.uk/vehicle-tax
* https://www.gov.uk/find-a-job
Non-hardcoded content has been wrapped in the Govspeak component - this led to a slight clash with styles coming from Static, which has been fixed with a slight override.
New focus states = win!
[Trello card](https://trello.com/c/1TOzet18)
=> Update transaction view focus states

app/assets/stylesheets/views/_local-transaction.scss, app/views/local_transaction/results.html.erb
The back link on the local transaction results page was updated to be a component from GOV.UK Publishing Components.
- [Trello card](https://trello.com/c/YXG9Fe6l/136-frontend-local-transaction-colours-checked)
The local transaction views needed updating to make sure that the newest focus states were being used on all links on it - the back link was the only link that wasn't picking up the new focus state.
- https://www.gov.uk/pay-council-tax/westminster
- https://www.gov.uk/apply-council-tax-reduction/westminster
=> Update local transaction views

app/views/licence/_action.html.erb, app/views/licence/_authority_details.html.erb, app/views/licence/_authority_url.html.erb, app/views/licence/_licensify_unavailable.html.erb, app/views/licence/start.html.erb
https://trello.com/c/wbLn9yKd/135-frontend-licence-colours-checked
This adds the govuk-link class to a number of links in the licence pages, ensuring that they will pick up the correct focus states both before and after the colour switch. Example page:
https://www.gov.uk/riding-establishment-licence/tamworth
Examples (shown in non-legacy mode here, but that commit has been removed as it should be applied later when the rest of the app has been sanity checked for it)
=> Add link class to various licence links

app/views/help/ab_testing.html.erb
Minor tweaks to better align layout on the A/B testing test page.
=> Fix A/B testing test page layout

app/views/help/cookie_settings.html.erb
This is no longer a valid example as we've changed the category of this type of cookie
[Trello](https://trello.com/c/tkJeubp2)
=> Update cookies content to remove example of essential cookie

app/views/application/_location_form.html.erb
Fixes #1095
We're using [target=_blank] which has a vulnerability
https://mathiasbynens.github.io/rel-noopener/
“To prevent pages from abusing window.opener, use rel=noopener. This
ensures window.opener is null in Chrome 49 and Opera 36.”
“For older browsers, you could use rel=noreferrer which also disables
the Referer HTTP header”
=> Add noopener and noreferrer to new window links

app/controllers/funding_form/check_answers_controller.rb, app/views/funding_form/check_answers.html.erb, app/views/funding_form_mailer/confirmation_email.text.erb, config/locales/en.yml, spec/controllers/funding_form/check_answers_controller_spec.rb
We were sending the departmental email for the EU Funding Form to the Grants Management Function team at Cabinet Office.  We now need to send the form directly to the relevant department.
This change allows us to send emails to specific departments, based on the grant name selected and permits multiple email addresses to be defined for each grant.
Content in check your answers page and confirmation email (to form submitter) also updated to reflect this change.
Check your answers (before):
Check your answers (after):
=> Send EU funding email directly to relevant department

app/views/funding_form/check_answers.html.erb
Reduces the size of the whitespace between the submit button and the disclaimer inset text below for the EU Funding form's 'check your answers' page.
Before:
After:
=> Reduce gap in EU Funding check your answers form

app/controllers/funding_form/check_answers_controller.rb, spec/controllers/funding_form/check_answers_controller_spec.rb
The funding form was sending emails to departments based on the project name, rather than the correct value of the funding programme.
=> Use funding programme for determining email destination

app/assets/javascripts/modules/cookie-settings.js, app/views/help/cookie_settings.html.erb, spec/javascripts/unit/modules/cookie-settings.spec.js
If a referrer is present, the cookie settings confirmation notice displays a link to the user's previous page. This link was taking up the entire width of the parent element, and had the old focus state.
- Corrected class on link from `govuk_link` to `govuk-link` to get updated focus state.
- Changed link display from `block` to `inline` to stop the link from taking up all the space available
Before:
After:
=> Fix link in cookie settings confirmation notice

app/assets/stylesheets/application.scss, app/views/place/_option.html.erb, app/views/place/show.html.erb
The place template powers pages like [Find a passport interview office
](https://www.gov.uk/passport-interview-office). Some of the links on the search page and the results page were not showing the correct focus states.
Updates links to use the `govuk-link` class so that the new focus states are used.
Before
After
---
Before
After
=> Update links on place template

app/views/layouts/application.html.erb, app/views/travel_advice/index.html.erb
Small change to the SRI of the CSS / JavaScript to use `crossorigin='use-credentials'` rather than `crossorigin='anonymous'`. This change is part of [RFC-114](https://github.com/alphagov/govuk-rfcs/pull/114).
=> Change crossorigin from 'anonymous' to 'use-credentials'

app/views/layouts/application.html.erb, app/views/travel_advice/index.html.erb
Reverts alphagov/frontend#2181
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at ‘https://assets.integration.publishing.service.gov.uk/frontend/frontend-7f9a59db277ec340f1dc70fbf02c886072883f9243a91384b2c6405ecf3be4a9.js’. (Reason: Credential is not supported if the CORS header ‘Access-Control-Allow-Origin’ is ‘*’).`
Need to investigate this issue first.
=> Revert "Change crossorigin from 'anonymous' to 'use-credentials'"

app/views/homepage/index.html.erb
Change the homepage number of agencies and public bodies to 408
The current number is inaccurate.
Looks like this:
Links to this:
=> Change home page number of agencies and public bodies to 408

app/assets/stylesheets/views/_simple-smart-answer.scss, app/views/simple_smart_answers/_completed_question.html.erb, app/views/simple_smart_answers/_outcome.html.erb, app/views/simple_smart_answers/flow.html.erb, app/views/simple_smart_answers/show.html.erb
Update the link focus states for the simple smart answers.
The new focus states weren't being used everywhere.
- /settle-in-the-uk
Before:
After:
---
Before:
After:
---
Before: 
After:
=> Simple smart answers focus state update

app/assets/stylesheets/application.scss
The final part of moving to the new colours for this app.
Part of progress towards making GOV.UK more accessible.
Card: https://trello.com/c/wIvM9an9/113-switch-to-new-colours-in-frontend
Summary is all of the colours should move to the new palette - too many differences to list all of them here. 
Form highlight should be the brighter yellow.
Before:
After:
---
Link focus states should be the brighter yellow.
Before:
After:
---
This will lead to a slight conflict in blues with the feedback element in the footer.
Before:
After:
=> Turn legacy colours off

app/views/homepage/index.html.erb
Tiny change to promo slot on homepage:
**before**
**after**
=> Change transition period promo text

app/assets/stylesheets/views/_simple-smart-answer.scss, app/views/simple_smart_answers/_completed_question.html.erb, app/views/simple_smart_answers/_current_question.html.erb, app/views/simple_smart_answers/_outcome.html.erb, app/views/simple_smart_answers/flow.html.erb, app/views/simple_smart_answers/show.html.erb, config/locales/en.yml, test/integration/simple_smart_answers_test.rb
Updates simple smart answers to use govuk-frontend markup for the page and also to use components properly - radio component was in use but error messages, hints and question titles were still being rendered external to the component.
Removes unnecessary CSS and markup and improves component use. This came about from looking into what sass in `static` was needed and what wasn't.
- Example simple smart answer: https://www.gov.uk/settle-in-the-uk
- Test URL: https://govuk-fronte-update-sim-kcpuvt.herokuapp.com/settle-in-the-uk
---
**Before:**
---
**After:**
=> Update simple smart answers

app/views/layouts/application.html.erb, app/views/travel_advice/index.html.erb
Change to remove SRI on the JavaScript / CSS and remove the `crossorigin` attribute.
This change is part of [RFC-115](https://github.com/alphagov/govuk-rfcs/pull/115).
Changes have been tested on integration, [seen here](https://github.com/alphagov/static/pull/1993#issuecomment-580287175)
=> Remove crossorigin and SRI from our static assets (CSS/JS)

app/views/homepage/index.html.erb
Currently on live:
Link on the homepage has hard coded 25 departments:
However after click through takes you to a page that immediately says 24:
=> Change homepage to reference 24 ministerial departments

app/views/homepage/index.html.erb
This removes the `aria-hidden` attribute present on a link, which makes it findable again.
The link in the paragraph of text was being hidden from assistive technologies, which wasn't good.
=> Update bank holiday link on homepage

app/views/simple_smart_answers/_current_question.html.erb
As it turns out, the question body can be made up of HTML tabs and used as a (potentlally elaborated) description for each question. We're moving that content [from hint text](https://github.com/alphagov/frontend/pull/2198/files#diff-8acdfa3012ce93b3df3f501bf424fd67R11) to description – which allows html content, but instead of outputting raw content [as we used to](https://github.com/alphagov/frontend/pull/2198/files#diff-8acdfa3012ce93b3df3f501bf424fd67L8) we're now sanitising the markup.
<table>
<tr>
<td valign="top">
</td>
<td valign="top">
</td>
</tr>
</table>
=> Fix current question description

app/views/homepage/index.html.erb
The Grenfell promo is linking to a piece of content that's been withdrawn.
Update this to point to something currently relevant.
The coronavirus promo link is pointing to a slug that was updated and redirected earlier.
Change this so we avoid a redirect.
=> Update grenfell link and coronavirus link

app/views/homepage/index.html.erb
Update the homepage promo link
All coronavirus content is tagged to the topical event page, so we want users to find the info that is relevant to them
https://govuk.zendesk.com/agent/tickets/3928783
=> Update homepage promo link for coronavirus

app/controllers/completed_transaction_controller.rb, app/controllers/concerns/electric_car_ab_testable.rb, app/views/completed_transaction/show.html.erb, config/locales/en.yml, test/functional/completed_transaction_controller_test.rb, test/integration/completed_transaction_test.rb
This test compares click through rates of people visiting the two done pages:
- /done/vehicle-tax
- /done/check-vehicle-tax
We append the variant name on to the end of the URL that leads to the GoUltralow website so that we they can do some measurement based on what users have seen here.
Measurement on GOV.UK only occurs if users have opted in to cookies (I can't speak for what happens on the destination website). People who haven't opted in will get the control variant which does not add a tracking query parameter to the link.
The config in en.yml will be changing when we get the final list from DfT.
https://trello.com/c/In6XcrQU/1399-set-up-dft-multi-variant-a-b-test-test-dev-work
Also hooks in with https://trello.com/c/EpuznchJ/1398-dft-for-the-multivariate-test-analytics-tasks
=> Add AB test for electric cars

lib/tasks/publishing_api.rake
It currently isn't possible to [unpublish these using the special-route-publisher](https://github.com/alphagov/special-route-publisher/blob/0e0bfa8fdf9aef998a86601ac787c87aadc173f0/data/special_routes.yaml#L23-L71) so I've added this temporary Rake task. Once I've run the task, I will delete this code.
=> Add a task for unpublishing the EU funding form routes
