alphagov/frontend

- app/views/licences/_introduction.html.erb
- app/views/root/_location_form.html.erb
- config/locales/en.yml
- test/integration/licence_lookup_test.rb
- test/integration/local_transactions_test.rb
- test/integration/places_test.rb
Please see for more details:
https://www.agileplannerapp.com/boards/105200/cards/5814
Addresses 2,3,4 and 27 of the attached spreadsheet
> Copy changes

- app/views/root/index.html.erb
:hocho: :hocho: :hocho: 
https://www.agileplannerapp.com/boards/105200/cards/9078
Linked to:
https://github.com/alphagov/static/pull/518
https://github.com/alphagov/whitehall/pull/1935
> Remove Directgov Businesslink branding

- app/assets/stylesheets/views/_make-a-sorn.scss
- app/assets/stylesheets/views/_vehicle-tax.scss
- app/views/root/make-a-sorn.html.erb
- app/views/root/vehicle-tax.html.erb
Make a SORN and Vehicle Tax online services will be
unavailable from 11:15pm on 12 January to 8am on 13 January
This is a hack but the deploy slot is at 16.30 and anyway we will need to revert the changes tomorrow morning.
https://www.agileplannerapp.com/boards/105200/cards/9111
> [URGENT]Add service unavailability callout

- app/assets/stylesheets/views/_make-a-sorn.scss
- app/assets/stylesheets/views/_vehicle-tax.scss
- app/views/root/make-a-sorn.html.erb
- app/views/root/vehicle-tax.html.erb
This reverts commit c3df49b73a4bbf1050120af27fcaaa6db558463d.
Make a SORN and Vehicle Tax services are back online.
https://www.agileplannerapp.com/boards/105200/cards/9111
> [MERGE ON morning of January 13th]Revert "Add service unavailability callout"

- app/assets/javascripts/media-player-loader.js
- app/assets/javascripts/transactions.js
- app/assets/javascripts/views/travel-advice.js
- app/assets/stylesheets/views/_help.scss
- app/assets/stylesheets/views/_make-a-sorn.scss
- app/assets/stylesheets/views/_travel-advice.scss
- app/assets/stylesheets/views/_vehicle-tax.scss
- app/assets/stylesheets/views/_view-driving-licence.scss
- app/helpers/campaign_helper.rb
- app/views/root/_guide_pagination.html.erb
- app/views/root/guide.html.erb
- app/views/root/tour.html.erb
- app/views/travel_advice/_travel_advice_navigation.html.erb
- app/views/travel_advice/index.html.erb
- lib/licence_details_from_artefact.rb
- test/integration/campaign_page_test.rb
- test/integration/programme_rendering_test.rb
- test/javascripts/unit/foreign-travel-advice-test.js
- test/routing/simple_smart_answers_routing_test.rb
- test/unit/helpers/campaign_helper_test.rb
- test/unit/simple_smart_answers/flow_test.rb
- test/vendor/jasmine-1.3.1/jasmine.js
> Remove stray whitespaces

- app/views/root/index.html.erb
Self assessment deadline is the end of this month and we want to promote it, including language they use in their wider campaign. 
[More detail in zendesk #921865]
> Change homepage promo to self assessment

- README.md
The list of formats is probably incomplete, but it's a start.
I expect the instructions for running the app to be the most helpful bit of this documentation.
> Update README to new GOV.UK standard

- app/views/root/index.html.erb
Swapped out promo spot for register to vote - needs to go live on 2 February.
> [MERGE ON 2 FEBRUARY]Promo update on homepage

- app/views/root/make-a-sorn.html.erb
- This page can't be edited through any of the publishing tools, hence https://govuk.zendesk.com/tickets/939261.
> Clarify 'Make a SORN' postal instructions

- app/views/root/index.html.erb
The changes have been 2i'ed by John Oates.
> 2i follow-up to homepage vehicle tax promo changes (#751)

- app/views/root/index.html.erb
It's now more accurate to say that they have been merged. Hurrah!
> Update the "are being merged" text on the homepage

- app/views/root/index.html.erb
The deadline to register to vote, we need to replace this promo with
bank holidays promo.
https://www.pivotaltracker.com/story/show/92781934
Before -
After -
> Replace register to vote promo with bank holidays

- app/views/root/vehicle-tax.html.erb
- Requested by the content team.
Before:
After:
> Remove the 'you will need' section on the vehicle tax page

- config/initializers/cve_2015_3226_fix.rb
Update monkey patch to include raise
> Update monkey patch to include raise

- app/views/root/transaction.html.erb
- test/fixtures/find-your-local-council.json
- test/integration/transaction_rendering_test.rb
See commits for more detail.
cc @dsingleton
> Dont treat empty strings as a valid analytics profile

- app/views/root/completed_transaction.html.erb
https://trello.com/c/9AP4TISW/190-welsh-organ-donation-law-changing-consider-link-on-transaction-done-pages-1-december
> Organ donation: there's a new law in Wales that is opt-out, not opt-in

- Gemfile
- Gemfile.lock
- lib/tasks/publishing_api.rake
https://trello.com/c/tx50hSOx/492-add-bearer-token-value-to-all-apps-using-publishing-api
> Use bearer token for publishing API authentication

- app/views/root/index.html.erb
As requested by the content team.
> Make the link EU referendum link shorter

- app/assets/stylesheets/views/_homepage.scss
- app/views/root/index.html.erb
- More prominent heading
- Fix rendering of external link icon at smaller type sizes (which are automatic from `core-x` mixins).
CC @boffbowsh @fofr @joelanman
> Tweaks to homepage promo banner design

- app/views/root/index.html.erb
Remove bottom link temporarily
Use same source tracking as other vote links
/cc @dsingleton @fofr
> Add Register to vote link to popular links block

- app/views/root/tour.html.erb
Lots of this hasn't been modified in ages. I've updated the bits which sound the most old.
> Update tour page

- Gemfile
- Gemfile.lock
This will allow to have the latest analytics functionality.
All tests pass, I pushed the branch to integration and everything seems normal.
[Trello](https://trello.com/c/mGibNI4w/420-upgrade-frontend-to-the-latest-version-of-govuk-frontend-toolkit-small)
> Upgrade govuk-frontend-toolkit

- app/views/root/index.html.erb
This should match what is shown in the following two places:
https://www.gov.uk/government/organisations
https://www.gov.uk/government/organisations#agencies-and-government-bodies
> Update department count

- app/assets/javascripts/modules/ukvi-ab-test-september-2016.js
This PR is related to #1009 
This commit addresses the issue raised by @gemmaleigh, where the p tag wrapped an unordered list.
> Fix paragraph wrapping unordered list

- app/assets/stylesheets/views/_homepage.scss
- app/views/root/index.html.erb
This is based on work done to create a very similar search box within the yet-to-be-published service manual homepage. We needed a different solution for users without Javascript as the label was larger, and tackled a few other quirks at the same time.
- Users without javascript will now see the label above the search box, rather than the label and input together next to each other within the white box.
- Fixes the focus state of the input and search box such that they do not obstruct each other.
- Alters the offset of the focus on the input to 'match' the focus of the submit button.
- Removes usage of `calc` so that the input is now full width in browsers that don't support calc (e.g. IE8, Safari 5) rather than 86% of the box.
- Increases the font size of the label from 16 to 19px …
> Improve CSS for the search box on the GOV.UK homepage

- app/views/homepage/_campaign_notification.html.erb
Related to https://github.com/alphagov/fabric-scripts/pull/228
> Improve comment in the banner related template

- app/views/search/index.html.erb
This was done in https://github.com/alphagov/frontend/pull/1011.
> Fix meta description for search pages

- app/views/homepage/index.html.erb
> Update title of EU promo on GOV.UK homepage

- Gemfile
- Gemfile.lock
- test/integration_test_helper.rb
- test/unit/artefact_retriever_with_request_cache_test.rb
- test/unit/postcode_sanitizer_test.rb
- test/unit/presenters/government_result_test.rb
- test/unit/presenters/local_authority_presenter_test.rb
- test/unit/presenters/search_results_presenter_test.rb
- test/unit/presenters/travel_advice_country_presenter_test.rb
Also taking this opportunity to remove the ENV switches in the gemfile, which are old and inconsistent between projects.
> Upgrade a handful of dependencies

- README.md
- lib/tasks/rummager.rake
We no longer depend on panopticon.
https://trello.com/c/7u8M6zrg
> Cleanup README & comments

- README.md
Alternative to https://github.com/alphagov/frontend/pull/1097.
> Make the app name more explicit

- Gemfile
- Gemfile.lock
https://github.com/alphagov/slimmer/pull/191
https://trello.com/c/TYpcs2W1
> Bump slimmer to fix memory leak

- app/views/layouts/application.html.erb
Trello: https://trello.com/c/fqPhgYA6/22-the-survey-link-doesn-t-open-in-a-new-window
> Open new nav survey in new window

- app/views/layouts/application.html.erb
See: https://github.com/alphagov/government-frontend/commit/def3f773697c01dd1ce9153e9c0fcf2961f0fea7
> Add fix for new window vulnerability

- Jenkinsfile
Otherwise, setting the environment value doesn't change anything.
> Pass env.SCHEMA_BRANCH to contentSchemaDependency

- test/unit/presenters/completed_transaction_presenter_test.rb
https://trello.com/c/nPPZhPrl/693-missing-presenter-test-in-frontend-for-completed-transaction
> Add a presenter test for CompletedTransactionPresenter

- app/views/homepage/_promo_banner.html.erb
> Link to campaign site home page from promo banner

- lib/artefact_retriever.rb
This should of been dealt with in a previous pull
https://github.com/alphagov/frontend/pull/1214
> Remove help from the artefact retreiver

- startup.sh
* Changed to follow structure of same script in government-frontend
> Update to startup script

- app/controllers/application_controller.rb
- app/controllers/concerns/benchmarking_contact_dvla_ab_testable.rb
- app/controllers/simple_smart_answers_controller.rb
- app/views/simple_smart_answers/flow.html.erb
- app/views/simple_smart_answers/show.html.erb
- test/functional/simple_smart_answers_controller_test.rb
- We're done with the A/B test for the DVLA title. We've also tested the DVLA button in the lab, and want to make it into a "proper" test.
This is a branch from a branch - #1249 - and so needs rebasing when that's merged. We don't want this merging until Thursday anyway when the lab is over with.
https://trello.com/c/R6kWqXF5/150-dvla-button-develop-and-deploy-a-b-test
> Remove DVLA title A/B test and make DVLA button A/B test non-lab

- app/views/homepage/_categories.html+new_navigation.erb
Add Childcare-and-parenting links to the AB-test
> Add Childcare and parenting links to the AB-test

- app/views/homepage/_categories.html+new_navigation.erb
trello: https://trello.com/c/KOpf8f3s/82-update-parenting-and-childcare-homepage-link-on-b-version-to-the-new-taxonomy
> Change text on the B-version of childcare-and-parenting link

- Gemfile.lock
To work towards a passing build on
https://github.com/alphagov/govuk-content-schemas/pull/634
> Update govuk-content-schemas-test-helpers and govuk_schemas

- Dockerfile
I want to test Frontend in a container. I nicked the Dockerfile from government-frontend.
> Add Dockerfile for Frontend

- config/tasklists/learn-to-drive-a-car.json
https://trello.com/c/cUEwJxUz/287-tweak-after-you-pass-content
> Amend "after you pass" text

- config/tasklists/learn-to-drive-a-car.json
It looks a little odd in one paragraph.
> Split description text into two paragraphs

- app/controllers/concerns/tasklist_pages.rb
Trello: https://trello.com/b/yPUeB93k/govuk-modelling-services-doing
> Remove tasklist sidebar from/view-driving-licence

- Gemfile.lock
This is to fix an issue with setting an item in a bulleted list as the active
item in a task list.
> Bump govuk_publishing_components

- app/assets/stylesheets/print.scss
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
Need to add print stylesheet for the task list, but frontend has no print stylesheet. Therefore:
- add mechanism for displaying print styles
- add print css, includes only print styles for task list and task list header
Trello card: https://trello.com/c/9CD3dY7r/409-add-task-list-print-styles-to-apps
> Add print stylesheet to frontend for task lists

- Gemfile.lock
This removes two step by step navs
> Bump govuk_navigation_helpers

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_simple-smart-answer.scss
- app/views/application/_location_form.html.erb
- app/views/completed_transaction/_assisted_digital_satisfaction_survey.html.erb
- app/views/completed_transaction/_standard_satisfaction_survey.html.erb
- app/views/completed_transaction/show.html.erb
- app/views/help/tour.html.erb
- app/views/licence/_action.html.erb
- app/views/licence/continues_on.html.erb
- app/views/licence/start.html.erb
- app/views/local_transaction/results.html.erb
- app/views/simple_smart_answers/_current_question.html.erb
- app/views/simple_smart_answers/show.html.erb
- app/views/transaction/jobsearch.html.erb
- app/views/transaction/show.html.erb
- test/integration/completed_transaction_test.rb
- test/integration/find_local_council_test.rb
- test/integration/licence_test.rb
- test/integration/local_transactions_test.rb
- test/integration/place_test.rb
- test/integration/simple_smart_answers_test.rb
- test/integration/transaction_test.rb
- test/support/component_helpers.rb
https://trello.com/c/3VwTvDrj/256-use-button-component-in-frontend-formats
Depends on https://github.com/alphagov/static/pull/1289
Use button component in Frontend formats. This will help with consistency and moving formats to other apps in future.
> Use button component

- config/routes.rb
This was missed when we introduced components to this application.
https://trello.com/c/OanAgv6p
> Expose the component guide

- app/assets/stylesheets/print.scss
Among other things, this will hide the feedback component when printing.
cc @fofr
> Include all component print styles

- app/views/find_local_council/_base_page.html.erb
- app/views/help/index.html.erb
- app/views/help/tour.html.erb
- app/views/licence/continues_on.html.erb
- app/views/licence/start.html.erb
- app/views/shared/_base_page.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/travel_advice/index.html.erb
- test/integration/licence_test.rb
- test/support/component_helpers.rb
> Use title component from gem

- app/views/transaction_variant/_additional_information_tabbed.html.erb
Added one additional line of copy to the variant version of VDL AB test
after further review from content editor and design.
Co-Authored-by: Jakub Miarka <jakub.miarka@digital.cabinet-office.gov.uk>
> HUB-194: Small copy addition to DVLA AB test variant.

- Jenkinsfile
- config/brakeman.ignore
This allows us to find security vulnerabilities.
[Trello Card](https://trello.com/c/JyrOAef3/363-fix-sql-injection-vulnerabilities-in-govuk-applications)
> Turn on Brakeman

- app/views/help/index.html.erb
> Add "Reuse GOV.UK content" to /help

- Gemfile
- Gemfile.lock
This is installed by govuk_test.
> Remove Capybara from Gem file

- app/views/homepage/index.html.erb
Zendesk ticket: https://govuk.zendesk.com/agent/tickets/3401616
Trello: https://trello.com/c/BH9pjP6I/324-replace-syria-promo-on-homepage-with-budget-promo
Follows on from PR #1654
> Update short url link to budget topic page

- app/views/homepage/index.html.erb
Updates central promo slot on GOV.UK homepage
> Update homepage promo slot URL

- app.json
This app does not use rummager.
> Remove PLEK_SERVICE_RUMMAGER_URI

- app/views/homepage/index.html.erb
> Update number of agencies and public bodies

- app/views/help/cookie_settings.html.erb
> Changes to cookie settings page content

- app/assets/javascripts/modules/cookie-settings.js
- spec/javascripts/unit/modules/cookie-settings.spec.js
Works with this PR: https://github.com/alphagov/govuk_publishing_components/pull/940/files
> Change seen_cookie_message expiry to 1 year

- app/views/homepage/index.html.erb
Corrects from "billon" to "billion".
> Fix typo in homepage index.html.erb

- app/views/help/cookie_settings.html.erb
Adds mention of government digital services
[Trello card](https://trello.com/c/zNJQh4fO)
> Update to scope of analytics

- app/controllers/funding_form_controller.rb
- app/views/funding_form/index.html.erb
- config/routes.rb
- spec/controllers/funding_form_controller_spec.rb
We will use this controller as the basis for the funding form.
> Add basic funding form controller

- app/controllers/funding_form/organisation_name_controller.rb
- app/views/funding_form/organisation_name.html.erb
- config/routes.rb
This creates a controller, view and routes for a new step in the funding form.
This should be expanded to include the step content, do something with the response and then used as a basis for each subsequent step.
Trello card: https://trello.com/c/Adl61pG7
> Add skeleton controller for a funding form step

- config/initializers/session_store.rb
The EU Funding Registration form will require sessions to persist data across the form questions.
Trello card: https://trello.com/c/Y9BVrkrl
> Enable sessions

- app/mailers/funding_form_mailer.rb
- app/views/funding_form_mailer/backend_email.text.erb
- app/views/funding_form_mailer/confirmation_email.text.erb
- app/views/funding_form_mailer/department_email.text.erb
- spec/mailers/funding_form_mailer_spec.rb
In preparation for when we have the content ready.
[Trello Card](https://trello.com/c/lusGwD0J/59-add-the-content-for-the-department-email)
> Add some dummy content for the emails

- app/mailers/funding_form_mailer.rb
- app/views/funding_form_mailer/department_email.text.erb
- spec/mailers/funding_form_mailer_spec.rb
This updates the content of the email as per our content designer.
The email will be used by the department to copy and paste the line into a spreadsheet, and hopefully save them some time processing the emails.
[Trello Card](https://trello.com/c/OAP1th04/13-implement-department-email-message)
> Improve department email content

- app/views/funding_form_mailer/confirmation_email.text.erb
As requested by the content designer.
> Add a message about the email address being unmonitored

- app/controllers/funding_form/check_answers_controller.rb
- app/controllers/funding_form/programme_controller.rb
- app/controllers/funding_form/project_details_controller.rb
- config/routes.rb
- spec/controllers/funding_form/check_answers_controller.rb
- spec/controllers/funding_form/programme_controller.rb
- spec/controllers/funding_form/project_details_controller.rb
Adds the programme details controller, project details controller and a placeholder for the check your answers controller.
The check your answers controller implements a reference number generator, which will be included in the emails.
> Add remaining controllers

- app/controllers/funding_form/check_answers_controller.rb
- app/controllers/funding_form/confirmation_controller.rb
- config/routes.rb
- spec/controllers/funding_form/check_answers_controller_spec.rb
On form submission, the user should be sent to the confirmation page
> Redirect to confirmation page on form submission

- app/mailers/funding_form_mailer.rb
- app/views/funding_form_mailer/department_email.text.erb
- spec/mailers/funding_form_mailer_spec.rb
This is currently how they're importing the row into the spreadsheet.
> Concatenate address into a single column

- app/controllers/funding_form/check_answers_controller.rb
This is the correct one we need to use.
> Update grants registration email address

- app/controllers/funding_form/contact_information_controller.rb
- app/controllers/funding_form/organisation_details_controller.rb
- app/controllers/funding_form/project_details_controller.rb
- app/helpers/mandatory_field_helper.rb
- app/views/funding_form/_validation_error.html.erb
- app/views/funding_form/contact_information.html.erb
- app/views/funding_form/organisation_details.html.erb
- app/views/funding_form/project_details.html.erb
- config/locales/en.yml
- spec/controllers/funding_form/contact_information_controller_spec.rb
- spec/controllers/funding_form/organisation_details_controller_spec.rb
- spec/controllers/funding_form/project_details_controller_spec.rb
Implements checks for mandatory text input fields, based on details in https://docs.google.com/spreadsheets/d/1u6s_MXlwA-rucJ55_72RxBbNK7ZWUOm6SnpCF3XFx1Q/edit#gid=0.
> Add mandatory text field validation for EU Funding form

- app/controllers/funding_form/project_details_controller.rb
- config/locales/en.yml
- spec/controllers/funding_form/project_details_controller_spec.rb
Ensures the amount of money awarded is a valid number.
> Ensure amount awarded is valid number in EU Funding form

- app/views/funding_form/companies_house_number.html.erb
- app/views/funding_form/project_details.html.erb
- config/locales/en.yml
Update content across the "Register as an organisation which gets funding directly from the EU" application form - as per prototype
> Improve copy across the registration form

- app/controllers/funding_form/project_details_controller.rb
- app/helpers/mandatory_field_helper.rb
- config/locales/en.yml
- spec/controllers/funding_form/project_details_controller_spec.rb
Ensures all dates are real dates (e.g. not 30th February) and that there is an entry in each field.
> Validate dates in EU Funding form

- app/controllers/funding_form/companies_house_number_controller.rb
- app/controllers/funding_form/grant_agreement_number_controller.rb
- app/controllers/funding_form/organisation_type_controller.rb
- app/controllers/funding_form/partners_controller.rb
- app/controllers/funding_form/programme_controller.rb
- app/helpers/mandatory_field_helper.rb
- app/views/funding_form/_validation_error.html.erb
- app/views/funding_form/companies_house_number.html.erb
- app/views/funding_form/grant_agreement_number.html.erb
- app/views/funding_form/organisation_type.html.erb
- app/views/funding_form/partners.html.erb
- app/views/funding_form/programme.html.erb
- config/locales/en.yml
- spec/controllers/funding_form/companies_house_number_controller_spec.rb
- spec/controllers/funding_form/grant_agreement_number_controller_spec.rb
- spec/controllers/funding_form/organisation_type_controller_spec.rb
- spec/controllers/funding_form/partners_controller_spec.rb
- spec/controllers/funding_form/programme_controller_spec.rb
This validates that the radio buttons are correctly selected.
> Add radio button validation

- lib/tasks/lint.rake
Lint spec files when running `rake lint`.
> Lint files in spec directory

- app/views/funding_form/organisation_details.html.erb
- config/locales/en.yml
So it matches our session field, and therefore gets rendered correctly.
> Change name locale to organisation_name

- app/controllers/funding_form/companies_house_number_controller.rb
- app/controllers/funding_form/contact_information_controller.rb
- app/controllers/funding_form/grant_agreement_number_controller.rb
- app/controllers/funding_form/organisation_details_controller.rb
- app/controllers/funding_form/organisation_type_controller.rb
- app/controllers/funding_form/partners_controller.rb
- app/controllers/funding_form/programme_controller.rb
- app/controllers/funding_form/project_details_controller.rb
- app/views/funding_form/_validation_error.html.erb
There seems to be bug where the problem box appears without any errors.
> Use flash.now

- config/routes.rb
- spec/features/funding_form_spec.rb
Add basic journey tests for "Register as an organisation which gets funding directly from the EU" form - missing from previous PRs
[Trello card](https://trello.com/c/fLP61ZBe)
> Add basic journey tests

- config/locales/en.yml
- spec/features/funding_form_spec.rb
Missed from the updated prototype.
> Update funding form copy

- app/views/completed_transaction/show.html.erb
Take out the full stop from the electric car promotion button text
> Remove full stop from button text

- app/views/funding_form_mailer/department_email.text.erb
- spec/mailers/funding_form_mailer_spec.rb
This value was being collected from users but not included in the email sent to Cabinet Office
> Add "Non UK partners" to funding form departmental email

- app/helpers/date_time_helper.rb
- app/views/funding_form/check_answers.html.erb
- config/locales/en.yml
- spec/features/funding_form_spec.rb
- test/unit/helpers/date_time_helper_test.rb
- Update copy on labels and hints (for amount, start date and end date)
- Format start date and end date when presented on the check your answers page
[Trello card](https://trello.com/c/OyJykI3u)
> Update copy and formatting for start/end award date

- app/controllers/funding_form/project_details_controller.rb
- app/helpers/currency_helper.rb
- app/views/funding_form/check_answers.html.erb
- spec/controllers/funding_form/project_details_controller_spec.rb
- spec/features/funding_form_spec.rb
- test/unit/helpers/currency_helper_test.rb
- format total amount awarded on the check your answers page
- allow comma separator to be entered in the amount input field and strip it when storing the amount on session
[Trello card](https://trello.com/c/X5DUZQA6)
> Format amount

- app/controllers/funding_form/project_details_controller.rb
- app/helpers/mandatory_field_helper.rb
- config/locales/en.yml
- spec/controllers/funding_form/project_details_controller_spec.rb
- spec/helpers/mandatory_field_helper_spec.rb
Makes the following changes:
- makes both project start and end date optional
- compares start and end date to ensure the end date is after the start date
- makes amount awarded optional
Trello card: https://trello.com/c/7qeZlqqV
> Update validation for amount and date on EU Funding Form

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
This is to keep in line with content changes at:
https://publisher.publishing.service.gov.uk/editions/5dd53694e5274a0aca896539/diff
> Update register to vote schema

- Gemfile
- Gemfile.lock
- app/assets/javascripts/modules/cookie-settings.js
- app/assets/stylesheets/views/_cookie-settings.scss
- app/views/help/cookie_settings.html.erb
- spec/javascripts/unit/modules/cookie-settings.spec.js
Update frontend cookie settings form with the new cookie mechanism
> Update cookie changes

- app/views/homepage/index.html.erb
> Update url missed in #2210

- app/views/homepage/index.html.erb
Update promo text as per [zesdesk request](https://govuk.zendesk.com/agent/tickets/3928783)
> Update promo text around coronavirus

- app/views/homepage/index.html.erb
This request came to our 2nd line.
> Add popular page

- app/views/homepage/index.html.erb
This is no longer wanted in the list
> Remove popular page from list

- config/locales/en.yml
It's cheaper than we thought :-)
> Fix the cost for electric vehicles

- app/assets/images/homepage/_README.md
Added a quick guide to optimising images for the homepage.
> Add readme for adding homepage images

- app/views/homepage/index.html.erb
The longer title wraps - is this something we want?
https://trello.com/c/GP3fDVtc/48-update-popular-links-on-the-govuk-homepage
> Update homepage popular links to point to new page

- app/views/travel_advice/index.html.erb
> Update travel advice callout with new FCO wording

- app/views/homepage/index.html.erb
Reverts alphagov/frontend#2301
> Reinstate searchbox on homepage

- app/assets/stylesheets/application.scss
- app/views/shared/_base_page.html.erb
- [Transaction](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/apply-renew-passport)
- [Completed Transaction](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/done/transaction-finished)
- [Local Transaction Results](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/pay-council-tax/hillingdon)
- [Local Transaction Search](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/pay-council-tax)
- [Place](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/id-scan-eu-settlement-scheme)
- [Simple Smart Answer](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/sold-bought-vehicle)
- [Without related links](https://govuk-fronte-make-sideb-vgf96n.herokuapp.com/shotgun-and-firearm-certificates)
> Make sidebar position consistent

- app/helpers/calendar_helper.rb
- app/models/calendar.rb
- app/models/calendar/division.rb
- app/presenters/calendar_content_item.rb
- lib/bank_holiday_generator.rb
- lib/ics_renderer.rb
- lib/tasks/bank_holidays.rake
- spec/controllers/calendar_controller_spec.rb
- spec/unit/bank_holiday_generator_spec.rb
- spec/unit/calendar_spec.rb
- spec/unit/division_spec.rb
- spec/unit/services/calendar_publisher_spec.rb
- spec/unit/year_spec.rb
I don't know how the original PR passed CI if there are all these linting issues.
> Fix linting issues

- app/views/homepage/index.html.erb
Updated as per the agreed copy in https://docs.google.com/document/d/1fshOi3jpE291jycZ6cBToN4z9Zw4uSRoK2Olstrcy5o/edit
https://trello.com/c/BkKFchnm/254-update-the-page-title-and-description-in-all-the-places
> Update coronavirus links on homepage

- app/views/travel_advice/index.html.erb
The FCO would like to change the content displayed on this page.
> Update COVID-19 Exceptional Travel Advisory Notice

- app/views/homepage/index.html.erb
This is a content request come through Zendesk:
https://govuk.zendesk.com/agent/tickets/4104597
> Edit transition period link text

- app/views/travel_advice/index.html.erb
> Update global travel advice callout to reflect 4th July updates

- app/views/travel_advice/index.html.erb
- This was supposed to be with the previous text change.
> Update travel advice COVID callout title

- app/views/travel_advice/index.html.erb
Do not merge or deploy until 2020-07-04.
> Longer update to travel advice COVID callout text

- app/views/homepage/index.html.erb
https://trello.com/c/Eh2z8SQJ/304-update-homepage-link-promo-spot
> Update the wording on Transition links

- app/views/homepage/index.html.erb
> Amend Other agencies and public bodies number to 410

- app/views/homepage/index.html.erb
https://trello.com/c/kfKMDlyt/343-change-get-ready-text-to-check-the-new-rules-on-the-landing-page-govuk-homepage-and-footer
> Reword transition messaging

- app/views/homepage/index.html.erb
> Update agencies and other depts to 412

- lib/data/when-do-the-clocks-change.json
> Remove previous clock changes

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/lYe5hSDx
Updates Global travel advice call out box with information about the new restrictions in England
> Update Global travel advice call out box

- lib/data/when-do-the-clocks-change.json
https://trello.com/c/tzHLWwhE/2227-add-2022-bank-holidays-and-clock-change-dates
> Add clock changes for 2022

- config/locales/en.yml
https://trello.com/c/BUxyUdey/1949-wording-change-in-bank-holidays
> Change name of platinum jubilee bank holiday

- app/views/completed_transaction/show.html.erb
Updated organ donation messaging to reflect new campaign messaging for Nov 2020.
> Organ donation campaign update

- config/locales/cy.yml
https://trello.com/c/BUxyUdey/2232-wording-change-in-bank-holidays
> Change name of platinum jubilee bank holiday in Welsh

- app/views/homepage/index.html.erb
> Change Agencies and other public bodies count to 408

- app/views/homepage/index.html.erb
> Other agencies and public bodies count to 409

- app/views/homepage/index.html.erb
https://trello.com/c/vedxnNDo/741-update-link-content-for-popular-on-govuk-7
> Update content for popular link for Brexit

- app/views/travel_advice/index.html.erb
See trello card for requested content: https://trello.com/c/afsR0MpI
> Update travel advice callout content

- app/views/travel_advice/index.html.erb
[Trello](https://trello.com/c/xZua4oZ2/1039-update-to-travel-advice-callout-box)
> Update travel advice callout box content

- app/views/travel_advice/index.html.erb
[Trello](https://trello.com/c/J01vLuo9/1042-display-different-travel-advice-content-based-on-country)
Updates the index call out box to match both call out box for the
majority of country specific pages (PR in Government Frontend to
follow).
> Update COVID call out box on travel advice index

- app/views/travel_advice/index.html.erb
This is in line with updates from FCDO
> Update travel advice callout box

- app/views/homepage/index.html.erb
Update Brexit wording on homepage under popular links and promo box.
[Trello card](https://trello.com/c/XmaPJL11/821-update-branded-brexit-sidebar-nav-placement-visual-and-logic#comment-6012e2b3ac338d8798c67f8f)
> Update brexit wording on homepage

- app/views/homepage/index.html.erb
Yep... again: https://github.com/alphagov/frontend/issues/2542
> Update organisations to 410

- app/views/travel_advice/index.html.erb
> Travel advice callout update for March 8th changes

- app/views/travel_advice/index.html.erb
This is in line with latest advice from DfT
> Remove text from travel advice callout box

- app/views/travel_advice/index.html.erb
Adds **(or in Wales, stay local)** to first line.
> Travel Advice callout updates - 12 March 2021

- config/locales/plurals.rb
https://trello.com/c/eEphXlio/2394-5-check-and-update-rules-for-plural-forms-across-frontend-apps
> Add plural rules missing from i18n

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
Amendments to the register to vote schema.
> Add register to vote deadlines

- app/views/travel_advice/index.html.erb
> Travel advice call out box update

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
Amendments to the register to vote schema 🗳
> Update register-to-vote metadata

- lib/config/local_transaction_config.yml
Trello: https://trello.com/c/OS5c71Bl/285-make-it-clearer-you-might-be-able-to-get-lateral-flow-tests-in-das
To make it clear they might be able to get tests
> Added more information for DA users

- app/views/homepage/index.html.erb
see: https://github.com/alphagov/frontend/issues/2542
> Change agencies_and_other_public_bodies to 411

- lib/data/when-do-the-clocks-change.json
Update the list of years in the description to match the years that are actually present in the page content.
> Update description for /when-do-the-clocks-change

- lib/config/local_transaction_config.yml
A better option for welsh users, we've been asked to update by welsh gov
> Updated link

- test/service_consumers/pact_helper.rb
It doesn't seem to be necessary to provide a port number.
> Remove port

- app/controllers/electoral_controller.rb
- app/models/election_postcode.rb
- app/models/uprn.rb
- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
- test/integration/electoral_look_up_test.rb
- test/unit/models/election_postcode_test.rb
- test/unit/models/uprn_test.rb
I've also inverted the controller flow, as it worked out easier to have the default at the end.
The second commit actually disappears in the end, but it helped me work out where I was going.
> Add some validation/sanitisation of inputs

- config/machine_readable/register-to-vote.yml
- test/integration/transaction_test.rb
as per https://docs.google.com/document/d/12feerYNxmQjbPugtY6op38M6ocOBDQHGTu_yoinb2gM/edit#
> Update register to vote top actions

- lib/config/local_transaction_config.yml
The payment exists in Scotland
We need to be clearer about this whilst following our content patterns
> Updated scotland content

- config/environments/development.rb
- config/environments/test.rb
- config/locales/cy.yml
- config/locales/en.yml
Normalises and adds missing locales.
More info in the commits ->
Trello:
https://trello.com/c/kYXvexWo/2455-add-missing-keys-to-locale-files-3 
> Adds missing locales

- app/views/travel_advice/index.html.erb
https://github.com/alphagov/frontend/pull/2763 introduced some time based logic so we wouldn't have to deploy at midnight. This removes that now the time has passed
> Cleanup time based travel advice logic

- app/presenters/simple_smart_answer_presenter.rb
- app/presenters/transaction_presenter.rb
- app/views/application/_location_form.html.erb
- app/views/calendar/when_do_the_clocks_change.html.erb
- app/views/completed_transaction/_assistance_received.html.erb
- app/views/completed_transaction/_assisted_digital_satisfaction_survey.html.erb
- app/views/completed_transaction/_standard_satisfaction_survey.html.erb
- app/views/completed_transaction/show.html.erb
- app/views/electoral/_form.html.erb
- app/views/electoral/address_picker.html.erb
- app/views/electoral/results.html.erb
- app/views/find_local_council/_base_page.html.erb
- app/views/find_local_council/district_and_county_council.html.erb
- app/views/find_local_council/index.html.erb
- app/views/find_local_council/one_council.html.erb
- app/views/help/ab_testing.html.erb
- app/views/help/cookie_settings.html.erb
- app/views/help/index.html.erb
- app/views/homepage/_categories.html.erb
- app/views/homepage/index.html.erb
- app/views/local_transaction/results.html.erb
- app/views/place/_option_report_child_abuse.html.erb
- config/locales/cy.yml
- config/locales/en.yml
Move hardcoded content into the English translation file and adds the same keys to the Welsh one for future translation.
https://trello.com/c/HXNiLKQx/2494-add-keys-which-arent-yet-in-any-locale-files-timebox-1-day-per-app
> Move hardcoded text into translation files

- app/views/homepage/index.html.erb
See: https://github.com/alphagov/frontend/issues/2542
> Update Agencies and other public bodies to 412

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/helpers/_overwrites.scss
- app/assets/stylesheets/print.scss
- app/assets/stylesheets/views/_homepage.scss
- app/assets/stylesheets/views/_simple-smart-answer.scss
- app/assets/stylesheets/views/_travel-advice.scss
- app/controllers/application_controller.rb
- app/controllers/calendar_controller.rb
- app/controllers/help_controller.rb
- app/controllers/homepage_controller.rb
- app/controllers/roadmap_controller.rb
- app/controllers/travel_advice_controller.rb
- app/views/application/_location_form.html.erb
- app/views/electoral/_form.html.erb
- app/views/find_local_council/_base_page.html.erb
- app/views/find_local_council/index.html.erb
- app/views/help/cookie_settings.html.erb
- app/views/layouts/application.html.erb
- app/views/place/_option.html.erb
- app/views/place/_option_report_child_abuse.html.erb
- app/views/shared/_base_page.html.erb
- app/views/simple_smart_answers/_outcome.html.erb
- app/views/simple_smart_answers/flow.html.erb
- app/views/travel_advice/index.html.erb
- spec/javascripts/unit/foreign-travel-advice.spec.js
- test/integration/licence_test.rb
- test/integration/place_test.rb
- test/integration/transaction_test.rb
- test/integration/travel_advice_test.rb
Reverting as this is breaking smokey tests and blocking deployment.
> Revert "Swap gem layout"

- app/views/travel_advice/index.html.erb
[Trello](https://trello.com/c/TWO78bFG/446-update-wales-link-in-fcdo-callout-box-on-travel-advice-pages)
> Update Wales travel advice link

- config/locales/en.yml
Resolving typo
While working on `frontend` noticed [open PR from external contributor](https://github.com/alphagov/frontend/pull/2813) - 
replicating to resolve.
None
> Update typo on Roadmap

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_homepage.scss
- app/views/homepage/index.html.erb
- app/views/travel_advice/index.html.erb
Applies the feature flag for the new link styles from the latest release of GOV.UK Frontend and fixes a couple of links to ensure they are utilising these new link styles.
So that this feature can start adding value to users.
[Card](https://trello.com/c/DUGRe64q/752-update-frontend-app-to-use-new-link-styles)
The following table additionally includes the pages that I tested against for review purposes.
| Page | Before | After |
| --- | --- | --- |
| https://www.gov.uk/ | ![Screenshot 2021-06-07 at 16 19 16](https://user-images.githubusercontent.com/64783893/121054954-c2bae100-c7b4-11eb-86f3-b46a1b8daabb.png) | ![Screenshot 2021-06-07 at 16 19 28](https://user-images.githubusercontent.com/64783893/121054995-cb131c00-c7b4-11eb-94f2-3b1ad7093978.png) |
| https://www.gov.uk/bank-holidays | …
> Apply feature flag for new link styles

- Gemfile
- Gemfile.lock
- config/i18n-tasks.yml
- config/locales/cy.yml
- config/locales/en.yml
Normalizes the locale files (i.e. sorts into alphabetical order) and adds missing translation keys.
[Trello card](https://trello.com/c/kB1a8jJE)
> Normalize locale files

- bin/rails
- bin/setup
- bin/yarn
- config/application.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/backtrace_silencers.rb
- config/initializers/new_framework_defaults_6_1.rb
- config/initializers/permissions_policy.rb
- config/puma.rb
- config/routes.rb
These were missed in #2636
https://trello.com/c/nWRFaLO3/2562-manually-bump-apps-to-rails-61
> Apply rails app:update changes

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/P881xXrT
> Travel advice callout changes - July 15 2021

- app/views/travel_advice/index.html.erb
Trello: https://trello.com/c/l7IyYZ5n
# Before
> Travel advice callout changes - 19 July 2021 

- config/locales/en.yml
Trello: https://trello.com/c/qG2DvPQR
> Update popular link for coronavirus - 19 July

- spec/javascripts/unit/foreign-travel-advice.spec.js
This looks to have been left behind from some debugging (by me - sorry)
> Remove rogue console.log

- startup.sh
It's hard to work on `place` format pages without this.
> Add Imminence reference to the startup config

- config/i18n-tasks.yml
- config/locales/cy.yml
- config/locales/en.yml
- test/fixtures/gwyliau-banc_translated.json
- test/integration/gwyliau_banc_test.rb
Imports translations and syncs locales.
More info on the commits ->
Trello:
https://trello.com/c/Xz78vNR4/2757-import-newly-sourced-translations-into-locale-files-5
> Import translations and sync locales

- app/controllers/sessions_controller.rb
- app/views/sessions/first_time.html.erb
- test/functional/session_controller_test.rb
> Remove some code which is now dead following the DI migration

- lib/data/when-do-the-clocks-change.json
Trello: https://trello.com/c/cX3nmA5o/2766-recurring-add-bank-holidays-and-clock-change-dates
> Add clock changes for 2023

- lib/data/bank-holidays.json
Trello: https://trello.com/c/cX3nmA5o/2766-recurring-add-bank-holidays-and-clock-change-dates
> Add bank holiday dates for 2023

- docs/update-homepage-promotion-slots.md
Update the docs for changing promo slots on the homepage
We've recently launched a new homepage which alters how promo slots are updated, no being via yml rather than in the template itself. These doc updates reflect this change.
> Update the promotional slot documentation

- test/functional/place_controller_test.rb
- test/support/content_store_helpers.rb
This test was failing as the place_type could be invalid and no places were returned
> Fix up PlaceController test

- config/locales/en.yml
There has been a request to add an **Improved translations** link
| Before  | After |
| ------------- | ------------- |
|  ![Screenshot 2022-02-09 at 12 40 50](https://user-images.githubusercontent.com/7116819/153204375-b1f38d21-a95d-4233-b60d-9c304e5d2617.png)  |  ![Screenshot 2022-02-09 at 12 46 35](https://user-images.githubusercontent.com/7116819/153204380-30ac554f-61d1-4ab4-868e-56979a56a3d7.png) |
-----
> Update Roadmap page with link to blog

- app/views/licence/_authority_details.html.erb
Add class to link
Missing
Found on: [teignbridge, apply link](https://www.gov.uk/premises-licence/teignbridge/apply)
Integration test: https://www.integration.publishing.service.gov.uk/premises-licence/teignbridge/apply
> Add missing link class

- app/controllers/sessions_controller.rb
- app/views/sessions/first_time.html.erb
- config/routes.rb
- test/functional/session_controller_test.rb
- test/integration/sessions_test.rb
Reverts alphagov/frontend#3234
> Revert "Remove first time sign in page"

- .github/workflows/deploy.yaml
> Investigate incorrect manualDeploy passed

- .github/workflows/set-automatic-deploys-enabled.yaml
> fixed variables

- .github/workflows/deploy.yaml
- .github/workflows/set-automatic-deploys-enabled.yaml
> fixes to GH workflows

- app/presenters/content_item/recruitment_banner.rb
- test/integration/recruitment_banner_test.rb
> Update Tree test survey link

- config/locales/en.yml
Updated first link with energy price guarantee
Screengrab:
[Trello ](https://trello.com/c/yHbZ5jug/1506-change-to-homepage-cost-of-living)
> Make changes to featured slot on homepage

- config/locales/en.yml
> Drop full stops at the end of titles

- config/locales/cy.yml
- config/locales/en.yml
- lib/data/bank-holidays.json
This applies to England, Wales, Scotland and Northern Ireland. No bunting
Wording as agreed in https://govuk.zendesk.com/agent/tickets/5071034
> Add State Funeral bank holiday

- config/locales/en.yml
Update popular links following request from Anna Sherrington 
> Update popular links

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/views/_completed_transaction.scss
- app/views/completed_transaction/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
https://trello.com/c/BegrAq4N/1391-update-mot-and-electric-car-promotional-component
Update design of promotion content on transaction done pages.
Each page should have a unique and descriptive title that defines it's purpose
- [Give feedback on Check the MOT history of a vehicle - MOT promotion](https://govuk-frontend-app-pr-3377.herokuapp.com/done/check-mot-history)
- [Give feedback on Tax your vehicle - Electric car promotion](https://govuk-frontend-app-pr-3377.herokuapp.com/done/vehicle-tax)
<table role="table">
<thead>
<tr>
<th>Before (MOT promotion)</th>
<th>After (MOT promotion)</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/87758239/191217300-60bb7930-a65e-46f9-98ee-85553a6908cc.jpg"><im …
> Update completed transaction page promotion

- app/assets/stylesheets/views/_completed_transaction.scss
- app/views/completed_transaction/show.html.erb
- config/locales/cy.yml
- config/locales/en.yml
- test/integration/completed_transaction_test.rb
https://trello.com/c/HLmurT4f/1536-add-new-designs-onto-organ-donation-pages
Update design of "organ donor" promotion on completed transaction pages.
Each page should have a unique and descriptive title that defines it's purpose
- [Give feedback on Book your driving test - organ donor promotion](https://govuk-frontend-app-pr-3394.herokuapp.com/done/book-driving-test)
<table role="table">
<thead>
<tr>
<th>Before (MOT promotion)</th>
<th>After (MOT promotion)</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/87758239/197506218-ad5edf63-95fc-4ef7-bad4-722cfdb88cd6.png"><img src="https://user-images.githubusercontent.com/87758239/197506218-ad5edf63-95fc-4ef7-bad4-722cfdb88cd6.png" width="360" …
> Update completed transaction page "organ donor" promotion

- Dockerfile
> There is no need for MKDIR in the Dockerfile.

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
Update component asset imports to match the current state of component usage.
Some components were no longer in use and some were missing assets.
None.
> Update component assets

- config/locales/en.yml
Update popular and featured links
> Update popular and featured links

- config/locales/en.yml
As per request via zendesk [1]
[1]: https://govuk.zendesk.com/agent/tickets/5196008
> Update energy bills link on Homepage popular links

- app/views/help/sign_in.html.erb
Fix issue with stylesheets not loading on the sign-in page
> Fix paths for components on sign-in page

- README.md
- the existing link wasn't directly linking to a simple smart answer
- adding some more examples instead
> Update README simple smart answer examples

- app/views/homepage/_chevron_card.html.erb
- app/views/homepage/_government_activity.html.erb
- app/views/homepage/_links_and_search.html.erb
- app/views/homepage/_more_on_govuk.html.erb
- app/views/homepage/_promotion-slots.html.erb
This PR fixes 2 bugs: 
- Fix 1: Renames `type: home page` to `type: homepage`
- Fix 2: Renames `action: Search` to `action: search`
Requested by the PA's.
[Fix 1 trello card](https://trello.com/c/VWbfKb3M/545-rename-homepage)
[Fix 2 trello card](https://trello.com/c/ODSHAwII/534-remove-capitalisation-on-action-search-on-home-page-and-header-menu-bar)
> Ga4 bug fixes

- app/controllers/homepage_controller.rb
- test/integration/homepage_test.rb
Update feature flag method so that it only activates the new design on integration
> Update feature flag

- app/views/homepage/index.html.erb
- config/locales/cy.yml
- config/locales/en.yml
New meta description for the new design.
Requested by Content Designer.
> New page description for new design

- app/views/simple_smart_answers/show.html.erb
- app/views/transaction/show.html.erb
Adds scroll tracking to the top visited simple smart answer and transaction pages.
None.
Trello card: https://trello.com/c/JfkV5NSI/750-add-scroll-tracking-top-100-pages
> Add scroll tracking

- config/locales/en.yml
Change 3rd feature box link and description.
Changes requested.
> Update featured section on homepage

- config/locales/en.yml
The image already exists in the repo.
> Update third homepage promo slot

- .govuk_dependabot_merger.yml
Reverts alphagov/frontend#3974
> Revert "Update .govuk_dependabot_merger.yml"

- app/controllers/place_controller.rb
Remove code that handled the old style of data returned from Places Manager (when it was Imminence).
Code tidying
> Remove code that handled old-style (array) api data from imminence.

- README.md
> 2nd line drill - code freeze

- README.md
This reverts commit df309d07529121a0ed4df1b4d601d10b1187fd45.
Revert changes introduced by the 2nd line drill
2nd line drill
> Revert changes introduced by the 2nd line drill

- yarn.lock
> Upgrade express and its dependencies

- .nycrc
- app/assets/javascripts/modules/app-b-main-navigation.js
- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/views/landing_page/blocks/_main_navigation.html.erb
- app/views/landing_page/show.html.erb
- config/initializers/dartsass.rb
- lib/data/landing_page_content_items/landing_page.yaml
- spec/javascripts/unit/modules/app-b-main-navigation.spec.js
- Add main navigation block
- https://trello.com/c/O79e9zUQ/47-build-main-navigation
- Wasn't sure if tests were needed as there's no model for this block.
> Add main navigation block

- app/models/block/document_list.rb
- app/views/landing_page/blocks/_document_list.html.erb
- app/views/landing_page/blocks/_statistics.html.erb
- lib/data/landing_page_content_items/task.yaml
- spec/fixtures/landing_page.yaml
- spec/models/block/document_list_spec.rb
Clean up the page at `/landing-page/task`, specifically:
- change the content in the hero
- correctly configure mid page hero
- adjust the chart block spacing and link output
- add a new block using the document list component
Doing final checks on the page layout and content testing.
Some! Hopefully improvements all.
Trello card: https://trello.com/c/t0DlqDkW
> Tidy task page

- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/tasks.yaml
Make all the links on the landing pages work correctly.
Improve the navigation of the pages for development purposes.
Includes some text changes to links, but nothing else.
Trello card: https://trello.com/c/WG11pcLc
> Add links to content

- app/views/landing_page/show.html.erb
Pass `inline: true` to the org logo component.
Requested by design.
> Make org logo inline

- app/views/landing_page/blocks/_side_navigation.html.erb
- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/landing_page.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
Fix the side navigation to match the design. [Trello](https://trello.com/c/oip5Sqwe/109-finalise-page-d-our-progress-landing-page)
Landing page navigation lists use a different style from default content lists.
| Before    | After |
| -------- | ------- |
| <img width="376" alt="image" src="https://github.com/user-attachments/assets/e1f74ead-992f-4987-b765-5d90f553df91">  | <img width="376" alt="image" src="https://github.com/user-attachments/assets/cccc2ac4-9a51-4e9f-a3df-1febf59d7a59"> |
> Apply correct options to sidebar navigation

- config/locales/cy.yml
- config/locales/en.yml
Normalize translations which have got a bit unsorted.
> Normalize translations

- spec/models/landing_page/block/blocks_container_spec.rb
- spec/models/landing_page/block/columns_layout_spec.rb
- spec/models/landing_page/block/grid_container_spec.rb
- spec/models/landing_page/block/share_links_spec.rb
Add missing model tests
No visual changes
> Add missing model tests

- lib/data/landing_page_content_items/be_kinder.yaml
- lib/data/landing_page_content_items/be_thankful.yaml
- lib/data/landing_page_content_items/donate_to_charity.yaml
- lib/data/landing_page_content_items/exercise_more.yaml
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
- lib/data/landing_page_content_items/learn_something_new.yaml
- lib/data/landing_page_content_items/tasks.yaml
> Fix hardcoded files

- app/controllers/application_controller.rb
- app/controllers/find_local_council_controller.rb
- app/services/electoral_service.rb
- spec/system/find_local_council_spec.rb
- spec/unit/strategy_spec.rb
Removes obsolete methods, improves tests for others, marks a bit of untestable code. Improves line coverage to 99.16%
> Tidy code 2

- config/environments/development.rb
- package.json
- spec/service_consumers/pact_helper.rb
- yarn.lock
Solves not being able to run Jasmine or pact tests in govuk-docker
> Fix jasmine and pact tests not running in govuk-docker

- app/views/landing_page/blocks/_share_links.html.erb
- Adds a border to the follow links, as per the designs
[Trello card](https://trello.com/c/37SyRmUF/150-rework-share-links)
> Add border to follow links

- app/assets/stylesheets/views/_landing_page/hero.scss
Fix "mid page" hero container sizing issue
To fix alignment of hero content.
> Fix mid page hero container sizing issue

- docs/building_blocks_for_flexible_content.md
[Document how to use the Whitehall Republish UI](https://github.com/alphagov/frontend/commit/7b6e38f1ff5422c6b85b49cb149bdf506a749fc7)
This will be useful information when the navigation groups change.
> Document how to use the Whitehall Republish UI

- app/assets/stylesheets/views/_landing_page/featured.scss
- app/models/landing_page/block/featured.rb
- app/views/landing_page/blocks/_featured.html.erb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/goals.yaml
- lib/data/landing_page_content_items/homepage.yaml
Rework feature block.
[Trello card](https://trello.com/c/3qI5JERP/152-rework-featured-block)
> Rework featured block

- app/models/landing_page/block/featured.rb
Use the `.present?` method to check for images
For consistency.
> Use the .present? method to check for images

- docs/building_blocks_for_flexible_content.md
> Fix the blocks docs on using govspeak markdown

- app/models/landing_page/block/press_notices.rb
- docs/building_blocks_for_flexible_content.md
- lib/data/landing_page_content_items/tasks.yaml
- spec/models/landing_page/block/press_notices_spec.rb
- Update documentation to add Press notices block
> PressNotices should inherit from DocumentList

- docs/building_blocks_for_flexible_content.md
Add and improve the blocks documentation.
I forgot to add the full width background documentation with the code for it, and then spotted a few other things that needed improving. This is a slightly work in progress as I've not got all the way through the file yet, but will come back to it later.
None, apart from the text.
> Improve blockumentation

- app/assets/stylesheets/helpers/_parts.scss
- app/assets/stylesheets/views/_landing_page/main-navigation.scss
- app/assets/stylesheets/views/_travel-advice.scss
> Fix Sass Deprecations

- app.json
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#updating-app-json
> Upgrade to Heroku-24

- app/assets/stylesheets/views/_popular_links.scss
Fix Sass mixin error
Produces an invalid CSS propery value
> Fix Sass mixin error

- app/views/layouts/application.html.erb
- Needed for the moment because of this: https://github.com/alphagov/government-frontend/pull/3076
> Add the span#top element

- app/controllers/specialist_document_controller.rb
- app/models/contents_outline.rb
- app/presenters/contents_outline_presenter.rb
- app/presenters/specialist_document_presenter.rb
- app/views/specialist_document/show.html.erb
- spec/models/contents_outline_spec.rb
- spec/presenter/contents_outline_presenter_spec.rb
- spec/presenter/specialist_document_presenter_spec.rb
Refactor contents outline work added here (https://github.com/alphagov/frontend/pull/4750)
Refactor improvement opportunities noted after PR had been merged.
> Contents outline refactor

- lib/content_item_loader.rb
> Bump news articles to quarter traffic in graphql

- lib/content_item_loader.rb
> Increase graphql news articles to 50%

- app/assets/javascripts/views/landing_page/map/data/cdc.geojson.js
Updates the CDC data on the map page.
New data.
> Update CDC data

- Gemfile.lock
> Bump govuk_web_banner to 0.13.1

- app/models/call_for_evidence.rb
- app/models/publication.rb
- app/views/shared/_attachments_list.html.erb
- spec/models/call_for_evidence_spec.rb
- spec/models/publication_spec.rb
Update variable name as agreed in https://github.com/alphagov/frontend/pull/5015#pullrequestreview-3263672680
[Jira issue](https://gov-uk.atlassian.net/jira/software/c/projects/PNP/boards/1356?selectedIssue=PNP-5618)
> Update attachments lists
